### ISSUE TITLE
Sequelize spams console when logging result of query

### ISSUE THREAD

**Issue by Maikkeyy** [sequelize/sequelize#10236]
Hi all,

Recently I encounter some problems with logging results from queries. I don't know if an update caused this problem and if so which version. What I do know is that i didn't have this problem before.

### Problem:
When i log the result from a query the console gets spammed with properties that are not mine, but I think from Sequelize itself. Sometimes this can take really long and what I want to be logged doesn't get logged.

An example:

```
     Item.bulkCreate(emptyItems, {
          raw: true
        }).then((res) => {
          console.log(res)
          resolve({});
        }).catch((err) => {
          reject(err);
        });
```

Logging the result gives an output like this(and a lot more):

![image](https://user-images.githubusercontent.com/19424609/49580693-d240e100-f94f-11e8-8788-00113e41d4f9.png)

## What do you expect to happen?
Logging my objects that have been saved/retrieved. This happens with all queries, also with findAll().

## What is actually happening?
Sequelize logs random properties?

Did someone else encounter such problem?

__Dialect:__ mariadb
__Dialect version:__ 15.1
__Sequelize version:4.41.2

**Comment by sushantdhiman** [comment]
Instances contains a lot of internal properties otherwise we can't offer most of features we do, you can use `toJSON` to get data only. This observation is true for most of Node libraries, like try logging `request` object from express middleware

**Comment by sylv3r** [comment]
@sushantdhiman I noticed the same issue. That's understandable when trying to log a query result or a sequelize instance object, but it also happens when setting something up in the sequelize option `logging` either in the main object or in a query.
Since this is an internal of sequelize and we don't get to know what's under the hood, it should have a useful output, not a shitload of data crashing the node process, because right now it is useless (or I am missing something here).
