### ISSUE TITLE
Document global hooks

### ISSUE THREAD

**Issue by tiboun** [sequelize/sequelize#1028]
Hi Guys!

This is a feature request.

I'm actually a new user from nodejs world and I wonder if sequelize can handle optimistic lock. I come from java world and I was used to use MyBatis. This "ORM" implements global hooks and then we can handle optimistic lock.

After each update query, we can then check if some data has been update. If this is not the case, then we can throw an exception or handle another way.

**Comment by venomcc** [comment]
@emielke , @janmeier 
**Optimistic Locking:**

User 1 queries table1 for row {id: 1 version: 1}
User 2 queries table1 for row {id:1 version: 1}
User 1 updates table1 row {id: 1 to version: 2}
User 2 tries to increase the version of table1 row {id:1 version: 1} but it is no longer possible because version 1 no longer exists on the database.

So i looked into implementing something like this, however to ensure atomicity update statements on versioned rows, the sql statement should look something like this.

```sql
update table1 set version = 2 where id = 1 and version = 1
```
The reasoning being that is explained here: http://dba.stackexchange.com/questions/28879/how-to-correctly-implement-optimistic-locking-in-mysql

Therefore here's my simple attempt at it:

```javascript
sequelize.addHook('afterDefine', function(factory){
   if(factory.options.optimisticLocking){

       //Add a version column based on an optimistic locking flag
       var newAttributes = {};

       //for now no column name collision detection
       newAttributes['version'] = {
           type: Sequelize.INTEGER,
           allowNull: false,
           defaultValue: 0
       };

       Utils.mergeDefaults(factory.rawAttributes, newAttributes);

       factory.refreshAttributes();


       //hook up a update where clause to find the old version and increase to a new version.
       factory.addHook('beforeUpdate', function(obj){

           //Problem here is that i'm unable to modify the update statement's where condition, so the
           //following statement did not work
           obj.__options.whereCollection['version'] = obj._previousDataValues['version'].toString();

           //increment version number
           obj.dataValues['version'] = obj._previousDataValues['version'] + 1;
       })

   }
});
```

As you can see from my code above, i ran into a problem trying to modify the update statement to take an where condition additional to the already existing primary key.  I don't know how.

Any thoughts?

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L535
The `where` for a save is not currently generated at the time of the hook being called, so it's not being included in the hook either, that's your primary issue i think.

**Comment by sprilukin** [comment]
+1 for this issue.
After Hibernate framework from Java world i thought that all ORM's have such kind of feature, but seems it's not the case )

The problem with optimistic locking is that it's not enough to just modify UPDATE query in this way:
```SQL
update table1 set version = 2 where id = 1 and version = 1
```
Also query execution result should be checked and ensured that exactly one row was updated,
Otherwise an exception like "Optimistic locking exception" should be thrown so second writer who trying to update row which was already updated will be informed about the issue and could handle it.

So plugins should ideally support such kind of extensions in order to correctly implement opt locking feature.

i've tried to implement an example in which i extended sequelize to support optimistic locking.
I was able to do this, but i had to fork sequelize by itself and make change in postgres dialect (i tested on postgres but example should work for any dialect after appropriate patch in this dialect).

my example with sequelize extension: https://github.com/sprilukin/sequelize-optlock-example
sequelize fork with dialect patch: https://github.com/sprilukin/sequelize

Alternatively Repeatable-read transaction isolation level could be used but it's more strict than just Read-committed+optimistic locking

**Comment by mickhansen** [comment]
@sprilukin Right with the where query added the code should still check for number of affected rows else it's pretty much pointless ;)

**Comment by igrayson** [comment]
+1 for this. Is this the main tracking issue for adding optimistic locking support to sequelize? :dancer:

**Comment by janmeier** [comment]
@igrayson Not really :)

I still think that optimistic concurrency would be better implemented as a plugin and does not belong in sequelize core. 

This issiue regards global hooks, ie. the ability to execute a function for example before each update query. As mick mentions can be already be done in an afterDefine hook, which will allow you to add a beforeUpdate to all models. 

You can also do:
```js
new Sequelize(..., {
  define: {
    hooks: { 
      beforeUpdate...
    }
  }
});
```

With the smallest caveat that if a model defines its own beforeUpdate function, it will be overwritten. Once that bug is fixed I believe this issue can be closed

**Comment by overlookmotel** [comment]
I believe you can already define global hooks (i.e. hooks that run on every model). See PR https://github.com/sequelize/sequelize/pull/2320

That PR which I authored added global hooks. Unless they were removed again later?

**Comment by janmeier** [comment]
@overlookmotel You are correct - just tested, and addhook on the sequelize isntnace works fine, even in combination with additional hooks on the model. 

In that case, tagging this as a documentation issue.

We should probably also add a couple of tests asserting that global hooks + model hooks work in combination

**Comment by sprilukin** [comment]
Well i'ts ok to implement this feature as a plugin, but i still think that some changes still should be done to the sequelize core -  at least it should be able to get affected rows count in afterUpdate hook, otherwise it will be impossible to throw an exception if 0 rows was affected during updating of versioned entity.

**Comment by janmeier** [comment]
@sprilukin I agree, you should be able to get the number of affected rows in (bulk)-update. But that should be tracked in a seperate issue, since it is not related to global hooks. Feel free to open one, it shouldn't be too hard to implement either.

Another issue is that currently an update of a single row (instance.update) does not have access to the number of affected rows, whereas bulk update (model.update) does - so there is no way to know if row was actually matched. Re. optimistic concurrency the primary key would need to be on id, version in order to detect that the version was updated - since `instance.save` always updates on primary key. Again, this is probably better to track in a seperate issue.

**Comment by greenify** [comment]
Hi,

just a quick mentioning in case @overlookmotel or someone else still wants the versioning feature:

I needed the mentioned historical records functionality, so I wrote the [sequelize-temporal](https://github.com/bonaval/sequelize-temporal) plugin.

Basically every update, bulkUpdate, destroy, bulkDestroy operation has a hook attach and saves the toBeOverwritten or toBeDeleted value(s) in a separate TableHistory database.

=> A huge thanks to the sequelize developers for their awesome hook system :)

And of course if someone is interested in this feature - I am happy about his/her feedback.

**Comment by janmeier** [comment]
Sounds awesome @greenify , feel free to add it to the wiki: https://github.com/sequelize/sequelize/wiki/Add-ons-&-Plugins

**Comment by overlookmotel** [comment]
This looks great. Thanks loads @greenify for letting me know you've done it. I'll have a look at it properly when I get a chance...

**Comment by overlookmotel** [comment]
@greenify I've had a quick look. I'll post an issue when I have time, but just to say quickly that I notice that your hooks implementation doesn't catch errors properly. It might be better to write the hooks as Promise-returning functions rather than using the `next` callback and that will deal with error-catching without any further code. Otherwise you need to use `.catch()` on all the calls to Sequelize methods.

**Comment by overlookmotel** [comment]
@greenify It could also be nice to be able to attach the plugin to all models simultaneously rather than just on a model-by-model basis.

**Comment by greenify** [comment]
@overlookmotel Thanks a lot for the feedback - I have put your points into issues, e.g. see:
https://github.com/bonaval/sequelize-temporal/issues/2

Do you mind continuing, so that we don't spam a closed issue?
