### ISSUE TITLE
Connection pool and old CLS context issue

### ISSUE THREAD

**Issue by iamnewspecies** [sequelize/sequelize#10462]
## What are you doing?
We are using CLS to connect all the logs in one request. We are logging the query with the help of Sequelize. While logging we have passed the Session Id with the help of continuation local storage (CLS) and we log Session Id along with rest of the query. The problem is, the session id does not change, we keep seeing the old session id even though the a new session id is created for the request.

## Possible issue!
We have an expiry of 60 sec on our connection pool. When the connection is idle for more than 60sec we see that session id in the log changes but any request before that time interval prints the old session id in the logs. The connection pool code is somehow storing the old CLS context and is logging with that.

__Dialect:__ mysql (probably this issue is there for all the dilects )
package.json library versions
    {
            "sequelize": "^4.36.1"
        ,   "mysql": "^2.16.0"
        ,   "mysql2": "^1.6.1"
    }

**Comment by schmod** [comment]
I've seen this too.  It looks like this happens because connections are "lazily" created the first time you query (and then the ping/keepalive `setInterval` on that connection retains the CLS context that created it).

I've had some luck calling `sequelize.authenticate();` when my server first starts, as that seems to instantiate connections outside of any CLS context.  However, I'm not 100% confident that this is actually a robust solution.

Having looked into this issue, I was unable to determine if CLS provides any mechanism to create side-effects that are specifically divorced from any CLS context -- it doesn't seem like there's any easy opt-out mechanism :-/
