### ISSUE TITLE
Deploy the v5 docs somewhere?

### ISSUE THREAD

**Issue by papb** [sequelize/sequelize#10475]
Currently the following documentation links are available in the readme:

> ### Documentation
> - [v4 Documentation](http://docs.sequelizejs.com)
> - [v3 Documentation](https://sequelize.readthedocs.io/en/v3/)
> - [v3 to v4 Upgrade Guide](http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html)
> - [v4 to v5(beta) Upgrade Guide](https://github.com/sequelize/sequelize/blob/master/docs/upgrade-to-v5.md)

I think it would be a great thing to have the v5 docs somewhere as well, even though it is still in beta. Currently, unless I am missing something, the only way to read the v5 docs is to:

* `git clone`
* `npm install`
* `npm run docs`

**Comment by SimonSchick** [comment]
Actually v5 is kinda overdue, are there any plans for a release?

**Comment by papb** [comment]
Hi @SimonSchick I am eager to see it too... But there are two issues still listed in [the milestone](https://github.com/sequelize/sequelize/milestone/18)...

**Comment by sushantdhiman** [comment]
Docs published

**Comment by papb** [comment]
@sushantdhiman Was it intentional to make the v4 API reference disappear? Currently we can browse through the v4 markdown guides but the esdoc-generated API is gone (unless I'm missing something). Was this intentional?

**Comment by sushantdhiman** [comment]
Yeah I want to keep v4 docs somewhere but currently there is no good way. @janmeier can we publish docs to another subdomain like `v4.squelizejs.com`?

**Comment by snowyfox** [comment]
I don't think the v5 docs were published quite right. There is no way to navigate around the API reference section ([link](http://docs.sequelizejs.com/identifiers)) like you could with v4. Instead of dropping you into the root of the API, its in a subsection on `Identifiers`. There is no way to get to the API reference for the Model class for instance, without clicking through into `Association` and then find a method that has a reference to `Model`. Before, the API Reference had all of the main classes listed in the side bar that you could drill down into.

**Comment by papb** [comment]
@snowyfox - You are very right!! I think this is very important to be fixed asap. You should open a new issue, can you do that? And mention this one?
