### ISSUE TITLE
when doing custom join during include, it still requires associations.

### ISSUE THREAD

**Issue by overflowz** [sequelize/sequelize#10554]
## What are you doing?
I'm trying to associate models with custom `.on` option, but it still requires column to be present (even though I don't really need it).

```js
// WARNING: pseudo code, not tested.
const Foo = sequelize.define('foo', {
  id: {
    primaryKey: true,
    autoIncrement: true,
    type: DataTypes.INTEGER(11).UNSIGNED,
  },
  meta: {
    allowNull: false,
    defaultValue: {},
    type: DataTypes.JSON,
  }
});

const Bar = sequelize.define('foo', {
  id: {
    primaryKey: true,
    autoIncrement: true,
    type: DataTypes.INTEGER(11).UNSIGNED,
  },
});

// ... snip

Foo.findOne({
  where: { ... },
  include: [{
    model: Bar,
    required: false,
    on: {
      '$bar.id$': sequelize.fn('json_extract', sequelize.literal('foo.meta'), '$.bar_id'),
    },
  }],
});
```

## What do you expect to happen?
I wanted to get Foo with Bars (without adding `barId` column in Foo).

## What is actually happening?
Error saying there are no associations between Foo and Bar.

SequelizeEagerLoadingError: Bar is not associated to Foo!

__Dialect:__ sqlite
__Dialect version:__ 4.0.6
__Database version:__ sqlite3?
__Sequelize version:__ 4.43.0
__Tested with latest release:__ No (If yes, specify that version)

**Comment by garymcm** [comment]
I looked through `model.js` and although I see a jsdoc reference `include.options[].on`, I don't see any code that might handle that option. Stepping through debug mode, when the non-associated model is validated, your error is thrown since it's not in the list of associated models. Somewhere in the issues list I read about `.on` and the replies seemed to indicate success, but I can't find that issue number now. Maybe the code was removed? I ended up creating the association, as I didn't want to go to raw SQL.

**Comment by overflowz** [comment]
@garymcm it is located here: https://github.com/sequelize/sequelize/blob/v4/lib/dialects/abstract/query-generator.js#L1455

**Comment by garymcm** [comment]
Thanks for that. I am kind of new to this poking-my-nose-into-code thing. I never got that far since the error happens earlier. Looking at history, this validation check was added in #7005 2 years ago, and the `include.on` was added 4 years earlier. It seems like the only way this will work is to dynamically create an association, maybe define it in the .on clause.

**Comment by overflowz** [comment]
Well, either we can have an option to specify associations when joining with `.on`  or to ignore association check if `.on` exists when including (but not sure on this, like how it will handle is it one record or many).

**Comment by garymcm** [comment]
I looked at ignoring the error, and it seems the model code is definitely expecting an association back. I didn't test it out though. We'd be expecting it to behave itself without an association until it gets to the dialect part and processes the `.on`.

**Comment by overflowz** [comment]
in that case I guess there should be an option to specify association via `.on`. Something like this:
```js
include: [{
  model: Foo,
  customAssoc: 'hasOne',
  on: {
    '$col.id': 1
  },
}]
```
or something like that, but honestly, I really need this ;c

**Comment by garymcm** [comment]
I have a feeling this is a hack, but I got it work by trying to satisfy everything it complained about as shown below.  So I am trying to join `model1` to `model2` on a common field `unique_row_id`.  I really don't know if this is what was intended by the author; however, it does appear to work. 

```
model1.findAll({
  include: [{
    model: model2,
    association: {
      as: 'm2',
      source: model2,
      target: model1,
      identifierField: 'unique_row_id'
    },
    on: {
      '$model1.unique_row_id$': { [Sequelize.Op.col]: 'm2.unique_row_id' }
    }
  }]
})
```

**Comment by overflowz** [comment]
Yeah, that looks like hacky (haven't tested by myself) but good work though! We need something like this officially tho.

**Comment by automatensalat** [comment]
I stumbled over this as well today. My current workaround a.k.a. hack is to to associate the two models with `Model1.belongsTo(Model2)` and then remove the artificially created foreign key with `Model1.removeAttribute("model2Model2Id")`. The FK attribute would be included in the generated query otherwise. This seems to work in my p.o.c., however I'm not sure if this will have any bad consequences lateron. I feel that an explicit association shouldn't be necessary if joined with a custom `ON` clause.
