### ISSUE TITLE
model type can not be infer because of the lack of @types/bluebird

### ISSUE THREAD

**Issue by alsotang** [sequelize/sequelize#10668]
## What are you doing?

I am using `sequelize` with typescript. Below is my demo file
```js
// code here
import {Sequelize, Model, STRING, DATE} from 'sequelize'
const sequelize = new Sequelize('postgres://user:pass@example.com:5432/dbname');

class User extends Model {}
User.init({
  username: STRING,
  birthday: DATE
}, { sequelize });

User.create({
  username: 'janedoe',
  birthday: new Date(1980, 6, 20)
}).then(vvvv => {

})
```

## What do you expect to happen?

`vvvv` should be infer to type `User`, but it doesn't.

## What is actually happening?

`vvvv` is infer to `any`.

when I run `npm i @types/bluebird`, the infer works.

__Dialect:__ any
__Dialect version:__ any
__Database version:__ any
__Sequelize version:__ 5.2.7
__Tested with latest release:__ Yes. 5.2.7

**Comment by alsotang** [comment]
![image](https://user-images.githubusercontent.com/1147375/55286905-b49ef800-53d4-11e9-8980-661fe1c5b48b.png)

**Comment by SimonSchick** [comment]
Please refer to http://docs.sequelizejs.com/manual/typescript.html we don't want to ship typing packages as hard dependencies for now.

Currently debating whether we should include it after all or have a post-install task that checks for a tsconfig being present.

Feel free to post your thoughts.

**Comment by alsotang** [comment]
At least you should suggest installing `@types/bluebird` as peer dependency in README? Or this lib cannot run when using typescript.

**Comment by SimonSchick** [comment]
This will usually generate a warning, I will look into it.

**Comment by alsotang** [comment]
When I crll+F `typescirpt` in README. I only found this url: https://github.com/RobinBuschmann/sequelize-typescript

According to https://github.com/RobinBuschmann/sequelize-typescript/issues/587#issuecomment-478332149 . You have a typescript guide here: http://docs.sequelizejs.com/manual/typescript.html . So if make it obvious, it would be nice.

**Comment by papb** [comment]
@alsotang Thanks for the heads up! SimonSchick and I are trying to improve the documentation to prevent these difficulties :)

**Comment by devoto13** [comment]
One potential solution would be to not require these type packages at the first place:
- If type definitions do not expose dependency on the `bluebird`, but return a built-in `Promise` instead there is no need for `@types/bluebird` package. Not sure how many people actually rely on the Sequelize to return Bluebird instance though. On the other hand it may be a good thing to make it an implementation detail, so people willing to rely on Bluebird methods use it at their own risk.
- `@types/node` does not seem to be needed at all.
- `@types/validator` is a bit tricky though - it is actually needed and hiding behind a facade is not very feasible given the broad API surface. But if it is only one dependency it may be reasonable to just add it as a regular dependency. It's size is pretty decent  (~30KB) comparing to `@types/node`, which is ~600KB + `@types/bluebird`, which is ~66K.

**Comment by SimonSchick** [comment]
@types/node is mostly required due to `Buffer` but iirc there were a couple more.

In any case, if you use sequelize you must use it in a node-ish environment so requiring it is reasonable.

Bluebird is considered a feature of sequelize, removing it from the typings would be considered a large breaking change.

**Comment by devoto13** [comment]
@SimonSchick

> Bluebird is considered a feature of sequelize, removing it from the typings would be considered a large breaking change.

Ok, got it!

> @types/node is mostly required due to Buffer but iirc there were a couple more.
> In any case, if you use sequelize you must use it in a node-ish environment so requiring it is reasonable.

The thing is that if you don't expose any of the types defined in `@types/node` in the type definitions (which Sequelize does not seem to do from a quick scan) the consumers don't need to install it. You may still need to have it in the `devDependencies` to use types in your TypeScript sources of the library (which is not the case here either).

**Comment by SimonSchick** [comment]
@devoto13 So I checked, there at least 2 references, NodeJS.CallSite and `Buffer`, we could shallow declare them via interfaces but my previous point still stands, if you use sequelize with TS you will most likely use it with node too, so what's the point of trying to avoid it?

**Comment by devoto13** [comment]
I see now. looks like I didn't remove the `@types/node` package completely, when checking and these usages didn't result in an error...

> so what's the point of trying to avoid it?

Two reasons here:
- Size. It may be more favourable to impose extra 90KB instead of 690KB on JS users to avoid extra installation steps for TS users.
- Not having/having `@types/node` only as a peer dependency. I quite often experience projects, which end up with 2+ instances of this package of different versions, which causes all sorts of troubles. Peer dependency approach will print a warning on installation for JS users (which is both annoying and confusing), so not having this dependency if possible looks like the best tradeoff here.

`NodeJS.CallSite` should be quite easy to get rid of, but `Buffer` is a tricky one.
