### ISSUE TITLE
Improve developer experience setting up TypeScript with Sequelize

### ISSUE THREAD

**Issue by BlueKore** [sequelize/sequelize#10690]
## What are you doing?
I'm adding sequelize as a reference to my package/project and compiling it with TypeScript.

## What do you expect to happen?
A successful compilation

## What is actually happening?
I've obtained some errors that told me some types were missing. I solved this adding them as dependencies. Should you include **@types/bluebird** and **@types/validator** on the sequelize package? The error was the following:

node_modules/sequelize/types/lib/promise.d.ts:2:27 - error TS7016: Could not find a declaration file for module 'bluebird'. 'C:/Users/X/Documents/Y/Z/node_modules/bluebird/js/release/bluebird.js' implicitly has an 'any' type.
  Try `npm install @types/bluebird` if it exists or add a new declaration (.d.ts) file containing `declare module 'bluebird';`

2 import * as Bluebird from 'bluebird';
                            ~~~~~~~~~~

node_modules/sequelize/types/lib/utils/validator-extras.d.ts:2:22 - error TS7016: Could not find a declaration file for module 'validator'. 'C:/Users/X/Documents/Y/Z/node_modules/validator/index.js' implicitly has an 'any' type.
  Try `npm install @types/validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'validator';`

2 import * as val from 'validator';


__Dialect:__ mariadb
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 5.2.8

**Comment by papb** [comment]
For TypeScript usage, you need to manually install the following packages: `@types/node`, `@types/validator` and `@types/bluebird`. This is documented on our [TypeScript Tutorial](http://docs.sequelizejs.com/manual/typescript.html). 

We know that this tutorial is a bit hard to find. This is already known and there is already an open PR to improve this: #10677 

Thanks for using Sequelize :grimacing:

**Comment by papb** [comment]
And if you're curious as to why we don't make these packages be installed automatically, the reason is that we don't want to bloat installation for non-TS users.

**Comment by SimonSchick** [comment]
Duplicate of #10668

**Comment by matushorvath** [comment]
@papb If you don't want to bloat the package for non-TS users, I suggest you separate the types to a `@types/sequelize` package and make that package depend on `@types/bluebird` and `@types/validator`. 

The way it is packaged now, we get the worst of both worlds:
- non-TS users get 320 kB of types installed automatically as part of the `sequelize` package
- TS users get broken types that can't be used unless you do manual steps, which is very nonstandard in npm world

I respectfully ask that you reconsider this approach.

**Comment by papb** [comment]
@matushorvath Thanks for your post, I will reconsider. I'm a bit confused though, can you clarify your first bullet point? What are those 320 kB?

**Comment by matushorvath** [comment]
@pabp The 320kB are this folder: https://github.com/sequelize/sequelize/tree/master/types
These types are obviously useless for non-typescript users, and also not usable for typescript users unless they install extra packages.

As a typescript user I am OK with installing extra packages to make types work, but the standard way to do that is to have a single @types/sequelize package which I would expects brings all the types it needs as its dependencies.

It's all about the principle of least surprise. If I install sequelize and find that types don't work, I will try installing @types/sequelize, since that's the pattern I am used to from other packages. To find that I need to install @types/sequelize and @types/validator requires nontrivial amount of googling.

**Comment by papb** [comment]
@matushorvath Thank you, and sorry to take long to reply. I am too busy right now though, this will have to wait more :(

**Comment by Ecostack** [comment]
Thanks for mentioning that there is a requirement to @types/bluebird, it is not mentioned in the docs at the moment.

Also, I would appreciate to consider the approach of making it a dependency of the @types/sequelize package. At this moment, `npx typesync` removes the @types/bluebird and @types/validator, due to not being used. 

Anyone else experiences that same issue?

**Comment by ephys** [comment]
We could include `@types/validator` in our dependencies

`@types/bluebird` is not needed anymore since v6 moved to native promises.

We won't remove the type definitions from the published bundle. They're a tiny part of the code and help non-typescript users too (some intellisense implementations like webstorm's exploit these typings)

**Comment by ephys** [comment]
`@types/validator` is now part of our dependencies, `@types/bluebird` is gone, and we provide our own typings. I think this task is done
