### ISSUE TITLE
Ability to pass N args on model import

### ISSUE THREAD

**Issue by raymonddavis** [sequelize/sequelize#10768]
I think having the ability to pass N arguments through when importing a model would be very helpful.

This would allow you to pass in for an example a Logger class so that you could use it in the model hooks, or using a custom class that generates a default value for the model.

In my case, I was exploring the possibility of utilizing the model hooks to make updates to a cache on certain models automatically.

**This is the current code regarding import.**
https://github.com/sequelize/sequelize/blob/4ec86a4bd43aa65e45546e2d4177ffcbeb2b4bac/lib/sequelize.js#L408-L415

**This is the purposed code.**
```javascript
    if (!this.importCache[importPath]) {
      let defineCall = arguments.length > 1 && typeof arguments[1] == 'function' ? arguments[1] : require(importPath);
      if (typeof defineCall === 'object') {
        // ES6 module compatibility
        defineCall = defineCall.default;
      }
      this.importCache[importPath] = defineCall(this, DataTypes, ...[...arguments].slice(1));
    }
```

_Note:_ 
This is my first Issue/Feature on a repo ever so if need to provide more details or better examples and test cases just let me know. 
Also, any feedback is helpful.

**Comment by steveacalabro** [comment]
+1

**Comment by papb** [comment]
Hello, thanks for reaching out to help, welcome to Sequelize :grimacing:

Sorry that your issue wasn't looked at sooner.

The `sequelize.import` feature is actually on the works to be removed (see #10892) - the idea is that usual `requires` should be enough. In this case, you should be able to customize them with whichever flexibility you would like. Of course, this would require an update on the Sequelize CLI as well, so that's why this change wasn't completed yet.

Suggestion: try to use the usual NodeJS `require`s directly and see if that works for you.
