### ISSUE TITLE
V6: Removing CLS support

### ISSUE THREAD

**Issue by SimonSchick** [sequelize/sequelize#10819]
We are currently considering remove CLS support as there are a few issues with it.

- It requires hooking the promise implementation which is not sustainable for the future of sequelize.
- It's generally unsafe due to it's implicit/magical nature, especially with developers that are unfamiliar with it's exact functionality.
- It isn't always reliable when mixed promise implementations were used.

Related issues:
- #9022
- #8978

We would like to gather some feedback/suggestions on this matter, we are currently looking at removing it entirely.

**Comment by janmeier** [comment]
Yes - I think removing CLS is a good idea. I have seen many others than the two linked issues having issues with CLS not always working / maintaning context. You can argue that it will be better if CLS uses async_hooks instead, but I still think it is too magical.

One big issue with CLS is that a user might see a piece of code that uses CLS and thus magically using the transaction, with no indication of how. I've slowly come to the realization, that explicit is almost always better.

I've yet to hear a use-case that could not be solved without CLS, but we're of course open to hear them :)

**Comment by Strate** [comment]
OMG, no, pls, no.
1. looks like bluebird soon will support async_hooks: https://github.com/petkaantonov/bluebird/pull/1472
2. cls-hooked works pretty good
3. context-based transaction is very great feature.
4. in the latest node performance impact was reduced

If you guys consider to remove it entirely, could you please make a point how to opt-in in v6? For example, I can still monkey-patch `query` method to support transaction from context, or somehow else.

**Comment by SimonSchick** [comment]
None of these 4 points are really related to the 3 points why we want to remove it.
1. How does that address the issues with promise interoperability.
2. async_hooks is experimental
3. It can be but the way it works is very error prone for developers, both sides are a little bit subjective tho.
4. In what latest, nodejs release?

I wouldn't mind to see CLS become a 'plugin' type of module for sequelize, maybe we can provide hooks for this.

**Comment by Strate** [comment]
1. This is related to promise interopability because you use bluebird
2. It at least documented =)
3. I see only 2 issues, doesn't look like "error prone"
4. At least in 10, as noted in https://github.com/petkaantonov/bluebird/pull/1472#issuecomment-485281282

@SimonSchick I don't think that I can change your opinion about this, and if you want to remove - remove. But, please, add something to get that functionality back. Hooks sounds gread, "onBeforeQuery" and "onBeforeTransaction" sounds well.

**Comment by SimonSchick** [comment]
@Strate this is not final, hence the `discussion` tag, we might not merge into v6 at all.

**Comment by SimonSchick** [comment]
Also please note that we intent do support node v8+, I kinda want to skip v8 since v12 is coming the next couple days but there is a desire for v8 to be support as well so we can't rely on v10 features 😢

**Comment by Strate** [comment]
@SimonSchick I think that this is not a feature of node v10. async_hooks available on v8, and cls-hooked package is a good alternative to node-continuation-local-storage with same interface (you can use cls-hooked instead of node-continuation-local-storage with sequelize).

**Comment by janmeier** [comment]
Converting CLS to a plugin should be as simple as 

```js
const ns = cls.createNamespace(...);

shimmer.wrap(sequelize, 'query', original => {
  return function wrappedQuery(sql, options) {
    if (options.transaction === undefined) {
      options.transaction = ns.get('transaction');
    }
    original.call(this, sql, options);
  };
});

shimmer.wrap(sequelize, 'transaction', original => {
  return function wrappedTransaction(options, callback) {
    let res;
    ns.run(context => res = original.call(this, options, callback));
    return res;
  };
});
```

Provided that bluebird merges support for async resource, so sequelize doesn't have to use a patched version.

Until that support lands, you should be able to patch sequelize's internal bluebird copy:
```js
require('cls-bluebird')(Sequelize.Promise);
```

**Comment by Strate** [comment]
@janmeier that's great, but don't enough. Created transaction need to be set to context in wrapped "transaction" method. I think it would be great if working example will exists in documentation.

**Comment by janmeier** [comment]
>  Created transaction need to be set to context in wrapped "transaction" method.

I'm not sure I follow?

**Comment by Strate** [comment]
@janmeier current transaction implementation calls to `this.sequelize.constructor._cls.set('transaction', this);`

**Comment by janmeier** [comment]
Previous comment updated.

I don't think this should be part of the official documentation, but live entirely in a plugin (maintained / owned by someone who actually uses CLS, instead of the sequelize tema)

**Comment by Strate** [comment]
@janmeier It is a good idea to make a plugin, and I think I can support that plugin. But, from the sequelize side, it would be great to maintain hooks to make plugin without shiming methods

**Comment by dhans** [comment]
What exactly are the implications of removing support for CLS? Is this removal specific to Sequelize transactions based on CLS, or all use of CLS within a code path that uses Sequelize? 

E.g. if code sets the CLS context, then awaits a Sequelize call, can we still access that CLS context in subsequent code?

Could you point at examples of instances that make it unsafe? What in particular make it behave in surprising ways? What details should developers be aware of when using it?

**Comment by SimonSchick** [comment]
@dhans we are removing cls support only for transactions, if you still use CLS that will still work for everything else.

**Comment by janmeier** [comment]
> we are removing cls support only for transactions, if you still use CLS that will still work for everything else.

We would also remove the bluebird cls patches from sequelize, so you would have to apply cls-bluebird in your own project.

> Could you point at examples of instances that make it unsafe? What in particular make it behave in surprising ways? What details should developers be aware of when using it?

For one, we have seen reports of cls context sometimes being lost in specific situations. And that's likely to happen again, since sequelize manually patches bluebird's methods to maintain the cls context.

The biggest problem to my mind is that it's too magic - The transaction is applied, without being passed as an argument. This does not only apply to the immediate transaction callback, but also to all nested functions and hooks. So one developer might write a hook without considering how it interacts with transactions, but suddenly the transaction is applied in the hook, because of CLS.

One of the original arguments for CLS was actually that it makes it _easier_ to obtain the transaction in nested contexts - And I agree, I just don't think the added ease outweighs the potential problems with reasoning about the code and how it works with transactions. The transaction is already available in the arguments passed to the hook, so I think it's better to be explicit

**Comment by Strate** [comment]
@janmeier 

> So one developer might write a hook without considering how it interacts with transactions, but suddenly the transaction is applied in the hook, because of CLS.

You name it "suddenly", but actually it is a biggest achievement of auto-transaction :) Actually, most frequent case is when you need to use transaction in a hook, than otherwise.

I can agree about "better to be explicit", but currently passing transaction with arguments is very error-prone. You can easily miss transaction in a function stack, and no one tool can help you - nor types, nor linters. CLS become a life-saver here.

As an alternative way to solve that problem, you can avoid from global sequelize instance, available as a module, but make an instance context-based (for example, initialize sequelize on each incoming http request), and pass that instance to related functions/services. That instance can hold transaction object if opened, and without that instance you can't perform query, so, it would become less error-prone.

**Comment by dhans** [comment]
We currently don't use transactions so cls-based transaction support is not an immediate concern for us. That being said, hypothetically, if you wanted to update another model inside of a hook function and do it as part of one transaction, is that possible without CLS? Can you get access to the current transaction in the options object?

Currently cls-hooked appears to work as expected inside of the various hook functions, which we do rely on. Is this dependent on the cls-bluebird patch?

**Comment by frlinw** [comment]
- Transactions are a must-have
- I'm using cls-hooked and it works like a charm
- A lot of people will miss this thread, if you remove cls without a drop-in alternative, expect a lot of cry.
- After upgrading to node v8, is there a reason to not remove bluebird? (which seems to cause some issue with cls)

> The biggest problem to my mind is that it's too magic - The transaction is applied, without being passed as an argument. This does not only apply to the immediate transaction callback, but also to all nested functions and hooks. So one developer might write a hook without considering how it interacts with transactions, but suddenly the transaction is applied in the hook, because of CLS.

I'm wrapping every POST/PUT/PATCH requests in transaction because I don't want to have to do it for each transaction (lot of boilerplate, more error prone)
Developer should know that hooks arre just delayed functions. If they don't, they will have others troubles, not just transaction related one.

**Comment by frlinw** [comment]
It seems to be done in v6. A nice fuck to users. love it.

**Comment by SimonSchick** [comment]
We still want to provide a facility to allow hooking transactions before we make a full release, the current one is just `@next` (which is just to allow people to test).
You are free to create a PR for that too, we are quite busy and won't make an official release for a while.

Also @dhans yes, transactions are usually passed in the query options so this is not a concern.

**Comment by frlinw** [comment]
I'm questioning the process here. you did great by creating this thread.
-> Gather feedbacks about feature removal
-> Result: There is no consensus
The good way:
-> provide an alternative
-> deprecate the feature
-> remove the feature
A bad way:
-> Remove the feature
-> Tell your users you'll think about provide something, someday, maybe, in the future

Rework a feature can take time, if you can't do it the good way, just leave it until you can

**Comment by papb** [comment]
@frlinw - As SimonSchick said, v6 is still in `@next`. So we haven't just dropped a functionality like you are saying.

I believe this issue won't be closed until a proper alternative or migration guide is provided.

**Comment by SimonSchick** [comment]
@papb I am currently extremely time constrained, it would be nice if you could take a look at this.
The idea was to make sequelize somewhat transparent to CLS and then provide a CLS package you can install separately, as a plugin.

**Comment by AiDirex** [comment]
I think doing transactions should be handled explicitly by users regardless of cls usage.
Anyway, I strongly suggest that Sequelize remain compatible with the internal "async_hooks" module. it is needed to pass something like and id for contexts in log lines when using the `logging` option.

**Comment by jdguzman** [comment]
I would like to chime in there and say that in our case using `cls-hooked` resulted from the fact that custom validations don't have access to the transaction context explicitly. I'm sure we aren't the only ones that have complex validation scenarios that when in a transaction context require that to be passed along to queries in custom validators.

I did read about using before/after hooks for this instead as the transaction context, via options, is available there, but that just feels like a hack rather than a real solution. IMO validations should happen in validators custom or otherwise.

**Comment by papb** [comment]
> the fact that custom validations don't have access to the transaction context explicitly

Can you clarify this, perhaps with a little code example in which you show what you would like to have?

**Comment by jdguzman** [comment]
@papb say you have the following (somewhat redacted):

```
        await sequelize.transaction(async () => {
          const newUser = await User.create(input);

          if (orgId) {
            await Membership.create(
              { userId: newUser.id, organizationId: orgId },
            );
          }
        });
``` 

In the membership model there's a custom validation like this (using sequelize-typescript):

```
  @Validator
  private async validateMembership(): Promise<void> {
    const [user, organization] = await Promise.all([
      User.findByPk(this.userId),
      Organization.findByPk(this.organizationId),
    ]);

    if (user.applicationId !== organization.applicationId) {
      throw new Error("User and Organization must belong to same application.");
    }
  }
```
That only works because of cls and the fact that the transaction gets passed into the `findByPk` calls in the validator. Without cls it's not possible to do this and things fail because the transaction isolation prevents `findByPk` from seeing the user created in the transaction.

This is just a simple example of what I was trying to get across. Hope that makes sense.

**Comment by papb** [comment]
@jdguzman That makes a lot of sense. Great explanation. Could you please create a feature request to allow passing the transaction as an argument to the validators? You can basically repeat what you said above. Thanks!!

**Comment by holm** [comment]
I think it would be a massive shame to remove CLS support. As many others have mentioned using Node 8 or higher with `cls-hooked` _just works_ for us. There is never any problems.

Having a transaction per request is a really good practice, and by removing this, you make it hard to do the right think. Passing around a transaction everywhere is a massive pain in the neck, that complicates everything for no good reason. Asking us to pull it out of the current context every call to Sequelize is really error-prone, and running an update outside an intended transaction is not a good thing for your application.

It seems very poor practice to me to ask for an opinion on removing a feature, and then removing it from master even with all the push back here. Is this really such a problem for the maintainers that you have to fully and completely break all applications using CLS with no current alternative?

**Comment by papb** [comment]
> It seems very poor practice to me to ask for an opinion on removing a feature, and then removing it from master even with all the push back here.

@holm It was not removed from master. It is removed in the v6 branch, which is still `@next`. PR #10817 was a partial refactor.

As I said in [another comment](https://github.com/sequelize/sequelize/pull/10817#issuecomment-515578740), I doubt a new major version will be released without providing an equivalent to the previous CLS usage, such as a separate plugin as @SimonSchick mentioned once.

Don't worry, this is why this issue is still open :)

**Comment by mdarveau** [comment]
You are right that CLS used to be a pain when alternate versions of Bluebird resulted in CLS context lost in unexpected ways. I've been debugging this and contributing to fixing such issues in the past. However, as others mentioned, everything went fine when I switched to `cls-hooked`.

Coming from a java world where it's standard to register transactions in a `ThreadLocal` (~equivalent to CLS from a userland perspective), I could not imagine having to pass my transactions around all the time.

If you want to remove support in the core codebase and enable it through a plugin, please make sure it's a supported and well-documented plugin.

**Comment by papb** [comment]
@mdarveau I agree.

**Comment by sushantdhiman** [comment]
Bluebird now supports `async_hooks` with https://github.com/petkaantonov/bluebird/issues/1403. Promises no longer required to be patched with `cls-bluebird`.

With v6 you should use `cls-hooked` https://github.com/sequelize/sequelize/blob/master/docs/manual/upgrade-to-v6.md#cls

For now we are not going to remove CLS support

**Comment by joaopedr0vieira** [comment]
> Converting CLS to a plugin should be as simple as
> 
> ```js
> const ns = cls.createNamespace(...);
> 
> shimmer.wrap(sequelize, 'query', original => {
>   return function wrappedQuery(sql, options) {
>     if (options.transaction === undefined) {
>       options.transaction = ns.get('transaction');
>     }
>     original.call(this, sql, options);
>   };
> });
> 
> shimmer.wrap(sequelize, 'transaction', original => {
>   return function wrappedTransaction(options, callback) {
>     let res;
>     ns.run(context => res = original.call(this, options, callback));
>     return res;
>   };
> });
> 
> shimmer.wrap(sequelize.Transaction, 'prepareEnvironment', original => {
>   return function wrappedPrepareEnvironment(options, callback) {
>     return original.call().then(() => {
>       ns.set('transaction', this);
>     });
>   };
> });
> ```
> 
> Provided that bluebird merges support for async resource, so sequelize doesn't have to use a patched version.
> 
> Until that support lands, you should be able to patch sequelize's internal bluebird copy:
> 
> ```js
> require('cls-bluebird')(Sequelize.Promise);
> ```

Hi, does this code pass an transactions to all queries, even inner function calls? Im looking for a way to do that!
