### ISSUE TITLE
V6: Removing operator aliases

### ISSUE THREAD

**Issue by SimonSchick** [sequelize/sequelize#10820]
With the v6 release we are looking to entirely remove operator aliasing support eg. `$eq` `$gt` `$and` etc. in favor of the symbol based operators introduced in v4 and enabled by default in v5.

Aliased operators are potentially vulnerable to user input injection when passing certain user generated input into sequelize calls.
This is especially problematic for query string parsers that support complex data structures.
For more details please see previous migration guides and documentation.

**Comment by janmeier** [comment]
Yes, _so much yes_ to this one! :taco: !

**Comment by SimonSchick** [comment]
@janmeier feel free to give it a checkmark in the linked PR :)

**Comment by knoxcard** [comment]
Operator aliases are for dinosaurs.............................dinosaurs are extinct.

**Comment by stalniy** [comment]
I don’t think using symbols instead of string keys somehow improves security. 

the issue is not in strings or symbols but in how apps process user input. Even documentation says something like: it will help but don’t forget to sanitize input. With symbols, a dev can make his code vulnerable to injection as well, the only thing which needs to be done is to map string keys to symbol keys. 

Frankly speaking, not a big deal :) I don’t think symbols operators somehow help but add a bit of complexity.

**Comment by SimonSchick** [comment]
@stalniy The issue was that many developers piped user input such as parsed json or the parsed results of certain query string decoders right into sequelize, the latter often came to them as a surprise.

Symbols are ~never~ usually not generated from JSON.parse or querystring parsers, and even if they are they'd still have to be the unique sequelize symbols.
It would be _extremely_ hard to unintentionally get a hold of these and populate an object with them.

In the end it adds another safety net and allowed to to make the where parsers a little bit nicer.

There is even a vulnerability reports for it https://snyk.io/vuln/SNYK-JS-SEQUELIZE-174147

tl;dr
Yes, it's not sequelize's fault.
Yes, it's a developer error due to lack of familiarity with libraries or lack of due diligence.
Yes, we _shouldn't_ have to fix that.

Unfortunately the reality is that it ~is~ was an issue that was widespread enough that we decided to be pragmatic and add another layer of safety and make the best out of it.

**Comment by stalniy** [comment]
I understand what you say but the thing is that it doesn't help much :) This is implementation of user input parser in pure js which converts old queries into new format with symbols:

https://jsbin.com/vuceboziki/edit?js,console

**Comment by SimonSchick** [comment]
🤷‍♂

**Comment by SimonSchick** [comment]
Ironically this is exactly the kind of thing this change was suppose to *prevent*.
If you *really* want to do this (and it sounds dangerous tbh) consider doing a deep key replacement, it's a fairly easy recursive algorithm.

**Comment by kevinlammers** [comment]
Yes, that's what it's supposed to prevent but I fail to understand how doing a deep key replacement fixes the problem. The client is going to need to send some form of operator alias to the server in order to define a where clause. The problem isn't mitigated by removing this functionality, it's simply pushed off onto the developer. There's still going to be this need and the security hole will still exist given that symbols are unique on the server and cannot be passed as part of the JSON body from the client to the server.

**Comment by SimonSchick** [comment]
> `and the security hole will still exist given that symbols are unique on the server`

Can you please elaborate on the security hole you are talking about?

The entire point of the removal of the `$` operators IS that this was seen as a security hole.

> `it's simply pushed off onto the developer.`

So just because *some* part of your application requires user queries you want to allow operator symbols for the entire app, this seems somewhat dangerous.

Here is a snippet that will more or less do what you want (untested cause on phone):

```js
const { Op } = require('sequelize');

function symbolify(obj) {
    if (typeof obj === 'object') {
        for (const key in obj) {
            const isOp = key.startsWith('$');
            if (!isOp) {
                continue;
            }
            const op = Op[key.substr(1)]
            if (!op) {
                continue;
            }
            obj[key] = op;
            delete obj[key];
        }
        return;
    }
    if (Array.isArray(obj)) {
        for (const subArr of obj) {
            symbolify(subArr)
        }
    }
}
```

You can apply this function wherever you want this behaviour instead of enabling it globally.

**Comment by papb** [comment]
> So what is the solution for sending a query from the client to the server?

As Simon said, this is exactly what Sequelize is trying to prevent. So you shouldn't do it, at least not how you worded it...

The only use I can think of what you want to do is SQL injection... Can you please show me of a valid use case for what you're trying to achieve? I fail to imagine why would you want to send an arbitrary query from client to server and have it executed... Thanks!

**Comment by stalniy** [comment]
@kevinlammers it always was the problem of the developer not sequelize (I argued about the purpose of removing operators in previous comments https://github.com/sequelize/sequelize/issues/10820#issuecomment-501959070). 

Now the “life” is a bit more complicated, it’s more complicated to send a silly/hard coded sequelize query from client to server. But it was always a wrong approach!

If you want to do reach filtering or sorting from the client, you need to 
1. create your own client to server language, 
2. create language translator which converts your language into sequelize query. 
3. During translation process don’t forget to prevent different injection attacks.

**Comment by papb** [comment]
> But it was always a wrong approach!

This is also what I thought.

**Comment by mpacary** [comment]
Thanks @SimonSchick for the snippet.
Tested & fixed it, here is the result:
```
function symbolify(obj) {
  if (typeof obj === 'object') {
    for (const key in obj) {
      const isOp = key.startsWith('$');
      if (!isOp) {
        symbolify(obj[key]);
        continue;
      }
      const op = Op[key.substring(1)];
      if (!op) {
        continue;
      }
      obj[op] = obj[key];
      delete obj[key];
    }
    return;
  } else if (Array.isArray(obj)) {
    for (const subArr of obj) {
      symbolify(subArr);
    }
  }
} 
```

**Comment by piboistudios** [comment]
> The only use I can think of what you want to do is SQL injection...

An ORM is supposed to help mitigate this. Having typed queries (basically what an ORM does) is a huge step towards mitigating SQL injection. 

> Can you please show me of a valid use case for what you're trying to achieve? 

 https://jsonapi.org/ (my personal recommendation)
 https://graphql.org/ (my personal dissuasion)
 https://www.odata.org/ (meh)


>I fail to imagine why would you want to send an arbitrary query from client to server and have it executed... Thanks!

Graph-based data access over the web is a thing. It's very easy to set up authorization/access control with it too. And if built as an OpenAPI with schema validation, you get very close to having a built-in WAF. This has worked very well for me in the past with various nodejs ORMs (including `sequelize`). You just build the schemas, the OpenAPI is generated and all requests get validated by the schema. More often than not, the problem is not people accessing data you don't want them to access, it's people _not_ being able to access data you do want them to access (as you assume a user has no access unless an authorization rule is defined).

OpenKoda, Odoo, any ERP/CRM solution you can think of probably has or could greatly benefit from graph-based data access as ERP is a well-defined domain, therefore software developed in those domains is usually domain driven. So the name of the game is adding many types of business objects. Would be very cumbersome to add CRUD routes for them all manually.
