### ISSUE TITLE
Error on Model.Update if prependSearchPath is set to true. cannot insert multiple commands into a prepared statement

### ISSUE THREAD

**Issue by seromenho** [sequelize/sequelize#10875]
## What are you doing?
Model.Update with search_path

```js
const Sequelize = require('sequelize');

const options = {
  dialect: 'postgres',
  logging: false,
  dialectOptions: {
    prependSearchPath: true
  },
  searchPath: 'test'
};

const sequelize = new Sequelize('URL', options);

const User = sequelize.define(
  'user',
  {
    id: { type: Sequelize.UUID, primaryKey: true },
    name: { type: Sequelize.STRING, field: 'full_name' }
  }
);

const id = '33ca7218-569f-4011-96ab-e219cdc8a4e6';
User.update({name: 'test'}, {where: {id}})
  .then(()=> {
    console.log('done');
  }).catch((e)=> {
    console.log('error', e);
  });
```
**To Reproduce**
1. Pass dialectOptions.prependSearchPath =true on contructor and a searchPath
2. Define a Model
3. Add some record
4. Update the added record
5. You'll get an error

## What do you expect to happen?
I expect no error and the update to happen.

## What is actually happening?
It is throwing an error:
```
SequelizeDatabaseError: cannot insert multiple commands into a prepared statement
    at Query.formatError (/home/rseromenho/dev/test-sequelize/node_modules/sequelize/lib/dialects/postgres/query.js:354:16)
    at query.catch.err (/home/rseromenho/dev/test-sequelize/node_modules/sequelize/lib/dialects/postgres/query.js:71:18)
From previous event:
    at Query.run (/home/rseromenho/dev/test-sequelize/node_modules/sequelize/lib/dialects/postgres/query.js:64:23)
    at Promise.try.then.connection (/home/rseromenho/dev/test-sequelize/node_modules/sequelize/lib/sequelize.js:577:22)
From previous event:
    at Promise.resolve.retryParameters (/home/rseromenho/dev/test-sequelize/node_modules/sequelize/lib/sequelize.js:574:10)
    at /home/rseromenho/dev/test-sequelize/node_modules/retry-as-promised/index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (/home/rseromenho/dev/test-sequelize/node_modules/retry-as-promised/index.js:60:10)
    at Promise.try (/home/rseromenho/dev/test-sequelize/node_modules/sequelize/lib/sequelize.js:554:30)
...
```

The SQL: 
```sql
SET search_path to test;UPDATE "users" SET "name"=$1,"updated_at"=$2 WHERE "id" = $3' 
```

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: XXX
Database version: 10
Sequelize version: 5.8.1
Node Version: 8.11.3
OS: Ubuntu
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 

"pg": "^7.10.0",
"pg-hstore": "^2.3.2",
"sequelize": "^5.8.1"

**Comment by itsmepetrov** [comment]
I faced with the same issue while upgrading to v5

**Comment by Rochet2** [comment]
I have the same issue. Also it seems to me like search path is ignored unless you use `prependSearchPath: true`, so it does not look like simply not prepending will allow to use different schema.

As a fix for now I have tried the following code. I hope sequelize keeps a single connection alive - otherwise the setting would be lost when a new connection is made.
```js
const Sequelize = require('sequelize');
const options = {
  dialect: 'postgres',
  logging: false
};
const sequelize = new Sequelize('URL', options);

sequelize.query('SET SESSION search_path to test'); // Set connection schema to test
```

I think sequelize should do the same if prependSearchPath is false. This way the schema is used for the connection and can be temporarily changed with `SET LOCAL search_path to <schema>` for transactions or by specifying schema in the SQL itself like `SELECT * FROM schema.table;`.
https://www.postgresql.org/docs/9.1/sql-set.html

**Comment by Rochet2** [comment]
All worked fine with above code so far .. except..
Seems that our migrations failed because sequelize defaults to hardcoding 'public' schema to migrations done through queryInterface if a schema is not defined explicitly in for example `queryInterface.removeColumn` arguments.
The hardcoded public can be seen here:
https://github.com/sequelize/sequelize/blob/eef1e88db8ea7c0863d745b58a1630e76d0bfeac/lib/dialects/abstract/query-generator.js#L44-L50

For example `queryInterface.removeColumn('table', 'column', { logging: console.log })`
generates the following PSQL: `ALTER TABLE "public"."table" DROP COLUMN "column";`

Due to the way that it is coded it seems to me like the only way to execute the migrations to the proper schema is to define the schema in every call of queryInterface methods (no thanks ..) or by using `prependSearchPath: true` which causes the issue in main post above.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/11236
