### ISSUE TITLE
Update method not returning an instance

### ISSUE THREAD

**Issue by huynhminhtufu** [sequelize/sequelize#10889]
I use MySQL, and the code is:

```
const update = async (req, res) => {
    const id = req.params.id;

    const updatingTracking = req.body;

    try {
        const tracking = await models.tracking.update(updatingTracking, {
            returning: true,
            plain: true,
            where: { id }
        });
        res.send(tracking);
    } catch (err) {
        res.status(422);
        res.send(err);
    }
};
```

The update() always return an array, not the updated instance.

**Comment by SimonSchick** [comment]
The `static update` method does NOT return an instance, it returns information about what rows where updates.
The non static `update` method does return an instance.

I can't find anything in the documentation that suggests otherwise.

Feel free to re-open and point us to the piece of problematic documentation.
