### ISSUE TITLE
Increased database connections in sequelize 5

### ISSUE THREAD

**Issue by deppy** [sequelize/sequelize#10902]
We upgraded from Sequelize 4.x to 5.x recently and have noticed that we are seeing many more connections to our database since the upgrade.  In the graph below you can see that the number of connections (red line) has gone up dramatically since the upgrade on 13 April while the number of servers (green line) has not changed much at all. I see that [pooling changed in v5](https://github.com/sequelize/sequelize/blob/master/docs/upgrade-to-v5.md#Pooling) but it seems that our config should still be valid and that nothing should have changed the number of connections we're seeing. Wondering if anyone else is seeing this because it wasn't an expected behavior.

![Screen Shot 2019-05-03 at 10 19 59](https://user-images.githubusercontent.com/1371279/57130201-0f8f8a80-6d99-11e9-946e-b403cdceebe6.png)

## What are you doing?

```js
  pool: {
    max: parseInt(config.database.pool.max), //Set to 40
    min: parseInt(config.database.pool.min), //Set to 2
    idle: 2 * 60 * 1000,
    acquire: 15 * 1000
  },
```
**To Reproduce**
1. Use the same config on sequelize 4.x and 5.x
2. Generate a bunch of requests and/or async tasks that require the database
3. Compare the number of open database connections

## What do you expect to happen?
I would expect the pool to use roughly the same number of database connections

## What is actually happening?
The number of database connections goes up by roughly 2.5x

## Environment
Dialect:
- [x] postgres
Dialect **library** version: 7.10.0 (pg)
Database version: 10.6
Sequelize version: 5.6.0
Node Version: 11.12.0
OS: Ubuntu 16.04

**Comment by knoxcard** [comment]
Hmm, maybe the pool logic was altered.  Did you try not defining acquire?

```
 pool: {
    max: parseInt(config.database.pool.max), //Set to 40
    min: parseInt(config.database.pool.min), //Set to 2
    idle: 2 * 60 * 1000
  },
```

**Comment by deppy** [comment]
@knoxcard I hadn't, but just now did and it didn't have much of an impact.  Looks like that did change between versions (10s -> 60s) though

**Comment by SnosMe** [comment]
Reproduction

For example:
MySQL `interactive_timeout = wait_timeout = 1h` and `max_connections = 50`
Sequelize v5.8.6 `pool: { min: 2, max: 10 }`

Imagine a night time, a time when startups do not receive requests
1. The connection is inactive for 1 hour, MySQL closes it
2. `sequelize-pool` detects closed connections and restarts them, so now we have **4** in total
3. Yet another 1h
4. `sequelize-pool` detects closed connections and restarts them, so now we have **8** in total
5. Yet another 1h
6. `sequelize-pool` detects closed connections and restarts them, so now we have **16** in total (completely ignoring the `{ max: 10 }`)
7. Yet another 1h
8. `sequelize-pool` detects closed connections and restarts them, so now we have **32** in total
9. Yet another 1h
10. `sequelize-pool` detects closed connections and restarts them, so now we have **50** in total
11. Ooops `max_connections` limit reached.

Waking up in the morning you will have no chance to login using the same username to DB (hope you did not use root).

#### Possible workaround until fixed `min: 0` 

I also use `knex` in parallel, and I do not have this problem. They decided to use a different pool library due to the large number of problems with generic-pool (https://github.com/tgriesser/knex/issues/2339)

**Comment by toxuin** [comment]
We're observing the same problem on sequelize5 migration test environment. Our config is:
`min: 5, max: 10` and after a while we can see connection count go from 5 to 10, then to 20 then to 40 then to 80. Every leap is exactly 8 hours apart.

**Comment by inian** [comment]
We are noticing jumps in connections exactly 8 hours apart as well with a pool configuration of 
```
pool: {
        min: 3,
        idle: 600000,
        max: 10
      }
```

**Comment by itai-sagi** [comment]
We see this happening as-well.
something interesting is that when killing a connection via mysql `kill` command, basically causes sequelize to create 2 more connections. we're still investigating the causes.

**Comment by brenc** [comment]
Seeing exactly what @SnosMe posted. Our `interactive_timeout = wait_timeout = 60` so within a few minutes all available connections are used up. `pool.max` isn't being respected. You can also simply kill a connection to see two more pop up right away.

**Comment by knoxcard** [comment]
@sushantdhiman, @SimonSchick  - emergency 911, :-) Just want you to be aware of this, I'll try to submit a pull request if I can. Thanks for the fantastic work guys.

**Comment by SimonSchick** [comment]
Unfortunaly I don't have time for OSS work atm, mostly due to E3 stuff.
Furthermore I don't have access to the `sequelize-pool` package so there is nothing I can really do for the time being.

If anyone comes up with a fix for this issue I would be willing to merge the pool class into this repo and bypass the publishing issue tho.

**Comment by sushantdhiman** [comment]
I'll take a look at this

**Comment by pankajtiwary** [comment]
Dear All,
Is that problem still persist? If I use connection pool, it opens thousands of un-managed connections. Anyone has got solution of it? Thanks in advance.

**Comment by Ariel-dono** [comment]
Hello everyone, we are facing the same problem with an implementation using sequelize version 6.5.0.

**Comment by pankajtiwary** [comment]
@Ariel-dono , I am able to solve above problem. It was due to App Dynamics Node JS Module we were using. It seems, It was a bug in that module, which was holding the connection live. So as soon as we upgraded (or removed) the AppD code form microservices, every thing started working fine.
