### ISSUE TITLE
Please put v4 docs back up somewhere on website

### ISSUE THREAD

**Issue by jedwards1211** [sequelize/sequelize#10911]
## What are you doing?

I'm trying to fix errors in flow type defs for v4 (we haven't even gotten around to v5 yet) and it seems like the scope API may have changed in various ways.

**Comment by bradennapier** [comment]
+1 - Need the v3 to v4 upgrade guide and its gone now

**Comment by SimonSchick** [comment]
@sushantdhiman please

**Comment by helibin** [comment]
please

**Comment by cjrd** [comment]
same here: are they anywhere in the repo? I couldn't find them

**Comment by jbauerrfid** [comment]
had am similar problem, I need the dos for QueryInterface v4, because `umzug` is not upgraded to v5 yet
but the v4 API is missing

example: https://github.com/sequelize/sequelize/blob/v4/class/lib/query-interface.js~QueryInterface.html returns 404 not found

**Comment by jedwards1211** [comment]
Another thing I've noticed is that the "reference" section isn't present in the `docs` folder of the v4 branch.  I'm guessing it's autogenerated.  So we have no access to API reference for v4.

**Comment by papb** [comment]
That's right, the "reference" section is automatically generated. Unfortunately, browsing the v4 docs is very limited right now (only tutorials can be seen)...

While @sushantdhiman does not publish the v4 docs back somewhere, if you really need to take a look at it, you can always build the documentation from source automatically:

1. Clone the sequelize repo
2. Git checkout to the latest v4 tag available
3. Run `npm run docs`
4. A folder called `esdoc` will be automatically generated (it will take a while). The documentation will be there, open `index.html` in your browser.

*Note:* if part of the docs look weird/unusual, try serving the `esdoc` with a local HTTP server instead of opening from `file://`, this helped me once. In other words, instead of just opening `esdoc/index.html` directly, do `cd esdoc && npx http-server` and open `http://localhost:8080/index.html` instead.

**Comment by sushantdhiman** [comment]
`v4` docs now available https://sequelize.github.io/v4/

**Comment by jedwards1211** [comment]
Thanks @sushantdhiman!
