### ISSUE TITLE
hasOne 'as' option produces wrong foreign key

### ISSUE THREAD

**Issue by demosglok** [sequelize/sequelize#10972]
## What are you doing?

i'm adding hasOne relationship with {as: ''} option, which leads to foreignKey in target table to be derived from alias name. Though same example is in docs, that is not what i'm expecting
```js
models.User.hasOne(models.Device, {as: 'Calculator'})
```
which leads to query SELECT .. LEFT OUTEER JOIN `Devices` As `Calculator` ON `User`.`id` = `Calculator`.`CalculatorId` instead of `Calculator`.`userId`

**To Reproduce**
1. Define models X, Y
2. Set association 'hasOne' with alias:  X.hasOne(Y, {as: 'Z'})
3. See error in query, Z.ZId instead of Z.XId

## What do you expect to happen?
I want foreign key on target table to be left untouched and derived from source table

## What is actually happening?
foreign key is derived from alias instead of source table name

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [*] sqlite
- [ ] mssql
- [ ] any
Sequelize version: 5.7.3
Node Version: 10.x
OS: windows 10

**Comment by 2kindsofcs** [comment]
the same thing happens when using mysql, too. 

By the way, according to the [doc](https://sequelize.org/v5/class/lib/model.js~Model.html#static-method-hasOne), it says

>  hasOne method creates an association between this (the source) and the provided target. 

and the description of `options.as` says 

> The alias of this model, in singular form.

as the doc says that `this` means the source, if there is an 'as' option then it seems normal to get `alias.Id` rather than `source.Id`.  I think it's just workig as same as the document implies. 

@papb if there's an 'as' option when using hasOne method, the foreign key added to the target table should be `source.Id` ?

**Comment by papb** [comment]
@2kindsofcs Thanks for the post, I don't think this is a bug, OP should probably use `Device.belongsTo(User, { as: 'Calculator' })` instead and it would probably work as they want.

About the docs improvement, I agree they need to be improved but leave it to me, I'm already working on it so let's not duplicate work :)

**Comment by brianle1301** [comment]
@papb But that wouldn't add the mixin to the source model? (i.e you can't do `user.getCalculator()`?)
