### ISSUE TITLE
Reading latitude and longitude from GEOGRAPHY data type

### ISSUE THREAD

**Issue by euglv** [sequelize/sequelize#11039]
### I have found how to insert new data into GEOGRAPHY column:
```
let lat =  51.509865,
    lng = -0.118092;
apartment = {
    name: 'Apartment Name',
    location: {
        type: 'Point',
        coordinates: [lng, lat]
    }
};
Apartments.create(apartment);
```

But I can't find how to read coordinates back from the database.
I insert JSON object to the database, but when I read it - geography data is returned as `Buffer` object with some HEX encoded string inside, not as original JSON object.

**Comment by PeledYuval** [comment]
Hi @euglv, 

The data is returned in a format called WKB, which is indeed a binary encoded in HEX. For more info read [here](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#Well-known_binary).

You can use the [wkx](https://www.npmjs.com/package/wkx) library to decode the data, like so:
```
// assuming "buffer" is a variable holding your binary-hex wkb data:
const geoJson = wkx.Geometry.parse(buffer).toGeoJSON();
```

**Comment by papb** [comment]
> I insert JSON object to the database, but when I read it - geography data is returned as Buffer object with some HEX encoded string inside, not as original JSON object.

If this is true, this is a bug, not a docs issue. Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) for this.

**Comment by yocontra** [comment]
@papb This bug seems to have popped back up for me recently - There is no `parse` for the Geography data type in the postgres data-types, but there is one for Geometry. Receiving a Geography value in a basic query (ie `SELECT ST_Centroid(field)`) yields a binary blob instead of a JSON object. It depends on the way PostGIS is installed/compiled - on some postgres instances it works fine, and others it does not.

Working PG docker image: https://hub.docker.com/layers/circleci/postgres/13-postgis/images/sha256-f7088b14985ff5898b45b454d781ee4f4ed21c0d46ed3238e7e8226e18023a5e?context=explore
Non-working PG docker image: https://hub.docker.com/layers/cimg/postgres/15.1-postgis/images/sha256-feadf37f498fec1db3d9b9fc3d72fecd6fd54a0d67f305b6b3769a2c14959aca?context=explore

**Comment by ephys** [comment]
The current issue is very unclear, and it's possible that your issue is not the same as the one in this thread. I recommend opening a new bug report with your issue so we can handle it separately

**Comment by WikiRik** [comment]
> Please reopen. We have the same problem

Does this occur on the latest v7 alpha as well? We've rewritten the DataTypes code extensively. You can download that under the package name `@sequelize/core`

**Comment by WikiRik** [comment]
I've made a PR to fix the incorrect link. Our implementation of sqlite does not support GEOMETRY. We welcome PRs from the community that adds this. Btw; we do not recommend using a different database engine for development/test than used on production since each dialect has different features and might behave differently.
