### ISSUE TITLE
Can we express GENERATED COLUMN added INDEX with schema file ( MySQL )

### ISSUE THREAD

**Issue by mztnnrt** [sequelize/sequelize#11123]
##### What was unclear.

Can we express GENERATED COLUMN added INDEX with schema file ?
We want to express below SQL to Sequelize schema file.

```sql
CREATE TABLE jsontable (
  id INTEGER,
  json_data JSON,
 # ✅ Generated Column
  user_id INTEGER GENERATED ALWAYS AS (json_unquote(json_extract(`json_data`,'$.user_id'))) VIRTUAL,  
  PRIMARY KEY(id)
  );
 INSERT INTO jsontable(id, json_data) VALUES(1, '{"name": "Kevin", "user_id": "111"}');
 INSERT INTO jsontable(id, json_data) VALUES(2, '{"name": "Jonh", "user_id": "222"}');
 ALTER TABLE jsontable ADD INDEX (user_id);  # ✅ ADD INDEX into GENERATED COLUMN
```

```js
/**
 * Test Table
 * @param {Sequelize} sequelize instance
 * @param {*} DataTypes data types
 */
module.exports = (sequelize, DataTypes) => {
  const JsonTests = sequelize.define('JsonTests', {
    id: {
      type: DataTypes.INTEGER.UNSIGNED,
      primaryKey: true,
    },
    json_data: {
      type: DataTypes.JSON,
      allowNull: false,
    },
// ---- ↓WE WANT TO EXPRESS GENERATED COLUMN↓ HOW TO? ----
    user_id: {
      type: DataTypes.INTEGER.UNSIGNED,
      allowNull: false,
    },
  }, {
   // Options...
    tableName: 'json_tests',
    timestamps: true,
    charset: 'utf8',
    indexes: [
        {unique: false, fields: ['id']},
// ---- ↓WE WANT TO ADD INDEX TO user_id ↓HOW TO? ----
        {unique: false, fields: ['user_id']},
     ]
  });

  return JsonTests;
};

```

I'm looking for information from the document, but because I couldn't find it, I made an issue.
It would be nice if you could tell me if you know.

**Comment by malyzeli** [comment]
I'm also in need of `GENERATED` columns support, since defining column as `autoIncrement` does not automatically prevent explicit value insertion, which can cause problems...

See those two questions and aswers on Stack Overflow for detailed explanation:
- [Postgres autoincrement not updated on explicit id inserts](https://stackoverflow.com/questions/9108833)
- [PostgreSQL serial vs identity](https://stackoverflow.com/questions/55300370)

I am not sure if this is related to Postgres only, but it would be nice to support this feature anyway.

As a quick workaround you can remove `id` values using `beforeCreate` hook, but unfortunately you have to define that for every single model individually...

```js
const ignoreField = field => (entity, options) => {
  options.fields = options.fields.filter(col => col !== field);
};

database.define(
  "user",
  {
    id: {
      type: Sequelize.INTEGER,
      allowNull: false,
      autoIncrement: true,
      primaryKey: true,
    },
  },
  {
    hooks: {
      beforeCreate: ignoreField("id"),
    },
  }
);

```

I did a quick search through the repository and there does not seem to be any implementation of `GENERATED ALWAYS` query (you can see results [here](https://github.com/sequelize/sequelize/search?q=GENERATED+ALWAYS)), so I suppose it's not possible to define that in the model. You can probably create such column using raw SQL query, but that's not an ideal solution.

It would be nice if Sequelize could at least automatically remove values for `autoIncrement` columns before passing entity data to the query builder, as shown in my code snipped above.

I might try to write a plugin for that, but unfortunately I didn't find any official documentation on writing plugins...

Will appreciate if anybody can give some hints or at least point us in the right direction!

**Comment by malyzeli** [comment]
@mztnnrt please consider renaming the issue to something like "Support GENERATED columns in model definition" so it's explicit and hopefully also more visible.

**Comment by papb** [comment]
@mztnnrt @malyzeli Hello, thanks for this.

@malyzeli You said:

> As a quick workaround you can remove `id` values using `beforeCreate` hook, but unfortunately you have to define that for every single model individually...

But you can actually do it only once by setting up [global hooks](http://docs.sequelizejs.com/manual/hooks.html#global---universal-hooks), right?

**Comment by malyzeli** [comment]
@papb good point, global hooks makes it easier! 

The only thing is it will expect all fields to have same name, so we can't have for example `userId` for `User` table and `orderId` for `Order` table, but I think that's not a problem...

Can we somehow dynamically ignore all fields defined as `autoIncrement` whatever their name is?

I am thinking about using `afterDefine` hook to check if field is `autoIncrement` and then adding this `ignoreField` function as `beforeCreate` hook for given model.

But I don't like the fact we have to run `filter` repeatedly - it would be better to remove such fields from `options.fields` in advance, so we don't have to run the hook with each query. 

The hard part is it would have to modify `fields` only for `Model.save` method and not for the others.

Is there a way to do that?

As I said before, I might try to write a plugin, if somebody can point me in the right direction. Does something like project skeleton for plugin code exist? I checked codebase of [`sequelize-hierarchy`](https://github.com/overlookmotel/sequelize-hierarchy) plugin, but it is quite complex and I'm not sure if that's the correct way...

**Comment by papb** [comment]
You have good points! Currently there is no guideline as for how to write a plugin, but I think that would be a great thing to have. Maybe I can look into it in the future.

But as for this specific problem, wouldn't it be better to just add a new feature to sequelize, allowing one to pass `preventExplicit: true` in the field definition and then sequelize would automatically ignore the field before creation?

**Comment by papb** [comment]
> You have good points! Currently there is no guideline as for how to write a plugin, but I think that would be a great thing to have. Maybe I can look into it in the future.

For this, check #2508. Short story: this was discussed in the past but nothing was decided...
