### ISSUE TITLE
Sequelize Migration with Transaction

### ISSUE THREAD

**Issue by furick1** [sequelize/sequelize#11188]
How can I convert the following to a transaction because when running it through local Postgres I got a failure that the column can't be added because it already (still) exists.  It looks like the prior remove is not completing before the add runs.  It is necessary to do the remove and then add because there isn't an alter that will support changing certain attributes. I know we will lose data in that field.

```
module.exports = {
  up: (queryInterface, sequelize) => {
    const migrations = [];
    migrations.push(queryInterface.removeColumn('data_analyst_profiles', 'verticals_experience'));
    migrations.push(queryInterface.addColumn('data_analyst_profiles', 'verticals_experience', {
      type: sequelize.STRING,
      allowNull: true,
      defaultValue: null,
    }));
    return Promise.all(migrations);
  },
  down: (queryInterface, sequelize) => queryInterface.removeColumn('data_analyst_profiles', 'verticals_experience'),
};
```

The example I have seen for transaction is as follows but am having trouble merging the two and getting it to work with sequelize migrations. Are transactions supported in migrations or is there a better way to do this without having to split up the migrations?

```
return sequelize.transaction({type: Sequelize.Transaction.TYPES.EXCLUSIVE}, transaction => {
  // your transactions
}).then(result => {
  // transaction has been committed. Do something after the commit if required.
}).catch(err => {
  // do something with the err.
});
```

**Comment by papb** [comment]
Hello, thanks for using sequelize.

For questions like this, please use StackOverflow.

By the way, now that I read your question anyway, here is the answer:

1. Transactions do work with migrations, but your problem has nothing to do with migrations.

2. Your problem is due to a misunderstanding of how Promises work. You are dispatching the `removeColumn` and `addColumn` queries in parallel. You should remove the column first and only then add the column, so you need to use the usual `.then` structure.

**Comment by furick1** [comment]
Thanks for the .then @papb  .  Transaction
