### ISSUE TITLE
`dropTable` not working as `map` parameter

### ISSUE THREAD

**Issue by artjoms-faltins** [sequelize/sequelize#11310]
## What are you doing?

```js
module.exports = {
  up: (queryInterface, Sequelize) =>
    Promise.all(['table1', 'table2'].map(queryInterface.dropTable))

```

## What do you expect to happen?
This should work, instead I do need to use this
```js
module.exports = {
  up: (queryInterface, Sequelize) =>
    Promise.all(['table1', 'table2'].map(table => queryInterface.dropTable(table)))
```

## What is actually happening?
ERROR: Cannot read property 'QueryGenerator' of undefined

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Database version: 9.6.9
Sequelize version: 4.42.0
Sequelize-cli version: 5.5.0
Node Version: v8.11.3
OS: MacOS
Tested with latest release:
- [ ] No
- [x] Yes

**Comment by papb** [comment]
Passing a function like this in JavaScript makes it ["lose the bind context"](https://stackoverflow.com/q/2701987).

This is not a problem with Sequelize. This is standard JavaScript behavior.

You can "fix" it by using `queryInterface.dropTable.bind(queryInterface)` instead of `queryInterface.dropTable`.
