### ISSUE TITLE
typings for `FindAttributeOptions` incorrect

### ISSUE THREAD

**Issue by jpollard-cs** [sequelize/sequelize#11377]
## Issue Description

The typings for `FindAttributeOptions` appear to be incorrect. They do not work as expected with the Sequelize `Literal` type.

### What are you doing?

Upgrading to Sequelize 5 doing something like this will no longer compile in TypeScript`

```
    return FooModel.findAll({
      attributes: [Sequelize.literal('DISTINCT ON ("someColumn") 1'), ...Object.keys(FooModel.rawAttributes)]
    });
```

### What do you expect to happen?

`attributes` should accept `[Literal, ...string[]]` or similar (not sure on the specifics here, but I imagine there may be a need for other types to be supported) - if I do the following it seems to work without issue (indicating it's just a problem with the typings and not an otherwise breaking change):

```
    return FooModel.findAll({
      attributes: [Sequelize.literal('DISTINCT ON ("someColumn") 1'), ...Object.keys(FooModel.rawAttributes)] as any
    });
```

### What is actually happening?

```
Type '(string | Literal)[]' is not assignable to type 'FindAttributeOptions'.
  Type '(string | Literal)[]' is not assignable to type '(string | [string | Literal | Fn, string])[]'.
    Type 'string | Literal' is not assignable to type 'string | [string | Literal | Fn, string]'.
      Type 'Literal' is not assignable to type 'string | [string | Literal | Fn, string]'.
        Type 'Literal' is not assignable to type '[string | Literal | Fn, string]'.
```

### Environment

- Sequelize version: 5.17.2 
- Node.js version: latest 10.x
- Operating System: latest macOS
- If TypeScript related: TypeScript version: 3.5.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by jpollard-cs** [comment]
@papb @sushantdhiman does `status: understood` label indicate I should move forward with a fix? Should I just go ahead with `[Literal, ...string[]]` or is there more this type definition should support?

I should be able to get to this next week.

**Comment by papb** [comment]
Hello! `status: understood` means that the problem described by the issue was understood by maintainers. This is useful because most issues lack information, or we are waiting for a response, or we are not sure it is a real issue, etc. Issues labeled `status: understood` are the ones for which PRs are welcome.

> (not sure on the specifics here, but I imagine there may be a need for other types to be supported)

> Should I just go ahead with `[Literal, ...string[]]` or is there more this type definition should support?

Hmmm, after taking a deeper look, I have a question:

```js
return FooModel.findAll({
  attributes: [
    Sequelize.literal('DISTINCT ON ("someColumn") 1'),
    ...Object.keys(FooModel.rawAttributes)
  ]
});
```

Are you sure the code you posted (repeated above) should work? After checking the typings, looks like they are trying to force you to do the following instead:

```js
return FooModel.findAll({
  attributes: [
    [Sequelize.literal('DISTINCT ON ("someColumn") 1'), 'some alias for this attribute'],
    ...Object.keys(FooModel.rawAttributes)
  ]
});
```

Which seems a logical attempt from the typings perspective. However, it seems from your example, that this literal in the attributes option is actually a nasty workaround for DISTINCT, right? `DISTINCT ON ("someColumn") 1` does not seem like an attribute... The `1` in the end even gives it a 'injection' feel.

I am actually starting to think that typings are correct. This usage example looks like a nasty workaround... If you really need to do that, then adding a forced type cast in TS would also be acceptable.

Am I wrong in my analysis? (I could be, not an expert in this part)

**Comment by jpollard-cs** [comment]
To be honest I've just been upgrading from 4 to 5 and not really questioning the code (the upgrade has been pretty brutal due to our reliance on `sequelize-typescript`) 😄 
Not sure on the reasoning behind this weird bit of code - I'll look into it. Either way it does seem like your suggested approach, with an alias, would be fine. I think I may have misinterpreted the typings here. I'll close for now and reopen if that doesn't work or a suitable work-around can not be devised.

@papb @sushantdhiman On a side note discriminated union types may help clarify valid use cases for some of these typings, but I recognize that may represent a potential explosion in valid input types (although these are cases that really should be identified anyways).
