### ISSUE TITLE
Sequelize.fn doesn't work with bind replacements if value has `$` in it 

### ISSUE THREAD

**Issue by andrew8088** [sequelize/sequelize#11533]
### What are you doing?

I'm inserting a record and using a database function (like `upper`) to format a field with a `$` in it.

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/11

```js
// more details in the link above

const User = sequelize.define('User', {
	name: DataTypes.TEXT
});

await User.create({
	name: sequelize.fn('upper', '$user3')
});
```

### What do you expect to happen?

I expect to successfully insert the record.

### What is actually happening?

I get the error: 

```
Named bind parameter "$user3" has no value in the given object.
```

### Environment

- Sequelize version: 5.16.0
- Node.js version: 10.15.0
- Operating System: MacOS X, Linux

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by papb** [comment]
Thanks for the report!!

> ### Would you be willing to resolve this issue by submitting a Pull Request?
> * [x]  Yes, I have the time but I don't know how to start, I would need guidance.

Fantastic. What kind of guidance do you want? The solution to this problem is probably to detect that the string given by the user has a `$` in it and escape it properly. If you don't know how to start, I suggest you start by creating a failing test. Let me know if you need further help.

**Comment by zacharysierakowski** [comment]
I spent some time looking into this as well. Should this actually be escaped? As I followed the code path to where I think the escape should happen, I got worried it could effect other instances of `Utils.SequelizeMethod`.

If we escape it, won't that mean that there is no support for variables? Maybe the solution here would be to document that if you need to do this, make sure to escape the dollar signs on your own. If you are aware of this and know to escape it when using `sequalize.fn`, it works as expected. 

For example:
```
sequelize.fn('upper', '$$user3')
```
will result in `$USER3` right now.

Heads up - this is the first time I've looked at Sequelize code, so there might be some history or context here that I'm missing. I'd be happy to put a PR up if it's decided that `$` should definitely be escaped.

**Comment by zacharysierakowski** [comment]
I created the PR above mainly as an example for now, but it also couldn't hurt to leave it in the codebase depending on the outcome of discussion in this issue.

**Comment by papb** [comment]
@zacharysierakowski Thanks for taking the time to help us!!

> If we escape it, won't that mean that there is no support for variables?

Hmmm... Can you show an example of variable usage with `sequelize.fn`? Thanks

**Comment by zacharysierakowski** [comment]
I'm not sure of an example of this, but was mainly pointing it out to be cautious. I got worried about escaping the dollar signs so deep in the logic of the code. To be more specific, I got down to the `handleSequelizeMethod` in the abstract dialect query-generator. 

https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L2128 was where I stopped. I believe this is where we could escape the dollar signs (by changing any '$' to '$$' I think), but was worried that by doing that, we might effect other callers of `handleSequelizeMethod`. Maybe that's fine, or maybe there is a better location in the code to escape that would be more isolated. I'm honestly not sure since I don't have much knowledge on `sequelize` itself.

**Comment by papb** [comment]
I see... Well I personally don't see a usage for an unescaped dollar sign there. Would you be willing to try implementing the automatic escape (to be used always) and confirm that no previous PR is broken by https.

**Comment by andrew8088** [comment]
@papb Thanks, I'll take a stab at this early next week!

@zacharysierakowski I can see what you're saying ... I'm gonna give it a try, just for fun, whether or not it ends up in the codebase.

**Comment by zacharysierakowski** [comment]
Okay, I'll hold off on anything else for now. Thanks @andrew8088!

**Comment by andrew8088** [comment]
@papb FYI, working on this with @schopr9

**Comment by papb** [comment]
Fixed by #11533

**Comment by danieltigse** [comment]
I am having the same problem but with an update
```js
const threadIds = ["05ff01d5e137$7b9dfce0$72d9f6a0$@xx.com"]
Email().update(params, { where: { threadId: threadIds } });
```
Stacktrace:
```
Error: Named bind parameter "$7b9dfce0" has no value in the given object.
    at ./sequelize/lib/dialects/abstract/query.js:102:15
    at String.replace (<anonymous>)
    at Function.formatBindParameters (./sequelize/lib/dialects/abstract/query.js:87:15)
    at Function.formatBindParameters (./sequelize/lib/dialects/sqlite/query.js:35:27)
    at ./sequelize/lib/sequelize.js:618:52
```

**Comment by Srkl** [comment]
Similar problem here using the function JSON_EXTRACT. 

The call
`sequelize.fn('JSON_EXTRACT', db.sequelize.col('custom_fields'), '$.F01')`

The loggs show that it is translated to:
`JSON_EXTRACT(`custom_fields`, '$$.F01')`

All the MySQL functions that deal with JSON objects use the symbol $ to identify the key of the object. Because Sequelize adds an extra $ to the query, none of the functions can be used.

**Comment by WozHuang** [comment]
To avoid escaping dollar sign when using JSON_EXTRACT:
```
sequelize.fn('JSON_EXTRACT', sequelize.col('aa.bb.field'), sequelize.literal(`'$.attr'`))
```

Logs:
```
JSON_EXTRACT(`Model->aa->bb`.`field`, '$.attr')
```
