### ISSUE TITLE
Stop providing a default `id` attribute for models

### ISSUE THREAD

**Issue by papb** [sequelize/sequelize#11830]
The default `id` that Sequelize provides for models is often source of confusion.

```js
const Foo = sequelize.define('foo', {
  name: DataTypes.STRING
});
```

Is actually equivalent to

```js
const Foo = sequelize.define('foo', {
  id: {
    type: DataTypes.INTEGER,
    allowNull: false,
    primaryKey: true,
    autoIncrement: true
  },
  name: DataTypes.STRING
});
```

It has the obvious advantage of less boilerplate code. However, it is often source of confusion and weird errors, such as in issue #11723 (as clarified in [this comment](https://github.com/sequelize/sequelize/issues/11723#issuecomment-560881383)) and #11714

I suggest a breaking change of no longer providing this default attribute. Let's make users define them. This way this kind of confusion will never happen.

**Comment by papb** [comment]
This might be related, I didn't check carefully though: #7800

**Comment by gamburgm** [comment]
I think this is a great idea! I do wonder how possible it would be for Sequelize to check the schema of a particular table in the database. It would be cool if it could identify an `id` appearing in the table in the schema (but not explicitly defined) and automatically inserting an integer if it knows that the `id` is present in the table, but otherwise leaving it alone. Other than that, though, this seems like the best compromise. 

Thanks for making this happen :)

**Comment by papb** [comment]
> It would be cool if it could identify an `id` appearing in the table in the schema (but not explicitly defined) and automatically inserting an integer if it knows that the `id` is present in the table

This looks like the feature request from #11770, would be good but probably quite hard to implement correctly...

Thanks!

**Comment by soryy708** [comment]
Related: https://github.com/sequelize/sequelize/issues/12096 https://github.com/sequelize/sequelize/issues/12092

**Comment by soryy708** [comment]
The feature of auto-generating the `id` column is indeed useful for minimizing boilerplate, but it does cause various problems. The type of problems caused touch on many sequelize subsystems and tend to be complicated edge cases.
Fixing all of the issues caused by the auto-generated `id` column may require a lot of effort. Removing the `id` column auto-generation would mean a breaking API change, but the effort required for migration is very small (and perhaps can be automated with a tool).
This issue was open since 2016, and it looks like no one's in opposition to the removal.

**Comment by Keimeno** [comment]
Will have a look into this, I suppose adding a `generatePrimaryKey` boolean into the options might be a good solution

**Comment by soryy708** [comment]
That's a good idea @Keimeno .
To maintain backwards compatibility, `generatePrimaryKey` will be `true` by default (current behaviour). We can then print a warning to the log if `generatePrimaryKey` isn't explicitly present, s.t. a version later we can change the API to make it `false` by default.

**Comment by Keimeno** [comment]
Created a PR for this, @soryy708 maybe you could look over it. Also; I think that the name `id` could be better suited as name for the option, as `createdAt` and `updatedAt` are similar and also named after their column name.

**Comment by damms005** [comment]
Perhaps, if the auto-generation of the id column is made very conspicuous in the docs.
