### ISSUE TITLE
Kill running query on MySql while working with Sequelize

### ISSUE THREAD

**Issue by talpazz** [sequelize/sequelize#12247]
Hi

We are using Sequelize in our project to work with MySQL DB.
we build dynamic tabular report with multiple actions. 
in some cases when the user doing some actions we might need to kill old query that not needed anymore because new query will replace his place.
we tryied to user the transaction rollback but it's seems to work just when the query not committed to the DB. 

My question - there is any why in Sequelize abort queries in DB?  or alternatively to get the query id in DB so we will kill it on direct access ?

we already opned stackoverflow:
https://stackoverflow.com/questions/61659699/kill-running-query-with-sequelize

Thanks in advanced,
Tal

**Comment by sushantdhiman** [comment]
> we tryied to user the transaction rollback but it's seems to work just when the query not committed to the DB.

You meant it doesn't work? As per my understanding you either commit or rollback. So rollback should work when you haven't committed. Can you explain a bit what happens when you rollback?

Every transaction has a `connection` attached, you can get thread id from that connection and kill queries related to that thread id

-  `transaction.connection` https://github.com/sequelize/sequelize/blob/784712e868a7f77fb23d87361b2238922ceec0f5/lib/sequelize.js#L607
-  `threadId` https://github.com/sidorares/node-mysql2/blob/0c913ea965ed5c1eb26ed37064bce6f1e38d2095/lib/connection.js#L66
