### ISSUE TITLE
[Milestone placeholder] Do not release v6 without fixing cli#895 first

### ISSUE THREAD

**Issue by papb** [sequelize/sequelize#12279]
Do not release v6 without fixing https://github.com/sequelize/cli/issues/895 first

**Comment by sushantdhiman** [comment]
I would like to release v6 soon, I think this is the last issue that we need to cover before we publish v6 to latest tag.

Although this requires some sort of updates/modernization to CLI, I'll try to find some time for that, basically move CLI to TypeScript. @papb if you are interested in that, let me know. Otherwise I'll try to find some time for this update operation.

**Comment by papb** [comment]
Hi! Sorry I haven't helped much these days, I have been busier than usual. Modernizing the CLI is something that I wanted to do since last year, but haven't found the time yet. I think for Sequelize v6 a simpler fix in CLI is enough, just rewrite a little bit the part of the code that uses `sequelize.import`. I don't think other modernizations are necessary.

My suggestion is that one of us just makes a mini change to the CLI only to avoid `sequelize.import`. Further modernization can be in another time.

**Comment by sushantdhiman** [comment]
You have help a lot @papb :) 

I agree that we just need to remove `import` usage for now, I'll take care of that.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/cli/pull/901
