### ISSUE TITLE
sequelize.import is not a function

### ISSUE THREAD

**Issue by AryanChothani** [sequelize/sequelize#12559]
const fs = require('fs');
     const path = require('path');

     module.exports = {
     load({ sequelize, baseFolder, indexFile = 'index.js' }) {
     const loaded = {};

    fs
       .readdirSync(baseFolder)
       .filter((file) => {
       return (file.indexOf('.') !== 0) && (file !== indexFile) && (file.slice(-3) === '.js');
      })
      .forEach((file) => {
      const model = sequelize['import'](path.join(baseFolder, file));
      const modelName = file.split('.')[0];
     loaded[modelName] = model;
     });

    Object.keys(loaded).forEach((modelName) => {
        if(loaded[modelName].associate) {
        loaded[modelName].associate(loaded);
      }
      });

        loaded.database = sequelize;

        return loaded;
    }
    };

i am not able to understand changes this is my [repository](https://github.com/AryanChothani/node_boilerplate)

**Comment by papb** [comment]
The `sequelize.import` method was deprecated in v5 and removed in v6. Your code seems to be based on the old version of our [express-example](https://github.com/sequelize/express-example) package. Please take a look at [the new example](https://github.com/sequelize/express-example/tree/master/express-main-example) which does not use `sequelize.import` anymore.

In short, you just have to call `sequelize.define` directly, instead of relying on `sequelize.import` to do this automatically for you.
