### ISSUE TITLE
LIKE op value start with '%f' generates wrong sql

### ISSUE THREAD

**Issue by raphaelsoul** [sequelize/sequelize#12570]
Hi there I am stepping into an unexpected sql generation issue with Operator `LIKE`.

See detailed below. The running sql is not expect when querying like start with `%`.
expecting `"Category"."title" LIKE '%foobar'`
I believe it should be an escape issue.
![image](https://user-images.githubusercontent.com/8615787/88876276-7f6b1a00-d255-11ea-9a6e-8dd7453d98c8.png)

#### use case 1:
`[Op.like]: "%poobar"`
generates `"Category"."title" LIKE '%poobar'`
it is all good.

#### use case 2
`[Op.like]: "foobar%"`
generates `"Category"."title" LIKE 'foobar%'`
it is all good.

#### use case 3:
`[Op.like]: encodeURIComponent("%foobar")`
generates: `"Category"."title" LIKE '%25foobar'`

#### use case 4
`[Op.like]: encodeURIComponent(";SELECT 1 + 1;")` and `[Op.like]: ";SELECT 1 + 1;"` 
generates `"Category"."title" LIKE '%3BSELECT%201%20%2B%201%3B'` and `"Category"."title" LIKE ';SELECT 1 + 1;'`
all good

using versions:
nodejs@14.5.0
sequelize@5.22.3
sequelize-typescript@1.1.0
typescript@3.9.6
ts-node@8.10.2
postgresql@10

**Comment by Spekpannenkoek** [comment]
It looks as if there's a call to a function (that works) like the classic `sprintf()`. `%f` would be a placeholder for a float—in your examples `%f` is replaced by 3,2,4—but `%p` is not a placeholder, so that's why it would show up as expected, same goes for the `%` in `foobar%`.

I'm not aware of `sprintf` (or similar) usage in Sequelize itself. There is an issue from 2015 that indicates that it's a dependency of the Mssql driver. Are you using that? Or are you using `sprintf` yourself?

Is the actual query that's being run wrong as well, or just debug output?

**Comment by raphaelsoul** [comment]
@Spekpannenkoek thank you. agree with your statement about sprintf
Firstly I had checked my `yarn.lock` there is indeed something like `sprintf`
[dep-tree.txt](https://github.com/sequelize/sequelize/files/5000263/dep-tree.txt)
* sprintf-js@~1.0.2:
* extsprintf "^1.2.0"

but they should be brought from `jest` or `babel` as child dependencies.

As for the output, the running sql was captured by constructor option `logging` of sequelize. And then send to `log4js` to print into stdout

**Comment by Spekpannenkoek** [comment]
According to [Log4js' documentation](https://log4js-node.github.io/log4js-node/api.html):

> If you’re using the basic, coloured or message pass-through layouts, the logged string will have its formatting (placeholders like %s, %d, etc) delegated to util.format.

`Util.format` has a `%f` placeholder, so it seems this is 'just' a display issue caused by log4js. Maybe you can use your own formatter that doesn't use `util.format`? Or perhaps before passing the log message to log4js you could escape the % character / wrap the default log output.

It seems to me that this problem's not in Sequelize itself. Hope this helps!

**Comment by raphaelsoul** [comment]
> According to [Log4js' documentation](https://log4js-node.github.io/log4js-node/api.html):
> 
> > If you’re using the basic, coloured or message pass-through layouts, the logged string will have its formatting (placeholders like %s, %d, etc) delegated to util.format.
> 
> `Util.format` has a `%f` placeholder, so it seems this is 'just' a display issue caused by log4js. Maybe you can use your own formatter that doesn't use `util.format`? Or perhaps before passing the log message to log4js you could escape the % character / wrap the default log output.
> 
> It seems to me that this problem's not in Sequelize itself. Hope this helps!

![image](https://user-images.githubusercontent.com/8615787/89123918-9c2d7900-d505-11ea-887a-0de8c634896c.png)
@Spekpannenkoek  Indeed. the raw sql generated is correct.  seems to be `log4js`'s problem.
Thank you
