### ISSUE TITLE
is there any way to pass the connection when consulting a model?

### ISSUE THREAD

**Issue by PQMISSCMP** [sequelize/sequelize#12720]
Hi all,
Is there any way to pass the connection when consulting a model?
I am using typescript and multiple connections to servers with the same databases, tables, models, etc, Currently the connection must be defined before with the model but I need to connect to the DB dynamically when using the model.
regards

**Comment by gonzus** [comment]
I have the same question (I think). I have acquired a connection to my MySQL database and would like to pass that into sequelize so that this connection is used for everything. This also implies that I don't want sequelize to close the connection or touch it in any way, other than using it to run queries. Is this possible?

**Comment by nawlbergs** [comment]
We are doing this.. and we use `sequelize.define` to create instances of a model to a specific sequelize instance.
Essentially, you create your databases instances and store them...
Then loop over your models and pass in your database instance as they are defined.
This article is similar to what we have going... https://medium.com/unetiq/using-multiple-databases-with-nodejs-and-sequelize-59e0abcbbe6f

however.. we are trying to implement typescript.. and for the life of me.. i cannot get the models to be correctly type when using `sequelize.define(...)` to define the models.
