### ISSUE TITLE
Associations on existing DB with non-conventional key names

### ISSUE THREAD

**Issue by quoininc-huudatran** [sequelize/sequelize#12777]
## Issue Description

Trying to write models and associations for an existing (very old and non normal form) db (MyIsam)

### What was unclear/insufficient/not covered in the documentation

How to customize each key on each table for each of the associations.

https://sequelize.org/master/manual/assocs.html

### If possible: Provide some suggestion on how we can enhance the docs

It would be nice to have a concrete example for each association with existing databases.

If the documentation could describe what are all the options and their default values. Like how does it knows which fields is used as source_key -> through_from_source -> through_to_target -> target_key when only specifying

`A.belongsToMany(B, { through: 'C' });`

How does it knows what key on `A` to use to get to `C` (which key on `C`?), then which key on `C` is used to get to `B` (again, which key on `B`?). I understand that if you start with sequelize from beginning, this is implementation details that most do not need to know, but coming from an existing DB (and without foreign keys on MyISAM), how should we proceed to "reverse-engineer" the models. Also, the relationship could target a unique but not primary key (if that's important).

My database is MyIsam so there are no foreign key defined in the DB, but it's in the application (used to be Django).

### Additional context

My example (not real table, but with key names random enough):

season: `seasonId` primary key
match: `match_id` primary key
tableThrough: `id` primary,  `left_id` foreign season.seasonId,  `right_id` foreign match.match_id

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by x-yuri** [comment]
What I've learned just now. `belongsTo()` adds a field (a foreign key) to `A`, `hasMany()` to `B`. The field name is derived from `B` for `belongsTo()`, and from `A` for `hasMany()`. That is, `Group.hasMany(User)` adds an attribute `GroupId` to the `User` model. By default the association is optional:

https://github.com/sequelize/sequelize/blob/v6.5.0/lib/associations/belongs-to.js#L85
https://github.com/sequelize/sequelize/blob/v6.5.0/lib/associations/has-many.js#L118

From what I can see it's a general default (`allowNull: true`). The foreign key attribute's options can be specified in the model, in `hasMany()`, or in `belongsTo()`. But it makes no sense to specify `allowNull` in `belongsTo()`. Because the latter only adds options that [weren't yet added][a]. And `allowNull` is added either in the model, or in `hasMany()` (the default, `allowNull: true`).

If you need a custom foreign key name, you've got to specify it in both `hasMany()` and `belongsTo()`.

That probably somewhat answers your question.

> how should we proceed to "reverse-engineer" the models

With a debugger, that's what I did.

[a]: https://github.com/sequelize/sequelize/blob/v6.5.0/lib/utils.js#L50-L64

**Comment by quoininc-huudatran** [comment]
I think that explicit examples like this would greatly improve understanding for everyone. I'm trying to document this for myself to get a better understanding:... but haven't worked on all cases yet.

```
A.belongsToMany(B, {
  through: C,
  foreignKey: C.tableAttributes.paperId.fieldName,
  otherKey: C.tableAttributes.countyId.fieldName,
  constraints: false,
});
```

or other explicit examples as such. I brain cannot comprehend what are the custom field if the documentation just expects us to mainly go happy path and let sequelize be the beginning of all time. 

Where is the list of options?

**Comment by x-yuri** [comment]
It should be noted that there are options for `belongsToMany()` (and other such methods), like `through`, `foreignKey`. And there are options (or rather attributes) for the foreign key. Those are passed via the `foreignKey` option and are the ones you would specify for any other column. Except for `name`. If you are okay with the default attributes you can specify just a name (`foreignKey: 'FooId'`). Which equals to `foreignKey: {name: 'FooId'}`. If you need additional attributes, `foreignKey` must be an object.

P.S. Not sure where `otherKey` and `constraints` come from. Although my acquaintance with `sequalize` has just started.
