### ISSUE TITLE
Associations foreign key naming convention

### ISSUE THREAD

**Issue by fateslayer** [sequelize/sequelize#12849]
### What was unclear/insufficient/not covered in the documentation

The documentation for associations says that the foreign key chosen automatically will be **fooId** but when I tried it, it was created as **FooId**.

**Q1.** Are the docs incorrect in this situation?
**Q2.** I used camelCase for my fields, how do I make foreign keys to be camelCase as well?
**Q3.** Should I use TitleCase for every field in my model?

### If possible: Provide some suggestion on how we can enhance the docs

I think the docs should be updated based on the current implementation rules.

### Additional context
Here is the link to [One-To-One Relationships Implementation](https://sequelize.org/master/manual/assocs.html#implementation)

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
Q1. I think that particular example is wrong. The rest of the docs give examples such as `TeamId` and `MovieId`.  
In [BelongsTo](https://github.com/sequelize/sequelize/blob/3cb75591cb33d6d9484a8985d22695a02ac9f269/src/associations/belongs-to.js#L40) and [hasOne](https://github.com/sequelize/sequelize/blob/3cb75591cb33d6d9484a8985d22695a02ac9f269/src/associations/has-one.js#L41) the model's name is joined with the foreign key name (often "id") & then camelcased. However, since the model name is generally written with an uppercase letter, the result _looks_ like TitleCase.

Q2. If you also want foreign key fields to not look [1] like they're TitleCased, you can set the name yourself: `Bar.belongsTo(Foo, { foreignKey: 'fooId' });`

Q3. The convention is Sequelize is to use camelcase for most fields. There's also an option to use underscores. I'd stick to what you've got.

[1] I would argue they're not actually titlecased. If you had a model with name `foo` the automatically generated field would be `fooId`. The automatic field name generator does not capitalize the first letter, it just happens to be one already.

**Comment by fateslayer** [comment]
Thanks for clearing my doubts. I will use camelcase for my tables and fields from now on to avoid such issues.
