### ISSUE TITLE
Duplicated unique constraints and indexes on sequelize.sync({ alter: true })

### ISSUE THREAD

**Issue by JekRock** [sequelize/sequelize#12889]
## Issue Description
When there is the `unique: true` property for any model field, sequelize creates a new unique constraint and index on each `sequelize.sync({ alter: true })`
### What are you doing?
Create any model with a unique field like that:
```typescript
  public initModel({ sequelize }: { sequelize: Sequelize }): ModelCtor<ExampleModel> {
    const exampleModel = sequelize.define<ExampleModel>(
      "ExampleModel",
      {
        id: {
          allowNull: false,
          defaultValue: DataTypes.UUIDV1,
          primaryKey: true,
          type: DataTypes.UUID,
        },
        exampleField: {
          unique: true,
          allowNull: false,
          type: DataTypes.STRING,
        },
    );
    return exampleModel;
  }
```
Then call `sequelize.sync({ alter: true })`.

### What do you expect to happen?
Only single unique constraint and index are created after the each `sequelize.sync({ alter: true })` call

### What is actually happening?
For each `sequelize.sync({ alter: true })` call there will be a new constraint named `ExampleModel_exampleField_key1` (the next will be `ExampleModel_exampleField_key2` and so on) and a new index called the same.
### Environment

- Sequelize version: 6.3.5 
- Node.js version: 14.15.0 
- Operating System: WSL2 Ubuntu 20.04
- If TypeScript related: TypeScript version: 4.0.2

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using PostgreSQL, with connector library version 8.3.3 and database version 12.4

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by yusufkhan07** [comment]
Facing the same issue.

**Comment by sandy912** [comment]
Facing the same issue with dialect Postgres.

**Comment by tiagowippel** [comment]
Facing the same issue here too.

**Comment by gkourpa** [comment]
Facing the same issue.

**Comment by FuketsuBaka** [comment]
Facing the same issue.

**Comment by EgoBrainProgrammer** [comment]
Facing the same issue. Postgres.

**Comment by LucasRosaWP** [comment]
Facing the same issue.

**Comment by ingrocha** [comment]
Facing the same issue.

**Comment by abtisam** [comment]
facing same issue today which exhaust table default indices 

Error: Too many keys specified; max 64 keys allowed

**Comment by IJlima** [comment]
I'm getting duplicate foreign key constraint when using sequelize.sync({ alter: true })

**Comment by mkantz84** [comment]
same issue here

**Comment by waqardeveloper** [comment]
same issue

**Comment by abtisam** [comment]
> same issue

Have you tried the above workaround ? It works for me

**Comment by WGriffing** [comment]
This is affecting my project as well.

I didn't want to write a manual query as a workaround, so I will share my workaround:

```javascript
UserModel.sequelize
  .getQueryInterface()
  .addConstraint(UserModel.tableName, {
    fields: ["email"],
    type: "unique",
    name: "users_email_unique",
  });
```
replace `UserModel` with your actual Model class and update the options argument of the `addConstraint` call to suit your purposes.

**Comment by ingrocha** [comment]
I found a solution, erase de `unique:true` from the attributes and declare this `indexes: [{ unique: true, fields: ["user"] }]`  in model options

**Comment by arvindnarang1i11y** [comment]
Please re-open , facing issues with this @WikiRik

**Comment by WikiRik** [comment]
> I found a solution, erase the `unique:true` from the attributes and declare this `indexes: [{ unique: true, fields: ["user"] }]` in model options

@arvindnarang1i11y I never closed this, the issue was still open. Did the workaround from above work for you?

**Comment by hyperdestru** [comment]
Hello, faced same issue (but with mysql db), the workaround consisting of replacing `unique: true` in model's field config by `indexes: [{ unique: true, fields: ["YOUR_FIELD_NAME_HERE"] }]` worked for me ! No more duplicate keys on sequelize sync (alter).

**Comment by gkourpa** [comment]
The workaround `indexes: [{ unique: true, fields: ["YOUR_FIELD_NAME_HERE"] }]` worked for me as well on my MySQL database!

**Comment by Seblor** [comment]
The workaround does not seem to work for me. Possibly because I am using a composite index.

Here is my model:

```js
sequelize.define('foo', {
  // Model attributes are defined here
  A: {
    type: DataTypes.STRING,
    allowNull: false,
    unique: 'someIndex'
  },
  B: {
    type: DataTypes.STRING,
    allowNull: false,
    unique: 'someIndex'
  },
  C: {
    type: DataTypes.STRING,
    unique: 'someIndex'
  }
}, {
  indexes: [
    {
      unique: true,
      fields: ['A', 'B', 'C'],
      type: 'UNIQUE',
      name: 'someIndex'
    }
  ]
})
```

**Comment by code2nd** [comment]
Facing the same issue.

**Comment by LeonardSSH** [comment]
@Seblor try:
```js
 indexes: [
    {
      unique: true,
      fields: ['A'],
    },
   {
      unique: true,
      fields: ['B'],
    },
   {
      unique: true,
      fields: ['C'],
    }
  ]
```

Works for me.

**Comment by Seblor** [comment]
@LeonardSSH Wouldn't that create 3 unique indexes ?

What I need is to have a single index that is based on the 3 fields.

**Comment by LeonardSSH** [comment]
@Seblor ![x](https://i.imgur.com/8SrQWys.png) Also works with only single index: 
```js
{
	sequelize,
	tableName: 'accounts',
	paranoid: true,
	indexes: [{ unique: true, fields: ['username', 'email'] }]
}
```

**Comment by Seblor** [comment]
@LeonardSSH I don't see the difference with the code snippet I posted.

It works, but throws an error when synchronizing with `{alter: true}`, which is the current issue.

**Comment by LeonardSSH** [comment]
I use `alter: true` too and it works perfectly.

My env:
```js
await sequelizeConnection.sync({ force: false, alter: true });
```
```js
Account.init({
	id: {
		type: DataTypes.INTEGER,
		autoIncrement: true,
		primaryKey: true,
		allowNull: false
	},
	username: {
		type: DataTypes.STRING(32),
		allowNull: false
	},
	password: {
		type: DataTypes.STRING(128),
		allowNull: false
	},
	email: {
		type: DataTypes.STRING(64),
		allowNull: false,
		validate: {
			isEmail: true
		}
	},
	createdAt: Sequelize.DATE,
	updatedAt: Sequelize.DATE,
	deletedAt: {
		type: DataTypes.DATE,
		allowNull: true
	}
},
{
	sequelize,
	tableName: 'accounts',
	paranoid: true,
	indexes: [{ unique: true, fields: ['username', 'email'] }]
});

```

**Comment by taozhi8833998** [comment]
@leonardssh You set the `force` to true in the sync options, it will drop the table and create it again, that's why it works, but the data in table will be lost.

**Comment by taozhi8833998** [comment]
same issue

**Comment by dilpazir-whizpool** [comment]
Fixed: my issue was in my code sequelize file for addModels and sync was being called multiple times. That is why it was putting constraint fine for the first time but second time it was throwing error. I fixed my code structure all went ok.

I am using sequelize with NestJS. I was adding database provider in every module. Correct way is to add it in app module and then import database module to the modules where you need

**Comment by rigolettofranc** [comment]
> I found a solution, erase the `unique:true` from the attributes and declare this `indexes: [{ unique: true, fields: ["user"] }]` in model options

Using a <b>unique index</b> in place of a <b>unique key</b> could trip you up when time comes. Note these two are <b>NOT</b> the same, see this stackoverflow [post](https://stackoverflow.com/questions/3794607/unique-index-or-unique-key#:~:text=The%20index%20and%20key%20are,data%20location%20for%20faster%20retrieval.). A <b>unique index</b> would filter out duplicates only in your index, but not in your table. It might seem to work for most people when their search query has just that field(column) where index is built upon, but that's only because it's index that's serving the query. When your search query has more than that field that the unique index can no longer serve, and have to rely on other non-unique index or no index at all, chances are you're going to see the duplicates reemerge - as they should - because they are still in the table.

If you need a <b>unique key</b> that guarantees uniqueness of the data in your table, you should use just that. 

Try `unique: 'any_unique_value'` instead of `unique: true`

The latter one with `true` is obviously still buggy at this point of discussion. A named unique constraint is usually used when placed on two fields(columns) (see this stackoverflow [post](https://stackoverflow.com/questions/42195348/how-to-define-unique-index-on-multiple-columns-in-sequelize)), but works great on a single field too.

**Comment by ephys** [comment]
While unique constraints/keys and unique indexes are different things, in practice creating one creates the other. In Sequelize, defining a unique index using the `unique` property of an attribute, or using the `indexes` option of the model does the same thing

It's more obvious in Sequelize 7 where `YourModel.getIndexes()` return indexes created by the `unique`  & `index` (this one is new) attribute options & the `indexes` table option, which is what we use then to create the unique constraint/indexes

**Comment by bhuwan-pandey** [comment]
I finally figured out the issue. I have been trying for days to figure out this and now i am here.
In _./node_modules/sequelize/lib/model-manager.js_, inside the function `getModelsTopoSortedByForeignKey`, there's this code:
`try {
      sorted = sorter.sort();
    } catch (e) {
      if (!e.message.startsWith("Cyclic dependency found.")) {
        throw e;
      }
      return null;
    }`
when i debugged and debugged and debugged, what i came to find was there was stupid cyclic dependency error in my model's relation. the `e` inside the `catch` block there helped me figure out but i am surprised to see that an error would get thrown in there except for a cyclic dependency. the above function is called through _.node_modules/sequelize/lib/sequelize.js_, inside of the function `sync` and in these lines:
`
      const models = this.modelManager.getModelsTopoSortedByForeignKey();
      if (models == null) {
        return this._syncModelsWithCyclicReferences(options);
      }`
Because due to cyclic dependency the `this.modelManager.getModelsTopoSortedByForeignKey();` would return null and thus execute `this._syncModelsWithCyclicReferences(options);`.
When i synced the models, no cyclic dependency error were thrown and i believe sequelize is supposed throw such errors.

Now my syncing WORKS like a charm like before !!! I would rather avoid cyclic dependency than to work with it and get lost.
