### ISSUE TITLE
Column name with parenthesis and quote application

### ISSUE THREAD

**Issue by GuillaumeCisco** [sequelize/sequelize#12920]
## Issue Description

I have a question regarding this [piece of code](https://github.com/sequelize/sequelize/blob/master/src/dialects/abstract/query-generator.js#L1530-L1534).
```js
} else if (!attr[0].includes('(') && !attr[0].includes(')')) {
    attr[0] = this.quoteIdentifier(attr[0]);
} else {
    deprecations.noRawAttributes();
}
```
As far as I can see, it was written 7 years ago in this [commit](https://github.com/sequelize/sequelize/commit/882d8492cdd611433dc1d956efa55745a6afa3e4).

Any insights why table column name containing parenthesis are not quoted?

When declaring our fields for not breaking everything, we have to write :
```
'Calories (Kcal/100g)': {
      type: DataTypes.DOUBLE,
},
```
if `underscored` is `false`.
And
```
'Calories (Kcal/100g)': {
      type: DataTypes.DOUBLE,
      field: 'Calories (Kcal/100g)'
},
```
if `underscored` is `true`.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
[This PR](https://github.com/sequelize/sequelize/pull/783) doesn't touch the same piece of [code](https://github.com/sequelize/sequelize/pull/783/commits/d14b8332ea5f1659f4ab82e5bb4ca20ff9cd4250), but the check for a `(` in the attribute name & then escaping based on its existence seems similar to the piece of code you quoted. Based on that, I believe—_and this is a bit of guesswork_—this check exists because of the following:

If you want to order randomly, nowadays you could do `.findAll({ order: sequelize.fn('RAND') })`.  
From the above PR and a vague recollection, I believe that you used to be able to do `.findAll({ order: 'RAND()' })`.  
The resulting query should of course be `ORDER BY RAND();` and not ``ORDER BY `RAND()`;``, thus the check if escaping should be done or not. The same would apply for queries that should generate `SELECT NOW();`, rather than `ORDER BY`, etc.

To prevent people's existing code from silently breaking, the [deprecation warning](https://github.com/sequelize/sequelize/blob/65549922fbe3a823cd11b3e8eea64122fe6142a5/src/utils/deprecations.ts#L7) in the `else` is thrown.  

I'm honestly not sure why setting `underscored:false` works in your set-up.

I hope this helps you towards the full answer, it seems plausible.

**Comment by GuillaumeCisco** [comment]
Yes thank you @Spekpannenkoek! It helps understanding it!
Was very unclear at first sight.
What we should do is more dealing with functions, `RAND()`, `NOW()` etc, rather than applies it to every column name containing parenthesis, don't you think?
