### ISSUE TITLE
Coordinates doesn't exist in type 'GeometryDataType'

### ISSUE THREAD

**Issue by krlicmuhamed** [sequelize/sequelize#12951]
### What are you doing?

I am trying to insert a geometry column into my Postgres PostGIS database
**Here is the link to the Stack Overflow for this issue:** [LINK-HERE](https://stackoverflow.com/questions/65688147/coordinates-does-not-exist-in-type-geometrydatatype) 

Unlike what it says in the [documentation](https://sequelize.org/master/class/lib/data-types.js~GEOMETRY.html) geometry datatype doesn't allow for coordinates in type GeometryDataType ie. It doesn't exist, its not defined.

### What do you expect to happen?

I expect Create a new point to work
```ts
const point = { type: 'Point', coordinates: [39.807222,-76.984722]};

User.create({username: 'username', geometry: point });
```

### What is actually happening?
The output error is :
```
src/actions/collectGpsData.ts:22:43 - error TS2322: Type '{ type: string; coordinates: any[]; }' is not assignable to type 'GeometryDataType'.
  Object literal may only specify known properties, and '"coordinates"' does not exist in type 'GeometryDataType'.

22       place.location = { "type": "Point", "coordinates": [point.latitude, point.longitude] };
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```
### Environment

- Sequelize version: 5.22.3 
- Node.js version: 15.5.0 
- Operating System: Windows 10
- If TypeScript related: TypeScript version: Version 4.1.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by nainkunal933** [comment]
Hi @krlicmuhamed,

Looking at your Stack overflow issue I believe place.location is defined as a Geometry data type in your model. Please paste your code snippet here as well for reference.

**Comment by nainkunal933** [comment]
@papb I think Geometry data type might not support coordinates by looking at the constructor. Can you please look into it?

**Comment by papb** [comment]
Hello @krlicmuhamed!

As @nainkunal933 noted, please include a complete code sample next time. The code you posted does not show how `User` is defined, for example. Please use a [sequelize-sscce](https://github.com/papb/sequelize-sscce).

That said, I took the time to look into what's happening and tried to figure it out.

So, first of all, this issue is typescript-only. The code works fine in runtime. Please include this information directly next time.

I ventured into your stackoverflow question and comments and found this:

https://gist.github.com/krlicmuhamed/199c0bc3560a08718b553f3f609acbcd#file-places-ts-L22

Did you find any documentation instructing you to use this specific type explicitly here? If yes, please post the link so I can fix it. Regardless, I don't blame you because we really should have a set of recommended types to apply on each data type. It turns out `GeometryDataType` is not the correct type to use in this case.

The solution is to install `@types/geojson`:

* `npm install --save-dev @types/geojson`

Then, import `Geometry`:

```
import type { Geometry } from '@types/geojson'
```

And then replace that line of code in which you put `GeometryDataType` with `Geometry`:

```diff
  @AllowNull(false)
  @Column(DataTypes.GEOMETRY)
-  location: GeometryDataType;
+  location: Geometry;
```

In the future we should provide a set of recommended types for columns in an organized way.

**Comment by papb** [comment]
I will close this issue since technically the error was caused by your own code, but I agree that we should provide better types for this in the future (or at least a clearer documentation).

In the future I plan on providing a set of recommended types for columns in an organized and well-documented way.

**Comment by papb** [comment]
> Did you find any documentation instructing you to use this specific type explicitly here? If yes, please post the link so I can fix it. 

Although I closed the issue, please still let me know on this part. Thanks!
