### ISSUE TITLE
Translation to Korean

### ISSUE THREAD

**Issue by paigekim29** [sequelize/sequelize#12987]
Good Evening,

My name is Joo Hee Kim. I am an aspiring developer and I would like to ask if you would be interested in translating your repository to Korean. If you would give us permission to, I will work with my group, @Sanghyuk-CH @ning1315, who are also aspiring developers and would want to take on a task like this. We believe that translating a notable repository like yours would truly benefit other Korean developers like ourselves. 

Thank you!

**Comment by papb** [comment]
Hello, Joo Hee Kim! Thank you very much! This would be great!

However, we are currently working on a major rewrite of our documentation, so I think it would be better if you could wait until we complete this (so that you can work directly with the new version).

It should take a few weeks or months. Once we're done with that I will let you know by pinging you here (like this: @paigekim29), and then you and your group can see if you are still interested. What do you think?

**Comment by paigekim29** [comment]
That would be perfect! Thank you for your prompt reply. I am looking forward to hearing back from you once you've rewritten your documentation. It will truly be an amazing opportunity!

**Comment by pbkim0725** [comment]
@paigekim29 I am also interested in helping translation, if you wouldn't mind :)

**Comment by paigekim29** [comment]
@pbkim0725 Thank you for interest in helping out. I am currently still waiting for a reply back from sequelize. I will reach out to you once we need any assistance :)

**Comment by danielsychoo** [comment]
@paigekim29 Can I join, about translate sequelize? I'm very interested!!!

**Comment by paulbkim01** [comment]
@paigekim29 any progress so far on the project? please update

**Comment by paigekim29** [comment]
@paulbkim01 There has been no update about when I will start the translation. I am just waiting on their go signal and I will start working on it.

**Comment by JeFF-KOR** [comment]
I would like to helping translation too!
