### ISSUE TITLE
updateOnDuplicate can't use Sequelize.literal('***').

### ISSUE THREAD

**Issue by Niubility-SunLight** [sequelize/sequelize#13033]
## Issue Description
insert date to mysql by using bulkCreate.updateOnDuplicate can't use Sequelize.literal('***').
### What are you doing?
insert date to mysql by using bulkCreate.updateOnDuplicate can't use Sequelize.literal('***').

**Here is the link to the SSCCE for this issue:** LINK-HERE 

### What do you expect to happen?
for example:
await Person.bulkCreate([{id:1,name:'jack'},{id:2,name:Tom}],{updateOnDuplicate:['name',Sequelize.literal('`age`+1'),]})
I want the age attribute to be automatically incremented by 1 when the data exists，but Sequelize.literal('`age`+1') did't work

I checked the SQL and found that age = value ('age '+ 1) does not exist in the SQL

### What is actually happening?

The age property was not updated，I checked the SQL and found that age = value ('age '+ 1) does not exist in the SQL

### Environment
- Dialect: mssql
- Sequelize version: sequelize@6.3.5
- Node.js version: 14.15.1
- Operating System: Windows

**Comment by HsinHeng** [comment]
> ## Issue Description
> insert date to mysql by using bulkCreate.updateOnDuplicate can't use Sequelize.literal('***').
> 
> ### What are you doing?
> insert date to mysql by using bulkCreate.updateOnDuplicate can't use Sequelize.literal('***').
> 
> **Here is the link to the SSCCE for this issue:** LINK-HERE
> 
> ### What do you expect to happen?
> for example:
> await Person.bulkCreate([{id:1,name:'jack'},{id:2,name:Tom}],{updateOnDuplicate:['name',Sequelize.literal('`age`+1'),]})
> I want the age attribute to be automatically incremented by 1 when the data exists，but Sequelize.literal('`age`+1') did't work
> 
> I checked the SQL and found that age = value ('age '+ 1) does not exist in the SQL
> 
> ### What is actually happening?
> The age property was not updated，I checked the SQL and found that age = value ('age '+ 1) does not exist in the SQL
> 
> ### Environment
> * Dialect: mssql
> * Sequelize version: sequelize@6.3.5
> * Node.js version: 14.15.1
> * Operating System: Windows

You can reference my comment [here](https://github.com/sequelize/sequelize/issues/12807#issuecomment-889240489).

**Comment by soknifedev** [comment]
is there any update on this? I am trying to do something like this, it would be useful for counting how many times a users attempts some action.

**Comment by WikiRik** [comment]
Depending on your exact use case, `Model.increment` could work for this. See these docs; https://sequelize.org/docs/v6/core-concepts/model-instances/#incrementing-and-decrementing-integer-values

**Comment by soknifedev** [comment]
Yup, what I am trying to do is a bulkCreate (with updateOnDuplicate) because a user can request "n" resources. Every time a resource is retreived by a user the retrivals count increases by 1 or performs an insertion.

I tried to achieve this by passing the literal in the bulkCreate's records array, but no luck since the ON DUPLICATE KEY UPDATE is just referencing the retrivals_count field provided in the records array ( and has no real effect on the update :( )

**Comment by soknifedev** [comment]
I'll elaborate more in the use-case because there may be other people trying to achieve this.


The query generated by the bulkCreate function is this:

```SQL

INSERT INTO
    `actor_usage` (`actor_id`, `resosurce_type`, `createdAt`, `updatedAt`)
VALUES
    (
        2806,
        'image',
        '2023-04-08 16:57:24.061',
        '2023-04-08 16:57:24.061'
    ),
(
        9084,
        'image',
        '2023-04-08 16:57:24.061',
        '2023-04-08 16:57:24.061'
    ),
(
        2807,
        'image',
        '2023-04-08 16:57:24.061',
        '2023-04-08 16:57:24.061'
    ),
(
        2808,
        'image',
        '2023-04-08 16:57:24.061',
        '2023-04-08 16:57:24.061'
    ),
(
        2809,
        'image',
        '2023-04-08 16:57:24.061',
        '2023-04-08 16:57:24.061'
    ) ON DUPLICATE KEY UPDATE
    `retrivals_count` = VALUES (`retrivals_count`),
    `updatedAt` = VALUES (`updatedAt`);
```


As you can see, in ON DUPLICATE KEY UPDATE there is 

```
...
    `retrivals_count` = VALUES (`retrivals_count`),
...
```

But, in this scenario, I would like to perform an increment in the retrivals_count if the records exists.

so, the query generated (If I use literal, or providing a value using a syntax like 

updateOnDuplicate: [ ['retrivals_count', sequelize.literal('retrivals_count + 1') ] ]) should be:
```

...
    `retrivals_count` = retrivals_count + 1,
...

```
