### ISSUE TITLE
Is there a feature to pull all the foreign key associations when making a Rest API call?

### ISSUE THREAD

**Issue by JimboGeesus** [sequelize/sequelize#13165]
## Feature Description
This is my first time using GItHub for questions so apologies if this is already a feature within Sequelize. I have created a Rest API that returns logs relating to a particular user however as the model has six columns that are just INT values that belong to other tables through foreign keys, I am currently just returning a lot of meaningless number values instead of Text. Is there a feature to include these automatically? I think I have my belongsToMany assoications already entered, not 100% if they are correct or not.

### Is your feature request related to a problem? Please describe.

Rest API is returning data which is meaningless without the foreign key association. High amount of code would have to be written to pull all the required information.

### Describe the solution you'd like

Rest API returns all association values in a tree like structure within a json.

```js
// If applicable, add a code snippet showing how your feature would be used in a real use-case
```

### Why should this be in Sequelize

Short explanation why this should be part of Sequelize rather than a separate package.

### Describe alternatives/workarounds you've considered

A clear and concise description of any alternative solutions or features you've considered. If any workaround exists to the best of your knowledge, include it here.

### Is this feature dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
If I understand your question correctly, you'd like something like this:

```
SomeModel
id | UserId | AbcId | XyzId
 1 |      4 |     8 |     7

Xyz table
id | UserId
 7 |      4
 
await SomeModel.findByPk(1);
```

To return something like this?

```
{
  id: 1,
  User: { 
    id: 4, name: "Alice",
  },
  Abc: { 
    id: 8, 
    ...etc,
  },
  Xyz: { 
    id: 7, 
    ...ect, 
    User: { 
      id: 4, name: "Alice" 
    }
  }
}
```

You've probably figured out how to do that 'manually' every time:

```
SomeModel.findByPk(1, {
  include: [ User, Abc, [{
    model: XyzModel, 
    include: [User],
  }] ],
});
```

If you don't want to include models manually every time you call `SomeModel.find`, [then there is a way to 'mix in'](https://sequelize.org/master/manual/scopes.html) some options into every query.

Add a default scope that includes the models you want. Now, by default, every time you use `SomeModel.find(optionsForThisSpecificQuery)`, it will merge `optionsForThisSpecificQuery` with whatever is in the default scope—like the whole `include: []` array as in the example.

You can also rather than use 'defaultScope', choose a different name for your scope and use it like this: `SomeModel.scope('my_custom_scope_with_everything_include[]-ed').findAll()`.
