### ISSUE TITLE
`quoteIdentifiers` is ignored for `mssql` dialect

### ISSUE THREAD

**Issue by nibblesnbits** [sequelize/sequelize#13263]
## Issue Description

`quoteIdentifiers` is ignored for `mssql` dialect (see `lib/dialects/abstract/query-generator/helpers/quote.js:64`)

### What are you doing?

Any query for `mssql` dialect;

**Here is the link to the SSCCE for this issue:** LINK-HERE 

### What do you expect to happen?

_SELECT someColumn FROM someTable_

### What is actually happening?

_SELECT [someColumn] FROM [someTable]_

When `quoteIdentifiers` is `false`.

### Environment

- Sequelize version: 6.6.2
- Node.js version: 12.13.0
- Operating System: Win10

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): mysql
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by theLAZYmd** [comment]
Resolved by bringing mssql dialect through a similar process to the already-specified one for Postgresql
Changes the default format to addTicks with doublequotes, i.e. dbo.["myTable"] or ["myTable"] which is standard for mssql.
Can be removed by specifying the quoteIdentifiers: false option in the sequelize init constructor.

**Comment by nibblesnbits** [comment]
Are you saying this change is already in a release?

**Comment by theLAZYmd** [comment]
No I sent a PR but have since deleted, issue is a lot more complicated than I thought

**Comment by theLAZYmd** [comment]
Hacky solution: change this line: 
https://github.com/sequelize/sequelize/blob/7ceeacc34a48f211552d17d5cdfd04d11d7cca9e/lib/dialects/abstract/query-generator.js#L957 to
```ts
let forceQuote = false
if (this.options.dialect === 'mssql') {
  forceQuote = true;
}
if (param.startsWith('[')) forceQuote = false;
table = this.quoteIdentifier(param, forceQuote);
```

In essence, the problem is this:

- You want to change it so that for mssql dialect, table names given schema by mssql defaults use double-quoting inside the square brackets, ex: `SELECT * FROM ["users"]`, **however**
- You don't want to change double quoting from attributes, for instance it should not be the case that the query generated is `SELECT * FROM ["users"] WHERE ["users"].[id]='foo'` uses double quotes around that `id` **and**
- You don't want to change double quoting for aliases, since sequelize by default naturally imports all the tables by a named alias, ex: `SELECT * FROM ["users"] as [user] WHERE ["user"].[id]='foo'`. The syntax of that query is wrong, since there should not be double quotes around the second `user` because the alias chosen by sequelize doesn't have double quotes.

So this is quite a difficult problem to accomplish with the current sequelize lib's quoteTable and quoteIdentifier functions. The hacky solution works but looks to be very contingent.
