### ISSUE TITLE
deletedAt on find

### ISSUE THREAD

**Issue by piotrek-r** [sequelize/sequelize#133]
I've tried many of ORMs for node.js and I like yours the most. I relay hard on deletedAt features in my databases. I don't like to delete stuff forever. But I found out that sequelize ignore's deletedAt on find() requests.

I've got the common code:

``` javascript
var Sequelize = require('sequelize');

var sequelize = new Sequelize('db', 'root', 'pass');

var Project = sequelize.define('Project', {
  title: Sequelize.STRING,
  description: Sequelize.TEXT
}, {paranoid: true});
```

And then all of them run one after another all including the first one:

``` javascript
sequelize.sync();
```

``` javascript
var project = Project.build({
  'title': 'My Second Task Title',
  'description': 'Task description for task number two.'
});
project.save();
```

``` javascript
Project.find(1).success(function(project) {
  project.destroy();
});
```

``` javascript
Project.find(1).success(function(project) {
  console.log(project);
});
```

I guess console on the last one should return null. Also find(All) should be prepared to omit adding deletedAt IS NULL on request.

Anyway, great job on the module!

**Comment by alirizwan** [comment]
Just one piece, for paranoid can we make two columns, one Boolean isDeleted and one DateTime deletedAT (which already is there) and when we query instead of adding WHERE deletedAt IS NULL we use isDeleted = false because IS NULL and NOT NULL checks slows the query and boolean can speed up the query a lot, especially when there are a lot of records being pulled.

**Comment by GeorgeWL** [comment]
I think I'd just like as part of the options object to include something like 
```js 
options.showDeleted = false // default to false
```
