### ISSUE TITLE
How can I search through a column with user long text?

### ISSUE THREAD

**Issue by Mrbeyond** [sequelize/sequelize#13562]
## Issue Creation Checklist

[ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

 I need to search a table through title column of blog table to find all matching articles.
 I have used %LIKE operator but it was not accurate.
  where {
        status: 1,      
       title:{
          [_op.like]: '%'+search+'%',
        }        
 }

Only a single word from search input works, Two or more words fetches nothing.

### If possible: Provide some suggestion on how we can enhance the docs

Write here.

### Additional context
Please I really need help with this. Thanks.

**Comment by soryy708** [comment]
I don't understand what you mean by "it was not accurate". What's the data in the table and how is the column defined?
Have you read https://sequelize.org/master/manual/model-querying-basics.html#simple-select-queries ?

**Comment by ericyd** [comment]
>For example if the title of a particular article is "How to become a professional with sequelize?"
>
>And the user enters "professional sequelize" , I want to get articles that have "sequelize" or "professional sequelize"

This doesn't feel like a Sequelize bug or issue to me. This is just not how the SQL `LIKE` clause works. If you're query looks like this

Given a table like this

```
id | text
-- | ----
1  | How to become a professional with sequelize?
```

if your query is this
```sql
select *
from my_table
where text like '%professional sequelize%'
;
```

it will not find results because no text matches that string.

A simple solution is to replace all spaces in your search query with `%` symbols, e.g.


```sql
select *
from my_table
where text like '%professional%sequelize%'
;
```

but keep in mind this will only work if the search terms are entered in the same order as the text. What you might want is to programatically split your query string into discrete words and use an `OR` clause to search for any of the terms.

Of course, the exact solution is dependent on your requirements but either way this is not a library issue

**Comment by ephys** [comment]
I agree that this is not a sequelize issue. `LIKE` isn't designed to search by keywords.

For postgres this might be of use to you: https://www.postgresql.org/docs/9.5/textsearch-intro.html
I don't know how other dialects support this use-case.

**Comment by Mrbeyond** [comment]
@ericyd Thanks for your answer, my question was more like how to do I do it, not a a bug. 

Thanks a lot, I was able to get around it by splitting the search words and chained the or statement in the array.

**Comment by ericyd** [comment]
> my question was more like how to do I do it, not a a bug

in general I'd recommend Stack Overflow for this use case, rather than a GitHub issue. In this case, there isn't anything missing from the documentation, it's a question on your specific implementation details. Regardless, I'm happy that your issue is resolved and I'd recommend that this issue be closed
