### ISSUE TITLE
Multi level include column name truncated

### ISSUE THREAD

**Issue by zettry1** [sequelize/sequelize#13800]
Multi level include truncated column name of child object.
` const new_troubleReport = await User.findAll({
      include: [
        {
          model: EquipmentType,
          required: false,
          include: [
            {
              model: Equipment,
              required: true,
              include: [   {
                  model: EquipmentDetail,
                  require: false,
                }]
}
]
}
]});`

When running this kind of 4 level include findAll query. Nested tables column name truncated. Example **EquipmentDetail.createdAt=> EquipmentDetail.creat**
Any way to solve this? I could not find similar issue.

**Comment by ephys** [comment]
It's likely that this issue did not get prioritised because it didn't follow the contributing guidelines.
If you want, you can [try again](https://github.com/sequelize/sequelize/issues/new?assignees=&labels=&template=bug_report.md&title=), but take the time to properly fill in the requested information, and format your code in a readable way. The more useful information we have, the more likely someone will take the time to understand your issue and help you
