### ISSUE TITLE
Clarify supported Microsoft SQL Server versions

### ISSUE THREAD

**Issue by joaoe** [sequelize/sequelize#13838]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

In `.github/workflows/ci.yml:200` there is the line
```
mssql-version: [2017, 2019]
```

In `lib/dialects/mssql/index.js:63` there is the line
```
MssqlDialect.prototype.defaultVersion = '12.0.2000'; // SQL Server 2014 Express, minimum supported version
```
In the documentation, there isn't a referenced minimum version
https://sequelize.org/master/manual/dialect-specific-things.html#mssql

If you need to refresh which versions of MS SQL Server exist, there's wikipedia, which also includes their end-of-support dates.
https://en.wikipedia.org/wiki/SQL_Server_Express#Version_history

### Possible Solution

The issue is that the three sources above don't match, and hence it is not entirely clear which is the minimum version supported.
If 2014 (version 12) shall be supported, there should at the very least be a CI job testing against that version. Microsoft is quite good with backwards compatibility so testing for that version should ensure compatibility with all newer versions.

Else, `mssql/index.js`  should be updated to mention version 14 and the version should be added to the docs.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): MS SQL
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by WikiRik** [comment]
Let's support the oldest referenced version, which in my opinion is indeed 2014 (version 12).
We've been using tedious 8.3.0 for a while, but we do not have a policy on which versions of tedious are supported. Maybe it's best to remove that one from https://github.com/sequelize/sequelize/blob/main/docs/manual/other-topics/dialect-specific-things.md since we have a version mentioned as optional dependency which should be enough.

So let's do CI checks on 2014 and 2019 and remove the tedious version from the docs. Is that something you want to do @joaoe ?

**Comment by joaoe** [comment]
@WikiRik sure, I think I have the time these day. I think the supported MS SQL Server versions should be mentioned in the docs too, so people don't have to dig through the code.

**Comment by WikiRik** [comment]
Agree. You can put it in that file or in the README + docs/index (or both). Now it refers to version 6.0.0 of tedious, which in my opinion is not needed.

**Comment by joaoe** [comment]
@WikiRik Hi. Shall we perhaps bump support to MS Sql 2017 for v7 ? Even MS themselves no longer support anything below that with their mainstream support. Hence, Sequelize does not need to claim support for versions 2012, 2014 if we can't test that in the pipeline.

**Comment by WikiRik** [comment]
Yes, seeing that there are no official Docker images for 2012 and 2014 I think we can go ahead and bump support to 2017. Can you add that to your PR by updating the [Migrating to v7 document](https://github.com/sequelize/sequelize/blob/main/docs/manual/other-topics/upgrade-to-v7.md) and other references in the docs? Maybe it might be good to make a separate PR for that since we normally squash commits before merging

**Comment by joaoe** [comment]
> Maybe it might be good to make a separate PR for that since we normally squash commits before merging

Can you please not do that with my PR ? I always rebase and cleanup my branches before merging.
