### ISSUE TITLE
Add scope to Umzug project

### ISSUE THREAD

**Issue by sdepold** [sequelize/sequelize#13895]
Release new version of umzug under @sequelize/umzug.

Q: Do we want that given, that umzug is theoretically independent from sequelize?

**Comment by ephys** [comment]
I'm always down for scoping because it gives me confidence regarding who developed the package.

On the other hand, people could take it as a sign that it only works with sequelize.

I'd still do it, but be clear on the npm page that this works with other solutions too?

**Comment by WikiRik** [comment]
@mmkal since you are the umzug man, do you agree with scoping umzug?

**Comment by mmkal** [comment]
Thank you for @ing me - I’d missed this. IMO it shouldn’t be scoped - even with a notice in the readme it doesn’t feel like an accurate reflection of its relationship with sequelize. Sequelize is a feature rather than a fundamental piece of it or its “scope”. And I think that’s one of umzug’s strengths. Misrepresenting it in the scope of the package risks incentivising decisions in future that to me would be wrong (I can’t say I can predict right now what would happen that’d be _super_ harmful, but in general increasing, rather than decreasing, coupling with sequelize would be a bad thing IMO).

Also, since I’m the main person working on it right now, but I’m not using it personally in production with sequelize, it doesn’t imply the right thing in terms of how the package is developed either. I am, of course, committed to making sure umzug always works with sequelize, so I’d be in favour of putting a notice that its part of the sequelize family in the readme rather than the other way round. That would be helpful for the npmjs.com readme - in GitHub the scope and ownership are already visible because it falls under the sequelize org.
