### ISSUE TITLE
SequelizeEagerLoadingError

### ISSUE THREAD

**Issue by serdarmutluu** [sequelize/sequelize#14209]
UnhandledPromiseRejectionWarning: SequelizeEagerLoadingError: 
family is not associated to file!

File.js

const db = require('../db');
const { Sequelize, DataTypes } = require('sequelize');

const File = db.define('file', {
    id: {
      allowNull: false,
      autoIncrement: true,
      primaryKey: true,
      type: Sequelize.INTEGER
    },
    fileName: {
      type: Sequelize.STRING
    },
    train: {
      type: Sequelize.STRING
    },
    ipn: {
      type: Sequelize.STRING
    },
    createdAt: {
      allowNull: false,
      type: Sequelize.DATE
    },
    updatedAt: {
      allowNull: false,
      type: Sequelize.DATE
    }
  },{
      freezeTableName:true
  });

  module.exports = File;

family.js
const db = require('../db');
const { Sequelize, DataTypes } = require('sequelize');

const Family = db.define('family', {
    id: {
      allowNull: false,
      autoIncrement: true,
      primaryKey: true,
      type: Sequelize.INTEGER
    },
    familyName: {
      type: Sequelize.STRING
    },
    createdAt: {
      allowNull: false,
      type: Sequelize.DATE
    },
    updatedAt: {
      allowNull: false,
      type: Sequelize.DATE
    }
  },{
      freezeTableName:true
  });

  module.exports = Family;

Association.js

const File = require('./file');
const Wire = require('./wire');
const Component = require('./component');
const Family = require('./family');
const Project = require('./project');
const db = require('../db');
const { Sequelize, DataTypes } = require('sequelize');

Component.belongsToMany(File , {through:'component_file'});
File.belongsToMany(Component , {through:'component_file'});

Wire.belongsToMany(File,{through:'wire_file'});
File.belongsToMany(Wire,{through:'wire_file'});

File.belongsTo(Project);
Project.hasMany(File);

File.belongsTo(Family);
Family.hasMany(File);

db.sync();

**Comment by ephys** [comment]
Hi,

Please format your code properly using [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks), as your current code is very hard to read

You should also follow our [bug report template](https://github.com/sequelize/sequelize/blob/main/.github/ISSUE_TEMPLATE/bug_report.md), including a [SSCCE](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#opening-an-issue-to-report-a-bug) that reproduces your error, otherwise it's unlikely maintainers will take the time to review your issue.

I'll re-open this issue once these problems are resolved
