### ISSUE TITLE
ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT

### ISSUE THREAD

**Issue by adminxh** [sequelize/sequelize#14335]
ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT。。。。。。In doing a 24-hour automatic database operation business logic, but after running for 6 hours, the database connection timeout was reported

**Comment by ephys** [comment]
I'm closing this issue because it doesn't follow the issue template. This issue doesn't contain enough information to work with.

Please take a look at https://github.com/sequelize/sequelize/blob/main/.github/ISSUE_TEMPLATE/bug_report.md and edit this issue with the relevant information

No need to open a new issue, you can update this one - let us know and we'll reopen it
