### ISSUE TITLE
Alias cannot be inferred

### ISSUE THREAD

**Issue by sakthissnite** [sequelize/sequelize#14381]
Given the following models, each of the associations work fine in isolation but not if used together. I'm getting:

Error: Alias cannot be inferred: "PwtAnswer" has multiple relations with "PwtrepoCharger"

```
@Table()
export default class PwtAnswer extends Model<PwtAnswer> {

   /**
     * Selected id of the AC Charger
     */
    @Column({
        field: 'ac_charger_id'
    })
    @ForeignKey(() => PwtrepoCharger)
    public acchargerId: number;

    @BelongsTo(() => PwtrepoCharger , { as: 'ac_charger', foreignKey: 'acchargerId' })
    public ac_charger: PwtrepoCharger;

 /**
     * Selected id of the DC Charger
     */
    @Column({
        field: 'dc_charger_id'
    })
    @ForeignKey(() => PwtrepoCharger)
    public dcchargerId: number;

    @BelongsTo(() => PwtrepoCharger, { as: 'dc_charger', foreignKey: 'dcchargerId' })
    public dc_charger: PwtrepoCharger;

}

@Table()
export default class PwtrepoCharger extends Model<PwtrepoCharger> {

  @HasMany(() => PwtAnswer , { as: 'ac_charger', foreignKey: 'acchargerId' })
        public ac_charge: PwtAnswer[];
    
        @HasMany(() => PwtAnswer, { as: 'dc_charger', foreignKey: 'dcchargerId' })
        public dc_charger: PwtAnswer[];

}
```

And the error:
Error: Alias cannot be inferred: "PwtAnswer" has multiple relations with "PwtrepoCharger"

can you help me?

**Comment by ephys** [comment]
This is an issue related to [`sequelize-typescript`](https://github.com/RobinBuschmann/sequelize-typescript), which is not maintained by Sequelize

We also don't have enough information, we're missing the stacktrace, versions of both libraries, what the code that throws the error looks like

That being said, I'm pretty sure it's because you have an `include` somewhere that only specifies the Model, and not the alias. e.g.

`include: { model: PwtrepoCharger }`
instead of 
`include: { model: PwtrepoCharger, as: 'ac_charger' }`
