### ISSUE TITLE
Forbid using instance `save`, `update`, `reload`, `destroy`, `restore`, `decrement` and `increment` if the model has no PK

### ISSUE THREAD

**Issue by ephys** [sequelize/sequelize#14402]
Initial comment: https://github.com/sequelize/sequelize/pull/14173#issuecomment-1065388719

After discussing this issue internally, we reached the decision that instance methods that need to uniquely identify an entity in a stable way will throw if the model had no Primary Key.

This will make using models without Primary Keys a worse experience, but also a *much* safer one.

It will still be possible to use all static methods, of course.

**Comment by frostzt** [comment]
Hey @ephys I was thinking of picking this up but I think it's already done? https://github.com/sequelize/sequelize/blob/main/src/model.js#L4009

**Comment by frostzt** [comment]
You're awesome @ephys I will try my best and have a PR ready for this, and I'll be sure to get back to ask for help if I need any further guidance! Thanks!

**Comment by frostzt** [comment]
Hey @ephys I believe the `update()` is already handled for this case. Since to create a model we would need to save it? Or my thinking is wrong? I tried to make a simple unit test for the `update()` method on instance and it throws since the save method is invoked first automatically. Or am I missing something, a bit of explanation would be awesome!
