### ISSUE TITLE
include dataValues can not be _sanitize

### ISSUE THREAD

**Issue by brucewar** [sequelize/sequelize#14438]
sequelize: v6.19.0

```js
User.findAll({
  include: [{
    model: SystemUnit,
    as: 'systemUnit'
  }]
})
```

I have tried to debug code and found that systemUnit attributes did not execute its DataType._sanitize

**Comment by brucewar** [comment]
`model.js` _setInclude childOptions maybe like this?
![image](https://user-images.githubusercontent.com/4013475/164951299-f48c7e9e-5dae-4585-9c2c-4138ddbe7711.png)

**Comment by ephys** [comment]
I'm afraid I don't understand what the issue is

`DataType._sanitize` is an internal method, it doesn't exist for every datatype

What's the issue you're encountering? Is one a value improperly parsed from the database?

Can you create a [SSCCE](https://github.com/sequelize/sequelize-sscce) as specified in our issue templates, as well as answer the questions that were asked? (see https://github.com/sequelize/sequelize/issues/new?assignees=&labels=&template=bug_report.md&title=)

**Comment by brucewar** [comment]
For example, if I defined `INTEGER` in custom dialect `data-types.js`，and overload _sanitize.

```js
class INTEGER extends BaseTypes.INTEGER {
  _sanitize (value) {
    if (typeof value  === 'bigint') return parseInt(value, 10);
    return value;
  }
}
``` 
If  include `SystemUnit` model has an INTEGER attribute in the above code, then `sequelize` would not execute into `_sanitize `
