### ISSUE TITLE
Join to Organization

### ISSUE THREAD

**Issue by Estevamsl** [sequelize/sequelize#14711]
Because I want to stay on top of everything that goes on in this organization and of course, as a good dev, you have to know about the challenges of this incredible world of programming

**Comment by WikiRik** [comment]
Hi! I'm not sure what your request is. If you want to know everything that's going on you can watch our repositories in GitHub and join our Slack. There's no need to join our organization on GitHub directly because we try to have most of our discussions on an open platform. Feel free to reach out on Slack if you have further interest in joining our team. The link for that is https://sequelize-slack.herokuapp.com/
