### ISSUE TITLE
Could Sequelize support both Sequelize.DATE and Sequelize.DATETIME

### ISSUE THREAD

**Issue by vjames19** [sequelize/sequelize#1514]
Currently I'm finding myself with the need to just store the date and not the timestamp, since it would alter my results by having a different time.

I'm using postgres and since I don't need the timestamp I'm finding myself using the 'date_trunc' function in raw sql queries.

Could you point me out if this could be fixed? And if need be I could create a PR.

**Comment by apapap** [comment]
How about adding a Sequelize.MOMENT_TZ type instead?  :)  Then just bypass all the "imperfections" of the JS Date() object and date/time handling of most of the databases.  See http://momentjs.com/ .  

More seriously, @overlookmotel and @vpontis, the addition of DATEONLY seems like a decent approach, and I recognize that it was added initially only as a hack, but it's currently a little dangerous without caveats in the documentation.  For example, if you create an instance with attribute `dateOnly1: new Date('3/1/2015')` and retrieve it with `dateOnly1.toString()`, you'd expect to get March 1.  Instead, you get `Sat Feb 28 2015 19:00:00 GMT-0500 (EST)`.  The servers are in EST.  

Even worse, retrieving the same attribute with `dateOnly1.toLocaleDateString()` results in `Saturday, February 28, 2015`!  :)

These results are probably because on retrieval the JavaScript Date object currently treats the '3/1/2015' DATE value in the database as having 0:00 time UTC and converts it to the local timezone.

**Comment by janmeier** [comment]
@apapap Thats a very legitimate concern indeed. I'm not even sure that `DATEONLY` should be returned as `Date` instances - rather I'd like it to be returned as strings, or a POJO with date, month and year props.

Regarding `MOMENT_TZ` - This could happen with datatypes up / down, which is hopefully not too far away (https://github.com/sequelize/sequelize/issues/2042)

In my mind this would allow something like
```js
MOMENT_TZ = Sequelize.DATE.extend({
  down: function (value) {
    return moment(value);
  }
  up: function (date) {
    return date.format('YYYY-MM-DD HH:mm:ss.SSS Z');
  }
}); 
```
So that when you get something from the DB it is returned as a moment instance, and sequelize expects a moment instance coming in

**Comment by alchen** [comment]
I have some `date` columns in Postgres that doesn't quite exhibit the same behavior as @apapap's, instead they are getting dumped into my local timezone, and I've not been able to figure out where this happens in the code:

 `2015-05-10` in Postgres gets converted into `Sun May 10 2015 00:00:00 GMT-0700 (PDT)` when retrieved or `2015-05-10T07:00:00.000Z` when JSON.stringified.

I read that Sequelize handles time internally in `UTC`, so I'm not sure if this is the expected result.

**Comment by janmeier** [comment]
@alchen Try adding a custom date parser with https://github.com/brianc/node-pg-types. 

The date from pg is being converted to a JS date object, which defaults to your current timezone.

You are also welcome to provide a PR that by default uses `sequelize.options.timezone` for dates without timezone

**Comment by alchen** [comment]
Ah, that link explains what `1114` was in the documentation. FWIW, `1082` is the `OID` for date columns:
```
require('pg').types.setTypeParser(1082, function(stringValue) {
  return new Date(stringValue);
});
```
It also parses slightly differently; the added parser produces `2015-05-10T00:00:00.000Z` instead of `2015-05-10T07:00:00.000Z`.

I'll see if I can figure out what Sequelize does and make appropriate changes.

**Comment by janmeier** [comment]
@alchen sweet :). It should be as simple as adding the code you show here in the pg connection manager.js / query.js. 

Remember to use `new Date(stringValue + sequelize.options.timezone)` - users may specify which timezone they want the data in

**Comment by alchen** [comment]
@janmeier I tried to do that, but there is a problem: if this was handled through `setTypeParser` in pg's `connection-manager.js`, then different instances of `sequelize` will be using the latest set parser and thus the same timezone. Even if this isn't a common use case, writing test case will be tricky. Probably better leave it for customization by the user for now, before #2042 happens.

**Comment by janmeier** [comment]
@alchen ah yeah thats true

**Comment by dgerena** [comment]
Hello, and thank you all for your work assistance and just all around conversations and topics for sequelize. I am currently working with a MSSQL server (so i believe tsql syntax.) And just ran into a strange... bug? i may call it. To give the rundown I created a single component that contains all it needs sequelize and the driver tedious among them. I have in this same document defined my models for the sake of seeing it all where i am working. The connection and all models and everything works Yet with a single work around. The database (I do not have the ability to modify or change design of) has a single row set to a datetime data type. When i used DATE i get a error and truncate warning.. {SequelizeDatabaseError: String or binary data would be truncated. Through trial and error i found my DATE 's to be the failing cause. After scouring about i learned of the tsql data types datetime and datetime2 and attempted to use DATEONLY. That worked like a charm and the fields are populating properly EVEN with a full timestamp... In which the term dateonly makes me scratch my head. Thank you for all you are doing, I have the situation functioning (albeit probably improperly) and wanted to at least bring this funky business to your attention. I will continue to monitor and see all of your input on the subject. Thanks (sorry bout all the thanks) I really appreciate all of your work guys.

**Comment by janmeier** [comment]
@dgerena `DATEONLY` is supposed to be only the date part (without time) - but it might be that we actually inserts the full timestamp, and a `DATE` field in mysql just ignores it. The reason you are getting a truncation warning is probably that the precision is too high, because we assume the backing for the timestamp is always `datetime2`

**Comment by justechn** [comment]
Any update on built-in support for this? I am just implementing sequelize and running into this issue.

**Comment by andrest** [comment]
Just stumbled on this too. The DATEONLY type is vexatious as the value returned varies on the system's timezone. Adding a custom parser works but it's not very obvious. I would expect to see the value returned as it's stored in the database.
