### ISSUE TITLE
False Warning: Timezone Configuration

### ISSUE THREAD

**Issue by AlexanderFalconi** [sequelize/sequelize#15693]
Many of us cannot use the timezone notations '-08:00' in documentation because we have to deal with daylight savings. When using the actual daylight savings 'America/Los_Angeles' it actually works, but a warning is thrown that complains it is an invalid configuration. 

I see that other sequelize users have figured this out: https://github.com/sequelize/sequelize/issues/854 (scroll down to those who figured out they can put Asia/Kolkata in as timezone.) 

Please remove the warning, since using the string seems to be working perfectly, is not an issue, and is actually required by those of us who are stuck with daylight savings issues. I tried -08:00 and it only works half of the year :P

**Comment by ephys** [comment]
Which database are you using and which warning are you referring to?

**Comment by WikiRik** [comment]
The warning refers to MySQL2, indicating that this is not a sequelize issue. The source code of that project refers to the original MySQL Node driver which has documentation on the supported formats for `timezone`; https://github.com/sidorares/node-mysql2/blob/master/lib/connection_config.js#L119-L133

I would recommend searching through the issues of those two projects to see why something like `Americas/Los_Angeles` is not supported.

**Comment by ephys** [comment]
That's because mysql itself does not support setting the timezone option to an actual time zone, they only accept timezone offsets.

The reason some things may work is because of we also use it in the Date datatype. I'm pretty sure it's a dangerous feature (looks like it's working but will eventually cause problems in your dates), but I am not sure yet. I personally strongly recommend against using that feature, but I'd need to know more about your use case to recommend a safe alternative

**Comment by WikiRik** [comment]
I'll close this as this should be added to mysql first before we work on it in sequelize
