### ISSUE TITLE
Raw queries not working with latest version of mariadb connector

### ISSUE THREAD

**Issue by tomfriedhof** [sequelize/sequelize#15701]
## Bug Description

Using the latest version of mariadb connector package (https://www.npmjs.com/package/mariadb) at version 3.1.0 produces the following error when running a raw query

```
Executing (default): SELECT * from mytable LIMIT 2
The error is TypeError: Cannot delete property 'meta' of [object Array]
    at Query.formatResults (/app/node_modules/sequelize/lib/dialects/mariadb/query.js:110:7)
    at Query.run (/app/node_modules/sequelize/lib/dialects/mariadb/query.js:73:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/sequelize/lib/sequelize.js:314:16
    ...
```

### What do you expect to happen?

Based on the stack trace pasted above, it seems that from version 3.0.2 to 3.1.0 the `Query.run` method changed the response type which is causing the error in Sequelize.

To get around this issue, lock mariadb to 3.0.2 and everything works as expected.

### Environment

- Sequelize version: 6.28.1
- Node.js version: 18.14.1
- If TypeScript related: TypeScript version:
- Database & Version: MariaDB:10.11
- Connector library & Version: mariadb:3.1.0

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by WikiRik** [comment]
Hi! We do not support mariadb v3 yet. For v3.0.2 there are a few failing tests due to the changed workings of BigInts iirc, but the rest works. Indeed for v3.1.0 more tests are failing.

We will add the support for mariadb v3 in sequelize v7. Support for mariadb v3 in sequelize v6 is not expected at this stage, since the first v7 beta is getting close.

**Comment by tomfriedhof** [comment]
I appreciate the quick response, and thanks for the update. I'll keep an eye out for the v7 release so that I can unlock the mariadb dependency and test things out.

**Comment by felicienfrancois** [comment]
This it not due to some api change in mariadb connector but more with an [unuseful and illegal delete data.meta command](https://github.com/sequelize/sequelize/blob/v6/src/dialects/mariadb/query.js#L143) in sequelize code which trigger an error in strict mode.
The meta property on data is defined as not configurable (the default with Object.defineProperty), which means not deletable.

On v7 branch it has been solved 3 years ago when enabling strict eslint config. [The corresponding live have just been deleted](https://github.com/sequelize/sequelize/blob/v7/packages/core/src/dialects/mariadb/query.js#L141).

I don't know how far v7 is close to the release, but applying this small fix on v6 would be easy and fix raw queries on mariadb with connector v3 and in an enforced strict mode environment.
