### ISSUE TITLE
Debugger doen't work with node.js > 16 because Context lost after await (cls-hooked related)

### ISSUE THREAD

**Issue by LeoLfL** [sequelize/sequelize#15751]
I just tried to use a debugger with the sequelize (latest version) module and found that in **node.js 18** with enabled **cls** it failed with the error message 

`No context available. ns.run() or ns.bind() must be called first.`

the error occurs only when you use the debugger. with normal start logic everything works fine 

it's related to this bug report https://github.com/Jeff-Lewis/cls-hooked/issues/74

it would be nice to find a solution for this because debugger is must have for the development process

**Comment by ephys** [comment]
async_hooks in general have had issues in Node 18. AsyncLocalStorage had this exact issue until node 18.9.0.

If you're on Node < 18.9, you can always try using a more recent node release

Here is the node issue about this: https://github.com/nodejs/node/issues/43148

Sequelize 7 uses AsyncLocalStorage instead of cls-hooked, but we can't backport that as it would be a breaking change.

There is not much more we can do about this

**Comment by LeoLfL** [comment]
ohh @ephys thanks a lot! with node 18.15.0 it works. so yes, it was related to the node version. thanks again ^^
