### ISSUE TITLE
Does Sequelize support passwordless authentication in PostgreSQL?

### ISSUE THREAD

**Issue by ysulyma** [sequelize/sequelize#1591]
I'm specifically interested in [peer authentication](http://www.postgresql.org/docs/current/static/auth-methods.html#AUTH-PEER)

**Comment by bikeshedder** [comment]
This is an issue in the _pg_ library: https://github.com/brianc/node-postgres/issues/613

It is possible to connect to unix domain socket right now, but the solution is far from being obvious:

```javascript
var sequelize = new Sequelize(databaseName, null, null, {
    host: '/tmp', // or /var/run/postgresql
    dialect: 'postgres',
});
```

Debian and Ubuntu decided to move that socket somewhere else so you need to pass `'/var/run/postgresql'` there.

It would make a lot more sense to use `null` as host or `'postgresql:///'` as the connection url, but that's currently not possible because of [issue 613](https://github.com/brianc/node-postgres/issues/613) in the _pg_ library.

Took me quite a while to figure that out so I'm adding this to the issue even though it's already closed.
