### ISSUE TITLE
Ability to specify plural & singular for model

### ISSUE THREAD

**Issue by aaronshaf** [sequelize/sequelize#1598]
``` javascript
var Individual = sequelize.define('Individual', attributes, {
  singular: 'individual',
  plural: 'individuals',
  tableName: 'INDIVIDUALS'
}
```

In my situation I have to use pre-existing tables that are, yuck, all uppercase. Even with `freezeTableName: true`, with a hasOne relation it will be returned as "iNDIVIDUAL" (lower case first letter).

**Comment by SolveSoul** [comment]
Is this still possible? It seems like the modelName is overridden in `model.js`

```
      name: {
        plural: Utils.pluralize(options.modelName),
        singular: Utils.singularize(options.modelName)
      },
```

where modelName is just the table name and not the name property of the options.

**Comment by timhuff** [comment]
This might need to be reopened. I just attempted to make use of this feature and it appears to not be working. Here's my definition:
```javascript
const Tech = db.define(
  'Tech',
  {/* field defs */},
  {
    name: {
      singular: 'Tech',
      plural: 'Techs',
    },
  }
)
```

When I run `sync()`, it creates a table called `Teches` (which I've confirmed [here](https://npm.runkit.com/inflection) is the output of running `pluralize()` on `"Tech"`).

**Comment by mnavarromugas** [comment]
It doesn't work with the create<ModelNameInPlural>.

For example, in a migration file:

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Locales', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      nombre: {
        type: Sequelize.STRING
      },
        ...  
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('Locales');
  }
};

And in model:

module.exports = (sequelize, DataTypes) => {
  const Local = sequelize.define('Local', {
  ...
  }, {
    name: {
      plural: 'Locales',
      singular: 'Local',
    }
  });
  Local.associate = function(models) {
    Local.hasOne(models.Postulante);
  };
  return Local;
};

When i want to create a local:
...
}).then(postulante => {
      postulante.createLocal({
        nombre: "nombre del local"
      });
    })

It produces (with 'Locals' instead of 'Locales'):

 INSERT INTO `Locals` (`id`,`nombre`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'nombre del local','2019-01-06 01:56:45','2019-01-06 01:56:45')
