### ISSUE TITLE
freezed table name not working on association name

### ISSUE THREAD

**Issue by mithrandirii** [sequelize/sequelize#1613]
hi,

i have an problem with the current master and freez table names. if i associate an model with freezed table name and an 's' (e.g. xyzs) at the end of the model name the association name in model.associations (e.g. model.associations.xyz) is without the s. but the s is not from pluralize, its my model/table name ?!

we use the current master of sequelize

mithrandir

**Comment by ajmueller** [comment]
@mickhansen I stumbled upon this issue when I was having a similar issue myself and am curious what your thoughts are.  In my opinion, what I'm seeing is unanticipated and strange behavior and I would classify as a bug, but perhaps I'm missing something.

The issue I'm having is that associations get created with pluralized names even if you set `freezeTableName` to `true`.  Since setting that property keeps the table name from getting modified by Sequelize via pluralization, my assumption would be that any associations to it would also be created without any modification by Sequelize via pluralization.

In my case, I have two models in a 1:M assocation, `GearType` and `Gear` (gear here being equipment or accessories, not a gear like in a machine).  As such, the `Gear` model should not be pluralized because this version of the word in English is not pluralized (e.g. one never says "fishing gears"), so it has `freezeTableName` set to `true`.  However, in my association, `GearType` is associated with hasMany to `Gears`, making my queries return with a key of `Gears` instead of `Gear`.  As mentioned above, I consider this to be unanticipated and strange behavior given the fact that `freezeTableName` is set to `true` for the `Gear` model.

My current solution is to use aliasing with `as` like you mentioned above.  This works, but adds in extra, seemingly unnecessary logic in our application that I'm hoping could be resolved in Sequelize, assuming you consider this a bug.  If it's better to create a separate issue and mention this one, I'd be happy to open a new issue; I merely figured the content and title of this issue was related enough that it was worthy as a starting place.  However, if you don't consider this to be something that needs to be fixed, I can stick with my alias solution.

**Comment by alvarofblanco** [comment]
I don't know why but @mickhansen answer only works for findAll and not for findOne

**Comment by papb** [comment]
Hello @ajmueller, feel free to ping me next time when you want to ask/discuss something. Sorry that it took me 8 months to see your message. I assume you're still using the workaround you mentioned? Please let me know, I will try to help you, thanks

**Comment by papb** [comment]
@alvarofblanco Can you create a [sequelize-sscce](https://github.com/papb/sequelize-sscce) to show what you said? Thanks

**Comment by ajmueller** [comment]
@papb thanks for the reply!  We are still using the workaround that I mentioned.  We have a few helper functions to make our lives easier, but it still means having to remember the workaround every time you make changes to or add code related to the `Gear` model I mentioned above.  If this functionality could be fixed in Sequelize, that would be awesome.  Let me know what I can do to help.

**Comment by papb** [comment]
> Let me know what I can do to help.

Thanks for being willing to help :grimacing: finding time to help maintain Sequelize has been hard, so many things happening here :grimacing: 

The first thing that comes to my mind, that you could probably do without much trouble and that would be super helpful, would be for you to create a [sequelize-sscce](https://github.com/papb/sequelize-sscce) showing your situation in which things are pluralized when they shouldn't. Thanks!!

**Comment by Ionys320** [comment]
Hello, I have the same issue with the 6.3.3 version ^^"
