### ISSUE TITLE
hasMany creates column but not constraint

### ISSUE THREAD

**Issue by JasonTheAdams** [sequelize/sequelize#1761]
Been working with sequelize for a couples days now. Awesome. :)

I was using the "references" option to define foreign keys (postgres), but then found the association functions. I'm finding, however, that while the functions add the column, they're not adding the constraints (and, obviously cascading).

I'm importing all the definitions and then running the association functions subsequently. Am I doing something out of order? I've looked around and this doesn't appear to be a bug.

**Comment by MtDalPizzol** [comment]
I'll not open a new issue for my problem, since I think this one is highly related to it and I did not saw any feature request for this. My code is as follows:

##### Models
```javascript
User.belongsToMany(UserGroup, {
    through: UserToUserGroup
});

UserGroup.belongsToMany(User, {
    through: UserToUserGroup
});

User.hasMany(Address, { onDelete: "CASCADE" });
Address.belongTo(User);
```
##### Controller
```javascript
User.destroy({
            where: condition // { id: req.query.id }
        }).then(function() {
            // Success!
        })
```

I have tried this with **v2.0.0-rc6** and **v2.0.3** and none of these work as expected. The records on the **User** and **UserToUserGroup are gone as expected**, but the **records on Adresses table still there with the user_id set to NULL**.

**Comment by mickhansen** [comment]
@MtDalPizzol did you resync? Constraints are database constructs, we don't simulate them in sequelize currently.

**Comment by MtDalPizzol** [comment]
I did not actually resynced, but I deleted the mentioned tables manually and restarted my app causing this tables to be created again. I have no idea if this have the same result than resync.

**Comment by mickhansen** [comment]
It is. .sync() creates tables, .sync({force: true}) drops them first.

**Comment by MtDalPizzol** [comment]
Right... I thought so... Any ideas about what can I do?

**Comment by mickhansen** [comment]
Well, drop/sync (which you said you already did) or manually setup foreign key constraints.

**Comment by MtDalPizzol** [comment]
@mickhansen , thanks for the attention until now. You're being a lifesaver since I'm using Sequelize on my company. I tried @JasonTheAdams solution, like this:

```javascript
User.hasMany(Address, { onDelete: "CASCADE" });
Address.belongsTo(User, { onDelete: "CASCADE" });
```
It in fact workek: records on Address table are being deleted now., But it resulted in another unexpected situation. Now, when i do something like:

```javascript
User.removeAddresses([address1, address2]);
```
It is setting user_id to NULL, not deleting the records as before. =/

**Comment by mickhansen** [comment]
@MtDalPizzol Hmm, i'm afraid that is as expected from the Sequelize point of view, `remove` generally disassociates, does not delete.

**Comment by MtDalPizzol** [comment]
Ok then... I'll work round this. Much thanks again! =)

Wouldn't be nice to have an option to force the deletion? Something like:

```javascript
User.removeAddresses([address1, address2], { force: true});
```

I could open a feature request for this...

**Comment by mickhansen** [comment]
@MtDalPizzol yeah i definitely see the merit of such a feature, especially for models that can't exist without being attached to another model :)
