### ISSUE TITLE
Hooks refactor + new hooks

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#1852]
This is just a issue for the milestone tracker.
We'll keep track of the general hook update progress here.
- [x] context/options on all hooks (#2240)
- [x] find hooks
- [x] connection hooks
- [ ] query hooks
- [ ] build hooks

**Comment by cusspvz** [comment]
@mickhansen I need to implement a caching layer on the next 2 days, could we discuss about how to implement it via hooks?

If I had the chance, i would vote to allow returnable values, only on **beforeFind** for now.

**Comment by mickhansen** [comment]
@cusspvz As i remember we don't have a good design for it yet. Having to remember to do `.return(undefned)` everytime is not ideal. Very open for suggestions on this (it could be attaching an option)

**Comment by cusspvz** [comment]
Attaching an option to allow returning something trough the hook option? I think the issue would maintain since a cache plugin would need to mark that option as default.

I was thinking on something internal, like assigning a sub-method on callback, or returning a specific wrapper Class.

Lets skip to approaches API examples...

## Approach 1 - sub-method on callback, by calling `done.return`
```
Model.hook( 'beforeFind', function ( options, done ) {
  return Promise.try(function () { return []; })
    .then(function ( instances ) {
      done.return( instances );
    });
});
```

## Approach 2 - returning using promise context
```
Model.hook( 'beforeFind', function ( options, done ) {
  return Promise.try(function () { return []; })
    .then(function ( instances ) {
      this.return = instances;
    });
});
```

## Approach 3 - returning an instance of some WrapperClass

```
var Sequelize = require( 'sequelize' );

Model.hook( 'beforeFind', function ( options, done ) {
  return Promise.try(function () { return []; })
    .then(function ( instances ) {
      return new Sequelize.Return( instances );
    });
});
```

NOTE to all approaches: if there are results to be returned, we shouldn't run next hooks on stack.

**Comment by cusspvz** [comment]
PS: I've added a proposal (#2932) on a separated issue so we can have separated discussions.

**Comment by mickhansen** [comment]
I meant adding a flag to the options inside the hook, sorry if that wasn't clear.
Not sure adding to the promise context is not feasible since that's influenced by bind.
Agree that if values are returned it will short circuit hook execution.

Honestly not a huge fan of any of those 3 approached (not that i have any better suggestions at the moment).

**Comment by cusspvz** [comment]
The only one that seems more reasonable for me its the last one, but I agree with you, I don't think that it is good enough...

**Comment by mickhansen** [comment]
```js
Model.hook( 'beforeFind', function (options) {
  this.returnsInstances = true;
  return Promise.try(function () { return []; });
});
```

**Comment by cusspvz** [comment]
> Edit: Oh wait, this is the Model for all hooks.

I was thinking on that... :)

**Comment by cusspvz** [comment]
I was thinking about another approach, a dirty one, but since I'm on verbose mode caused by the lack of solutions... :D

## Approach 5 - setting `_sequelizeResult`
```
Model.hook( 'beforeFind', function ( options, done ) {
  return Promise.try(function () { return []; })
    .then(function ( instances ) {
      instances._sequelizeResult = true;
      return instances;
    });
});
```
Then, obviously, after response evaluation it should be deleted before returned to original method returned promise.

**Comment by cusspvz** [comment]
I hope this last approach could help you to lead to a better one! :)

**Comment by awdogsgo2heaven** [comment]
Is there any hook out there that can be called after a model is created no matter how its created? (through build , create, or whatever). I have some post processing I would like to do on some models..

**Comment by mickhansen** [comment]
@awdogsgo2heaven build/save, findOrCreate and create are handled by the beforeCreate, upsert is not handled by that.

**Comment by tom2strobl** [comment]
Sorry for digging out old threads again, but I have a case where I need to hydrate a user model with data fetched via http from a different server (async) and I can't seem to find any option to accomplish it with sequelize.
### Option A): Virtual Field
I'd like to have one http request for multiple fields, but even if I'd group it under one field getters can't be async, so that's not gonna work.
### Option B): Hooks
Unfortunately hooks seem to be only fired when changing data, not on queries.
### Option C): Overriding fetch
We used bookshelf in the past where we monkey-patched fetch() and fetchAll() on the model, with Sequelize I don't even know where to start if going this route and it's quite dirty.

So are there any updates regarding reading hooks? Maybe I missed something? Any other ideas?

**Comment by jacob-israel-turner** [comment]
Just curious if `afterFind` was ever implemented?  I'd love to use to to apply formatting (applying a base URL to an image column) across the board, rather than manually after each find.

**Comment by guylhermetabosa** [comment]
@jacob-israel-turner I don't think so, but would be great to have this feature.

**Comment by guylhermetabosa** [comment]
@overlookmotel Glad to know that, but I wasn't able to find in the docs.

**Comment by jacob-israel-turner** [comment]
@overlookmotel Awesome!  Good to know!  Would be nice to have in the docs, as @guylhermetabosa mentioned.  If there's no update to the docs before I'm able to implement `afterFind` in my codebase, I'll take a whack at a PR updating them.

**Comment by overlookmotel** [comment]
@jacob-israel-turner Just to clarify, I'm not a maintainer of Sequelize. I've not contributed for a couple of years now as busy with other things. So if you want it in the docs, yes make a PR!
