### ISSUE TITLE
Drop table doesn't drop custom type

### ISSUE THREAD

**Issue by ee99ee** [sequelize/sequelize#1871]
When dropping a table with a custom type (e.g., enum), the dropTable method doesn't also remove the type. Maybe it shouldn't, but there doesn't seem to be a method to remove the type. Since Sequelize automatically adds the type, there should be _some_ way to remove it.

(This is for Postgres)

**Comment by artlogic** [comment]
I can confirm this. The problem seems to be this line:

```javascript
var daoTable = self.sequelize.daoFactoryManager.getDAO(tableName, { attribute: 'tableName' });
```
https://github.com/sequelize/sequelize/blob/799dcf7af78d5eb00e4c890eb00ce5a3f37cf62c/lib/query-interface.js#L213

During the course of migrations, when models have not been loaded, this returns undefined, and the following logic to remove enums is never executed. This wouldn't be nearly as bad if the QueryInterface had dropEnum method, but for some reason it doesn't.

I can also confirm that if models are loaded, this problem does not occur.
