### ISSUE TITLE
Transactional migrations

### ISSUE THREAD

**Issue by meredian** [sequelize/sequelize#1882]
I've explored code for 1.7.8 and encountered a fact, that it's not possible to run migrations in a transaction. Is it a design feature or limitation? After some hacking I had passed queryParams to createTable sql, and it looked quite working.

This question leads me to another one: What is current migration behaviour? What actions should be performed according to library design to handle situation when migration (somewhy) fails?

**Comment by dorrotman** [comment]
Hi there, searched on this topic and got to this issue.

I am trying to figure the best practice for grouping together several DDL operations in a single migration. I want to avoid a scenario where a part of the migration has run, there was some error (power failure for instance), and upon re-running the migration, it failed because it could not resume where it left off.
I see this is OK when calling `migration.createTable` because it translates to  `CREATE TABLE IF NOT EXISTS` (at least in MySQL). What about other DDL commands? are they always conditional?

(Actually, since the migration is logged only when `done` is called, it is also possible for a failure to occur between the migration and the logging of its execution. So this can happen with a single DDL operation as well.)

Thanks!

**Comment by sdepold** [comment]
HI there. It should be fairly simple to wrap single migrations in transactions. You would just need to add the transaction part to the migration itself. We could probably also add that by default within the CLI/Umzug. If you want a rollback for every executed transaction once one failed, things might be a bit different. *thinks* What happens internally is: We are gathering all migrations that have to be executed and run them step by step afterwards. In theory it should be possible to just wrap a big transaction around it. Rollbacking would need to be adjusted for such a case though.

**Comment by sdepold** [comment]
@dorrotman Not every DDL command is conditional. Only create table and drop table afaik.

**Comment by dorrotman** [comment]
It's indeed a question, what is an atomic unit? Is a single migration the atomic one, or the whole pending set of migrations? I believe that since they are up/downable, probably a single migration is an atomic unit. At least that could work for me. If some migration's `up()` method failed, I can always go back by calling `down()` as much as needed. Also, transactions on a large list of DDL commands can become huge. 

I'm trying to handle a different challenge: What if my database (MySQL) doesn't support transactions on DDL. In a rare case, I could add a column and then power would turn off, preventing persistence of the migration success into the `SequelizeMeta` table. Then upon retry, the migration would be retried since it wasn't marked as executed. The column would already exist and the migration would fail and there would be no recovery aside from manually fixing the state. To prevent this, I am probably going to have to call `migration.describeTable()` in this case to make sure the column does not exist before attempting its creation.

**Comment by sdepold** [comment]
I actually just noticed that my answer was partially non-sense. If nothing has changed dramatically lately one still has to tell a function to actually use a transaction. That means I won't be able to actually automagically wrap a transaction around a migration. You'd have to create a transaction in the migration's up/down method and pass it to the respective DDL calls.

**Comment by sdepold** [comment]
Yes you are right. This can happen and I'm not sure if there is a sane way to fix that.

**Comment by dorrotman** [comment]
Thanks for the replies! :thumbsup:

**Comment by mickhansen** [comment]
Truly idempotent migrations is a tricky thing indeed :)

**Comment by rjmunro** [comment]
+1 to this feature. By default migrations should happen in a transaction. When anything fails, the transaction should be rolled back. That way you can fix the migration and try again. When writing a migration I shouldn't have to think about this. SQLite documentation says that to make changes to a database, the [proper procedure](https://www.sqlite.org/lang_altertable.html#otheralter) includes starting a transaction (step 2)

[All major databases](http://stackoverflow.com/a/4736346/3408) support transactions for DDL statements, except MySQL. MySQL is seriously broken here.

**Comment by mickhansen** [comment]
@rjmunro integration transaction support for DDL statements in sequelize should not be a lot of work.
As for automatically running migrations in transactions you'll have to open an issue at umzug, perhaps suggest using CLS.

**Comment by josser** [comment]
Before it's not implemented, is it safe to use such workaround:  

```javascript
up: function (queryInterface, Sequelize) {
    var sequelize = queryInterface.sequelize;
    
    return sequelize.transaction(function(t) {
            
      return Promise.all([
        
        sequelize.query('CREATE TABLE .. ', {transaction: t}),
        sequelize.query('DROP TABLE ..', {transaction: t}) 
      
      ]);      
            
    });
  },
```

Thanks!

**Comment by kylecordes** [comment]
Echoing what many others above written, I but also much appreciate if migrations were transactional (each migration, and perhaps a group of them together optionally). Most RDBMSs nowadays support this, I don't see a reason to omit the feature because one or a handful do not.

**Comment by mickhansen** [comment]
@kylecordes Some methods already support the transaction option, haven't gone through everything though.

**Comment by rjmunro** [comment]
The problem with using transactions manually inside my migration myself is that it won't include the changes to the SequelizeMeta table. If that table can't be updated, the whole migration should be rolled back. If any other part of the migration cannot happen, SequelizeMeta should be rolled back.

**Comment by mickhansen** [comment]
@rjmunro makes sense, so to start we need umzug or whatever migration library you're using to support a transaction setting of some sort.

**Comment by brad-decker** [comment]
Quick question. If the queryInterface passed in migrations eventually calls sequelize.query and passes in the options argument how do migrations not support transactions? Something i'm missing here?

**Comment by mickhansen** [comment]
@brad-decker Well the migrations that don't support transactions should not receive a transaction option from the user

**Comment by shawnbissell** [comment]
Whats the status of this? Is there an acceptable workaround using manual transactions?

**Comment by shawnbissell** [comment]
I just tested @josser workaround and it does work correctly. As long as the transaction result is returned, the SequelizeMeta table is not updated when the rollback occurs (the same as when a javascript error is encountered) so it's possible to fix the script and just do the migration again.

**Comment by DiegoGallegos4** [comment]
@shawnbissell How has it work for you? Do you recommend this approach?

**Comment by shawnbissell** [comment]
Very well. I use this method in all of my migration scripts.

**Comment by josser** [comment]
I must say, my solution is not "general". 
In most cases you can run all migration scripts at once via Promise.all() but sometimes you want step-by-step execution. I.e: create table and after that add index. 

For those of you guys who using babel / es7 features there is a cool way to write migrations: 

Here is two examples: 

`
module.exports = {
  up: ({ sequelize: db }) => db.transaction(transaction => Promise.all([
    db.query('...', { transaction }),
    db.query('...', { transaction }),
  ])),

  down: ({ sequelize: db }) => db.transaction(async (transaction) => {
    await db.query('...', { transaction });
    await db.query('...', { transaction });
  }),
};
`

**Comment by pkyeck** [comment]
@josser I know it's been a while but wanted to ask nonetheless.
writing the migration like this:

```javascript
db.transaction(async (transaction) => {
  await queryInterface.addColumn('...', { transaction });
  await db.query('...', { transaction });
})
```

there is no rollback happening when one of the queries is throwing an error. was this working for you?

**Comment by CocaColaBear** [comment]
@pkyeck same result. No rollback
