### ISSUE TITLE
Is it possible to add "synthetic" attribute to use in ORDER BY?

### ISSUE THREAD

**Issue by 747500** [sequelize/sequelize#1915]
Something like `select *, (now() - order.start_date) as distance from ... order by distance asc`

**Comment by aberigle** [comment]
I'm trying to use this approach with `findAndCount` and pagination/limiting and it seems not possible. It's complaining with `ER_BAD_FIELD_ERROR: Unknown column` when trying to append the ``ORDER BY `model`.`field` ASC `` in the nested query because mysql is not able to find the column. Could I be missing something? 

Thanks!

**Comment by felixfbecker** [comment]
@aberigle Please don't resurrect old issues. I can confirm that it works, please consider asking your question with code snippet on StackOverflow or Slack.
