### ISSUE TITLE
Problem using order and limit together when eager loading associations

### ISSUE THREAD

**Issue by icecubed** [sequelize/sequelize#2004]
I have a transaction table with multiple columns that correspond to primary keys in master tables. Basically simple one to one relations. 

When I use limit and order and I am eager loading all the relations in the findAll function, the resulting query generates a subquery for the FROM clause which is used by the LIMIT. The ORDER on the other hand is applied to the outer query. I am using LIMIT as there could be a zillion transactions and I need to page through them in a sane way. 

This does not provide the desired result as the order is not applied on the entire data set but rather on the set that is returned by the subquery. 

Is there a way I can apply the order on the subquery as well?

I am using Sequelize 1.7.9

``` javascript
db.Transaction.findAll({
          order: '`transactions`.`some_date` DESC',
          limit: 10,
          offset: 10,
          include: [{
            model: db.Master1,
            attributes:['name'],
            include: [{
              model: db.Master2,
              attributes:['name']
            }]
          }, {
            model: db.Master3,
            include: [{
              model: db.Master4,
              attributes: ['name']
            }]
          }, {
            model: db.Master5,
            attributes: ['name'],
            where: {
              id: '12345'
            }
          }]          
        })
```

yields SQL of the form 

``` SQL
SELECT `transactions`.*,
       `master1`.`name` AS `master1.name`,
       `master1.master2`.`name` AS `master1.master2.name`,
       `master3`.`name` AS `master3.name`,
       `master3.master4`.`name` AS `master3.master4.name`       
FROM
  (SELECT `transactions`.*,
          `master5`.`id` AS `master5.id`
   FROM `transactions`
   INNER JOIN `master5` AS `master5` ON `master5`.`id` = `transactions`.`session_id`
   AND `master5`.`id`='12345' LIMIT 10, 10) AS `transactions`
LEFT OUTER JOIN `master1s` AS `master1` ON `master1`.`id` = `transactions`.`id`
LEFT OUTER JOIN `master2s` AS `master1.master2` ON `master1.master2`.`id` = `master1`.`id_fk`
LEFT OUTER JOIN `master3s` AS `master3` ON `master3`.`id` = `transactions`.`master3_id`
LEFT OUTER JOIN `master4s` AS `master3.master4` ON `master3.master4`.`id` = `master3`.`master4_id`
ORDER BY `transactions`.`some_date` DESC;

```

Can the order be somehow shifted into the subquery? 

``` SQL
SELECT `transactions`.*,
       `master1`.`name` AS `master1.name`,
       `master1.master2`.`name` AS `master1.master2.name`,
       `master3`.`name` AS `master3.name`,
       `master3.master4`.`name` AS `master3.master4.name`       
FROM
  (SELECT `transactions`.*,
          `master5`.`id` AS `master5.id`
   FROM `transactions`
   INNER JOIN `master5` AS `master5` ON `master5`.`id` = `transactions`.`session_id`
   AND `master5`.`id`='12345'  
   ORDER BY `transactions`.`some_date` DESC 
   LIMIT 10, 10) AS `transactions`
LEFT OUTER JOIN `master1s` AS `master1` ON `master1`.`id` = `transactions`.`id`
LEFT OUTER JOIN `master2s` AS `master1.master2` ON `master1.master2`.`id` = `master1`.`id_fk`
LEFT OUTER JOIN `master3s` AS `master3` ON `master3`.`id` = `transactions`.`master3_id`
LEFT OUTER JOIN `master4s` AS `master3.master4` ON `master3.master4`.`id` = `master3`.`master4_id`;

```

**Comment by yangchristian** [comment]
+1 just ran into this as well

**Comment by nitrog7** [comment]
You might want to check this out, worked for me.
http://stackoverflow.com/questions/26021965/sequelize-with-nodejs-cant-join-tables-with-limit

**Comment by ataurrahim** [comment]
lucaswxp's solution still works. This needs a better solution.

**Comment by janmeier** [comment]
@ataurrahim Well the solution posted by @lucaswxp is the right solution :) The various ways of specifying order is mentioned [here](http://docs.sequelizejs.com/en/latest/docs/models-usage/#manipulating-the-dataset-with-limit-offset-order-and-group)

The reason a plain string won't work is that strings with mixed case needs to be escaped in postgres, which they won't be if you pass a string - when you pass an array with a column and a dir element its escaped properly, but we can't do that if its just a string.

This issue is not about the problem @lucaswxp mentioned, which can be easily solved, this pertains to limit and order in subqueries, which we are working on improvin g

**Comment by ataurrahim** [comment]
Thanks, got it.

**Comment by ppham27** [comment]
+ 1, I'm running into this problem, too. Any news on a fix?

**Comment by katiabondartw** [comment]
There's still an issue when trying to sort by both "parent" and "child" table fields. In SQL I would expect the inner query to have parent's sorting clause, and the outer to include the child's "order by". But at the moment it can only include both into both queries which definitely causes an error in SQL because the child table reference in the inner query is not defined (i.e. it says "missing FROM-clause entry for table "child").
Any workarounds for this case?

**Comment by aysbg** [comment]
So, I have had this problem yesterday, I was including another model and I am using pagination (obviously limit and offset are a must) and there is a need for order by clause as well.

I tried this:
`queryParams.order = 'created_at DESC'` - no go, complains that "created_at" column doesnt exist.
the this:
`queryParams.order = [['created_at', 'DESC']]` - only did sorting on first batch of results
so after re-reading the documentation I decided to try this:
```
queryParams.order = [
   [models.sequelize.col('"createdAt"'), 'DESC']
];
``` this produced correct SQL and data was being sorted properly on every page (limit + offset).

In my case the issue was "aliased" columns.

**Comment by chaudhryjunaid** [comment]
Needed feature. 
Order and limit both cannot be applied to included eager loaded models. I encountered the following error:
`Unknown column 'PostImages.index' in 'order clause'`

where PostImages belong to posts and PostImages table contains field index. Limit is applied on PostImages.

**Comment by DPM1** [comment]
On SQL server I was having the problem listed here:

http://stackoverflow.com/questions/26021965/sequelize-with-nodejs-cant-join-tables-with-limit

It seems that it is actually still not possible to order by a nested property, and select the top n rows.

This is a big problem as anyone using even moderately large datasets will want to sort and limit the return.

**Comment by rogergl** [comment]
It seems as if this is still a problem. The generated query looks like this:

`SELECT "person".*, "posts"."id" AS "posts.id", "posts"."title" AS "posts.title", "posts"."content" AS "posts.content", "posts"."createdAt" AS "posts.createdAt", "posts"."updatedAt" AS "posts.updatedAt", "posts"."personId" AS "posts.personId" FROM (SELECT "person"."id", "person"."firstName", "person"."lastName", "person"."email", "person"."createdAt", "person"."updatedAt" FROM "people" AS "person" LIMIT 2) AS "person" LEFT OUTER JOIN "posts" AS "posts" ON "person"."id" = "posts"."personId" ORDER BY "firstName";`

But that is wrong, since the ORDER BY "firstName" should be on the inner query.

**Comment by mountHouli** [comment]
I ran into a similar (or perhaps the same) problem.  My problem happens due to the combination of the LIMIT and ORDER subquery, and the _use of column name aliases_ on the column I'm ordering by.  Specifically, i have
`depature_time` aliased as `depatureTime`

### The fix/workaround is
(Not sure how to classify as fix/workaround because I don't fully understand how it should work.)

#### Example A
Doesn't Work (meaning, results NOT ordered by flight.depature_time AKA flight.depatureTime)
```
Model.flight.findAndCountAll({
  where: //Stuff
  include:  //Stuff
  limit: 20,
  offset: 0
  order: [[ sequelize.col('departure_time') , 'DESC' ]]
})
```
#### Example B
Works (meaning, results ARE ordered by flight.depature_time AKA flight.depatureTime):
```
Model.flight.findAndCountAll({
  where: //Stuff
  include:  //Stuff
  limit: 20,
  offset: 0
  order: [[ sequelize.col('departureTime') , 'DESC' ]]
})

```

### Queries

#### Example A
Doesn't work.
Notice attempt to order by 'depature_time', but column is aliased as 'departureTime'

```
SELECT
  "public.flight".*,
  "from"."id" AS "from.id",
  "from"."name" AS "from.name",
  "from"."city" AS "from.city",
  -- ...
  "to"."id" AS "to.id",
  "to"."name" AS "to.name",
  "to"."city" AS "to.city",
  -- ...
  "reservations"."id" AS "reservations.id",
  "reservations"."pending" AS "reservations.pending",
  -- ...
  "reservations.passenger"."id" AS "reservations.passenger.id",
  "reservations.passenger"."first_name" AS "reservations.passenger.firstName",
  -- ...
  "reservations.invitation"."id" AS "reservations.invitation.id",
  "reservations.invitation"."name" AS "reservations.invitation.name",
  -- ...
  "reservations.status"."id" AS "reservations.status.id",
  "reservations.status"."short_name" AS "reservations.status.shortName",
  -- ...
  "modifications"."id" AS "modifications.id",
  "modifications"."flight_id" AS "modifications.flightId",
  -- ...
  "trip"."id" AS "trip.id",
  "trip"."organisation_id" AS "trip.organisationId",
  "trip"."name" AS "trip.name",
  -- ...
  "trip.organization"."id" AS "trip.organization.id",
  "trip.organization"."name" AS "trip.organization.name"
  -- ...
FROM
(
  SELECT
   "public.flight"."id",
   "public.flight"."trip_id" AS "tripId",
   "public.flight"."departure_time" AS "departureTime",
   "public.flight"."arrival_time" AS "arrivalTime",
   "public.flight"."origin",
   "public.flight"."destination",
   -- ...
   "public.flight"."trip_id"

  FROM "public"."flight" AS "public.flight"

  WHERE "public.flight"."cancelled" = false

  ORDER BY "departure_time" DESC

  LIMIT 20

  OFFSET 0
)
AS "public.flight"

LEFT OUTER JOIN "public"."destination" AS "from" ON "public.flight"."origin" = "from"."id" 
LEFT OUTER JOIN "public"."destination" AS "to" ON "public.flight"."destination" = "to"."id" 
LEFT OUTER JOIN "public"."flight_reservation" AS "reservations" ON "public.flight"."id" = "reservations"."flight_id" 
LEFT OUTER JOIN "public"."passenger" AS "reservations.passenger" ON "reservations"."passenger_id" = "reservations.passenger"."id" 
LEFT OUTER JOIN "public"."invitation" AS "reservations.invitation" ON "reservations"."id" = "reservations.invitation"."flight_reservation_id" AND "reservations.invitation"."pending" = true 
LEFT OUTER JOIN "public"."reservation_status" AS "reservations.status" ON "reservations"."reservation_status_id" = "reservations.status"."id" 
LEFT OUTER JOIN "public"."modify_flight" AS "modifications" ON "public.flight"."id" = "modifications"."flight_id" AND "modifications"."approved" = false 
LEFT OUTER JOIN "public"."trip" AS "trip" ON "public.flight"."trip_id" = "trip"."id" 
LEFT OUTER JOIN "public"."organisation" AS "trip.organization" ON "trip"."organisation_id" = "trip.organization"."id"

ORDER BY "departure_time" DESC;

```
#### Example B
Does work.
Notice order by `departureTime`, which is what the column is aliased as.

```

SELECT
  "public.flight".*,
  "from"."id" AS "from.id",
  "from"."name" AS "from.name",
  -- ...
  "to"."id" AS "to.id",
  "to"."name" AS "to.name",
  -- ...
  "reservations"."id" AS "reservations.id",
  "reservations"."pending" AS "reservations.pending",
  -- ...
  "reservations.passenger"."id" AS "reservations.passenger.id",
  "reservations.passenger"."first_name" AS "reservations.passenger.firstName",
  -- ...
  "reservations.invitation"."id" AS "reservations.invitation.id",
  "reservations.invitation"."name" AS "reservations.invitation.name",
  -- ...
  "reservations.status"."id" AS "reservations.status.id",
  "reservations.status"."short_name" AS "reservations.status.shortName",
  -- ...
  "modifications"."id" AS "modifications.id",
  "modifications"."flight_id" AS "modifications.flightId",
  -- ...
  "trip"."id" AS "trip.id",
  "trip"."organisation_id" AS "trip.organisationId",
  "trip"."name" AS "trip.name",
  -- ...
  "trip"."organisation_id" AS "trip.organisation_id",
  -- ...
  "trip.organization"."id" AS "trip.organization.id",
  "trip.organization"."name" AS "trip.organization.name"
  -- ...
FROM
(
  SELECT
    "public.flight"."id",
    "public.flight"."trip_id" AS "tripId",
    "public.flight"."departure_time" AS "departureTime",
    "public.flight"."arrival_time" AS "arrivalTime",
    "public.flight"."origin",
    "public.flight"."destination",
    -- ...
    "public.flight"."trip_id"
  FROM "public"."flight"

  AS "public.flight"

  WHERE "public.flight"."cancelled" = false

  ORDER BY "departureTime" DESC

  LIMIT 20

  OFFSET 0
)
AS "public.flight" 

LEFT OUTER JOIN "public"."destination" AS "from" ON "public.flight"."origin" = "from"."id" 
LEFT OUTER JOIN "public"."destination" AS "to" ON "public.flight"."destination" = "to"."id" 
LEFT OUTER JOIN "public"."flight_reservation" AS "reservations" ON "public.flight"."id" = "reservations"."flight_id" 
LEFT OUTER JOIN "public"."passenger" AS "reservations.passenger" ON "reservations"."passenger_id" = "reservations.passenger"."id" 
LEFT OUTER JOIN "public"."invitation" AS "reservations.invitation" ON "reservations"."id" = "reservations.invitation"."flight_reservation_id" AND "reservations.invitation"."pending" = true 
LEFT OUTER JOIN "public"."reservation_status" AS "reservations.status" ON "reservations"."reservation_status_id" = "reservations.status"."id" 
LEFT OUTER JOIN "public"."modify_flight" AS "modifications" ON "public.flight"."id" = "modifications"."flight_id" AND "modifications"."approved" = false 
LEFT OUTER JOIN "public"."trip" AS "trip" ON "public.flight"."trip_id" = "trip"."id" 
LEFT OUTER JOIN "public"."organisation" AS "trip.organization" ON "trip"."organisation_id" = "trip.organization"."id"

ORDER BY "departureTime" DESC;


```

**Comment by joewood** [comment]
I hit this problem recently. As described on SO [here](http://stackoverflow.com/questions/26021965/sequelize-with-nodejs-cant-join-tables-with-limit).

I understand the design issue when one-to-many associations are used, the limit/offset is going to apply to the expanded resultset and not the root table. I ended up using **separate** queries for the associations. This may actually be a better solution, although the current implementation does separate queries for each row, this could be optimized and batched with one or more `in` clauses queries.

**Comment by manoellribeiro** [comment]
I ran into the same problem and the @lucaswxp answer helped me as well.

**Comment by egrojMonroy** [comment]
I tried @lucaswxp solution, but it seems to not work still. 
I am tring to sort by a nested property, but when I set the order by as @lucaswxp solution I get this error: 
 The multi-part identifier "code_project_type.project_type_name" could not be bound.
