### ISSUE TITLE
Insert Blob - ECONNRESET

### ISSUE THREAD

**Issue by thanlankon** [sequelize/sequelize#2069]
I use mysql for storing attachments for my website. I'm trying to insert an attachment data by using data type BLOB. It works fine with small file but when I insert a large file about over 2Mb, the Sequelize give me an error with code: ECONNRESET
I'm using Sequelize version 1.7.5, MySQL Server 5.6 with default configuration.

Is this problem of mysql configuration or the sequelize issue? I have no experience for deal with this. Please give me a help. Thanks you so much.

**Comment by zsoi** [comment]
Actually, you can send very large data to mysql in insert statements by using prepared statements! The mysql C API has a function called [mysql_stmt_send_long_data()](https://dev.mysql.com/doc/refman/5.0/en/mysql-stmt-send-long-data.html)

I have the same problem (the need for storing large binary data in a MySQL table) and I'll now try some workarounds to append data chunk-by-chunk to the existing data in the column, but native send_long_data support would be great!.

**Comment by aaltepet** [comment]
I also have this problem, except using postgres and the psql library.  Any suggestions on how to workaround this limitation?

**Comment by zsoi** [comment]
I worked around the problem by changing my data model to store large data in smaller chunks instead of in a large blob column (so for 10MB blob data I create 10 rows with 1MB chunks). That served me well in other aspects as well because I could easier stream data from the database instead of pulling the whole blob from the database at once.

Other approaches I did not test: Using CONCAT etc. to append more data to a column (don't know if CONCAT works well with BLOBs...)
