### ISSUE TITLE
Lodash global template settings

### ISSUE THREAD

**Issue by dizlexik** [sequelize/sequelize#2281]
I got burned a few days ago while trying to do a `sync()` on my database and getting the error `SyntaxError: Unexpected token =` originating within lodash's `.template` function. It turns out and some other module in my project is altering lodash's global `templateSettings.interpolate` value and since Sequelize is utilizing the global lodash object it was wasn't able to parse templates with the default interpolate regex. I know this is the other library's fault at the end of the day but wouldn't it make sense within Sequelize to either pass default options to each call of `.template(text, data, [options])` or perhaps instantiate a separate lodash object to `Util._` instead of using the global singleton?

**Comment by BridgeAR** [comment]
@janmeier @mickhansen This has nothing to do with sequelize and it would be best to fix the issue in the library that alters the the function. So I would close this issue.
@dizlexik Would be so kind and open an issue in the problematic library? Because this is bad for all librarys that depend on the lodash function.
