### ISSUE TITLE
Problem with postgres (2.0.0-dev13)

### ISSUE THREAD

**Issue by pola88** [sequelize/sequelize#2285]
Hi Guys,

I have a problem with the version 2.0.0-dev13. When I execute the tests and it finishes, Jasmine is still waiting that the connection is closed. Do you have this problem? I didn't have this problem with dev11.
I am using jasmine-node for testing.

Something else, I'm still seeing 'undefined' for default connection id.

Thank in advance,

**Comment by gianu** [comment]
@pola88  @janmeier @mickhansen  I added sequelize.close() (you can check the new code here: https://github.com/gianu/testing-sequelize/blob/master/spec/pgAdmin.js) and the test is still taking 10 seconds to finish (apparently because the connection is not closed).

You can see a video with the run here: http://cl.ly/ZBZG

The only way I found to reduce the time is adding a small idle time to the pool option (but I think this is not the correct solution).

Do you have any other suggestion?

Thanks!

**Comment by mickhansen** [comment]
@gianu will try running it later.
A workaround with always be `process.exit()`

**Comment by gianu** [comment]
@pola88 @mickhansen @janmeier I test with RC6 and the issue was fixed. In fact the issue was fixed on rc4. The problem I was seeing was related to the pool waiting the idle time to close the connections (10s by default).

The solution to my particular problem was fixed with this line:

https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L51

Thanks for your support, and thanks for doing such a great library!

**Comment by janmeier** [comment]
Thanks for the update @gianu. I'll go ahead and close this issue then. 

Please reopen or comment if the latest rc does not fix the issue for you pola

**Comment by pola88** [comment]
Great! It works for me too!:)
Thanks @gianu @janmeier @mickhansen !! :smile:
