### ISSUE TITLE
Rename/refactor hasMany x 2 to belongsToMany

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#2366]
Keep BC support but switch docs and primary reference to belongsToMany for N:M with join table associations.

**Comment by cusspvz** [comment]
@mickhansen I've updated `sequelize` and this deprecated noticed appeared, so...

I was thinking, since i use `sequelize`, to open a discussion about the change from two `hasMany` to a specific name, and since you've already changed the method name, i would suggest a new change to `hasAndBelongsToMany`.

It makes more sense and [CakePHP](http://book.cakephp.org/2.0/en/models/associations-linking-models-together.html#hasandbelongstomany-habtm) uses it also.

ping @janmeier @mickhansen @durango @sdepold

**Comment by sdepold** [comment]
+1 on that.

**Comment by sdepold** [comment]
Active record uses that name as well afaik

**Comment by mickhansen** [comment]
And a lot of other ORMs use `belongsToMany`.
We can alias it, `hasAndBelongsToMany` is just a bit too unwieldy for my tastes.

**Comment by sdepold** [comment]
Alias is fine for me :)

**Comment by cusspvz** [comment]
Alias is fine for me too
