### ISSUE TITLE
Hook callback not a function

### ISSUE THREAD

**Issue by nova706** [sequelize/sequelize#2411]
I just upgraded to 2.0.0 rc1 (mysql) from 1.7.10 and my hooks no longer function properly:

In the following example (http://sequelizejs.com/docs/latest/hooks#declaring-hooks):

```
User.beforeCreate(function(user, fn) {
  if (user.accessLevel > 10 && user.username !== "Boss") {
    return fn("You can't grant this user an access level above 10!")
  }
  return fn()
})
```

"fn" is an object not a function.

I just downgraded to make sure I wasn't crazy so I don't have what fn exactly is but I believe it was similar to:

```
fn: {
  fields: [
    // Array of field names from my model
  ],
  hooks: true,
  returning: null // I don't quite remember if this was null or not
}
```

Obviously, calling fn() throws a type error that it is an object, not a function.

I read that you can use the hooks by returning promises but the create continues before my asynchronous code completes (I am fetching another record and need to use that record to set a property on my instance). If anyone has an example of a hook that works in 2.0.0 rc1 using either a callback or promise with something asynchronous in it, it would be much appreciated.

**Comment by nickvlku** [comment]
Hey guys,

Just found this myself after spending an hour debugging this issue.  I completely understand not updating the documentation until the 2.0 release is out, but your web site tells users to download the 2.0rc (which is what you get by default anyway with npm) and then links to outdated 1.7 documentation with no mention the documentation is for an older version.  

I'd suggest a big disclaimer on the readthedocs page (especially since it claims to the "latest" and not "stable")...  I'm sure other people are being bit by this too.  

Thanks for the hard work!  This library is great!
Nick

**Comment by mickhansen** [comment]
@nickvlku we are working on the docs but have limited time available, PR welcome :) However RTD is for 2.0, as fast as we are updating them.

**Comment by mickhansen** [comment]
I just looked at the docs and they are indeed way out of date for hooks, i'm updating them as we speak.

**Comment by MeisterJustice** [comment]
Thank you soo much man. I encountered a lil problem with User.hooks but it's all good now

change
 User.hook("beforeCreate", function(user) {
    user.password = bcrypt.hashSync(user.password, bcrypt.genSaltSync(10), null);
   });

to

User.beforeCreate(function (user, options) {
    user.password = bcrypt.hashSync(user.password, bcrypt.genSaltSync(10), null);
  });
