### ISSUE TITLE
Join and sum

### ISSUE THREAD

**Issue by tom95** [sequelize/sequelize#2427]
I was not able to find a way to run a sum on an include. The special use case here would be a posts table with a separate votings table from which I need only the sum of upvotes/downvotes. If that's already possible without running raw queries, it would probably be worth adding to the wiki.

**Comment by dongseok0** [comment]
Hmm same question like this.
It seems include is not supported by sum method?

```
Model.sum('point', {
			where: {
				verified: false
			},
			include: [{
				model: Model2,
				where: {
					id: this.params.id
				}
			}]
		});
```

**Comment by janmeier** [comment]
@dongseok0 Can you provide some more context? What do your models and associations look like, and which column do you want to sum on?

**Comment by dongseok0** [comment]
Association:
```
Model.belongTo(Model2);
Model2.hasMany(Model);
```

And I want the 'point' column from Model. Currently I'm doing below:
```
Model.findOne({
            attributes: [
	       [sequelize.fn('SUM', sequelize.col('point')), 'points']
	    ],
            where: {
                verified: false
            },
            include: [{
                model: Model2,
                where: {
                    id: this.params.id
                }
            }]
        });
```

**Comment by pimterry** [comment]
Am I missing something @dongseok0? The example you give doesn't work for me, I get "'Column \'Model.id\' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause".

As soon as I add an 'include' array, Sequelize automatically Model.id to the SELECT (as noted in #3920, because it's the primary key) and this breaks the aggregation. See https://github.com/sequelize/sequelize/blob/2c4a9f3cf9887fb33c31e397e758dd4aa3374d01/lib/model.js#L1176. Are you sure this works? Any idea what you're doing that I'm not?

**Comment by dongseok0** [comment]
@pimterry - Yeah, above example is currently working on our production. 
Do you have any problems if you just find instead of using fn?
