### ISSUE TITLE
Profiling and benchmarking

### ISSUE THREAD

**Issue by vodolaz095** [sequelize/sequelize#2494]
Is there any way to profile this module?
I have learned that there is a way to output the queries send to database by using
`options.logging = function(query){ ....}`
http://sequelizejs.com/docs/1.7.8/usage#block-4-line-14

Is there any way to add timestamps to this function, so we know when query was send, when it was processed by database, does it have errors or valid response and so on?

**Comment by sushantdhiman** [comment]
@vodolaz095  #5116 provide an option to benchmark the queries via logs. May be it can help

**Comment by sushantdhiman** [comment]
Should we close it as #5116 is now merged and there is a way to benchmark. @janmeier @mickhansen

**Comment by janmeier** [comment]
@sunshinewyin At least were mostly there :)

I think for your PR to be useful for profiling, it would be nice if the logging function was passed the sql and the timing as two separate arguments, instead of having to extract the running time from a string.

In that case the `sequelize.log` function should create the `Executing...` string from its arguments

**Comment by sushantdhiman** [comment]
Yes thats a good idea. I will work on it if I get some time.

**Comment by janmeier** [comment]
Fixed in https://github.com/sequelize/sequelize/pull/5282
