### ISSUE TITLE
findOrCreate returns array 

### ISSUE THREAD

**Issue by icodeforlove** [sequelize/sequelize#2498]
in 1.7 `findOrCreate` returned an object, and now in 2.0 it returns an array, is this expected behavior?

**Comment by RobertDaleSmith** [comment]
I know we are on v5 now but for anyone that finds this and still not sure. The answer to this question for myself was done this way:
```
const [ user, created ] = await User.findOrCreate({
  where: { email, verified: false },
});
```

**Comment by ignaciohermosillacornejo** [comment]
Thank you @RobertDaleSmith, that helped me

**Comment by KGrzeg** [comment]
I was confused because the fact, that `findOrCreate` return array. API reference don't show exacly what is in the returned array. Always 2 elements, or N elements + `created` boolean? `created` is always second element, or the last one?
The docs don't describe scenario when more than one object are matched by query. What happen then? Does only first matched element be returned?

**Comment by RobertDaleSmith** [comment]
@KGrzeg in my experience on my current working project on latest Sequelize version, I always get the `created` boolean as the second element of the array and the `result` in the first.

**Comment by mickhansen** [comment]
https://sequelize.org/v5/class/lib/model.js~Model.html#static-method-findOrCreate

> The successful result of the promise will be (instance, created)

findOrCreate only supports one element, if multiple elements match the where statement it will only return one. findOrCreate is primarily safe when used with unique constraints and a transaction.
