### ISSUE TITLE
afterUpdate hook

### ISSUE THREAD

**Issue by rafacustodio** [sequelize/sequelize#2674]
I would like to report, I don't know if it is a bug, but the afterUpdate hook doesn't work the previousDataValues, for example, I would like to send an email when the status is changed, so I will compare the new status with the old one and if it's changed I will send that email, but I have the use the beforeUpdate hook, because the afterUpdate hook the previousDataValues is the same as the dataValues.

**Comment by tsheaff** [comment]
@mickhansen I know this question is (very) old, but I'm not seeing .changed() working from within my `afterUpdate` hook. `dataValues` and `_previousDataValues` are the same when the hook is called, despite having changes several values in the DB.  Is this functionality still supported? I'm on 3.9.0, would upgrading to 4.0 be recommended here?

Thanks!

**Comment by xitij** [comment]
+1 for this as well. I'm having the same issue using `v3.18.0`

**Comment by skn3** [comment]
+1 this as well have just faced this issue.

I have a beforeUpdate hook when checks to see of an attribute has changed. In the after update hook it then generates a new css file based on the state of the instance. During the process of generating the css file in the afterUpdate hook, it actually causes the instance to update again to stash the path to the css file. This then causes an infinite recursion because it goes through the beforeUpdate hook and cant detect the change we previously saved.

So you might say "why not create the css file before?". Well you cant rollback a css file upon error so was using the known validity of "afterUpdate" to indicate that the operation completed so therefore it is safe to generate a css file!

**Comment by skn3** [comment]
it looks like `instance.changed(key, false)` actually does this. Is there any reason this is built into a public function but has not been documented? Is this safe to use?

**Comment by skn3** [comment]
Just to add more details for future coders. I guess the trick (and quite rightly) is to just do the secondary update in my example, with `hooks: false`. It is probably going to be a fairly controlled/safe change, so a good enough solution!
