### ISSUE TITLE
option for ignore validation on fields with 'allowNull=true'

### ISSUE THREAD

**Issue by m9dfukc** [sequelize/sequelize#270]
Would be nice to have an option to ignore the validation settings if the field value is null with the allowNull parameter set. 

Another way would be come up with custom validation methods (for example 'allowNullOrIsEmail') but that would mean that we need access to the other validation functions (to reuse em).

**Comment by papb** [comment]
@tremby and @janmeier Hello and sorry to bring this up after so many years, but I would like to point out that this should be an opt-out option instead of a forced behaviour.

@tremby said: "I don't think it should even be an option. If allowNull is true, clearly you want to allow null."

This is being a problem for me, because I want to allow null depending on other fields:

```js
myField: {
  validate: {
    custom(value) {
      if (value === null && !foobar(this.otherField1, this.otherField2)) {
        throw new Error("myField can't be null when otherField1 and otherField2 satisfy property X");
      }
    }
  }
}
```

But with the changes made in #601, if I do `allowNull: true`, it is always allowed. If I do `allowNull: false`, it is never allowed, and I can't escape this... (if I omit it, it defaults to true)

This should be an option (that comes enabled, of course), so I can disable it for `myField` in my case... It's very specific but maybe others will encounter the same problem.

What do you think?

Thanks a lot!

**Comment by tremby** [comment]
I hadn't considered a use case like that. But I am going to bow out of discussion -- I haven't used Sequelize in years.

**Comment by papb** [comment]
@tremby Thank you for responding! No problem.

I opened a new issue about this: #9143
