### ISSUE TITLE
findAndCountAll distinct with include but without include.where condition

### ISSUE THREAD

**Issue by PierrickP** [sequelize/sequelize#2713]
Something looks bad on [these lines](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L836-L838)

if i try this kind of query
```
Dishes.findAndCountAll({
  distinct: true,
  include: [{
    model: Tags
  }]
});
```

The count query will be ``SELECT count(DISTINCT(*)) AS `count` FROM `dishes` AS `dish` WHERE 1=1;``
with an **option.include** to *undefined* at https://github.com/sequelize/sequelize/blob/master/lib/model.js#L837

**Comment by PierrickP** [comment]
Ok i understood everything.
I have 2 case.

When i want to **findAndCountAll** without **include.where** condition, ``distinct`` are useless (and generate the bad query, maybe should be handle ?) 

Distinct are *mandatory* (for me) when you use **include.where**. because, without, **count** and **rows**.length arn't egal (see http://runnable.com/VK_-zN3jAYAH3UZq/bad-count-when-using-include-condition-for-node-js-and-sequelize not using distinct, count query count twice one dish beacause it has both tags!)

For my case, it's now all right. There are probably still an error when using `distinct` with `findAndCountAll` and without  **include.where**

**Comment by mickhansen** [comment]
@PierrickP So to boil it down, distinct is needed with includes (sometimes), but illegal syntax without includes (joins)? So perhaps we should turn off distinct when there's no include needed.

**Comment by mickhansen** [comment]
I would prefer that you open a PR with a failing unit test rather than a runnable, that would help us in a possible fix :)

**Comment by BridgeAR** [comment]
I just checked the documentation and sqlite3 seems to [allow](https://www.sqlite.org/lang_aggfunc.html) the current behavior.

**Comment by sushantdhiman** [comment]
Now Fixed

**SSCCE Test**

```js
/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();

var M = sequelize.define('M')
  , N = sequelize.define('N');

M.hasMany(N);

sequelize.sync({ force: true })
  .then(() => M.findAndCountAll({ distinct: true, include: [N] }))
  .then(console.log)
  .catch(console.error);
```

**Output**

```js
Using database:  sequelize-test-54
Executing (default): SELECT count(DISTINCT("M"."id")) AS "count" FROM "Ms" AS "M" LEFT OUTER JOIN "Ns" AS "Ns" ON "M"."id" = "Ns"."MId";
{ count: 0, rows: [] }
```

**Comment by aqdas95** [comment]
Hi, 

I understand that,

`sequelize.sync({ force: true })
  .then(() => M.findAndCountAll({ distinct: true, include: [N] }))
  .then(console.log)
  .catch(console.error);`

resolves to 

`Executing (default): SELECT count(DISTINCT("M"."id")) AS "count" FROM "Ms" AS "M" LEFT OUTER JOIN "Ns" AS "Ns" ON "M"."id" = "Ns"."MId";
{ count: 0, rows: [] }`


but shouldn't there be an option to do 

`sequelize.sync({ force: true })
  .then(() => M.findAndCountAll({ distinct: ['"M"."abc"', '"N"."xyz"'], include: [N] }))
  .then(console.log)
  .catch(console.error);`

which would resolve to 

`Executing (default): SELECT count(DISTINCT("M"."abc", "N"."xyzzy")) AS "count" FROM "Ms" AS "M" LEFT OUTER JOIN "Ns" AS "Ns" ON "M"."id" = "Ns"."MId";
{ count: 0, rows: [] }`

Please Guide me regarding this. I am in a scenario where I get the wrong count just because of this missing functionality.

**Comment by MarianyFerreira** [comment]
up

**Comment by PokatilovArt** [comment]
I've setted these 2 properties

`distinct: true,
 col: "MODEL_NAME.MODEL_PRIMARY_KEY"` 

and it's worked for me
