### ISSUE TITLE
An Adapter for the Cordova/PhoneGap Sqlite Plugin.

### ISSUE THREAD

**Issue by ronyrun** [sequelize/sequelize#2715]
Cordova / Phonegap is growing very fastly !!
There is a good plugin to manage a Sqlite Database on phone device : 
https://github.com/brodysoft/Cordova-SQLitePlugin

Today only the ORM persistenceJS is available but it seems to be abandoned since several years....
If someone could create easily this adapter it would be great and add a huge community to the Sequelize ORM :)

**Comment by mparpaillon** [comment]
Yup, that would be great :)

**Comment by dakshhmehta** [comment]
Do we have any progress by anyone?

**Comment by janmeier** [comment]
@dakshhmehta Unfortunately not.

**Comment by chauthai** [comment]
+1 for cordova plugin

**Comment by janmeier** [comment]
I looked briefly at the readme of cordova sqlite and I have no idea how we would integrate it - does it even run on node, and if so, how?

In order to integrate an adapter it would need to pass the full test suite, which means it needs to be able to run under node on travis

**Comment by glebtv** [comment]
Cordova / Phonegap does not run node, it is more like a mobile browser with custom addons.
So it would require also using something like browserify.

Currently https://github.com/jxcore/jxcore-cordova seems to be the best option to try to run sequelize on phonegap

**Comment by IvanAR** [comment]
Up for this.

**Comment by AndersonSlivinski** [comment]
+1

**Comment by davidbnk** [comment]
+1

**Comment by sushantdhiman** [comment]
Cordova / Phonegap is an browser based platform that use WebViews to create mobile application. It doesn't support running NodeJS. I don't think we could port Sequelize to work on Cordova.

If someone want to to try they are welcome to open a PR with possible implementation. But this will not be implemented by maintainers.

**Comment by mobidev111** [comment]
@sushantdhiman please re-open - so that requirements can be collected here

would love to see support for the browser platform.

* the author of the typeorm ORM did a similar abstraction towards making the ORM run in the browser (https://github.com/typeorm/typeorm/issues/61) - maybe this can give some cues on how to achieve a similar thing for sequelize. 

* [cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) provides a sqlite interface, so the work from the existing sqlite adapters should be re-usable
