### ISSUE TITLE
How to require a foreign key to be not null

### ISSUE THREAD

**Issue by vinkaga** [sequelize/sequelize#2837]
I want to require, for some entities, foreign keys to be not null. In this example for a Task entity, I would like userId to be not null and throw an error when a Task is created without userId. But it creates a Task without error.

How can I require a foreign key to be not null?
```JavaScript
var Sequelize = require('sequelize')
    , sequelize = new Sequelize('seqex', 'root', 'mysql', {logging: false});


var User = sequelize.define('user', { name: Sequelize.STRING })
    , Task = sequelize.define('task', { name: Sequelize.STRING })

Task.belongsTo(User)
User.hasMany(Task)

sequelize.sync({force: true})
    .then(function () {
        User.create({name: 'John Doe', id: 1})
            .then(function() {
                //Task.create({name: 'A Task', id: 1, userId: 1})
                Task.create({name: 'A Task', id: 1})
                    .then(function() {
                        Task.find({where: {id: 1}, include: [User]})
                            .then(function (tasks) {
                                console.log(JSON.stringify(tasks));
                            })
                            .catch(function(e) { console.log (e); });
                    })
                    .catch(function(e) { console.log (e); });
            })
            .catch(function(e) { console.log (e); });
    })
    .catch(function(e) { console.log (e); });

```

**Comment by janmeier** [comment]
In recent versions of 2.0 (+rc2 i believe), you can pass a column definition to `foreignKey`

```js
Task.belongsTo(User, { foreignKey: { allowNull: false }, onDelete: 'CASCADE' })
User.hasMany(Task, { foreignKey: { allowNull: false }, onDelete: 'CASCADE' })
``` 

Notice that you will also have to set onDelete, since the default is `SET NULL`, which for obvious reasons does not play well with `NOT NULL`. (there is an open issue for automatically setting onDelete to cascade when the foreign key does not allow nulls https://github.com/sequelize/sequelize/issues/2831)

**Comment by vinkaga** [comment]
Works like a charm! :-)

**Comment by theofabry** [comment]
I'm glad to find an answer here, but why isn't it in the docs ?

**Comment by janmeier** [comment]
@theofabry Because it's a secret that we only tell to users who are diligent enough to search for it! :)

Or maybe just because no-one has had the time to write about it yet. We're a small team with limited time, and plenty of open bugs. It's mentioned in the [api docs](http://docs.sequelizejs.com/en/latest/api/associations/), but a PR which mentions it in the regular docs would be very much appreciated

**Comment by theofabry** [comment]
@janmeier Haha I love your humour ;)

My intention was obviously not to push you, nor reproach that you didn't do it. I totally understand that you have a lot of things to do and I'm pretty impressed by your availability to answer me that quick.

I've never done a PR on a doc, but I'm going to see how I can do it and contribute, I think it's important.

Thanks again !

**Comment by janmeier** [comment]
Should be pretty easy to create the PR - since its only a single file, you can even do it directly on github I think https://github.com/sequelize/sequelize/tree/master/docs/docs

**Comment by angelxmoreno** [comment]
"Because it's a secret that we only tell to users who are diligent enough to search for it!" consider me one of the Elites!

**Comment by janmeier** [comment]
@angelxmoreno welcome to the club ;)

**Comment by tratnayake** [comment]
Super happy to find this, though I have a question. 
Before I was able to specify `foreignKey: <fk_name>` but now if it is `foreignKey: {allowNull: false}` , what is the proper way to specify the foreignKey name?

**Comment by tratnayake** [comment]
Disregard, just figured it out, you can do:
`foreignKey: {name: fk_name_here, allowNull:false} ` :smile:

**Comment by mjangir** [comment]
How to set both foreign key constraint name (fk_company_id) and field name (company_id) in the above object???

**Comment by DaAwesomeP** [comment]
In this case, how does the cascade delete work?
```js
User.hasMany(Task, {
  foreignKey: {
    name: 'user',
    allowNull: false
  },
  onDelete: 'CASCADE'
})
```
If I delete a User, will it delete the user's tasks, or if I delete a task will it delete a user, or both? I would only want deleting a User to delete a task in this case.

**Comment by igordeoliveirasa** [comment]
Mine is not working if I set "as" property, like: 
...
{
            as: "profileCategory",
            foreignKey: {allowNull: false}
}

**Comment by FranckFreiburger** [comment]
@igordeoliveirasa, I encounter the same issue, did you find a solution ?

**Comment by Skaronator** [comment]
@FranckFreiburger  Noticed the same issue

**Comment by NoxPhoenix** [comment]
This is still an issue if you include the `as` property... Cannot constrain foriegn keys to not be null is very frustrating...

**Comment by nomadoda** [comment]
@igordeoliveirasa Would it not be essentially the same to specify the field of the foreignKey?

```
Profile.hasMany(Category, {
  foreignKey: {
    name: 'profileCategory',
    field: 'category_id',
    allowNull: false,
  },
  onDelete: 'CASCADE'
})
```

**Comment by normancarcamo** [comment]
Hi, as far I can see currently In the [docs](http://docs.sequelizejs.com/class/lib/associations/base.js~Association.html) there're only 2 constraints for integrity referential: 

- CASCADE
- SET NULL

But I want to know if I can use: "NO ACTION" due to my requirements says that a record in deletion cannot deletes references, also they must stay but not change it as NULL value.

May I use "NO ACTION"? afterall it's just a string but I don't know...

I think that the docs could mention it.

Thanks.

**Comment by igordeoliveirasa** [comment]
> @igordeoliveirasa, I encounter the same issue, did you find a solution ?

Not yet. What about you?

**Comment by igordeoliveirasa** [comment]
I noticed if I cut "foreignKey = {allowNull: false}" of belongsTo and past in hasMany works. However it does not work for each one. It's weird.

**Comment by igordeoliveirasa** [comment]
Well, it works when I repeat {foreignKey: {allowNull: false}} in hasMany and belongsTo. But I don't believe its beautiful.
