### ISSUE TITLE
Outer (Overall) Limit - useful with findAll + include + attributes.

### ISSUE THREAD

**Issue by prasad83** [sequelize/sequelize#2843]
I needed limit findAll to work with include (attributes) and required true. But ended with a faulty query due to sub-query. Got around this by adding (outer limit) support.

_Usage_

``` javascript
var options = {
      where: { },
      include: [{model: MyModel, required: true, attributes: ['name']}]
      olimit: 100, // <-- Outer Limit
      ooffset: 10, // <-- Outer Offset
}
```

_File: sequelize/lib/dialects/abstract/query-generator.js_

``` javascript
selectQuery: function(tableName, options, factory) {
    // ...
    var limitOrder = this.addLimitAndOffset(options, query)
    // Add LIMIT, OFFSET to sub or main query
    if (limitOrder) {
        // ...
    }

    // Add OUTER LIMIT, OFFSET if specified to mainQuery
    if (options.olimit && !options.limit) {
        var olimitOrder = this.addLimitAndOffset({offset: options.ooffset, limit: options.olimit}, query);
        mainQueryItems.push(olimitOrder)
    }
```

**Comment by mickhansen** [comment]
Limit works in a lot of cases, where didn't it work?
I hope you realize that a outer limit is useless when you have a join that results in row duplication - So assuming that there are more than 1 MyModel per main model (which there likely is since you defined it as hasMany) you will get less than a 100 main model elements when the query is done executing.

**Comment by mickhansen** [comment]
It's also possible to pass `subquery: false` to the call in case you don't care about the row duplication issue.
