### ISSUE TITLE
QueryChainer (sequelize 2.0.0 rc7)

### ISSUE THREAD

**Issue by pola88** [sequelize/sequelize#2916]
Hi guys,

I have a question, In the previous version I was using ```QueryChainer``` and I updated to the new version.
When I run my code, I get the following warnings:
```
EventEmitter#success|ok is deprecated, please use promise-style instead.
EventEmitter#failure|fail|error is deprecated, please use promise-style instead.
```

The Code is:

```
var queryChainer = new QueryChainer();
queryChainer.add(user.save());
queryChainer.run().then(function() { ... });
````

I looked at the code, and I saw that the chainer is going to be deprecated,
if I can't use it, What Should I use instead?
or if I can, why I get those warnings?
Anyway, I am not getting the warning to stop using this.

Thanks in adnvance.

**Comment by mickhansen** [comment]
You should use a promise library instead of the query chainer.

**Comment by pola88** [comment]
Oh! ok, I got it! :+1: 

Thanks @mickhansen

**Comment by Domiii** [comment]
I had the exact issue because I thought that Chainer actually does something different from promises (i.e. sending all transactions in a single batch, instead of sending them one by one etc.).

The chainer deprecation and its replacement with promises should be reflected in the [Sequelize 2.0 migration document](https://github.com/sequelize/sequelize/wiki/Upgrading-to-2.0); probably as a sub-section under "Promises replaces EventEmitter" with example?
