### ISSUE TITLE
How to realize foreign Key to non-primary key

### ISSUE THREAD

**Issue by Pana** [sequelize/sequelize#2967]
Two table has a 1:n relationship, let's say 
ModelA has a model_b_id column
ModelB has id, another_id, id is the primaryKey column,  another_id is a unique column
I need to setup the relationship ModelA.belongsTo(ModelB, {foreignKey: 'model_b_id'}), but didn't find a option to specify the reference column in ModelB.

I also find this in sequelize doc

model_b_id: {
   type: Sequelize.INTEGER,
   references: ModelB,
   referencesKey: 'another_id'
}

but this is not work for me, it will use ModeB's primary column to join the table.

**Comment by mickhansen** [comment]
Sequelize only supports primary keys as reference keys at the moment.

**Comment by shawninder** [comment]
Any progress on this? Does Sequelize still not support primary keys as reference keys?

I have a Sequelize model with 3 fields:
- created_at
- A
- B

A and B are both foreign keys pointing to unique but non-primary-key fields in other tables. When I insert data into this table however, I end up with 5 columns instead of 3. The 2 new columns are `user_uid` and `door_uid`, which look like the primary keys of the tables referenced by A and B (`uid` field of table `users` and `uid` field of table `doors`). This is fine, except that instead of inserting these primary key values, I just get `null` in those fields.

- Am I getting this unexpected behavior because of this here issue?
- Am I wrong in my analysis of the situation or in my expectations?
- Is there something else I can do to either not have those columns "appear" or at least get the correct information in them?

**Comment by kimobrian** [comment]
https://medium.com/@sherryhsu/sequelize-associations-and-foreign-keys-c2d70f7134e9
