### ISSUE TITLE
BelongsToMany and BelongsTo - eager loading not working

### ISSUE THREAD

**Issue by JuSKT** [sequelize/sequelize#3036]
Hello,

I am currently using this very good ORM (latest version - v2.0.0-rc8) and I am happy with it but it seems that I have a problem that I can't resolve.

I am trying to find a way to load the nested associations using a join table with a BelongsToMany and a BelongsTo.

My "through" model (Invitation)
```javascript
models.User.belongsToMany(models.Item, { through: { model:Invitation, unique:true }, foreignKey: 'userId', otherKey: 'itemId', as: {singular: 'invitationItem', plural: 'invitationItems'} });
models.Item.belongsToMany(models.User, { through: { model:Invitation, unique:true }, foreignKey: 'itemId', otherKey: 'userId', as: {singular: 'invitationUser', plural: 'invitationUsers'} });

Invitation.belongsTo(models.User, { as: 'userSender', onDelete: 'CASCADE', foreignKey: { name:'userSenderId', allowNull: false }});
```

I am trying to find with my "through" model (not using the get with my models User or Item)
```javascript
models.Invitation.findAll({ where: {userId: auth_userId},
  include: [
    {model: models.User, as:'userSender'}
    {model: models.Item, as:'invitationItem'},
    {model: models.User, as:'invitationUser'}
  ]
})
```
This is not working but when I delete the two last include, the query is working. I have already tried the other way with the getContributionItems but it seems that in this case, I can't load the nested userSender association.

Why I can't fetch the invitationItem and invitationUser in a BelongsToMany associations?

Is there a workaround to manage this (by fetching the model directly or using the getter) ?

**Comment by mickhansen** [comment]
Try `as: 'invitationItems'` instead of the singular version.

**Comment by JuSKT** [comment]
Thanks for your answer but its not working.

In my query, I am trying to fetch with my "through" model. Regarding the doc, I have invitationItems in my User model and invitationUsers in my Item Model (because of my two BelongsToMany) but nothing in my "through" model. Does this means that I can't load eagerly using my "through" model?

**Comment by janmeier** [comment]
Through models do not set up associations - other associations work through them.

If you want to explictily load the data from the through model you should setup `Invitation.belongsTo(Item)` etc.

**Comment by JuSKT** [comment]
It seems to be working now.

Thank you for your great help !

**Comment by hfar** [comment]
Hello ,

I am new on this .. i couldn't understand how this get solved.

I am using  "belongsToMany" and when using include i can see duplicate results coming for Roles,Roles {results} and UserRole  {results} 

for more information:
User.belongsToMany(models.Role, {through: models.UserRole,foreignKey: 'userId'});
Role.belongsToMany(models.User, {through: models.UserRole,foreignKey: 'roleId'});

and i didn't add any association to "UserRole" because belongsToMany already adds primary/foreign keys to junction table "UserRole" ..

db.User.find({where: {userId: id},include: [
			{model: db.Role}
		]}).then(function(user){
            console.log('Session: { id: ' + user.userId + ', email: ' + user.email + ' }');

			done(null, user);

        }).catch(function(err){
            done(err, null);
        });

Thanks,
Hussein

**Comment by janmeier** [comment]
@hfar We'll need more debugging info than that. Try to create a small, isolated test case that shows the problem and open  new issue

**Comment by diosney** [comment]
@janmeier Can you post an example of a three level nested eager loaded include with a belongsToMany relationship?

I tried to set up the `belongsTo` and/or `hasMany` on the models I need to include and it trigger an error stating that it doesn't find the related `ModelId`.

**Comment by diosney** [comment]
After testing a lot of variants, found how to do it. In my case was:

```js
models
    .Reservation
    .findOne({
      where  : {
        CreatorId: req.user.id
      },
      include: [
        {
          model  : models.LodgingBedroomReservationItem,
          include: [
            {
              model  : models.LodgingBedroomPriceContract,
              through: 'LodgingBedroomReservationItemPriceContractMembership',
              as     : 'LodgingBedroomPriceContracts'
            }
          ]
        }
      ]
    })
```

There the `belongsToMany` relationship is  'LodgingBedroomReservationItemPriceContractMembership'.

The key points were:

- for nested eager loading, just nest the `includes` mimicking the relationship.
- the `model` attribute **must be** a real sequelize model, not the resulting membership (belongsToMany relationship).
- `through` and `as` has to be passed alongside in order to work properly.

@janmeier Can this be added to docs?

**Comment by janmeier** [comment]
> for nested eager loading, just nest the includes mimicking the relationship.

Yep

> the model attribute must be a real sequelize model, not the resulting membership (belongsToMany relationship).

You can use `association: ` instead of `model:` to pass the association - which is often easier

> through and as has to be passed alongside in order to work properly.

through does not - `through` is actually used for stuff like `attributes` and `where`, so you can select only some attributes or make extra where conditions based on the join table.

`as` is required yes, unless you pass `association`, in which case we can infer it :)

> @janmeier Can this be added to docs?

It definitely can, PRs welcome. I'm not saying this out of lazyness - partly out of lack and time, and partly because it can be hard to write documentation if you know a system "too well" - since everything is obvious to you ;). So documentation from regular users is definitely welcomed!

**Comment by lekhnath** [comment]
while using 
```
{
  include: [
    {
        association: 'assoc_name'
    }
  ]
}
```

I am getting TypeError: Cannot read property 'name' of undefined error.
But it works fine when used both model and as options.

```
{
  include: [
    {
        model: ModelClass,
        as: 'assoc_name'
    }
  ]
}
```

**Comment by chornbe** [comment]
Anyone ever heard of backward compatibility????
