### ISSUE TITLE
Avoid single quote in place holder raw query

### ISSUE THREAD

**Issue by ramprakash-ravi** [sequelize/sequelize#3124]
The issue is that the replacement string includes single quotes for both the :file replacement (which is good because it's a path) and the :table replacement (which is bad because it's just supposed to be an unadorned table name, and breaks the query). How do I avoid those quotes in the case of the table name replacement?

```js
var sequelize = require('sequelize');
sequelize
   .query("LOAD DATA LOCAL INFILE :file
           INTO TABLE :table
           FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\n';",
          null,
          {raw:true},
          {file: datasetPath, table: "dataset_" + datasetName})
```

**Comment by juvasquezg** [comment]
Hi,

I have the same problem but i get "passing raw query replacements as the 4th argument to sequelize.query is deprecated. Please use options.replacements instead".

Thak you.

**Comment by mickhansen** [comment]
@juvasquezg on newer versions we have deprecated 4th param replacements, they still work but for future proofing you should do something like:

```js
sequelize.query(sql, null, {raw: true, replacements: []});
```

**Comment by janmeier** [comment]
When using un-named replacement you can do `??` to escape the string like an identifier. Any suggestions for a similar syntax for named replacements? `::` Probably won't work, since that syntax is already used by PG.

Perhaps we should also consider using https://github.com/node-modules/sqlstring an providing a PR / wrapping the module to provide our small snippets of dialect specific functionality

**Comment by juvasquezg** [comment]
Hi,

The query  still work but the result is diferent, I had to change the FrontEnd.

Now the is an Array, the second position is:

```bash
Object
RowCtor: function anonymous(parsers,rowData) {
_getTypeParser: function () { [native code] }
_parsers: Array[5]
command: "SELECT"
fields: Array[5]
oid: NaN
rowAsArray: false
rowCount: 3
rows: Array[0]
__proto__: Object
```
```bash
"pg": "^4.1.0",
"pg-hstore": "^2.3.1",
"sequelize": "^2.0.0-rc3",
```

Thank you

**Comment by janmeier** [comment]
@juvasquezg https://github.com/sequelize/sequelize/wiki/Upgrading-to-2.0#changes-to-raw-query

**Comment by juvasquezg** [comment]
Than you so much. Perfect.

**Comment by janmeier** [comment]
@ramprakash-ravi Any suggestions for a named parameter syntax that shows the param should not be escaped? As mentioned `::` won't work, since it already has a different meaning in PG. 

If you don't need named params, `??` should work

**Comment by janmeier** [comment]
`??` Can be used as a replacement for un-escaped params. Please comment / reopen if you have suggestions for a syntax for named params @ramprakash-ravi

**Comment by imVinayPandya** [comment]
I am getting this same error because of single quote (') 

Executing (default): SELECT * FROM "User_Assets" WHERE user_id = '132' ORDER BY 'created_at' ASC LIMIT '2' OFFSET '0'

{ SequelizeDatabaseError: non-integer constant in ORDER BY

As per doc, it is not working because i am using replacement. but if i use Bind parameter it is working fine. Ref: http://docs.sequelizejs.com/manual/tutorial/raw-queries.html

(i am using this, not working) replacement: `SELECT * FROM "User_Assets" WHERE user_id = :userId ORDER BY :orderBy ASC LIMIT :limit OFFSET :offset`

(this is working): `SELECT * FROM "User_Assets" WHERE user_id = $userId ORDER BY $orderBy ASC LIMIT $limit OFFSET $offset`

**Comment by awhitehouse104** [comment]
@janmeier Do you have any examples using `??` for this case? Seems to be treating it as two separate `?` to replace, and I don't see anything in the documentation.

**Comment by EduardsE** [comment]
> `??` Can be used as a replacement for un-escaped params. Please comment / reopen if you have suggestions for a syntax for named params @ramprakash-ravi

@janmeier  This does not seem to work at all

**Comment by papb** [comment]
Hello, this issue is old and our issue templates have changed since then; investigating this issue as-is would need extra effort from maintainers (and our time is really short). Can someone please open a new issue about this, filling our modern templates, to save time from the maintainers? Especially including a nice SSCCE, preferably from our [sequelize-sscce repository](https://github.com/papb/sequelize-sscce). For those hoping for a fix, doing this would greatly help and in theory is something anyone encountering this issue should be able to do. Thanks for understanding! Don't forget to link to this issue in the new issue.
