### ISSUE TITLE
[Question]: Just how deprecated are '2x hasMany' relationships?

### ISSUE THREAD

**Issue by bitwit** [sequelize/sequelize#3225]
First: Thanks for the continued hard work on Sequelize and congrats on the recent release of 2.0!

Second: Can you please elaborate on the current deprecated state of '2x hasMany' relationships as of version 2.0.3? We just updated from version 2.0-rc2 and while nothing is breaking our unit tests and behaviour appears normal, we just want to understand whether sequelize is politely warning us about our relationships for posterity or whether action has already been taken in the ORM not to honour these types on some fundamental level.

Furthermore, how does this change affect issues #1997 and #2459 ? Is this still considered a bug that will be fixed, or does belongsToMany solve this problem? We ended up using a 2x hasMany style relationship to solve the problem described in these issues.

Thank you

**Comment by mickhansen** [comment]
It's deprecated as in eventually we will completely remove the functionality. But we won't do that for atleast a few minor (2.x.0) versions.

For the near future it means that it won't receive any features or bug fixes, which belongsToMany will.
The two issues you are referring to will be fixed for belongsToMany, when we get to them, and will most likely not be backported to 2 x hasMany.

**Comment by dag10** [comment]
What would be the correct way to associate the following models:

There's four models: User, Room, Song, and SongStatistic. The SongStatistic model contains these fields:
- user
- room
- song
- event (enum)

Many SongStatistic models can exist, describing an event (enum) that occurred on a song, by a user, in a room, at a time (has a timestamp too).

In 2.x-rc, I was using SongStatistic.belongsTo(User), SongStatistic.belongsTo(Room), and SongStatistic.belongsTo(Song). However, the docs say that belongsTo must be used only for 1:1 relationships, whereas this is a 1:MMM.

I can't use Song.belongsToMany(User, {through: SongStatistic}), since that leaves out the Room association. Does this make sense?

In the doc for 2.0.3, I can't find any association that's appropriate for this schema.

**Comment by mickhansen** [comment]
belongsTo can be used in 1:M aswell, if the docs state only 1:1 there must be an error :)
belongsToMany won't work with multiple associations as  you've deduced, i would keep doing what you're doing (doing the through association by hand with multiple hasMany/belongsTo).
