### ISSUE TITLE
Is there support for windows azure sql database?

### ISSUE THREAD

**Issue by baladin** [sequelize/sequelize#3240]
I try the following and never get a callback

var Sequelize = require('sequelize');
var sequelize = new Sequelize('dbname', 'username', 'passwd', {
  host: 'hostname',
  dialect: 'mssql',

  pool: {
    max: 5,
    min: 0,
    idle: 10000
  },
});

sequelize.authenticate().complete(function(err) {
      if (err) {
        console.log('Unable to connect to the database:', err);
      } else {
        console.log('Connection has been established successfully.');
      }
  })

**Comment by mickhansen** [comment]
@mbroadst

**Comment by mbroadst** [comment]
@baladin yes, the underlaying driver used for mssql supports azure so we do as well, although we do no explicitly test for support (and honestly I haven't even tested it locally myself). I do know that in order to connect to azure with raw tedious you need to pass this to the Connection factory: ```options: {encrypt: true}```. To do that in Sequelize, you need to specify that as a dialectOption when you initialize Sequelize:

```
var Sequelize = require('sequelize');
var sequelize = new Sequelize('dbname', 'username', 'passwd', {
  host: 'hostname',
  dialect: 'mssql',
  pool: {
    max: 5,
    min: 0,
    idle: 10000
  },
  dialectOptions: {
    encrypt: true
  }
});
```

**Comment by mbroadst** [comment]
@baladin did this answer your question?

**Comment by artem-tkachuk** [comment]
https://github.com/sequelize/sequelize/issues/9574#issuecomment-477470348 helped me!

**Comment by juank2808** [comment]
Hi all

Can you help me?

I need to run the migrations to create the tables in my database, currently my database is on a MySQL azure server, how do I run the migrations from my local host?

regards.
