### ISSUE TITLE
2.1 milestone/goals/issues

### ISSUE THREAD

**Issue by ilanbiala** [sequelize/sequelize#3296]
What are the issues that are going to be taken care of for 2.1? Is there a milestone for it?

**Comment by mickhansen** [comment]
General roadmap: https://github.com/sequelize/sequelize/issues/2869
No specific version milestones. 2.1 will be released when we have one or two new features ready for it and when we're ready to completely remove the events codebase.

**Comment by ilanbiala** [comment]
Ok, also improving the docs would be great. It's really hard to understand what to do when there seem to be so many possible implementations that differ. Also very little public blogs/tutorials for Sequelize, so it means that the project docs have to be a lot better.

**Comment by mickhansen** [comment]
Docs are an ongoing process, we are aware they need attention :) And we give it as we can. But the Sequelize team is pretty much no more than two people who only have so much spare time :)

Pull requests and suggestions for documentation always appreicated.

**Comment by ilanbiala** [comment]
The biggest source of confusion is that there is no example code for most things and pros cons for certain ways of using Sequelize, e.g. build+save vs create, or attaching associations in the schema vs `.belongsTo` or another method.

**Comment by mdarveau** [comment]
Sorry to jump in this thread but I am learning Sequelize and there are definitelly some areas in the documentation that could be improved. It is a GREAT documentation but it lacks the best practices and some examples. I was about to add blog entries about what I discovered along the way and what I assume are the best practices.

Instead of this, I am willing to submit pull requests on the documentation. However, I would like to confirm that what I write is indeed a good practice. What is the best channel to do that? Should I simply send PR and wait for feedback, or open issues on this project asking for confirmation on content?

**Comment by mickhansen** [comment]
@mdarveau Small individual PR's would be great for discussion, otherwise perhaps IRC or the google group.

**Comment by pilsy** [comment]
@mickhansen @mdarveau, 

It would be awesome to do this collaboration in the Google Group, i think discussing this (and others like it) in the google group will help another area of your documentation, helping users figure out (by example) where they can find answers, or immediately know where they should go to ask a new question that is an edge case or misunderstood area of the api that they feel is not covered in the docs/guides.

This is an area i'm addressing in CleverStack at the moment with Dan Cancro, and if the two of you don't mind me helping with this, then i'm quite happy to help :+1: 

Additionally @mickhansen, JSONB as well, but specifically Polymorphic Associations, and include.seperate are things i feel that i can provide value in - in the last year or so, solutions/application's i have been developing for companies have required all of them - with viable solutions implemented for both polymorphic and include.seperate.

My clever-orm module already implemented include.seperate functionality, as well as lazy loading (somewhat like the proxies in doctrine 2) and a few more complex loading implementations.

**Comment by mickhansen** [comment]
@pilsy we could use all the help we can get.
The problem with using google groups have historically been that people don't do it, especially not new-ish developers.

**Comment by pilsy** [comment]
I agree, however new-ish developers don't typically like creating github issues, and irc has no history so you have to coach everyone each time. This is a problem area i have been focusing on, and i think together we can at least improve the status quo

**Comment by mickhansen** [comment]
The amount of questions we get on GitHub compared to Google Groups would suggest otherwise :)
I would love for people to posts questions on Google Groups rather than GitHub and keep GH for features and bugs, but to achieve that'd we'd probably have to close all questions on GitHub with an advisement to post on the google group and that the question will be ignored.

**Comment by mickhansen** [comment]
I'm open to any and all improvements though :)
