### ISSUE TITLE
Sequelize Upsert() return value

### ISSUE THREAD

**Issue by hfar** [sequelize/sequelize#3354]
Hello,

 I need to get the id for the inserted/updated record when using .upsert() in sequelize.

right now .upsert() returns a boolean indicating whether the row was created or updated.

thanks for your help.

```
return db.VenueAddress.upsert({
            ...
        }).then(function(test){
            //test returned here as true or false how can i get the inserted id here so i can insert data in other tables using this new id?
        });
```

**Comment by janmeier** [comment]
This is only supported by postgres, so to keep the API consistent across dialects this is not possible

**Comment by FredKSchott** [comment]
:+1: for adding this feature, there's plenty of precedence for dialect-specific features. This seems exactly like `[options.returning=false]` on [Model.update()](http://docs.sequelizejs.com/en/latest/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows)

**Comment by GabeIsman** [comment]
I also just ran into this problem. I wanted to upsert a list of records, and then do something with them (associate them with another model). That seems to be impossible the way the API is defined now. Is there a recommended workflow for this use case? I'm trying to avoid just recreating all associated records on update, which seems to be the path of least resistance given the API design (particularly that the records must already exist in the DB before they can be associated).

**Comment by hfar** [comment]
+1

**Comment by coderholic** [comment]
+1 for adding options.returning on upsert.

**Comment by rfink** [comment]
+1, would be tremendously useful

**Comment by FredKSchott** [comment]
So I did some digging into this, and it won't be easy. I wanted us to be able to take advantage of `RETURNING *` in postgres, but the problem is that the return value of insert & update are both already being used to detect which one occurred. ([link to code](https://github.com/sequelize/sequelize/blob/d3ac832c14b1fa8e0c0d17139848c8cee0103cae/lib/dialects/postgres/query-generator.js#L319))

At this point I think the best way forward is to append a simple `SELECT *` query to the end of the upsert transaction. We'll need to append the upsert response (1 or 2) in the result as well, which is where I got stuck (got `Cannot read property 'sequelize_upsert' of undefined` error when appending `; SELECT *, pg_temp.sequelize_upsert() FROM users WHERE ...`) 

I don't have any more time to work on this for a while, but if anyone wants to take over where I left off feel free!

**Comment by kylehotchkiss** [comment]
+1; this would be useful for me as well.

I thought there was an update() function with { upsert: true } as an option but it's totally possible i'm getting confused with Mongoose

**Comment by janmeier** [comment]
@kylehotchkiss We do have `ON DUPLICATE KEY UPDATE` support for bulkCreate  http://docs.sequelizejs.com/en/latest/api/model/#bulkcreaterecords-options-promisearrayinstance

**Comment by angelxmoreno** [comment]
I agree it would be nice to have this. Aren't we already implementing dialect specific solutions to do `upsert()` ? That is how I am interpreting the docs:
```
Implementation details:

MySQL - Implemented as a single query INSERT values ON DUPLICATE KEY UPDATE values
PostgreSQL - Implemented as a temporary function with exception handling: INSERT EXCEPTION WHEN unique_constraint UPDATE
SQLite - Implemented as two queries INSERT; UPDATE. This means that the update is executed regardless of whether the row already existed or not
```

At any rate, below is my workaround with a mild performance hit:

```js
classMethods: {
    upsertWithReturn: function (options) {
        return this.findOrCreate(options).spread(function (row, created) {
            if (created) {
                return [row, created];
            } else {
                return row.updateAttributes(options.defaults).then(function (updated) {
                    return [updated, created];
                });
            }
        });
    },
}
```

I foresee only having race condition issues. However, I am under the impression that `modelInstance.updateAttributes()` will not do anything in the situation where a second call would have already updated the row somewhere between the first insert and the first update.

Thoughts?

**Comment by mickhansen** [comment]
@angelxmoreno `updateAttributes` is only idempotent if the instance is currently the source of truth, that would be false in the case where a parallel code path updates the database entry.

Your code is open to race conditions - But our code isn't 100% perfectly race condition free since technically a parallel connection could change the entry while we run our two sequential queries (but less race prone since there's less roundtrips).

**Comment by angelxmoreno** [comment]
@mickhansen :+1:

**Comment by dyeje** [comment]
+1

Running into the same issue with needing to associate objects.

**Comment by nadavoosh** [comment]
+1

**Comment by spacelan** [comment]
+1

**Comment by taozhi8833998** [comment]
+1

**Comment by lorenmh** [comment]
+1

**Comment by rubbingalcoholic** [comment]
+1

**Comment by OlivierCuyp** [comment]
+1

**Comment by CameronK** [comment]
+1

**Comment by nechama** [comment]
+1

**Comment by giovannipessiva** [comment]
+1

**Comment by darmalovan** [comment]
+1

**Comment by jejrthompson** [comment]
+1

**Comment by KD4** [comment]
+1 plz. take my hand.

**Comment by AndyMathys** [comment]
+1

**Comment by felixfbecker** [comment]
Please don't +1 issues. It clutters the thread without adding value to the discussion and spams maintainers with notifications. Use GitHub reactions to upvote features.
![image](https://cloud.githubusercontent.com/assets/10532611/18344735/bb60c2f6-75b8-11e6-88a9-822fae298110.png)

**Comment by Shahor** [comment]
Oh haï there o/
It would be really nice to have some updates on this issue.

**Comment by Shahor** [comment]
What do you mean `this is only supported by Postgres` ?

<img width="369" alt="screen shot 2017-04-18 at 10 58 49" src="https://cloud.githubusercontent.com/assets/204561/25122669/0ba3017c-2426-11e7-98bb-ab557f1b7e18.png">

**Comment by janmeier** [comment]
@Shahor That only applies to the case where the row doesn't already exist though? We can't get the id of an existing row like we can with `RETURNING *` in postgres

**Comment by Shahor** [comment]
@janmeier You have a point on this.

That being said, an ORM should provide abstraction to the developer and make it easy to interact with a database. 
In that context, shouldn't sequelize perform the necessary queries in order to return the useful data to the developer instead of just returning the type of query that has been applied?

A workaround to this problem could be something [like this comment](https://github.com/sequelize/sequelize/issues/3354#issuecomment-139377985) but shouldn't it be part of the ORM to begin with?

**Comment by felixfbecker** [comment]
@Shahor read https://github.com/sequelize/sequelize/issues/3354#issuecomment-139470795.

**Comment by chrisnew** [comment]
@Shahor @janmeier where `id` is the primary key `INSERT INTO … ON DUPLICATE KEY UPDATE … id = LAST_INSERT_ID(id)` allows you to immediately ask for the `id` on the same connection with `SELECT LAST_INSERT_ID();`

Implementing that trick would solve the issue with MySQL and getting the primary key in both inserted and updated case.

**Comment by antondc** [comment]
Trying to get inserted record after upsert, but no success even with Sequelize v5 and PostgreSQL.
See [https://stackoverflow.com/questions/53179703/sequelize-upsert-get-new-id-from-inserted-record](https://stackoverflow.com/questions/53179703/sequelize-upsert-get-new-id-from-inserted-record)

**Comment by anshulg93** [comment]
Use create() instead of upsert(). It will return you created object.

**Comment by mi-mazouz** [comment]
any update on this?

**Comment by gabegorelick** [comment]
Upsert was recently reimplemented in https://github.com/sequelize/sequelize/pull/12301. Are people still having issues?

**Comment by sushantdhiman** [comment]
@gabegorelick It is still a `v6-beta` feature & most users are using `v5` (latest) release

**Comment by cirosantilli** [comment]
SQLite also added RETURNING in 2021 BTW: https://www.sqlite.org/lang_returning.html so now this could be solved nicely for it.
