### ISSUE TITLE
Canceled promise with findOrCreate makes subsequent commands hang

### ISSUE THREAD

**Issue by vinkaga** [sequelize/sequelize#3407]
The following code fails to complete `sequelize.sync` command after the promise of `findOrCreate` is canceled. 
```JavaScript
var Sequelize = require('sequelize')
    , sequelize = new Sequelize('seqex', 'root', 'mysql', {logging: false});

var User = sequelize.define('user', { name: {type:Sequelize.STRING, allowNull:false} });

sequelize.sync({force: true}).then(function () {

    User.create({name: 'Gina'}).then(function() {

        var promise = User.findOrCreate({where: {name: 'Gina'}}).cancellable();
        promise.cancel('forced cancel');
        promise.spread(function() {

            console.log('It should not get here');

        }, function(err) {

            console.log('Expected error:', err);

            sequelize.sync({force: true}).then(function () {
                console.log('After sync: It should get here');
            }, function(err) {
                console.log('Error in sync:', err);
            });
        });
    }, function(err) { console.log(err)});
});
```
It generates the following output
```
Expected error: [Error: forced cancel]
```
If the `findOrCreate` is replaced by `find`, it works correctly and produces the following output
```
Expected error: [Error: forced cancel]
After sync: It should get here
```

**Comment by janmeier** [comment]
This is likely because the internal transaction in findorcreate is not comitted or rolled back when the promise is cancelled. Generally I'd say that sequelize promises are not meant to be canceled.

Whats your specifc usecase for `cancel` here ?

**Comment by vinkaga** [comment]
The use is `cancel` here is purely for testing purpose. I don't know of another way to create failure conditions on demand to ensure that our code behaves correctly under those failure conditions. I've used `cancel` with other sequelize commands and other APIs (e.g. Stripe) for this purpose. All other situations seem to result in forced failure without side effects except for this one.

Without ability to create failures on demand, our code coverage would remain at an unacceptably low level (< 90%) for some modules.

**Comment by janmeier** [comment]
The problem is that findOrCreate uses a transaction internally. That transaction is comitted in a `.finally` function, but if you `cancel` the promise, that function is never called, meaning the transaction is never comitted. 

When you try to do a sync, which starts by dropping the users table, that query hangs because there is still an open transaction which accesses the users table.

The solution here is probably to mark `findOrCreate` as `uncancellable` - this means that the transaction chain will be allowed to finish, but you can still reject it using `cancel`

A much easier way to make the code fail in my view would be use `sequelize.Promise.reject()`
