### ISSUE TITLE
GROUP BY support

### ISSUE THREAD

**Issue by nagyv** [sequelize/sequelize#348]
hi,

are there any plans for GROUP BY support? or in general: support for aggregates beside the simple pre-coded aggregate queries of min, max and count?

I'm quite new the sequelize, coming from a Python knowledge with Django's ORM and SqlAlchemy, and would be really happy to see these features.

I would be happy to contribute these too, if we can start a discussion on its design here. Do you have any thoughts on how to make it work?

**Comment by Mijago** [comment]
It seems that using the group by in scopes does not concatenate the group-clauses.

                /* GROUP */
                g_date     : {
                    attributes: [
                        ["datum", "date"]
                    ],
                    group     : ["datum"]
                },
                g_lanr     : {
                    attributes: ["lanr"],
                    group     : ["lanr"]
                },

with
`xxx.scope("g_date", "g_lanr").findAll()`
just creates
`SELECT "datum" AS "date", "lanr" FROM "xxx" AS "xxx" GROUP BY "datum" LIMIT 10;`
which throws an error, because `lanr` is not in the GROUP clause.
I'm using PostgreSQL.


I can work around this by creating an extra scope, but this is not the perfect solution.

                g_lanr_date     : {
                    attributes: ["lanr", ["datum", "date"]],
                    group     : ["datum","lanr"]
                },

**Comment by janmeier** [comment]
@Please don't necro old issues :)

**Comment by Mijago** [comment]
Okay, sorry :D Should I create a new one?

**Comment by janmeier** [comment]
Yep :)

**Comment by Abhimishra2424** [comment]
driverid, orderid :: This is table cloum how  can we write in Sequelize  ?
