### ISSUE TITLE
UUID MySQL not working

### ISSUE THREAD

**Issue by kimthangatm** [sequelize/sequelize#3483]
I use both UUID, UUIDV1, UUIDV4 and res.send(result) return : id, user_id, parent_id with SAME format:

```
id: {
	type: "Buffer",
	data: [
		53,
		52,
		99,
		56,
		...
		...
	]
	...
```

```
__models.categories.findAll({
        limit : 1,
        order : 'name DESC'
    }).then(function (result){
        res.send(result);
    });
```

```
'use strict';
module.exports = function (sequelize, DataTypes) {
    return sequelize.define('categories', {
        id: DataTypes.UUID,
        user_id: DataTypes.UUIDV1,
        parent_id: DataTypes.UUIDV4,
        
        name: DataTypes.STRING(255),
        alias: DataTypes.STRING(255),
        description: DataTypes.TEXT,
        status: DataTypes.STRING(20),
        wp_id: DataTypes.INTEGER,
        publish_date: DataTypes.DATE,
        tags: DataTypes.STRING
    }, {
        tableName: 'categories',
        createdAt: 'created',
        updatedAt: 'modified'
    });
};
```

**Comment by janmeier** [comment]
So the issue you are having is that UUIDs are not correctly stringifiied, right?

I cannot reproduce this on latest master - which version are you experiencing this on?

**Comment by kimthangatm** [comment]
I use MariaDB 10.0.17 (MySQL) with Sequelize v2.0.5

```
CREATE TABLE IF NOT EXISTS `categories` (
  `id` binary(36) NOT NULL,
  `user_id` binary(36) DEFAULT NULL,
 `parent_id` binary(36) DEFAULT NULL,
  `alias` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  ...
  ...
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
![Screen shot](http://i.imgur.com/qtBXJlh.png?1 "Screen shot")

**Comment by janmeier** [comment]
Ah, so your table is not created by sequelize I take it? Sequelize will create the table as `CHAR(36) BINARY` - actually I think mysql just ignores the binary part....

The binary data is returned as a buffer, and `buffer.toJSON` returns the output you saw. 

Not sure what the best behaviour here would be.... Should we do `buffer.toString('utf8')` perhaps. @mickhansen 

It wouldn't work to do it for all buffers though, since some people would be fine with getting the regular json representation of a buffer in their json. 

The best fix for your case would probably be to change the columns to `CHAR(36)`

**Comment by kimthangatm** [comment]
Thank @janmeier for suport!
