### ISSUE TITLE
sequelize update model columns by its value

### ISSUE THREAD

**Issue by HussamQaza** [sequelize/sequelize#3485]
hey guys, 

i am trying to make sql query 
```javascript
Users.update({
    mark  : "mark  + 3" , 
    rate : "rate + '_upper' "
   } , {
         where : { 
             name : "roy"
          }
})
```

but the generated query is not a valid query

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

http://docs.sequelizejs.com/en/latest/api/instance/#incrementfields-options-promisethis
