### ISSUE TITLE
Synchronous database call, Possible?

### ISSUE THREAD

**Issue by perara** [sequelize/sequelize#3500]
I'm attempting to fetch some rows from my database, i wish to do something like this:

```
var table1 = Table1.all();
var table2 = Table2.all();

//
// Do something with these tables
//
```

Sadly i have not found a way to do this
Is it even possible to do this?

**Comment by janmeier** [comment]
node.js is inherently async, so no this is not directly possible. There are still other ways to achieve something similar however:

Promise.all / join
```js
sequelize.Promise.all([
  Table1.all(),
  Table2.all()
]).spread(function (table1, table2

sequelize.Promise.join(
  Table1.all(),
  Table2.all(),
  function (table1, table2
```

Using [generators](https://github.com/tj/co)
```js
co(function *() {
  var table1 = yield Table1.all();
  var table2 = yield Table2.all();
});
```

Closing this issue, since it is neither a bug report nor a feature request.

For further general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
