### ISSUE TITLE
Associations with a transaction timeout (includes CLS)

### ISSUE THREAD

**Issue by meanjoe45** [sequelize/sequelize#3501]
Hello,

I'm trying to use transactions with queries that switch between associated tables. The test code below demonstrates what I'm trying to do and the error that I'm receiving. The error is the following:

`ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction`

If I uncomment the `taskId` field in the Audit table and comment out the associations between the Task and Audit tables, the timeout does not occur. If I keep the table associations in place and comment out the use of CLS (at the top of the code), the timeout does not occur.

If I'm using something improperly, please let me know. I am at a loss as to what is causing this issue. Thanks for the help.

```javascript
'use strict';

// sequelize: 2.0.5
var Sequelize = require('sequelize');

// continuation-local-storage: 3.1.4
var cls = require('continuation-local-storage');

Sequelize.cls = cls.createNamespace('sequelize-namespace');

var sequelize = new Sequelize('testDB', 'meanjoe45', null, {
    dialect: 'mysql',
    define: {
        timestamps: true,
        underscored: false,
        freezeTableName: true,
        syncOnAssociation: true,
        engine: 'InnoDB',
        charset: 'utf8',
        collate: 'utf8_general_ci',
    }
});

var Task = sequelize.define('Task', {
    status: Sequelize.INTEGER
});

var Audit = sequelize.define('Audit', {
    message: Sequelize.STRING,
    // taskId: {
    //     type: Sequelize.INTEGER,
    //     allowNull: true,
    //     defaultValue: null
    // }
});

Task.hasMany(Audit, { foreignKey: 'taskId' });
Audit.belongsTo(Task, { foreignKey: 'taskId' });

sequelize.sync({ force: true })
    .then(function() {
        return Task.create({ status: 1 });
    })
    .then(function() {
        return sequelize.transaction(function (t) {
            return Task
                    .find({
                        where: {status: 1}
                    })
                    .bind({})
                    .then(function(task) {
                        this.task = task;
                        return Audit.create({taskId: this.task.id, message: 'Step 1'}, {transaction: null});
                    })
                    .then(function() {
                        this.task.status = 2;
                        return this.task.save();
                    })
                    .then(function() {
                        return Audit.create({taskId: this.task.id, message: 'Step 2'}, {transaction: null});
                    })
                    .then(function() {
                        console.log('Finished');
                    })
                    .catch(function(error) {
                        console.log(error.message);
                    });
        });
    })
    .catch(function(error) {
        console.log(error.message);
    });
```

**Comment by mdarveau** [comment]
Hi,

The problem here is not sequelize, it's the transaction management... and
mysql. If you try this code in Postgres, it will run fine. However, MySQL
has a different locking mechanism and here is what happens (BTW, next time,
if you paste the query log, it will help a lot):

1 - Executing (default): INSERT INTO `Tasks`
(`id`,`status`,`updatedAt`,`createdAt`) VALUES (DEFAULT,1,'2015-04-10
00:25:25','2015-04-10 00:25:25');
2 - Executing (415b6ae2-fc99-4e55-86f4-462e849a4154): START TRANSACTION;
3 - Executing (415b6ae2-fc99-4e55-86f4-462e849a4154): SET SESSION
TRANSACTION ISOLATION LEVEL REPEATABLE READ;
4 - Executing (415b6ae2-fc99-4e55-86f4-462e849a4154): SET autocommit = 1;
5 - Executing (415b6ae2-fc99-4e55-86f4-462e849a4154): SELECT `id`,
`status`, `createdAt`, `updatedAt` FROM `Tasks` AS `Task` WHERE
`Task`.`status` = 1 LIMIT 1;
6 - Executing (default): INSERT INTO `Audits`
(`id`,`message`,`taskId`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'Step
1',1,'2015-04-10 00:25:25','2015-04-10 00:25:25');
7 - Executing (415b6ae2-fc99-4e55-86f4-462e849a4154): UPDATE `Tasks` SET
`status`=2,`updatedAt`='2015-04-10 00:25:26' WHERE `id` = 1
8 - Executing (default): INSERT INTO `Audits`
(`id`,`message`,`taskId`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'Step
2',1,'2015-04-10 00:25:26','2015-04-10 00:25:26');
9 - ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting
transaction
10 - Executing (415b6ae2-fc99-4e55-86f4-462e849a4154): COMMIT;

As you can see (and by looking at the 'transaction: null' in your code, I
assume this is what you wanted), there are two transactions involved:
default (with auto-commit after each SQL statement) and the 415b6ae2*
transaction.

You start by inserting the Tasks (line 1) and since it's in auto-commit, it
gets saved immediately.
Line 2, 3, 4 if transaction bootstrap.
Line 5: the initial select and as there is no "FOR UPDATE" or anything, no
lock is taken. So far so good.
Line 6: An insert is made into Audits. Since this table has a foreign key
to task #1, mysql will take a shared lock on the task #1 record, insert the
Audit record and since it's the default transaction and in auto-commit,
everything is committed and the task shared lock is released.
Line 7: The task #1 is updated by the *transaction 415b6ae2** and, to
execute the update, mysql takes an *exclusive lock on the task #1 record*.
Until the transaction is committed, that transaction will hold an exclusive
lock on that record.
Line 8: An insert is made into Audits. Since this table has a foreign key
to task #1, mysql will try to take a shared lock on the task #1 record
BUT... it can't since there is already an exclusive lock held by the
transaction 415b6ae2*. MySQL then wait until the exclusive lock is
released, but this never happens because the transaction 415b6ae2* is not
committed since the last promise is not resolved. You are in a deadlock and
mysql timeout after some time. At that point, the last promise is resolved
and the transaction commits.

To help you further, I would like to know why are you passing
"transaction: null"
in the create statements?

Manuel

**Comment by meanjoe45** [comment]
Thanks Manuel for the response and sorry for having no query logs. I'll include them in the future. With your explanation, I was able to finally search for the issue correctly and found all the information I could handle on the topic. This is definitely not a sequelize issue and this issue should be closed.

To answer your question, I was separating the audit 'creates' from the task work in case an error occurs during task processing. It is meant to record the progression and to help with debugging if a error occurs (and the transaction is rolled back). Of course, it has to work for it to be of any help! If there are better ways of documenting a complex task processing in a transaction, I'd love to hear about them.

Thanks again.

**Comment by janmeier** [comment]
To counter this issue you can add constraints: false to the options on the two associations. This will disable the foreign keys

**Comment by meanjoe45** [comment]
Thanks for the suggestion!
