### ISSUE TITLE
why active record?

### ISSUE THREAD

**Issue by PLEEROCK** [sequelize/sequelize#3514]
I've been working with active record and data mapper implementations of ORM enough to know the problems with using active record implemented ORM in my large projects. Why did you decide to go active record instead of data mapper and is there any plans to do it data mapper way, or at least introduce some options for the library to turn off some active record-like features?

**Comment by mickhansen** [comment]
This library was originally authored by @sdepold who used AR i imagine.
The current mtaintainers have no experience with Ruby and no real idea what you are talking about :)

**Comment by PLEEROCK** [comment]
:disappointed: I think its important to look towards this way and start to think how to re-implement core in a data mapper way in a future major releases. Its important concept and is more popular in enterprise and big projects.

**Comment by mickhansen** [comment]
@PLEEROCK Again, you are talking to maintainers who have no experience with ruby - And we don't necessarily have time to go through an orm to pick up what you think is better.

You should contribute some specific examples where you think things could be better, then we can open a discussion about that.

**Comment by PLEEROCK** [comment]
there is nothing about ruby. I don't know ruby either. We are talking about orm implementation. Read more books to understand what is better. I suggest you to read http://www.amazon.com/Enterprise-Application-Architecture-Addison-Wesley-Signature-ebook/dp/B008OHVDFM which describes both patterns very well. Also take a look on java's hibernate implementation, or php's doctrine implementation as a good example how orm should work in the enterprise

**Comment by mickhansen** [comment]
Both AR and datamapper are ruby, so i'd say there's quite a bit of ruby.
I don't have the time to pick up another book at the moment.

You are as i said more than welcome to come with *CONCRETE* examples and improvements but generalizations won't help us much at this time.

Alternative orms that you can check out:
https://github.com/tgriesser/bookshelf
https://github.com/balderdashy/waterline

**Comment by tomasz-szymanek** [comment]
@mickhansen It's not pattern's (active record)  fault, that some Ruby RoR devs decided to name their ORM by the name of that pattern. You should really read about design patterns, because what you are saying is really embarrassing.

**Comment by pleerock** [comment]
@tomasz-szymanek take a loon on [typeorm](https://github.com/typeorm/typeorm) if you are looking for data mapper orm

**Comment by mickhansen** [comment]
@tomasz-szymanek Really? Necroing a 1½ year old issue to bad mouth a maintainer on not knowing a specific data pattern by name.

In hindsight i should have probably have given the issue more time, but we've dealt with quite a bit of issues over the years.

Frankly your behaviour is emberassing @tomasz-szymanek, perhaps you ought reflect on how you interact with open source libraries.

**Comment by mickhansen** [comment]
@pleerock typeorm looks great

**Comment by felixfbecker** [comment]
@pleerock @tomasz-szymanek data mapper and active record patterns both have their up and downsides. But most of the criticism for the active record pattern doesn't apply in JavaScript because a class is also just an object. You can stub static methods, pass it around etc. I would be very interested in constructive criticism on how to make Sequelize better / avoid downsides of Active Record, but just saying "buy these books, this is how ORMs must work in enterprises" is just plain arrogance.

**Comment by pleerock** [comment]
@felixfbecker 

Yes, both data mapper and active records have pros and cons, but in most cases data mapper wins because its simply better scales once your app gets larger. And we know that any real app gets larger by a time. I'm not talking about mocking stubs in active record, its not the only problem of AR. And the fact that it wins is not only my opinion, most experienced devs will admit it. 

And yes, this issue doesn't have a big sense and can be closed because this orm will mostly never be converted into data mapper orm. However there are real-world examples when active record orm has evolved into data mapper orm and only got better and more popular from it.

The discussion here is mostly about responses @mickhansen gave, not about AR vs DM.
I know you are supporting your college, but take a look on his earlier responses and think whose responses really deserve 👎 . But yeah, he has admitted that he simply didn't put enough attention to this issue. I can understand this even despite of answers he gave, because maintaining popular open source library for free isn't easy.

**Comment by janmeier** [comment]
I think the issue stems from the fact that you stated "active record is bad - data mapper is better" without any backing arguments - We welcome discussions about code structure, but not without better arguments.

In the best of all words the answer should have been along the lines of "please tell me more about why you think so", but given that we get a lot of issues, we may be quick to dismiss those questions that are not perfectly worded instead.

I'm going to lock this thread - Anyone who wants to have a discussion about active record, data mapper, or any other pattern you think sequelize should follow in the future, feel free to open a new issue
