### ISSUE TITLE
Transaction autocommit option

### ISSUE THREAD

**Issue by greghart** [sequelize/sequelize#3568]
This may be less of a bug and more of a mis-understanding. This regards the transaction `autocommit` option, as detailed here (http://sequelize.readthedocs.org/en/stable/api/sequelize/#transactionoptions-promise). 

First of all, it seems like this is unnecessary (as on MySQL at least a transaction is an implicit autocommit: false. See https://dev.mysql.com/doc/refman/5.0/en/commit.html : "To disable autocommit mode implicitly for a single series of statements, use the START TRANSACTION statement:"). Maybe this is not the case for other dialects, or I am missing the point of this field.

Regardless, code I am working on upgrading from 1.7 to 2.0 was was already using `transaction(autocommit: false)`, and claimed to need it for certain bugs (outside the scope of this issue). While working out the kinks, I noticed that applying this flag keeps the connection it's run on  with autocommit mode disabled, even after the transaction completes. My intuition is that with the flag being supplied in the transaction call, it would be reset back at the end of the transaction. If that's not the case, maybe fix here is as simple as some documentation as to this option.

Here is the code I am using to see this
```coffeescript
Sequelize = require 'sequelize'
Promise = require 'bluebird'

config = 
  host: '127.0.0.1'
  dialect: 'mysql'
  sync: {force: false}
  syncOnAssociation: false
  define:
    timestamps: false
    underscored: true
    freezeTableName: true
    syncOnAssociation: false
  maxConcurrentQueries: 250
  pool: { maxConnections: 1 } 

sequelize = new Sequelize 'test', 'user', 'pass', config

Test = sequelize.define 'test', 
  thing: Sequelize.STRING

showAutocommit = ->
  sequelize.query("show variables like 'autocommit'")
  .spread (results) ->
    console.log results[0].Value

Test.sync(force: true)
.then showAutocommit
.then ->
  sequelize.transaction(autocommit: false)
.then (t) ->
  options = transaction: t
  Test.create(
    {
      thing: "transaction"
    }, 
    options
  )
  .then ->
    t.commit()
  .catch ->
    t.rollback()
# autocommit is now OFF for this session. Should this be the case?
.then showAutocommit

```

Also I know coffeescript isn't this repo's thing, LMK if you'd like the test code in Javascript, or any other info. Thanks!

**Comment by mickhansen** [comment]
1.7 had quite a few transaction bugs so probably unrelated.
I must admit i'm not 100% certain how auto commit work, but i agree that it doesn't seem to make a lot of sense for MySQL, however for PG there's a difference.

**Comment by ppoo24** [comment]
Come up against this issue in my project (under __sequelize v2.0.4__) !
i wasted a half-day working on this problem, finally focused on the maybe "autocommit" reason.
thanks for @greghart 's deeply analysing, now i'm making sure that resetting `autocommit` to `ON` after every transaction is a way to solve my problem.
but it still needs to be fixed, isn't it?

**Comment by janmeier** [comment]
I believe there was some reasoning for setting autocommit manually (@sdepold wrote the code originally). But the mysql documentation seems pretty clear on this:

> With START TRANSACTION, autocommit remains disabled until you end the transaction with COMMIT or ROLLBACK. The autocommit mode then reverts to its previous state.

**Comment by janmeier** [comment]
And I would infer from the following 

>  By default (without BEGIN), PostgreSQL executes transactions in "autocommit" mode,

That with BEGIN, the transaction is _not_ in autocommit mode

**Comment by ppoo24** [comment]
may change the option - autocommit 's default value to `auto`, then if mysql, sequelize will not call `SET autocommit=x` by `auto`

**Comment by janmeier** [comment]
@ppoo24 Sounds like a good solution - PR welcome

**Comment by jbarros35** [comment]
This problem is very very important. How do you expect open a transaction in postgres with autocommit true? Why using transaction so? I have a table with posts and related to several tags, when open a transaction to postgres sequelize made a commit on the post and after  when open the bulk inserts to hashtags the transacion was ALREADY COMMITED. Do you realize how important is that?
Executing (c457e532-b164-43dc-9b0e-432be031fe36): START TRANSACTION;
Executing (c457e532-b164-43dc-9b0e-432be031fe36): SET SESSION TRANSACTION ISOLAT
ION LEVEL REPEATABLE READ;
Executing (c457e532-b164-43dc-9b0e-432be031fe36): INSERT INTO "posts" ("title","
shortdescription","description","updatedAt","createdAt") VALUES ('hero one','her
o one','hero one','2015-06-28 20:40:48.989 +00:00','2015-06-28 20:40:48.989 +00:
00') RETURNING *;
Executing (c457e532-b164-43dc-9b0e-432be031fe36): COMMIT;
Executing (c457e532-b164-43dc-9b0e-432be031fe36): INSERT INTO "hashtags" ("hashI
d","description","createdAt","updatedAt") VALUES (DEFAULT,'abc','2015-06-28 20:4
0:48.989 +00:00','2015-06-28 20:40:48.989 +00:00'),(DEFAULT,'def','2015-06-28 20
:40:48.989 +00:00','2015-06-28 20:40:48.989 +00:00'),(DEFAULT,'ghij','2015-06-28
 20:40:48.989 +00:00','2015-06-28 20:40:48.989 +00:00');
undefined
POST /api/posts/ 200 38.196 ms - 231
Unhandled rejection Error: commit has been called on this transaction(c457e532-b
164-43dc-9b0e-432be031fe36), you can no longer use it
Just try by yourself and don't blame me.

**Comment by yonjah** [comment]
Just noticed this issue (After about 2 days of debugging weird concurrency issues)
 
Can this be ported back to 3.x ? 
Even under some feature flag ?
The way things are currently transactions are basically broken

Also I'm not sure if this fix completely solves this issue.
At least with mysql autocommit is a global setting that will leak outside of the transaction.
So it goods it's not being set by default. 
But if you'll try to set autocommit to false since autocommit will not be activated back when the transaction ends this will mess all future queries.
It's probably be a bit messy to set the autocommit back to its original value but I think this can be converted to no op method since with mysql it doesn't make any sense to set it in the transaction level and having the option there especially when it leaks is really confusing.

**Comment by OlgaIvantsova** [comment]
Thank you so much! you saved my time

**Comment by rsshilli** [comment]
This only took me FOREVER to debug this one.  Why isn't anything getting saved to the DB even though there are perfectly good SQL statements being spit out to the log?  OMG autocommit got turned off permanently in a transaction somewhere.
