### ISSUE TITLE
Ho to count up an INT Column in Sequelize

### ISSUE THREAD

**Issue by BernhardBezdek** [sequelize/sequelize#3570]
I want to count a column up related on the latest value.
In plain plain old SQL I do it this way:

```
UPDATE `db`.`table_a` 
SET 
    `requests` = requests + 1
WHERE
    `id` = 123;
```

Is there a similar way to do this with sequelize model item?

**Comment by janmeier** [comment]
`Model.find().then(function (instance) { instance.increment) });`
http://docs.sequelizejs.com/en/latest/api/instance/#incrementfields-options-promisethis

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by BernhardBezdek** [comment]
@janmeier Thanks for that fast reply and sorry haven't fount increment in documentation.
Is it also possible to increment values beside other updated values?

**Comment by janmeier** [comment]
Nope, that is not currently possible. Should be doable if the extend the $ syntax to updates as well though, something like `Model.update({ where...}, { someColumn: 42, someOtherColumn: { $increment: 2 });`
