### ISSUE TITLE
Sequelize Date without timezone.

### ISSUE THREAD

**Issue by GuilhermeReda** [sequelize/sequelize#3584]
Hi, is there a way to override the date type to without timezone?

Because my db is used for other applications that dont use sequelize and they use without timezone.
And ```{timezone: "-03:00"}``` in sequelize options it don't really work.

**Comment by janmeier** [comment]
You should be able to override the create a custom date type like this https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/data-types.js#L43-L51, to use instead of `Sequelize.DATE`

You might also have to provide a custom date parser with https://github.com/brianc/node-pg-types to make sure the date is parsed as UTC

**Comment by janmeier** [comment]
No response, closing
