### ISSUE TITLE
How to count the results of a group by column?

### ISSUE THREAD

**Issue by DelvarWorld** [sequelize/sequelize#3596]
I can't for the life of me figure this out. The documentation doesn't have much in the way of common usage examples.

    SELECT models.*, count(likes.*)
    FROM models
    LEFT JOIN likes on models.id = likes.model_id
    GROUP BY models.id

**Comment by janmeier** [comment]
You can use `Model.count` to get the count for a single instance:

```js
Model.count({
  where: { id: a model id },
  include: [Like]
});
```

Note that you need to specify a where clause that matches a single model, and the function will be resolved with a single integer. `.count` probably needs a refactor to support this case properly. 

However, you can use `findAll`:

```js
return Model.findAll({
  attributes: ['id', [sequelize.fn('count', sequelize.col('likes.id')), 'likecount']],
  include: [{ attributes: [], model: Like }],
  group: ['model.id']
});
```
`likecount` is the attribute the count will be stored under. `attributes: []` on the include ensures that no data is actually selected from the like table, just the count

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by DelvarWorld** [comment]
http://stackoverflow.com/questions/29869077/how-to-count-a-group-by-query-in-nodejs-sequelize ;)

**Comment by KevinDanikowski** [comment]
@janmeier I know this is old, but for the example above (which worked perfectly), how can I get the attributes of my likes to be returned so that I can get `group: {..., likecount: 324 , likes: [id, createdAt]}` ?

**Comment by hephzaron** [comment]
`return Model.findAll({
  attributes: ['id', [sequelize.fn('count', sequelize.col('likes.id')), 'likecount']],
  include: [{ attributes: [
'id',
...other-attributes
], model: Like }],
  group: ['model.id','likes.id',...'likes.other-attributes']
});`
