### ISSUE TITLE
Add $key, $value syntax to query generator

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#3643]
Hi,

Could someone help me.
I want to the where, which produces `lower(email)=lower('test@email.com')`

Came up with this code:

``` javascript
return this.find({
                        where: 
                        {   
                            'email': this.sequelize.fn('lower', this.sequelize.col('email')),
                            'singupclient': client.toUpperCase()
                        }
                    });
```

Which produces:

``` sql
SELECT "id", "test1", "test2", "test3", "test4", "test5, "test6" FROM "user_" AS "user" WHERE lower("email") AND "user"."singupclient" = 'TEST' LIMIT 1;
```

How could I use the `sequelize.fn` with where?

Regards,

**Comment by PavelPolyakov** [comment]
I have managed to do this like this:

~~~javascript
                    return this.find({
                        where:
                                [this.sequelize.where(this.sequelize.fn("lower", Sequelize.col("email")),'=', email.toLowerCase()),
                                {'singupclient': client.toUpperCase()}]
                        });
~~~

Are there any other options to do that in more friendly manner? I mean without all those wrappings.

Regads,

**Comment by janmeier** [comment]
You should be able to drop the comparator argument, but other than that there's unfortunately no way to make it shorther right now.

The problem is that JS does not allow objects as keys. The ideal would be to be able to write 
```js
where: {
  sequelize.fn("lower", sequelize.col("email")): email.toLowerCase(),
}
```

But that is not possible, since `sequelize.fn` returns an object.

Perhaps this would be a more readable abstraction:

```js
where: {
  $and: [
    { $key: sequelize.fn("lower", Sequelize.col("email")), $value: email.toLowerCase() }
  ]
}

**Comment by mickhansen** [comment]
@janmeier that syntax is less than ideal, currently over query builder is completely hierarchical, having sibling aware operators would require some refactoring i think. Wrapping it in a key could work though:

```js
$custom: {
  $left: sequelize.fn
  $right: 'asdasd'
  $comparator: '>'
}
```

Or key/value rather than left/right, i just find left/right more generic since `key` is not necessarily a key at all, and `value` could be another column or an expression.

**Comment by janmeier** [comment]
Yeah that could work as well - and left an right are probably more clear name, at least less prone to misunderstanding
