### ISSUE TITLE
findall - dynamic where clause in sequelize

### ISSUE THREAD

**Issue by hfar** [sequelize/sequelize#3697]
Hello,

Is there any way to write dynamic where clause in sequelize ? i am trying to build an advanced search method by passing some parameters ,and if any one of them is empty/null then it will be ignored in where clause..

Also can we implement `where exists` using `findall` in sequelize? 

i am trying to do the following , return all records in `venue` model where exists in the associated model `venuetag` : 

```
SELECT * FROM VENUE V 
WHERE EXISTS (SELECT 1 FROM VENUETAG VT WHERE VT.VENUEID = V.VENUEID AND VT.TAGID IN (1,2))
```

i searched alot to find best practice solution with no result,thank you for your help.

**Comment by janmeier** [comment]
Perhaps you can use the query generator to build the nested query - https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L862. But mind you, it is not at all public API.

Generally, there is not very good support for nested queries at all in sequelize - unfortunately we haven't been able to define a good API for it yet, which is also in line with the rest of the API.

I'll close this issue since this is already something we are aware of. But if you have any suggestions, feel free to post them here and I'll make sure to keep them in mind
