### ISSUE TITLE
Model scopes and `complexFunctions`

### ISSUE THREAD

**Issue by franciscocardoso** [sequelize/sequelize#3724]
The new implementation of [model scopes](https://github.com/sequelize/sequelize/issues/3486) broke the ability to do something like this:

```js
complexFunction: function(email, accessLevel) {
  return {
    where: ['email like ? AND access_level >= ?', email + '%', accessLevel]
  }
}
```

Was this intentional?

**Comment by janmeier** [comment]
I'd say this was intentional, yes. The old implenementation tried to convert string where clauses to objects, but the implementation was rather broken - therefore I removed that part in my rewrite.

A big thing about scopes is that they can be intelligently merged, but we can't do that with strings.

The complexfunction example has been rewritten in the API docs - generally almost everything you want to write should be doable in object form http://sequelize.readthedocs.org/en/latest/api/model/#scope

**Comment by franciscocardoso** [comment]
Thanks for the reply @janmeier.

I have a scope in a postgres project which does, among other things, the following:

```js
parent->>'child' = 'true' 
```

What is the best way to achieve this with the new model scopes implementation?

**Comment by janmeier** [comment]
http://docs.sequelizejs.com/en/latest/docs/querying/#jsonb

**Comment by franciscocardoso** [comment]
Thanks @janmeier.

The issue is when trying to do more complex stuff like subquerying, etc.:

```js
('queryString' IN (SELECT value->>\'raw\' FROM json_array_elements(field)) OR parent->>'child' = 'foobar'
```

I recommend checking if the user creates a string instead of an object and allow raw queries.

Will that be something that you will consider to merge?
Should I create a PR with this?

**Comment by janmeier** [comment]
Yeah I guess that would be a reasonable solution. A PR that defaults to simple $and when where is a string would be good :)
