### ISSUE TITLE
it meet an bug wei postsql user where and $ne: null

### ISSUE THREAD

**Issue by qqqzhch** [sequelize/sequelize#3732]
<code >
   where: {
               
                        repo_full_name: fullname,
                        
                        player: {
                            $ne: null
                         }
                        // where: "player is NULL"

                    },
</code >
but the sql is player is not 'null'  ，is error

**Comment by janmeier** [comment]
`$ne` means not equal - if you want `IS NULL` you need `player: NULL`

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
