### ISSUE TITLE
Year 0 and PostgreSQL date parsing

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [sequelize/sequelize#3762]
I encountered this issue yesterday but wasn't sure if this should be handled in user-land or in sequelize directly.

Currently, in JavaScript it is possible to create a date with the year ```0```:

```
> new Date('0000-01-01')
Sat Jan 01 0 01:00:00 GMT+0100 (CET)
```

and if you query for this date's year you of course get back ```0```:

```
> new Date('0000-01-01').getFullYear()
0
```

Now if you pass this date to PostgreSQL through sequelize, you will get the following error:

```
{
    [SequelizeDatabaseError: ERROR: date / time field value out of range: "0000-01-01 00:00:00.000 +00:00"
        LINE 7: ...lt = "" / > ',ARRAY['
        Nature Publishing Group ']::TEXT[],'
        0000 - 01 - 0... ^
    ]
    name: 'SequelizeDatabaseError',
        message: 'ERROR:  date/time field value out of range: "0000-01-01 00:00:00.000 +00:00"\nLINE 7: ...lt=""/>\',ARRAY[\'Nature Publishing Group\']::TEXT[],\'0000-01-2...\n                                                             ^\n',
        parent: {
            [Error: ERROR: date / time field value out of range: "0000-01-01 00:00:00.000 +00:00"
                LINE 7: ...lt = "" / > ',ARRAY['
                Nature Publishing Group ']::TEXT[],'
                0000 - 01 - 0... ^
            ]
            severity: 'ERROR',
                sqlState: '22008',
                messagePrimary: 'date/time field value out of range: "0000-01-01 00:00:00.000 +00:00"',
                statementPosition: '685',
                sourceFile: 'datetime.c',
                sourceLine: '3534',
                sourceFunction: 'DateTimeParseError',
                sql: ...
        },
        original: {
            [Error: ERROR: date / time field value out of range: "0000-01-01 00:00:00.000 +00:00"
                LINE 7: ...lt = "" / > ',ARRAY['
                Nature Publishing Group ']::TEXT[],'
                0000 - 01 - 0... ^
            ]
            severity: 'ERROR',
                sqlState: '22008',
                messagePrimary: 'date/time field value out of range: "0000-01-01 00:00:00.000 +00:00"',
                statementPosition: '685',
                sourceFile: 'datetime.c',
                sourceLine: '3534',
                sourceFunction: 'DateTimeParseError',
                sql: ...
        },
        sql: ...
}
```

So my questions is basically: Who / How should handle this ?

**Comment by janmeier** [comment]
Hmm good question - I wasn't even aware that you could store dates BC in postgres. 

For dates with year < 0 the syntax is `199-01-10 .. BC`  but that doesn't work for year 0. No idea how we should handle this or how to even to it in pg :)

**Comment by janmeier** [comment]
@Mickael-van-der-Beek What is the syntax for inserting year 0 in pg?

**Comment by janmeier** [comment]
Scratch that, found it:

> The first century starts at 0001-01-01 00:00:00 AD, although they did not know it at the time. This definition applies to all Gregorian calendar countries. There is no century number 0, you go from -1 century to 1 century. If you disagree with this, please write your complaint to: Pope, Cathedral Saint-Peter of Roma, Vatican.

http://www.postgresql.org/docs/9.0/static/functions-datetime.html

**Comment by Mickael-van-der-Beek** [comment]
@janmeier PostgreSQL has the particularity of not having a 0 year. PostgreSQL and maybe other SQL databases too, follows the UTC standard that is itself based on the Gregorian calendar which doesn't have a 0 year.

**Comment by janmeier** [comment]
* Mysql does not support dates BC http://stackoverflow.com/questions/18654781/how-to-store-very-old-dates-in-database
* Neither does mssql https://msdn.microsoft.com/en-us/library/bb677335.aspx
* Sqlite allows you to store dates back to "noon in Greenwich on November 24, 4714 B.C." https://www.sqlite.org/datatype3.html - but sequelize cannot parse them back correctly, because of [this](http://scholarslab.org/research-and-development/parsing-bc-dates-with-javascript/) - postgres handles this fine, presumably because the database actually returns `-000001-01-01... `

The fix for this would be to add an exception if [dateToString](https://github.com/sequelize/sequelize/blob/master/lib/sql-string.js#L167) which substracts one and adds BC from the year and then an exception in [sqlite/query.js](https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query.js#L75) which formats the date-string before it is converted to a JS date

PR welcome

**Comment by janmeier** [comment]
Actually, scratch that, it won't work for PG - if we convert new `Date('0000-01-01') = Sat Jan 01 0`  to `-0001-01-01 BC' in the DB, it will be converted back to `new Date('-000001-01-01') = Fri Jan 01 -1`

**Comment by janmeier** [comment]
Alright, final comment :) 

Since [year 0 is not a valid year](http://en.wikipedia.org/wiki/0_(year)) javascript shouldn't even allow you to represent it, and there is no way we can map it to and from the database in a reasonable way. This needs to be handled in userland

**Comment by noinkling** [comment]
@janmeier Sorry to bring this up again but after running into this sort of issue I think this needs more awareness.

JavaScript uses (modern) ISO 8601 semantics, which uses astronomical numbering, which means that "year 0" represents 1 BC, -1 represents 2 BC, etc.

Check the "ISO 8601" section of the article you linked: https://en.wikipedia.org/wiki/Year_zero#ISO_8601

From the ES spec itself (https://tc39.github.io/ecma262/#sec-expanded-years):

> -271821-04-20T00:00:00Z | 271822 B.C.
> -000001-01-01T00:00:00Z | 2 B.C.
> +000000-01-01T00:00:00Z | 1 B.C.
> +000001-01-01T00:00:00Z | 1 A.D.

The underlying issue is that the ISO spec changed between the 1988 and 2000 versions. In the old version, 1 BC was represented as -1, 2 BC as -2, etc, and "year 0" was indeed invalid. These are the semantics that Postgres uses, which is why there is a mismatch. Weirdly enough there are at least a couple of exceptions that match the modern standard, at least for input:

```
=# SELECT to_date('0', 'YYYY');
    to_date
───────────────
 0001-01-01 BC

=# SELECT to_date('-1', 'YYYY');
    to_date
───────────────
 0002-01-01 BC

=# SELECT to_timestamp('-1', 'YYYY');
          to_timestamp
─────────────────────────────────
 0002-01-01 00:00:00 BC
```

But as you're probably aware, this doesn't match, e.g, `make_date`:
```
=# SELECT make_date(-1, 1, 1);
   make_date
───────────────
 0001-01-01 BC
```

And unfortunately there doesn't seem to be a built in way to get back correct, modern ISO with a negative sign.

**Comment by janmeier** [comment]
@noinkling I honestly have no idea how to handle that - It's never been a problem to have to store dates close to year 0 in my applications :)
You are welcome to provide a PR if you have any idea how to solve it

**Comment by noinkling** [comment]
@janmeier I don't actually use Sequelize currently, but this issue came up while searching if anyone else had encountered this problem so I just thought I'd set the record straight for posterity if nothing else.

You were basically on the right track I believe: input dates of `Date('0000-01-01')` should be converted to `"0001-01-01 BC"`, `Date('-000001-01-01')` to `"0002-01-01 BC"` and so on. The reason why this breaks the roundtrip is because the output parsing is also buggy and needs to account for the difference 😛

Since Sequelize uses the `pg` module under-the-hood, it probably uses its output parsing right? I've opened an issue at bendrucker/postgres-date#5 to see if that can be fixed. What about input serialization, where is that handled?

Note that this also affects the timestamp types in addition to `date`.

> It's never been a problem to have to store dates close to year 0 in my applications :)

Yeah working with BC dates (or at least using built-in datatypes for them) is indeed a very niche use case, and the thing is... those who do might not even be aware or care that their `Date` objects are wrong, since they still see the "right" number in the timestamp and it's a consistent roundtrip. So I'm not sure how big a deal this could potentially be.
