### ISSUE TITLE
.changed() detects value as changed when set from null to null.

### ISSUE THREAD

**Issue by JrSchild** [sequelize/sequelize#3812]
If the value of an instance was `null` and is `.set()` to `null`, Sequelize detects the value as changed.
Using sequelize 3.1.1.

**Comment by Thomathan** [comment]
instance.js has a primitives array and only compares values that match it. Since null is a primitive it should be included as well. 

However, typeof null returns object which seems to be bug in ecmascript.

Will probably need to explicitly check for null.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null
http://www.ecma-international.org/ecma-262/5.1/#sec-4.3.2
http://www.ecma-international.org/ecma-262/5.1/#sec-4.3.11

**Comment by JrSchild** [comment]
Thank you for the fast response. I can confirm that it fixes the issue.
