### ISSUE TITLE
Constraint error with deleted entry

### ISSUE THREAD

**Issue by adam-back** [sequelize/sequelize#3813]
Hi Sequelize Team!

Thanks so much for your open-source project. It makes my life a lot easier. I've build a PostgreSQL database with your help.

**Background**
Recently, I found either a bug or something that breaks my understanding. I have a plug which includes an electricity meter which has a unique serial number. This serial number should only be used once, but could be moved to another plug. Therefore:

**Model**
```javascript
module.exports = function( sequelize, DataTypes ) {
  var plug = sequelize.define('plug', {
    id: {
          type: DataTypes.INTEGER,
          autoIncrement: true,
          primaryKey: true
    },
    ekm_omnimeter_serial: {
      type: DataTypes.STRING,
      unique: true
    }
  }, { paranoid: true, underscored: true } );

  return plug;
};
```
**Problem**
When I delete a plug, the `deleted_at` column updates appropriately. I move the electricity meter to a new plug. This results in a sequelize constraint error because the serial number is not unique. This makes sense, as the serial number is already created as an entry in the database, but technically I've "deleted" it. Is this just a reality of using paranoid and an architechtual choice I need to make? Or, is this an error?

Thanks for your help!

**Comment by mickhansen** [comment]
You'll either need to have your unique column span both the serial and the deletedAt column or reuse the plug (via `restore()` first).

The constraint is a database one, not a sequelize one, so not any setting to fix this (it's simply the unique constraint in the database disallowing it).

**Comment by adam-back** [comment]
Thanks for the input! The first idea sounds like it might be a good workaround. How would I do that? Sequelize creates deletedAt itself.

**Comment by adam-back** [comment]
My work-around was to remove the unique constraint and use
```javascript
findOrCreate( { where: { ekm_omnimeter_serial: <number> }  } )
```
Find or create automatically filters-out deleted entries. If it finds a plug with a matching serial number, that is a unique error.

Wrote a [blog post](http://adam-back.azurewebsites.net/unique/) about it in more detail. 

Thanks for your help @mickhansen!

**Comment by BridgeAR** [comment]
You should be able to do the same thing without the need to remove the constraint by using the paranoid flag in your findOrCreate query. That way the find will find the 'deleted' entries and won't try to insert a new one.

**Comment by adam-back** [comment]
I'm sorry if my post is not clear, but I think that's exactly the opposite of what I'm trying to accomplish. I want `create()` to insert regardless of unique constraints if the conflicting row is deleted.

As an aside, I couldn't find the use of the paranoid flag in the [API documentation](http://docs.sequelizejs.com/en/latest/api/model/#findorcreateoptions-promiseinstance-created). Am I looking in the wrong place?

**Comment by BridgeAR** [comment]
I should have read more thoroughly what you wrote. You'll find the paranoid flag in the [model.findAll options] (http://sequelize.readthedocs.org/en/latest/api/model/#findalloptions-promisearrayinstance). 
Besides that: If you want to set a composite Key as @mickhansen suggested you have to insert the deletedAt in your model explicitly and declare the key by inserting `unique: 'keyName'`. Sequelize will detect the field through it's name and use that one instead of creating a new deletedAt field.

```js
module.exports = function( sequelize, DataTypes ) {
  return sequelize.define('plug', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true
    },
    ekm_omnimeter_serial: {
      type: DataTypes.STRING,
      unique: 'ekm_omnimeter_serial_deleted_at_const'
    },
    deleted_at: {
      type: DataTypes.DATE,
      unique: 'ekm_omnimeter_serial_deleted_at_const'
    }
  }, { paranoid: true, underscored: true } );
};
```

Here are all [define] (http://sequelize.readthedocs.org/en/latest/api/sequelize/#definemodelname-attributes-options-model) options.

**Comment by OlivierCuyp** [comment]
I got tricked with Postgres this last solution using a compound unique key.
This will in fact allow to create multiple record with the same `ekm_omnimeter_serial`.
Which is not the desired behavior.

**In postgres**

> Null values are not considered equal

More info here: https://www.postgresql.org/docs/9.0/static/indexes-unique.html

You might find some solution hints here: https://stackoverflow.com/questions/8289100/create-unique-constraint-with-null-columns

**Comment by lschnoller** [comment]
This is definitely a use case that should be solved from inside Sequelize framework. Generally, you wouldn't like to trigger a unique key constrain over a previously soft-deleted record. 

Since mysql allows duplicates on null composite keys, you wouldn't get the desired behavior even if the unique key is declared as a composite of the desired col + the deletedAt col. This is because the deletedAt column is null by default so you can get duplications on the other column for all the records that have not been soft-deleted. 

@mickhansen The solution to this problem taking into account mysql, is for Sequelize to add another boolean column called is_active with a 1 by default and to use it for paranoid flags along with the deletedAt col. Then, when a unique key is declared, Sequelize should add a composite unique key of the desired column + the is_active column.

**Comment by ValheKouneli** [comment]
I use Sequelize with paranoid and need uniqueness too. My solution is to define in the model like this:

```
const Plug = sequelize.define('Plug', {
...
  }, {
    indexes: [
      {
        unique: true,
        fields: ['serialNumber'],
        where: {
          deletedAt: null
        }
      }
    ],
    paranoid: true,
...
```

On a migration:

`return queryInterface.sequelize.query('CREATE UNIQUE INDEX serialNumber_unique ON "Plug" ("serialNumber") WHERE "deletedAt" IS NULL;')`

Works like charm.

The particular project where I use this is not on GitHub.

**Comment by alexandervonwl** [comment]
@ValheKouneli this does ot work for me. the migration is generated but the constraint does not include the where... any ideea?
