### ISSUE TITLE
Sequelize and ES6 Classes - Roadmap?

### ISSUE THREAD

**Issue by trevoro** [sequelize/sequelize#3840]
Hey there,

With ES6 a lot of new features are coming down the pipe, and one of them is classes.
Has anyone given any thought to using ES6 features in sequelize yet?

Thanks!

**Comment by BridgeAR** [comment]
Sequelize should also work in old nodejs versions. So this is not really an option. Besides that: What would be the benefit for you?

**Comment by janmeier** [comment]
ES6 is not coming to sequelize anytime soon (and propably not anytime late either ;) )

As @BridgeAR mentions, we need to support older node versions as well. [Object initializers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) would be cool, but personally I don't see much gain from classes either

**Comment by mickhansen** [comment]
I've actually been given a lot of though to using babel-node internally so we can use ES6 features in the project but still support 0.10. However that wouldn't really enable you to use ES6 classes.

I see a lot to gain by using ES6 classes though, generally better semantics rather than trying to roll your own like we do currently with sequelize.define()

**Comment by trevoro** [comment]
That's what I was thinking too. We're backing into a world where these things will be 1st class citizens, and I was wondering how to get "from here there". I use `babel-node` in all of my projects for this particular reason and that's why I was wondering about sequelize.

I'll take a few stabs at implementing something and see what happens. If you have any implementation ideas I'm all ears. ;)

**Comment by xpepermint** [comment]
+1 for `babel` (`cli` also)

**Comment by SpainTrain** [comment]
:+1: 

@BridgeAR @janmeier For an example of a project that supports ES5 and ES6 syntax for creating derived classes - https://facebook.github.io/react/docs/reusable-components.html 

Admittedly React is an extreme case due to jsx, but interop is feasible even in smaller and simpler projects e.g., https://github.com/home-buddy/rest-buddy

I would love to see ES6 interop on the sequelize roadmap.

@trevoro Did you make any progress on your attempt?  I am about to create a wrapper for one of my projects, but wanted to see what folks may have already done that I could use.  Thanks!

**Comment by felixfbecker** [comment]
@SpainTrain https://www.npmjs.com/package/sequelize-decorators
