### ISSUE TITLE
 sequelize.getMigrator is undefined

### ISSUE THREAD

**Issue by mypark** [sequelize/sequelize#3926]
trying to programmatically do a migration but I'm getting getMigrator is undefined errors

var migrator = sequelize.getMigrator();

TypeError: undefined is not a function

```
var Sequelize = require('sequelize');
var db = new Sequelize(
    config.get('database_name'),
    config.get('database_user'),
    config.get('database_password'),
    {
        host: config.get('database_host'),
        dialect: config.get('database_type'),
        pool: {
            max: 5,
            min: 0,
            idle: 10000
        }
    }
);
var migrator = db.getMigrator();
```

**Comment by janmeier** [comment]
Migration logic has been removed from sequelize core. See github.com/sequelize/cli and github.com/sequelize/umzug instead

**Comment by mypark** [comment]
Oh ok.  We should remove that programmatic migration section from the documentation.  http://docs.sequelizejs.com/en/latest/docs/migrations/#programmatic-use

**Comment by janmeier** [comment]
We should indeed :)

**Comment by stephenhu** [comment]
ok, as i suspected, seems this has been moved to sequelize-cli, so i assume umzug is the only way to do this programmatically?

**Comment by janmeier** [comment]
@stephenhu Yep

**Comment by stephenhu** [comment]
here's a code snippet for anyone else that has run into this issue and needs programmatic access:

// assumes you've already run ./node_modules/.bin/sequelize init and ./node_modules/.bin/sequelize model:create --name xxx --attributes "name:string, mobile:string"

var Sequelize = require("sequelize");
var Umzug = require("umzug");

var config = require("./config/config")["development"];
var sequelize = new Sequelize(
  config.database,
  config.username,
  config.password,
  config
);

var umzug = new Umzug({
  migrations: {
    params: [ sequelize.getQueryInterface(), Sequelize ],
    path: "migrations"
  },
  storage: "sequelize",
  storageOptions: {
      sequelize: sequelize,
      path: "./db"
  },
  logging: console.log
});

umzug.execute({
  migrations: ["20150809110723-create-blob"],
  method: "up"
}).then(function(migrations) {
  console.log(migrations);
});

you can also extract code from models/index.js that iterates through all migration files in the migrations directory instead of discreetly listing these here.  if you just follow the umzug README.md, you'll get an error about "getMigrator function from undefined object".  i had to look directly at the umzug source code lib/migrator.js to find that it's looking for a queryInterface object which you can receive from sequelize.getQueryInterface() (which i figured out from sequelize-cli lib/tasks/db.js).

**Comment by sushantdhiman** [comment]
@mickhansen This one has been documented [here](https://github.com/sequelize/sequelize/commit/f0a77caef43248370669e39dbc469d059851b9a6), Please close it.

**Comment by expelledboy** [comment]
The example posted by stephenhu was quite useful. Perhaps the docs should include it?

**Comment by timMogensen** [comment]
Guys, the documentation is not clear enough. Also leaving the programmatic usage stuff in the migrations section caused some grief for me during a period when deadlines where tight.
Googling sequelize getMigrations is not a function did not bring this thread up in search results.
migrations.getMigrations  was the only way I found this thread.....AND ITS THE ONLY PLACE WHERE THE DOCS ARE CORRECTED.

**Comment by timMogensen** [comment]
Love your work, please fix it

**Comment by mickhansen** [comment]
@timMogensen migations are removed from core, look at sequelize/umzug

**Comment by expelledboy** [comment]
@mickhansen I agree that the migration has moved out of sequelize and comprehensive docs should rather be with umzug, however a sequelize/umzug programmatic migration example would be extremely helpful!

I would do a pull request, but I am looking for the solution myself! 👍

**Comment by timMogensen** [comment]
@mickhansen Thanks, yup found that out. Its just the docs need a bit of work.
Thanks for the reply.
