### ISSUE TITLE
"Validation notEmpty failed" on empty strings and optional email field always has "isEmail" validator run

### ISSUE THREAD

**Issue by canebat** [sequelize/sequelize#3958]
I'm trying to have an optional email field, but setting `notEmpty: false` does not prevent `isEmail` validator from running:

    email: { type: DataTypes.STRING, unique: true, validate: {
        isEmail: { args: true, msg: "not a valid email!" },
        notEmpty: false,
        len: { args: [0, 100], msg:"email can't be bigger than 100"},
     } },

When saving a blank email (ie, `email: ""`), I always see two errors:

    SequelizeValidationError: Validation error: not a valid email!,
    Validation error: Validation notEmpty failed

Why does `notEmpty` keep failing, and how do I make the `isEmail` validator only run when an email has been given?

**Comment by janmeier** [comment]
I know it can seem quite confusing, but whenever you put something in the validation object, that function is run, no matter if you pass true or false. 

You could set allowNull true on the field instead and set the field to null for blank emails. 

Otherwise you'll have to create a custom validation function

**Comment by canebat** [comment]
@janmeier  I understand why the `isEmail` would throw an error, although I'm still puzzled why `notEmpty` is failing? It's been set to `false`, so shouldn't the validator accept `""`?

**Comment by janmeier** [comment]
What you put as the values doesn't matter - as long as notEmpty is there we run the validator regardless of whet

**Comment by mickhansen** [comment]
We merely look for the presense of the key `notEmpty` when running validations, while `true` is used in all examples it's really just a placeholder value.

**Comment by janmeier** [comment]
Closed, not a bug

**Comment by bbnnt** [comment]
how can you cleanly make it optional then if a value is still passed as an empty string `""` ?

Even with a custom function, it seems to first try those embeddeds validators

**Comment by ajmueller** [comment]
@canebat @bbnnt I came across this issue just now while trying to solve the same problem.  Presumably an email is submitted with an empty string because the desire is to remove it from the database, correct?  That's the scenario I'm in, so I'm solving it by simply iterating over the body of the form submission that will be used to update the database like so:

```javascript
exports.emptyStringsToNull = function(object) {
	for (var key in object) {
		if (object[key] === '') {
			object[key] = null;
		}
	}

	return object;
};
```

This is obviously very simple and doesn't do deep replacements within the object, but it gets the job done for what I need.  Hope that helps.

**Comment by jasonbodily** [comment]
@ajmueller - Where are you putting this function? Is there a way something like this could be used universally?

**Comment by ajmueller** [comment]
@jasonbodily I tend to have a utilities.js "catch all" for these types of functions.  I suppose you could write some middleware to do this for you as well.  Something like this would work for an Express app, for instance:

``` javascript
exports.emptyStringsToNullMiddleware = function(req, res, next) {
    for (var key in req.body) {
        if (object[key] === '') {
            object[key] = null;
        }
    }

   next();
};
```

Or, assuming you want to have the `emptyStringsToNull` function available separately:

``` javascript
// in utilities.js
exports.emptyStringsToNull = function(object) {
    for (var key in object) {
        if (object[key] === '') {
            object[key] = null;
        }
    }

    return object;
};

// in middleware.js
var utilities = require('./utilities');

exports.emptyStringsToNullMiddleware = function(req, res, next) {
    req.body = utilities.emptyStringsToNull(req.body);

    next();
};
```
