### ISSUE TITLE
how do I get current value of update row?

### ISSUE THREAD

**Issue by smithb1994** [sequelize/sequelize#3975]
How do I get the current value of the row I'm about to update?
Do I have to do a findOne query before I do an update, in order to find the previous value?
Here's what I want to do: 
`UPDATE userModels SET nonce = nonce + 1 WHERE u_id = 1`

Is there some way to make that work from here? How would I get [CURRENT VALUE OF NONCE]? Do I have to do a separate query?
```javascript
return userModels.update({
        nonce: [CURRENT VALUE OF NONCE] + 1
    },{
        where: {
            u_id: 1
        }
    }
);
```

**Comment by janmeier** [comment]
If you need the current value in your application you will need to do a select first.

If you only need to update the value you can use [`increment`](http://docs.sequelizejs.com/en/latest/api/instance/#incrementfields-options-promisethis)

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
