### ISSUE TITLE
Please improve documentation for PRACTICAL use

### ISSUE THREAD

**Issue by jbarros35** [sequelize/sequelize#3992]
I'm done, trying to figure out a simple, very very very simple relationship like this:
"use strict";
module.exports = function(sequelize, DataTypes) {

var Profile = sequelize.define("user_profile", {
	  id: {
		type:DataTypes.INTEGER,
		primaryKey: true,
		autoIncrement: true
	},
	fk_user_id: DataTypes.INTEGER,
	fullname: DataTypes.STRING       
  },{
      classMethods:{
          associate: function(models){
              Profile.belongsTo(models.User,{ foreignKey: 'fk_user_id', foreignKeyConstraint:true });
          }
      }
  }  
);

Profile.sync({force:true}).then(function(){});

return Profile;
};
"use strict";
module.exports = function(sequelize, DataTypes) {

var Profile   = sequelize.import(__dirname + "/Profile");

  var User = sequelize.define("users", {
	  id: {
		type:DataTypes.INTEGER,
		primaryKey: true,
		autoIncrement: true
	},
	email: {
		type:DataTypes.STRING,
		unique: true
	},
    password: DataTypes.STRING,
    token: DataTypes.TEXT     
  });

  // create tables
  User.sync({force:true}).then(function() {
	
  });
  
  return User;
};

Inside my index.js I try to linke those things:

(function(m) {
  m.User.hasOne(m.Profile, {foreignKey: 'id'});
  m.Profile.belongsTo(m.User, {foreignKey: 'id'});
})(module.exports);

Read ALL DOCUMENTATIONS SINCE YESTERDAY MIDNIGHT, lost my sleep time only for try how to create a simple relation between User and a Profile, one to one, try to figure out how to insert those beasts together without success. Read several stackoverflow threads and only crap code snippets which cannot help me out.

I have a model folder, my models are inside of it and User and Profile each of one are separated loaded. When my node server starts it gives me an error:

Unhandled rejection Error: user_profile is not associated to users!

Can you please update documentation for really practical use? Only code snippets cannot help us, we are new ones on this technology and documentation only focus on snippets, you don't focus on put it together for work inside a node server! I tried everything, very upset because I'm not a beginner programmer, I have more than 10 years on this, so can you explain how to work on this ORM framework???? 
By the way I'm following this tutorial but cannot pass from the initial steps as you can see.
http://www.redotheweb.com/2013/02/20/sequelize-the-javascript-orm-in-practice.html
Was the best I could find... opensource is really a nightmare people pretends to be a heaven and everything works but its fair away from reality...

**Comment by jbarros35** [comment]
No code snippets please! I need something really useful.

**Comment by mickhansen** [comment]
Please make the effort to properly format code, makes it alot easier for us to read.
I'm sorry you're having such a hard time getting started, that has generally not been the case (as far as we know).

The error your seeing generally appears because either the association doesnt exist, or you are using `as` in one place and not in the other. Can you show the find call triggering the error?

It looks like you are syncing your models individually, remember that they are asynchronous calls, so you might be better off doing a single `sequelize.sync({force: true})`.

You are passing `'id'` to `foreignKey`, that is almost always wrong, `foreignKey` should point at the attribute that holds the foreignKey (foreign key in SQL terms), so for belongsTo it's the source attribute pointing at target primary key, and for other relations it's the target attribute pointing back at the source primary key. If you are using sync you can generally leave out the foreignKey parameter completely since Sequelie will drop and recreate the tables for you.

**Comment by janmeier** [comment]
This user has been blocked from the sequelize organization because of multiple rude comments and refusal to listen to advice, so I'm closing this one
