### ISSUE TITLE
Validate model object without committing?

### ISSUE THREAD

**Issue by tylerFowler** [sequelize/sequelize#4002]
Basically I'd like to be able to statically validate an object against a given Model without necessarily committing said object. I took a look around at the code around the `Model::build` method and was unclear about validation behavior. It looks like validation can occur while building an instance but it's unclear how to do it or detect it for that matter.

Perhaps there's a better way to do this, but as an example say I have a Users signup page, but for email confirmation I have to put the user data into a Pending Users table first. But I still need to validate the User object server side before I serialize it into the temp table (which might just have a JSON field for user data), I'd like to be able to reuse the validations from the User model, which is the eventual destination of the user's data from the form.

**Comment by janmeier** [comment]
You can build an instance and then call `validate` on that. Remember that validate returns a promise http://docs.sequelizejs.com/en/latest/api/instance/#validateoptions-promiseerrorsvalidationerrorundefined

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by tylerFowler** [comment]
Interesting, I looked around for something like that both in docs & code (& google) and didn't find it so I assumed it didn't exist. Thanks!
