### ISSUE TITLE
UTC Conversion

### ISSUE THREAD

**Issue by daw451-duplicate** [sequelize/sequelize#4003]
We have a nodejs server that takes in a SMS text message where the user could text the date and time that they would like to record the text message for. So we create a date and try to save the reported date to the date sent in the text. But of course when we go to save it sequelize changes it to UTC. Side  note that this data will be accessible from anywhere in the world. The node server is in NY. 

The data will be viewable through a UI by the user... but when i select the data back out how do i get that back into local time for the user? All sequelize knows about is the timezone set in the connection within node right?

thanks

**Comment by Joshua-F** [comment]
[This](http://momentjs.com/timezone/) might help.

**Comment by janmeier** [comment]
Sequelize will stored time on UTC by default, this can be changed with the `timezone` option.

You should send the date from server to user in UTC (json.stringify on a date object wil do that automagically). The user's browser should then take care of displaying the date properly to the user 

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
