### ISSUE TITLE
Multiple actions in a migration file

### ISSUE THREAD

**Issue by kerdany** [sequelize/sequelize#4020]
Hi,

I'm trying to create a table `users` in a migration file, by calling both `queryInterface.createTable()` and then add indexes through multiple calls to `queryInterface.addIndex()`.

Quoting an example from the documentation, all examples show the `up` function returning the output of a single call to some `queryInterface.someAction()`.
```
    module.exports = {
      up: function(migration, DataTypes) {
        return migration.dropAllTables();
      }
    }
```
How can I call multiple `queryInterface` methods in a single `up` function body?

Thanks

**Comment by janmeier** [comment]
Either call `then` on the first action:

```js
return migration.dropAllTables().then(function () {
  return migration.somethingelse();
});
```

Or if you want everything to execute in parallel, use promise.all

```js
return Promise.all([
  migration.dropAllTables(),
  migration.somethingelse()
});
```

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
