### ISSUE TITLE
TIMESTAMPDIFF query

### ISSUE THREAD

**Issue by akocmark** [sequelize/sequelize#4030]
Hi guys!

I just wanna ask how could I do this query without using raw query? (because i have nested includes)
I only want to do this in the main source table. Here is the sample snippet that I want to use in sequelize.

```
SELECT name, birthDate
FROM Users
WHERE TIMESTAMPDIFF( YEAR, birthDate, CURDATE( ) ) > 18;
```

Sequelize is really awesome! thank you to all the contributors.

**Comment by janmeier** [comment]
`where: sequelize.where(sequelize.fn('timestampdiff', 'year', sequelize.col('birthDate'), sequelize.fn('currdate')), '>', 18)` should do the trick

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by ninjudd** [comment]
For anyone who finds this, using `'year'` directly does not work. You have to do this:
```
sequelize.fn('timestampdiff', sequelize.literal('year'), sequelize.col('birthDate'), ...) 
```
