### ISSUE TITLE
findAndCountAll count is wrong when query with associations

### ISSUE THREAD

**Issue by fourpixels** [sequelize/sequelize#4042]
Hi guys,
Unfortunately I stumbled upon a very unpleasant bug, that I cannot understand nor figure out how to work out. It's about when query with associations, the count is different from the returned values. Here's an example (quite simplified though):

```js
Question.belongsToMany(models.Resource, {
    through: models.QuestionToTag,
    as: 'Tags'
});

Resource.belongsToMany(models.Question, {
     through: models.QuestionToTag,
    as: 'Tags'
});

orm.models.Question.findAndCountAll({
    include: [
        model: Resource,
        as: 'Tags',
        where: {
            'id': { $in: [15, 16] }
        }
    ]
}).then(function(result) {
    console.log(result);
});
```

I have 3 questions, few different Resources (tags), and this is the result:
![Sequelize findAndCountAll association error](http://fourpixels.net/sequelize.jpg)

You can see that I've made a few relations, and that question #1 is associated to three resources (two of which I query - `#15` and `#16`) - `#15`, `#16` and `#17`. On the bottom half you can see the result from the debugger, stating that there are is a total of 4 items (`count = 4`), but the result contains **only** 3 rows. Question with id 1 is listed only once.

This is the count query (styled a little):

```sql
SELECT
	count(`Question`.`id`) AS `count` 
FROM
	`Questions` AS `Question`
INNER JOIN 
	(`question_to_tags` AS `Tags.QuestionToTag`
		INNER JOIN
			`Resources` AS `Tags`
			ON 
			`Tags`.`id` = `Tags.QuestionToTag`.`resource_id`
	)
	ON
		`Question`.`id` = `Tags.QuestionToTag`.`question_id`
	AND
		`Tags`.`id` IN (15, 16);
```

This is a big problem for me as I'm dealing with pagination and I need to have the total amount of items, so that I can make proper offset/limit query. 

Any ideas?

**Comment by janmeier** [comment]
I recently (https://github.com/sequelize/sequelize/commit/97d355aa80cad217a8bd7190a6c00433a73f367f) pushed a fix for something similar. Does adding distinct to the query fix it for you?

**Comment by fourpixels** [comment]
How to add distinct? Keep in mind I'm not writing raw query, I'm using regular ones (and cannot find nothing about distinct in docs :))

**Comment by janmeier** [comment]
The fix I posted adds distinct in the code - I just wanted you to test if adding distinct to the query you posted gives the right result if you run the query manually?

**Comment by fourpixels** [comment]
I'll ask again - how (where) to add distinct? :) In the include, in the where clause? Tried a few different places - all the same results (or errors).

**Comment by janmeier** [comment]
`SELECT count(DISTINCT `Question`.`id`) AS `count` `

**Comment by fourpixels** [comment]
What I've said is that the `count` is **correct** - there are four rows in the table. Adding distinct (the query you specified isn't working though) won't make any difference, as they are already distinct - 4 rows. The problem is with the other query (not the count one), which somehow shows only 3 rows. Here is the query that actually fetches the results:

```sql
SELECT 
	`Question`.`id`,
	`Question`.`type`,
	`Question`.`time`,
	`Question`.`difficulty`,
	`Question`.`correct_answers_count`,
	`Question`.`wrong_answers_count`,
	`Question`.`status`,
	`Question`.`created_at`,
	`Question`.`updated_at`,
	`Question`.`resource_id`,
	`Question`.`description_id`,
	`Question`.`created_by`,
	`Tags`.`id` AS `Tags.id`,
	`Tags`.`value` AS `Tags.value`,
	`Tags`.`description` AS `Tags.description`,
	`Tags`.`created_at` AS `Tags.created_at`,
	`Tags`.`updated_at` AS `Tags.updated_at`,
	`Tags.QuestionToTag`.`id` AS `Tags.QuestionToTag.id`,
	`Tags.QuestionToTag`.`question_id` AS `Tags.QuestionToTag.question_id`,
	`Tags.QuestionToTag`.`resource_id` AS `Tags.QuestionToTag.resource_id`,
	`Tags.QuestionToTag`.`created_at` AS `Tags.QuestionToTag.created_at`,
	`Tags.QuestionToTag`.`updated_at` AS `Tags.QuestionToTag.updated_at`
FROM
	`Questions` AS `Question`
	INNER JOIN (
		`question_to_tags` AS `Tags.QuestionToTag`
		INNER JOIN 
			`Resources` AS `Tags`
		ON `Tags`.`id` = `Tags.QuestionToTag`.`resource_id`
	)
	ON `Question`.`id` = `Tags.QuestionToTag`.`question_id`
	AND `Tags`.`id` IN (15, 16);
```

And here are the results (again seems right):
![Sequelize findAndCountAll association error](http://fourpixels.net/sequelize2.jpg)

**BUT** the final results that I get in the code are wrong. How is that possible?

**Comment by janmeier** [comment]
Ah, then I misread your post slightly - I figured since you posted the count query that was were your issue was.

As you mentioned yourself, you have 3 questions, so the count part is wrong. findAndCount returns the number of parent rows. That will be fixed by adding distinct to the count part of the query. The result is 3 question rows, one with 2 resources and the other two with one

**Comment by fourpixels** [comment]
After brute force tries, I figured out `findAndCountAll({ distinct: true ...})` fixes the problem. It does something similar to what you've posted (maybe I've messed up some brackets somewhere)..
It would be **very nice** if you update the docs somehow about this issue.....

**Comment by janmeier** [comment]
As I said, this has already been fixed in master :) https://github.com/sequelize/sequelize/commit/97d355aa80cad217a8bd7190a6c00433a73f367f

**Comment by fourpixels** [comment]
Just to mention - this throws error if I don't provide `$in` clause.....

**Comment by janmeier** [comment]
Which error?

**Comment by fourpixels** [comment]
Adding `distinct: true` in search params, without having `where`, I get this SQL being executed:

```sql
SELECT count(DISTINCT(*)) AS `count` FROM `Questions` AS `Question`;
```
and therefore this error:
```sql
ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*)) AS `count` FROM `Questions` AS `Question`' at line 1
```

**Comment by janmeier** [comment]
Yes, we already take that into account - If you look at the code I referenced you'll se that it only adds the distinct if there are includes on the count query

**Comment by fourpixels** [comment]
I have a lot of includes going around this query, especially where the `where` clause is used. And where `distinct` is used, the include I've posted is one out of 5. I won't argue, I'm just saying that in my case, the `where` is pretty important, otherwise it blows..

**Comment by janmeier** [comment]
I'm sure what we're arguing here? If there are required includes (include with where) we will set `distinct: true` And if there are includes passed to count, it will include the primary key in the query, resulting in `COUNT(DISTINCT id)`. Are you saying there are cases where this breaks for you?

**Comment by fourpixels** [comment]
I think you've dived too much into this project, and you should keep in mind others didn't.
So I didn't get your first "if there are includes", nor I get what "required includes" mean. I have includes, plenty of them! And this doesn't help not getting the error.. If you mean I must have where clause in at least one of those includes - ok, that's what I've meant.

**Comment by janmeier** [comment]
Sorry if my explanation was too technical :)

A required include is an include which results in an inner join. This can happen either if `where` is present on the include, or if explicitly set by `required: true`.

```js
orm.models.Question.findAndCountAll({
    include: [
        model: Resource,
        as: 'Tags',
        where: {
            'id': { $in: [15, 16] }
        }
   ]
});
```
The include for tags is required, because where is set. The question _must_ match a tag with one of the following ids.

```js
orm.models.Question.findAndCountAll({
    include: [
        model: Resource,
        as: 'Tags',
        where: {
            'id': { $in: [15, 16] }
        },
       required: false
   ]
});
```
This include is explicitly marked as not required, and will return all questions, but only those tags with id 15 or 16.

For the count part of findAndCount we only keep the required includes - because the left join ones don't have any impact on the count.

If a count query has includes we add `count(id)` as opposed to `count(*)`. So `count(DISTINCT(*))` will never happen, because we only set `distinct: true` from `findAndCount` when we pass includes to the count part

**Comment by alockwood05** [comment]
I am finding a distinct(*) problem;  I had the includes inside of a scoped model before the findAndCountAll options.  I found a fix which is not explicitly mentioned in this thread so I'll bring it up (not IDEAL, but it works for now: 

>  I had to pass into the query options `include:[]` in addition `distinct: true`;    

Even though my sequelize query already had includes from a **scope**.  Feels like a work around, but works just fine. :)

**Comment by Rudedog9d** [comment]
Hey all, sorry to bring up an old issue, but I was experiencing the same situation. I am using MySQL, and `findAndCountAll` was returning a number higher than appropriate when associations were including via the `include` option. 

I saw @janmeier said it is fixed in commit 97d355a, but I do not see the code in master. Adding the code to my project fixed the problem, however, I am concerned that the code never made it/didn't stick around in master. 

Did this code introduce a bug?

**Comment by doovers** [comment]
I'm having the same issue

**Comment by wilmer2000** [comment]
Me too, I'm having the same issue :/

**Comment by fourpixels** [comment]
I think @sushantdhiman is the one maintaining this now? It's sad such a good framework is going in the down spiral :(

**Comment by bhutten** [comment]
This is the same as #7225 (right?). The fix mentioned there is just to use "distinct: true". In my tests this resolves the issue.

**Comment by cmiwjaeger** [comment]
i have similar issue then i try to add findAndCountAll({ _**subQuery: true**_ ...}) and its fix my problem.

**Comment by FahadAshraf26** [comment]
added beforeCount hook inside the DB connection file this snippet will fix the wrong count issue in findAndCountAll()

```
sequelize.addHook("beforeCount", function (options) {
  const includeAvailable = options.find((item) => item["where"]);
  if (this._scope.include && this._scope.include.length > 0) {
    options.distinct = true;
    options.col =
      this._scope.col || options.col || `"${this.options.name.singular}".id`;
  }
  const whereSymbols = includeAvailable
    ? Object.getOwnPropertySymbols(includeAvailable["where"]).length
    : 0;
  const whereString = includeAvailable
    ? JSON.stringify(includeAvailable["where"]).length
    : 0;
  const whereObject = whereSymbols > 0 ? whereSymbols : whereString > 2 ? 1 : 0;
  if (whereObject === 0 && options.include && options.include.length > 0) {
    options.include = null;
  }
});
```

**Comment by aercolino-cognizant-cepsa** [comment]
I don't get why Sequelize is not automatically generating `SELECT DISTINCT ...` when I pass `distinct: true`. 

I mean, for the **count** it generates 
```SQL
SELECT count(DISTINCT(`ModelName`.`id`)) AS `count` FROM ... INNER JOIN ... WHERE ...
``` 
as expected 🎉, but for the **rows** it forgets I asked for `distinct: true` and instead of generating 
```sql
SELECT DISTINCT `ModelName`.`id` AS `id`, ... FROM ... INNER JOIN ... WHERE ...
``` 
it generates 😞
```sql
SELECT `ModelName`.`id` AS `id`, ... FROM ... INNER JOIN ... WHERE ...
```

What's the point of having the DISTINCT only in the **count** ??

**Comment by aercolino-cognizant-cepsa** [comment]
> I don't get why Sequelize is not automatically generating `SELECT DISTINCT ...` when I pass `distinct: true`.

Due to the half-baked support for `DISTINCT` in Sequelize 6 (mysql), I had to use the `raw: true` option for stopping Sequelize from prepending the primary key of the model to the list of selected attributes, so that the `[literal("DISTINCT `ModelName`.`id`"), "id"]` attribute I prepend myself will in fact be at the start of the selected attributes (just after `SELECT`, with nothing in between). 

However that causes Sequelize to not instantiate the Model on each row, of course, which forces me to `convertRawToExpectedShape(rows)` before returning the rows. 

Am I missing any alternative EASY way to get Sequelize generate 
```sql
SELECT DISTINCT `ModelName`.`id` AS `id`, ... FROM ... INNER JOIN ... WHERE ...
```
??
