### ISSUE TITLE
Pluggable comparators

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#4066]
The where query builder was recently refactored to make it a bit easier to read.
However we often get requests for new comparators and people have to wait for us to implement and release (if they don't offer up a PR themselves, which can be daunting for new users).

I think an API for adding operators would be great, both for internal and public use.
Perhaps something like:

```
sequelize.operator('$gt', function (key, value) {
  return [key, sequelize.escape(value)].join(' >= ');
});
```

**Comment by BridgeAR** [comment]
@mickhansen I like that idea. I think it's a good short hand solution in a couple of edge cases. I would not use that internal though and would not want to expose the function to the user and instead wrap it into an add operator function.

Question is thought what do we do if the operator already exist and is not the same? I'd throw but we'll need another function to remove the operator in that case.

Adding / removing a operator could look like:

sequelize.addOperator('$gt', ' >= ');
sequelize.removeOperator('$gt');

**Comment by mickhansen** [comment]
@BridgeAR To me it only makes sense if we use it both internally and externally, and i'd just let users overwrite operators if the key is duplicate.

**Comment by mickhansen** [comment]
Using it internally ensures that it's stable, and exposing it helps users and plugin authors that might offer advanced functionality (like subquery lookups).

**Comment by BridgeAR** [comment]
@mickhansen using it internally is fine, true. But letting the users overwrite an operator is calling for trouble. Just think about two people working on a bigger project each dealing with a special case and nameing a operator just the same as the other but with different logic. And I also think that altering the build in operators is not a good idea.
Exposing might be fine if you provide a warning to be careful while using that function. I can imagine that some people might come up with some "interesting" ideas otherwise ^^.

**Comment by mickhansen** [comment]
@BridgeAR The entire point is to allow external users to add and change operators, otherwise the feature would be pretty useless. The point was to let users implement obscure or missing operators that they might need, say we didn't have JSONB support yet, this feature would have let people use it might faster.

Any developer should know the dangers to overloading in any case.

**Comment by janmeier** [comment]
I'm all for - and I think it should also be used internally.

As for overloading, I think thats fine - Add a warning and a flag to let the user silence the warning

**Comment by mbroadst** [comment]
yeah I don't understand why you -wouldn't- use it internally, eat your own dog food and all that

**Comment by mickhansen** [comment]
It should definitely be used internally - my point was there was no point in making this (imo) if we didn't also expose it.

(did i ever make the point that it should not be used internally? :D)

**Comment by overlookmotel** [comment]
Sounds great to me!

**Comment by janmeier** [comment]
Perhaps this could also be extended to pluggable updaters. I.e. `update({ $foo: 'bar' })`. This could be used for https://github.com/sequelize/sequelize/issues/4644 and https://github.com/sequelize/sequelize/issues/4387

**Comment by mickhansen** [comment]
@janmeier that would be great, let's work out an API.

**Comment by overlookmotel** [comment]
I'm not sure if this is within the scope of what you're talking about here but...

On problem I keep running up against is not being able to compare a field's value to another field's value in a where clause.

For example, in SQL:

```
SELECT *
FROM documents
INNER JOIN documentVersions ON documentVersions.documentId = documents.id
    AND documentVersions.revision = documents.latestRevision
```

In this case `documentVersions.revision` and `documents.latestRevision` are integers which count upwards from 1 **for each document**. i.e.:

* Each `document` has many `documentVersion`s
* The first document version has `revision` = 1
* The next version of the same document `revision` = 2 (etc)
* Another document also has `revision` = 1, 2, 3 etc
* `(documentId, revision)` is a unique key on `documentVersion`

In order to achieve this in Sequelize, it would (I think) need a syntax something like:

```js
Document.findAll( {
    include: {
        model: DocumentVersion,
        where: {
            revision: Sequelize.field('latestRevision')
        }
    }
} )
```

or...

```js
Document.findAll( {
    include: DocumentVersion,
    where: {
        latestRevision: Sequelize.field(DocumentVersion, 'revision')
    }
} )
```

Or is this already possible? Maybe through some cunning use of scopes?

**Comment by mickhansen** [comment]
@overlookmotel I actually just added basic support for that: https://github.com/sequelize/sequelize/commit/825eb75f31e71a242477a16e9a593ffc4519cd84

But yeah, a big problem is that we need to support all cases and be very generic. It would be great if the user had the option of just working around us (they generally only have a single dialect)
