### ISSUE TITLE
could I discard unwanted column in a query?

### ISSUE THREAD

**Issue by superlbr** [sequelize/sequelize#4072]
Usually,a query will return the results with all columns in a model,so as the question mentioned. 
Or does sequelize support views in mysql?

**Comment by janmeier** [comment]
`findAll({ attributes: ['id', 'name', etc ] })` http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-promisearrayinstance

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
