### ISSUE TITLE
Make ValidationErrorItem 'type' property more specific

### ISSUE THREAD

**Issue by Jake0oo0** [sequelize/sequelize#4079]
Currently, the 'type' property of validation errors returns "Validation Error". This is very broad, and could be made more specific by using the type of validation that failed such as `numeric` or `length`. 

We could also be able to set our own types for fields, especially on custom validations.

Take this for example

``` js
{ [SequelizeValidationError: Validation error: Validation isNumeric failed,
Validation error: Name already in use!]
  name: 'SequelizeValidationError',
  message: 'Validation error: Validation isNumeric failed,\nValidation error: Name already in use!',
  errors: 
   [ { message: 'Validation isNumeric failed',
       type: 'Validation error',
       path: 'port',
       value: 'Validation isNumeric failed',
       __raw: 'Validation isNumeric failed' },
     { message: 'Name already in use!',
       type: 'Validation error',
       path: 'name',
       value: [Object],
       __raw: [Object] } ] }
```

The raw Objects are irrelevant, but the point is that the `type` property is the same, and could be set to something more specific like `numeric`, which is already set in the value property, except that it's wrapped in more text.

**Comment by janmeier** [comment]
Agreed, that would make sense. The relevant part of the code should be around here https://github.com/sequelize/sequelize/blob/master/lib/instance-validator.js#L413

**Comment by Joanne16** [comment]
Any news on this feature request ? We need such an option for our project also to be able to display appropriate error messages.

It would be nice also,if the validation error could specify if it is a 'minimum/maximum' length error when "len:[]" validation is used.

**Comment by mickhansen** [comment]
@Joanne16 Open feature requests without comments generally don't have news i'm afraid.

**Comment by Joanne16** [comment]
@mickhansen Thanks for the reply. I just wanted to know if this feature will be added to a future release or if there is another way to get more details on the validation error that is raised by sequelize.

Thanks

**Comment by mickhansen** [comment]
@Joanne16 No one is working it as far as i know. We do welcome contributions, especially from people who work with the validations daily.

**Comment by Joanne16** [comment]
@mickhansen Alright, no worries. Do you have a guide somewhere on how to contribute to sequelize ?

Thanks

**Comment by Jake0oo0** [comment]
[CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)

**Comment by iamjochem** [comment]
hi there,

Any movement on this issue. In my use case I am trying to marshal valiation error data/info to a clientside app in such a way that it can recognize not only the instance (& attribute) that the error relates to but also the "name" of the validation and (where applicable) the parameters/arguments used for the validation - I want all this info so that I can find the relevant component and data in the clientside (React app) and so that I can generate a suitable user-friendly error message - default/standard sequelize messages are rather cryptic (not very helpful for "normal users") and the users' client-side language may not correspond with language setting that is in effect in various micro-services on the server.

I think the `type` attribute is useless in it's current form, I think that `type` should contain the name of the validation (as given/found in the model/attribute definition) - this could obviously refer to a built-in or specify something custom. given that such a change is likely to be a breaking change it might be better to define a new attribute for ValidationErrorItem, e.g. `validator_name`. In the example output above "**isNumeric**" is the `validator_name` ... it is available at error instance creation but not accessible  as an explicit error object attribute (technically it is possible to extract such information from the error message but that is brittle and there is no garantee of getting a default sequelize error message from which to extract such info).

ValidationErrorItem should also be entended to also capture the instance that triggered the error AND the validator function parameters/arguments that were used to run the [failing] validator (I am of the opinion that the validator args/params are required in order to generate a really user-friendly error message - "X is too long" is less helpful than say "X is too long, max 64 chars allowed.")

given these musings I would like to suggest that ValidationErrorItem gets the following extra, optional attributes:

      - `validator_name`    - name of the validator object property as specified in the model/attribute definition
      - `validator_args`      - array of parameters used to call the validator function with (again as specified in the model/attribute definition)
      - `instance`               - a sequelize DAO instance to which the error relates

I need this and would like to bake PR, do you guys think this has validity?

**Comment by iamjochem** [comment]
I have been looking a little harder at the `type` parameter of `ValidationErrorItem`, the possible values according to the source are:

- "notNull Violation"
- "string violation"
- "Validation error"
- "unique violation"

these are all the current values I have found (as strings) in various places in the source (including dialect specific code),  given that these are arbitrary strings it is not a good idea to rely on them.

I feed that values for `ValidationErrorItem.type` should be pre-defined, a list of valid constant values that are officially exposed somewhere in the Sequelize API. 

AFAICT there are effectively 3 different "types" of error item:

1. "**core**" - covers any validation error that relates standard model/attrib properties (e.g. whether an attrib is nullable or not) , this includes the not null & string-type check
2. "**db**"- covers any validation error that is triggered by the DB itself, most notably FK/PK contraint violations
3. "**validation**" - convers any validation error triggered by a specifically defined model/attrib validation rule/function (applies to both built-in and custom validators!)

I'm interested to know your opinion(s)! do you even agree there is room for improvement with regard to the usage/interface of `ValidationErrorItem`?
