### ISSUE TITLE
Delete with 1=1

### ISSUE THREAD

**Issue by festo** [sequelize/sequelize#4091]
Today I ran into a big issue, my delete query was look like this:
```
HashtagSubscribe.destroy({where: params}).then(function(result){
  // Success handler ...
})
```
And the following SQL generated:
```
DELETE FROM "hashtag_subscribe" WHERE 1=1
```
Yes, it dropped everything from `hashtag_subscribe` table, fortunately the app is in development state...

I printed out the `params` value and it looks like everything is correct:
```
sails.log.debug({where: params});
// Result
// debug: { where: { hashtag: '蘋果', userId: 1 } }
```

It took me long time to find out what is the problem: I use ProtoBuffer for communication with the clients and I use the decoded proto object as `params`. It looks like the original one, but there is some additional function in their prototype and the Sequelize abstract query builder is checked the object is a plain object:
https://github.com/sequelize/sequelize/blob/3.0/lib/dialects/abstract/query-generator.js#L1986

**My suggestion**
Never replace `WHERE` parameters in `DELETE` query with `1=1` if the `smth` is none of the recognised type. Instead of this, throw an error!

**Comment by janmeier** [comment]
Agreeed, this is a rather unfortunate issue. With that being said, I believe only very few users will experience it, since most will just pass plain objects.

I still believe we should fix this, to prevent users from loosing data. [This line](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1963) should probably add a check that where has the expected structure (Array, plainObject or an object with `_isSequelizeMethod === true`)

Same applies for update
