### ISSUE TITLE
How to define bidirectional references

### ISSUE THREAD

**Issue by nkt** [sequelize/sequelize#4094]
In my project I have two entities: `cafe` and `city`. Cafe must reference to city, but city also could reference to cafe (top cafes).
```js
// city.js
const City = sequelize.define('City', {
    top_cafe: {
      type: DataTypes.INTEGER,
      references: {
        model: sequelize.model('Cafe')
      }
    }
};

// cafe.js
const Cafe = sequelize.define('Cafe', {
    city_id: {
      type: DataTypes.INTEGER,
      allowNull: false
      references: {
        model: sequelize.model('City')
      }
    }
};
```
As you can guess, I've got `Cafe has not been defined`.
You can suggest me to add `top_cafe` into `Cafe` as `is_top`, but it's impossible cause in my project there are 5 fields for top, I mean (top_cafe1, top_cafe2, etc.).

**Comment by janmeier** [comment]
You can pass a string instead `model: 'Cafe'`

If you create the associations with sequelize, references constraints will be added as well 

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by nkt** [comment]
@janmeier thanks for fast answer! I've thought this is a bug.
