### ISSUE TITLE
Unclear how to count associated models

### ISSUE THREAD

**Issue by kenkouot** [sequelize/sequelize#4147]
I have two tables, `groups` and `users`. I have a query for `groups` that includes associated user models. I'm trying to count the # of users associated with a group as follows:
```js
  Group
   .findAll({
     // TODO: This doesn't actually return the correct count of members in a group yet...
     attributes: ['id', 'name', [sequelize.fn('COUNT', sequelize.col('users.groupId')), 'userCount']],
     include: [{
       model: User,
       attributes: []
     }],
     group: ['users.id', 'group.id']
   })
```

This produces this sample set:
```sql
 id |       name        | userCount
----+-------------------+-----------
  4 | sshfsjaf          |         0
  1 | default           |         1
  5 | fsadfsadasasaaaaf |         0
  1 | default           |         1
  7 | sdafsdfsadfsdaf   |         1
  1 | default           |         1
  1 | default           |         1
  1 | default           |         1
  6 | fdsssaf           |         0
  2 | string            |         0
```

How do I form the subquery/aggregate function so that `userCount` properly reflects total number of users per unique group?

**Comment by kenkouot** [comment]
I should also note that, as it stands, I'm required to have both `users.id` & `group.id` in the GROUP BY field.

**Comment by janmeier** [comment]
This should do the trick

```js
  return Group
   .findAll({
     // TODO: This doesn't actually return the correct count of members in a group yet...
     attributes: ['id', [sequelize.fn('COUNT', sequelize.col('users.id')), 'userCount']],
     include: [{
       model: User,
       attributes: []
     }],
     group: ['group.id']
   })
```

First group the rows by group, then count the number of users in each group.

The reason you are seeing `x must appear in ...` is a postgres technicality - you can't aggregate (join multiple rows) without making a descision about what should happen when a column has multile differnet values. Most other DBs just hide this, and make the choice for you :)

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
