### ISSUE TITLE
addAssociation now returning arrays

### ISSUE THREAD

**Issue by simonstre** [sequelize/sequelize#4148]
I have this association:

    Team.Players = Team.belongsToMany User, {as: 'Players', through: TeamPlayer}

In 3.2.0, I could do:

          team.addPlayer( player.id, {position: position} )
          .then ( teamPlayer ) ->
            console.log(JSON.stringify(teamPlayer)) # { "TeamId": 1, "UserId": 2, "position": "C"}

and retrieve my association attributes.

But in 3.4.1, when I do

          team.addPlayer( player.id, {position: position} )
          .then ( teamPlayer ) ->
            console.log(JSON.stringify(teamPlayer)) # [[{"position":"C","UserId":2,"TeamId":1}]]

I receive my association attributes in two arrays.

Is that a regression? Thank you.

**Comment by janmeier** [comment]
The return value for addAssociation has never been formally specified, so I wouldn't count this as a regression. The reason you are seeing this is that we changed it to work more directly on the join table. The result you get back is that of calling `bulkCreate` on the join table.

We did this change (https://github.com/sequelize/sequelize/pull/3929) for performance reasons - we no longer load all the currently attached entries to check if something is already associated.

If you need to access the player, you can do: 
```js
team.addPlayer( player.id, {position: position} ).return(player) .then ( teamPlayer ) ->
```

**Comment by simonstre** [comment]
Ok, thank you for the details!

**Comment by mdarveau** [comment]
Hi @janmeier,

I understand this is not a regression and that it make sense that addXXX return an array since associations can be added in bulk. However, I don't understand why it's an array in an array. `bulkCreate` return an array of instance AFAIK.

Do you think it would be a good idea to formalize the contract so addXXX return the added model+join attributes when only one associated object. And return an array of model+join attributes when multiple associated objects are added.

Consider the following relation:
```League.Substitutes = League.belongsToMany User, {as: 'Substitutes', through: LeagueSubstitute}```

Without the old behavior, I need to execute an additional roundtrip to the database to get the just added object:
```
league.addSubstitute( player.id, {favorite: favorite ? false } )
.then ->
  league.getSubstitutes( {where: {id: player.id}} )
.then (substitutes) ->
  substitute = substitutes[0]
  console.log "substitute: #{JSON.stringify(substitute, null, '  ')}"
```

You said that we could `team.addPlayer( player.id, {position: position} ).return(player).then(teamPlayer) ->` but I don't understand how this could work.

Thanks a lot!

**Comment by janmeier** [comment]
The reason we return two arrays is that we run both bulkCreate and bulkUpdate - for associations that already exist, we still update the join table attributes. So the first array is the bulkcreate result, and the second is bulkupdate. 
We could just return the bulkCreate result, but I'm, not sure that would be such a good idea. If I call `add([notAssociated, alreadyAssociated])` the array will only contain `notAssociated`, because `alreadyAssociated` was run through bulkupdate instead - so its not clear for the user how many rows will be returned. Bulk update does not return rows (except for postgres), so when we are updating, there is no way for us to get those rows, except for an additional query. And there is no reason to run that if were not sure the user needs it.

> You said that we could team.addPlayer( player.id, {position: position} ).return(player).then(teamPlayer) -> but I don't understand how this could work.

Yeah, I misspoke - you can get the `player` object that way, but not the `teamPlayer`
