### ISSUE TITLE
Best Paractice: DB Sync + Migrations? Or just Migrations?

### ISSUE THREAD

**Issue by duro** [sequelize/sequelize#4160]
I am trying to setup a best practice for my team. I look at the overlap between sync and migrations and I have some concerns about having them both integrated into the app.

Can anyone speak to this? Will I better off just forcing everyone to make all DB alterations, even new table creations, with Migrations?

Or is anyone happily using them together with no difficulty? 

We have sizable team and the scope of the project will be on the large side. So I want to set the precedent early on.

Thanks

**Comment by duro** [comment]
One more thing that I just found out is that Django, which has a similar syncdb command, and migrations layer (South), recently recommended that you stop using the syncdb command, and only use migrations. This seems to me like it might be leaning more in that direction.

**Comment by mickhansen** [comment]
I would suggest migrations. I personally only use migrations in production, i do use sync for local development and testing though.

**Comment by janmeier** [comment]
Migrations are definitely the recommendation for production code

**Comment by kitakoj18** [comment]
Can someone kindly explain why not to use sync() to initialize the database and the tables within it, and then after that use migrations for any changes that need to be made to a table? I'm trying to go off of @smallbee3 [article](https://medium.com/@smallbee/how-to-use-sequelize-sync-without-difficulties-4645a8d96841) but I still don't understand why a process like this would be an issue

**Comment by papb** [comment]
Hi @kitakoj18, I don't see any issue at all, in fact you described exactly what I did recently and what I would suggest people to do. We will have a major overhaul of all documentation manuals in which all of this and more will be better explained.

**Comment by smallbee3** [comment]
Hello @kitakoj18
The process you mentioned( Use "sequelize.sync()" during development -> Use "sequelize db:migrate" in production mode) has no problem at all as papb said above.

The article that I wrote in Medium is only for certain cases. For example, you might want to build the database from the scratch without dumping/loading the data of the production database. Testing would be such a case because you don't want to dump all the data into your testing database which will be destroyed after the test. Then, you need further works as I explained in the post ("faking migration by inserting data with raw SQL", "generating migration scripts for all models." or "using the raw sql queries created by ‘sync()’")

**Comment by kitakoj18** [comment]
Awesome! Thank you both @papb and @smallbee3!
