### ISSUE TITLE
Using hooks in associations

### ISSUE THREAD

**Issue by pola88** [sequelize/sequelize#4182]
Hi guys,

I have a model that belongs to another one, when I retrieve the object with 'find' including the association, the hooks of the second model is not run, is there a way to do it?

E.g.
```
FirstModel.find({ include: [ model: SecondModel, as: 'second_model' ]})
```
It's in Postgres, 
Sequelize Version 3.2.0

Thanks,
PoLa

**Comment by janmeier** [comment]
Are you refering to before/after find hooks? Nope, thats not possible. You could theoretically do it yourself in the hook for FirstModel though, by looping through options.include ;)

**Comment by pola88** [comment]
Yes, I was talking about those hooks.
I know if I do ```firstModel.getSecondModels()``` , this calls the hooks of SecondModels, I thought if there was an option that does the same with include option.

**Comment by janmeier** [comment]
Nope, no option like that exists. I'm not sure it would be a good idea either :). 

Generally our hooks are invoked before and after calling a function. A before find is run before calling find. If we begin to invoke  `modelX.beforeFind`, without the user having called `find` on `modelX`, but because `modelX` was included with `modelY` I think the abstraction we have now breaks down.

One could argue, that something similar happens with `individualHooks` in update / destroy, but I don't think these are quite similar.

What exactly are you doing in the `beforeFind` hook that you also want to do on includes? Perhaps it could be solved with a (default)scope instead?

This would be solved by `include.seperate` though - which calls find on the individual models instead of joining :)

**Comment by janmeier** [comment]
Closing, no response

**Comment by PatrickGeyer** [comment]
Hi @janmeier , what about when it's a 1:1 relationship where 'separate' is not allowed.
