### ISSUE TITLE
Question regarding associations

### ISSUE THREAD

**Issue by bloodhawk** [sequelize/sequelize#4184]
Does anyone know a way to represent a many to many relationship within sequelize that also has a one to many, which also has a one to many relationship? This is not the actual data from my project but for example it would be:

Users hasMany Projects , 
Projects hasMany Users, 
ProjectUsers (junction table) hasMany otherThings, 
otherThings has many otherThings1
otherThings belongsTo Users
otherThings1 belongsTo Users

**otherThings and otherThings1 are specific to the relationship between the user and project.

I want to structure this in the best way that will take advantage of the helper methods.
Thanks for any assistance.

**Comment by janmeier** [comment]
If you want to be able to load Users, Projects and Otherthings in one go you'd need to setup direct relations between user and projectusers yourself:

```js
User.hasMany(ProjectUsers);
ProjectUsers.hasMany(OtherThings)

 User.findAll({
  include: [
    { model: ProjectUsers, include: [OtherThings] } 
  ]
}).then(function (users) {
  users[0].projectusers[0].otherthings[0].someAttribute
});
```

If you need to access project directly from users you can also setup a belongs to many alongside:

```js
User.belongsToMany(Project, { through: ProjectUsers });

user.getProjects();
```

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
