### ISSUE TITLE
Case insensitive matching?

### ISSUE THREAD

**Issue by bishtawi** [sequelize/sequelize#4227]
Is it possible to make this query using sequelize (without just using the raw sql statement obviously)?
````
SELECT *
FROM mytable
WHERE UPPER(name) = 'SOME INPUT STRING'
````

I know sequelize provides the sequelize.fn() ability but can I use it on a column in the where clause?

**Comment by janmeier** [comment]
Duplicate of https://github.com/sequelize/sequelize/issues/1529#issuecomment-126409547

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
