### ISSUE TITLE
updatedAt not updating on save

### ISSUE THREAD

**Issue by chronotc** [sequelize/sequelize#4230]
In 3.5, when I alter ```instance.name = 'Bob'``` and call ```instance.save()```, the ```updatedAt``` is no longer updating. Is this the expected behaviour as this operation was previously working on 3.4

**Comment by janmeier** [comment]
This seems to work fine for me - can you show an example (model defintion + code)

The only exception is if the name was already Bob - in that case the instance won't be updated at all

**Comment by gcatto** [comment]
Related to this: is there an easy way to force an update to updatedAt? I have a basic inheritance setup where the timestamps are in the table for the superclass, where I'd like to change its updatedAt even if nothing in the superclass's table changed (i.e., only stuff in the sub-class's table changed).

**Comment by janmeier** [comment]
@gcatto `instance.changed('updatedAt', true)` will mark the `updatedAt` column as dirty so it will be updated

**Comment by gcatto** [comment]
Perfect, thanks kindly!

**Comment by janmeier** [comment]
Closing, no response from OP

**Comment by tonytamps** [comment]
Sorry for thread necromancy, but just incase someone else is coming across this issue...

Sequelize (before version 3.5.0) would trigger a change on the `updatedAt` field regardless of what data was changed. So if we set `model.nonExistantField = 'lol';` then `model.save()`, this would change the `model.updatedAt` but cause no actual update.

Since 3.5.0, setting a field on the model that doesn't exist will not trigger a change to the `model.updatedAt`.

This is the issue OP was having, he is a colleague.
