### ISSUE TITLE
bulkCreate - performance for large data set

### ISSUE THREAD

**Issue by samsfisher** [sequelize/sequelize#4247]
Hi

I have a reset routine for a PostGres DB. i am trying to create 20000+ entries using bulkCreate with a JSOn object. however, it is taking insane amount of time to add those records to the DB. When i tried with 2000 records it is fast. What is the limitation of BulkCreate ? how do i design for a mass upload event..

THanks

**Comment by janmeier** [comment]
The reason 10 times more entries take more than 10 times the time is probably because you hit a memory limit.

A big reason for bulkcreate being heavy is this piece of code I would guess https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1994-L1996

For each row you pass, it builds a new instance, just like you would with `.create`. Why you might ask? Because we support validation, hooks and getter methods in bulk create.

For cases as big as yours, a `raw: true` flag might be beneficial, which just takes the data passed as-is and inserts that

**Comment by mrgamer** [comment]
I am fighting with the same issue, bulkCreate hangs on creating objects, even with disconnected database (it's not the remote connection that hangs)

Creating the bulkCreate promise takes minutes, seems like some huge loop

**Comment by sushantdhiman** [comment]
**master** branch performance status

```bash
bulkCreate#100000 x 0.10 ops/sec ±3.72% (5 runs sampled) (mean 9.9011s)
bulkCreate#10000 x 0.96 ops/sec ±5.72% (9 runs sampled) (mean 1.0363128888888888s)
bulkCreate#1500 x 4.81 ops/sec ±11.37% (28 runs sampled) (mean 0.2079707857142857s)
```

**Comment by yjwong** [comment]
I did some profiling after stumbling upon this issue when creating 150k+ rows in a single `bulkCreate` call. Memory doesn't seem like an issue, the node process is taking up just 190 MB while consuming 100% of a CPU core.

It seems like one part of `bulkInsertQuery` is taking > O(n) time, which I suspect are lines 241-248: https://github.com/sequelize/sequelize/blob/1f8348fbf42ff5991ee7d70296f92814b8255344/lib/dialects/abstract/query-generator.js#L241

Will do a little more digging to see what I can find.

**Comment by sushantdhiman** [comment]
Fixed In https://github.com/sequelize/sequelize/pull/7391

**Comment by basantzimyo** [comment]
> 

> 

> [``](_**### 

> url

**_)
