### ISSUE TITLE
Build diagram from sequelize models

### ISSUE THREAD

**Issue by gebrits** [sequelize/sequelize#4251]
I'm getting on a project with over 100 models defined through sequelize. For some unclear reason there's no good overview of the models and relations. 

I wondered if any sub project exists that, given sourcecode of sequelize, can generate a nice ER-diagram or something?

**Comment by DanMMX** [comment]
You can generate diagrams with MySQL Workbench, obviously you'll need to define all your settings to use with MySQL. Also, there are some cases, like `constraints: false` that wouldn't be linked at all in your tables. For the rest, I widely recommend [Workbench](https://www.mysql.com/products/workbench/)

**Comment by janmeier** [comment]
I've never heard of a project that can do that, my advice would also be mysql workbench or similar

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
