### ISSUE TITLE
SQLite: finding fails on trying to fetch virtual attributes

### ISSUE THREAD

**Issue by soletan** [sequelize/sequelize#4256]
Testing with Sequelize 3.5.1 und sqlite3 3.0.9 I encountered issue on trying to find instances of model containing virtual attributes. Test file was this:

```javascript
var sequelize = require( "sequelize" );
var path = require( "path" );


var link = new sequelize( "default", null, null, { dialect: "sqlite", storage: path.join( __dirname, "test.sqlite" ) } );

var test = link.define( "Test", {

	id: {
		type: sequelize.INTEGER,
		autoIncrement: true,
		primaryKey: true
	},

	actual: {
		type: sequelize.STRING
	},

	virtual: {
		type: sequelize.VIRTUAL,
		get: function() {
			return this.getDataValue( "actual" ).toUpperCase();
		}
	}

} );

link.sync()
	.then( function() {
		return test.findAll( { attributes: [ "actual", "virtual" ] } )
	} )
	.then( function() {
		console.log( "hooray!" );
	} )
	.catch( function( cause ) {
		console.dir( cause );
	} );
```

This file renders this output:

```
Executing (default): CREATE TABLE IF NOT EXISTS `Tests` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `actual` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`Tests`)
Executing (default): SELECT `actual`, `virtual` FROM `Tests` AS `Test`;
{ [SequelizeDatabaseError: SQLITE_ERROR: no such column: virtual]
  name: 'SequelizeDatabaseError',
  message: 'SQLITE_ERROR: no such column: virtual',
  parent: 
   { [Error: SQLITE_ERROR: no such column: virtual]
     errno: 1,
     code: 'SQLITE_ERROR',
     sql: 'SELECT `actual`, `virtual` FROM `Tests` AS `Test`;' },
  original: 
   { [Error: SQLITE_ERROR: no such column: virtual]
     errno: 1,
     code: 'SQLITE_ERROR',
     sql: 'SELECT `actual`, `virtual` FROM `Tests` AS `Test`;' },
  sql: 'SELECT `actual`, `virtual` FROM `Tests` AS `Test`;' }
```

As far as I understand ORM model-consuming code shouldn't need to take care of attributes being virtual or not. So, IMHO this is a bug. If you don't agree in this you might consider this a feature request. ;)

**Comment by eventhough** [comment]
I am getting the same error when I try to select a virtual column. I guess it makes sense that the DB should complain because these aren't "real" columns. I feel like Sequelize should be smart enough to know how to select a virtual column but that would require knowing exactly which columns are used to create the virtual column result.

For example, I changed the `name` column in my users table and broke it into `firstName` and `lastName`. Then I created a virtual column called `name` which just concatenates the first name and last name together:

```javascript
    firstName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    lastName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    name: {
      type: DataTypes.VIRTUAL,
      get: function() {
        return this.getDataValue('firstName') + ' ' + this.getDataValue('lastName');
      },
    },
```

This broke my code all over the place because `name` is not a real column in the db. If you want to use the `name` virtual column you have to make sure `firstName` and `lastName` are included in attributes otherwise you get something like `undefined undefined` for name.

I feel like this would be very hard to do.

**Comment by soletan** [comment]
I basically agree. Maybe it would help putting attributes on virtual columns indicating dependencies of virtual column. Otherwise using `getDataValue()` might fetch either real column unless it has been cached before. So the problem would be limited to poor performance in case of selecting a bunch of rows all requiring to fetch `firstName` and `lastName` individually on every column. And this performance issue might be handled by simply knowing the code and ensuring to include `firstName` and `lastName` so `getDataValue()` might operate on those cached fields.

**Comment by mickhansen** [comment]
I've on my personal todo to let the VIRTUAL type contain info of dependency fields and the return type. I need it for graphql stuff.

**Comment by janmeier** [comment]
Dependent types for virtuals have been implemented  http://docs.sequelizejs.com/en/latest/api/datatypes/#virtual
