### ISSUE TITLE
targetKey not working as expected with custom data types.

### ISSUE THREAD

**Issue by JrSchild** [sequelize/sequelize#4264]
The targetKey option doesn't seem to work with custom data types. Am I missing anything or is this a bug? Example code below. [Or pull my repo](https://github.com/JrSchild/sequelize-targetKey)

```js
var Sequelize = require('sequelize');
var config = require('../config.json');

var sequelize = new Sequelize(config.database, config.user, config.password, {
  host: config.host,
  port: config.port
});

var Trigger = sequelize.define('Trigger', {
  hash: {
    type: Sequelize.STRING(40),
    allowNull: false
  }
});
var TriggerLog = sequelize.define('TriggerLog');

Trigger.hasMany(TriggerLog, {foreignKey: {name: 'hash', type: Sequelize.STRING(40)}});
TriggerLog.belongsTo(Trigger, {foreignKey: {name: 'hash', type: Sequelize.STRING(40)}, targetKey: 'hash'});

sequelize.sync({force: true});
```

The query that fails sets the wrong `REFERENCES` of the foreign key to id rather than hash.
```sql
CREATE TABLE IF NOT EXISTS `triggerlogs` 
  ( 
     `id`        INTEGER NOT NULL auto_increment, 
     `createdat` DATETIME NOT NULL, 
     `updatedat` DATETIME NOT NULL, 
     `hash`      VARCHAR(40), 
     PRIMARY KEY (`id`), 
     FOREIGN KEY (`hash`) REFERENCES `triggers` (`id`) ON DELETE SET NULL ON 
     UPDATE CASCADE 
  ) 
engine=innodb; 
```
The error message is
```
SequelizeDatabaseError: ER_CANT_CREATE_TABLE: Can't create table 'sequelize.test.TriggerLogs' (errno: 150)
```

**Comment by janmeier** [comment]
Hmm, the test would seem to suggest that we only actually test this for tables without primary key (note how id is being removed). This should definitely work in the regular case as well :)
https://github.com/sequelize/sequelize/blob/master/test/integration/associations/belongs-to.test.js#L619

Tagging this as a bug. As a quick-fix I think you can set `constraints: false`, since all other code but the constraints one seems to handle `targetKey` fine

Do note however, that targetKey is only implemeneted for belongsto and belongstomany so far

**Comment by JrSchild** [comment]
Hi Jan,

Thanks, your quickfix indeed did the job for now.

**Comment by vcasadei** [comment]
I'm also having problems with this. And the constrains fix did no work.

**Comment by mickhansen** [comment]
Maybe fixed by https://github.com/sequelize/sequelize/commit/9d08b583d4fdcaacd87679e7ca61f066b5feb7b3 assuming  `hash` is a unique.
