### ISSUE TITLE
How to get the current year only?

### ISSUE THREAD

**Issue by abhinav76** [sequelize/sequelize#4277]
I can get the current datetime by NOW function of sequelize but i want just the current year.
is there any way i can do that or any way through which i can split the date to year month and day?

**Comment by janmeier** [comment]
Do you want the current year to use as a default value, or how do you want to use it? You should able to use sequelize.fn (the example below is for mysql, but you should be able to find something similar for pg)

```js
sequelize.fn('YEAR', sequelize.fn('CURDATE'))
```

**Comment by abhinav76** [comment]
I'm using <code>defaultValue:NOW</code>. but i just want the current year
and also can you tell me the way to split current date
Actually I want to convert 2015-09-08 08:09:07 to 2015090807080909 BIGINT 
so trying to figure out that

**Comment by janmeier** [comment]
Well `defaultValue: sequelize.fn('YEAR', sequelize.fn('CURDATE'))` should work fine then

Perhaps toString and remove -, : and spaces? 

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
