### ISSUE TITLE
Take entity in browser

### ISSUE THREAD

**Issue by mhf-ir** [sequelize/sequelize#4312]
Can i build my entity in browser? with all validation.
Send serialize of my entity to server server recheck and store ... or even better for response i send server JSON serialize to client and client build the entity not the just simple JSON.
I cant find it any documentation about it

**Comment by janmeier** [comment]
If you can get sequelize and all its modules to run in the browser, then yes - but probably no :)

You could store your model validation functions in seperate files and import that in the browser to run the validations that way. validator.js https://github.com/chriso/validator.js should run fine in the browser as well

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
