### ISSUE TITLE
SQLServer datetime insert error

### ISSUE THREAD

**Issue by diegomesata** [sequelize/sequelize#4319]
Hello, in the model I got: 
/////
Birthday: {
      type: DataTypes.DATE,
      allowNull: false,
      primaryKey: 'false'
    },

When I tried to create a new object in the db, the sql insert code generated by sequelize
 is: 

INSERT INTO .... '2015-08-13 18:31:45.000 +00:00'

The object is not inserted. That datetime format is not compatible with sqlserver.

I tried with: 

myobj.Birthday = new Date();

and 

myobj.Birthday = moment().format("YYYY-MM-DD");

But always I got a string like this: '2015-08-13 00:00:00.000 +00:00'

What could I do?

Thank you

**Comment by janmeier** [comment]
Are you trying to work with an existing schema, or one created by sequelize? Which sql server version are you using?

That format is supposed to work with `DATETIME2`, and works fine in tests - what type is your column? 

Might be related to https://github.com/sequelize/sequelize/issues/3892

This can be fixed with https://github.com/sequelize/sequelize/pull/4186 which would allow you to custome the date format for mssql

**Comment by diegomesata** [comment]
I'm working with an existing schema, the version is SqlServer 2014, the model was generated with sequelize-auto.

I changed the schema from datatime to datetime2 and it worked fine. Thank you.

Only one thing, if the schema is datetime and you create the object, the sql insert is written in the log but it will never thrown error, the program seems to stay in an infinite cycle.

**Comment by janmeier** [comment]
Hmm, that sounds weird - If you can create a test that reproduces the issue and post it as a PR / in a separate issue i'll be happy to take a look
