### ISSUE TITLE
Question: how to: where lower(ColumnFoo) = "value"

### ISSUE THREAD

**Issue by User4martin** [sequelize/sequelize#4322]
It is NOT possible to write the actual sql.
```
     where: {     'lower(name)':  'foo'  }
```
That leads to
```
  where "tablealias"."lower(name)" = 'foo'
```

Is there an official way?

also what if 2 column need to be compared? "where colFoo < colBar" ?

**Comment by janmeier** [comment]
`where: sequelize.where(sequelize.fn('lower', sequelize.col('name')), 'foo')`

`where: sequelize.where(sequelize.col('name'), 'foo', '<')`

And if you want ot combine them

```js
where: { $and: [
  sequelize.where(sequelize.fn('lower', sequelize.col('name')), 'foo'),
  sequelize.where(sequelize.col('name'), 'foo', '<')
]}
```

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by AlamTheInnov** [comment]
If someone is still looking for it in 2023 ;)

```
const users = await models.User.findAndCountAll({
            where: {
                role: role,
                where: sequelize.where(sequelize.fn('lower', sequelize.col('fullName')), {
                    [sequelize.Op.like]: `${req.body.keyword.trim().toLowerCase()}%`
                }),
            }
));
```

**Comment by andresWeitzel** [comment]
This option is the most optimal. In the case of applying the sequelize lower format, it is not necessary to convert the parameter to be compared. It could also be summarized as the following...

```js
const { User } = require("../../models/sequelize/user");
const { Op, Sequelize } = require("sequelize");

const users =  await User.findAll({
        attributes: {},
        where:
          Sequelize.where(Sequelize.fn('lower', Sequelize.col('colExample')), {
            [Op.like]: `%${parameterExample}%`
          }),
 })
....
```
