### ISSUE TITLE
MSSQL query generator uses OFFSET FETCH clause only supported in SQL Server 2012 and up

### ISSUE THREAD

**Issue by treythomas123** [sequelize/sequelize#4404]
The query generator uses an OFFSET FETCH clause to apply the offset and limit parameters, which works fine in SQL Server 2012 and newer, but is unsupported in older versions of SQL Server.

[Link to relevant code](https://github.com/sequelize/sequelize/blob/88217aea7ec6380739697de89dba2a830ada19ea/lib/dialects/mssql/query-generator.js#L586-L599)

I found this when I tried to use `findById` against an SQL Server 2008 R2 database. The server came back with this error message:

    Invalid usage of the option NEXT in the FETCH statement.

Looking at the code, it looks like this will also happen when using `findOne`, or when the `offset` or `limit` options are used in a `findAll`, `findAndCount`, etc.

So the `offset` and `limit` functionality should either be changed to use a syntax supported by all SQL Server versions, or there should be logic to fall back to an old method when a version before 2012 is detected. Or the docs could be updated to specify that only versions newer than 2012 are supported.

**Comment by janmeier** [comment]
We do have the functionality for conditionally changing syntax based on db version, see e.https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L253

Pull request with functionality for older versions would be welcome.

However, I guess the syntax is more terse for older versions?

**Comment by treythomas123** [comment]
Thanks for the link @janmeier. Will work on a pull request if my team ends up using Sequelize for our project.

**Comment by jacobbridges** [comment]
I found this same issue today. But so far I only get the error when doing `Model.findById`. `Model.findOne` works perfectly and does not return the `Invalid usage of the option NEXT in the FETCH statement.` error.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1435 needs to be removed, don't need a limit when we're looking for a primary key.

**Comment by romuloctba** [comment]
I'm getting `Invalid usage of the option NEXT in the FETCH statement` with this code:

```
sequelize.Clientes.findAll({limit: 30, offset: 5  }) 
	 .then(function(result) {
    res.json({result: result}); //this never happens :P
  });
```

It generates the following query sintax: `... from [Clientes] ORDER BY [cnpj] OFFSET 5 ROWS FETCH NEXT 30 ROWS ONLY`

wich is not supported by mssql 2008.
Well, I tried setting `tedious` TDS version with

```
dialect: 'mssql',
  dialectOptions: {
    options: {
    tdsVersion: '7_3_A'
}
```

but it did no good also. :(

Weird enought, when I try Sequelize.query('Raw query using row_num() here') I get `undefined function`error :P

**Comment by janmeier** [comment]
@romuloctba The query is generated by sequelize, so setting dialectOptions does not matter. We have to actually implement another syntax for older versions before this will work.

Try `sequelize.query` instead (the instance, not the constructor)

**Comment by romuloctba** [comment]
Hey guys, here's how's worked for me

```javascript

var sequelize = new Sequelize(.....); 
var page = 2;
var rowsPerPage =  30;

var theQuery = 'declare @rowsPerPage as bigint; '+
        'declare @pageNum as bigint;'+
        'set @rowsPerPage='+rowsPerPage+'; '+
        'set @pageNum='+page+';   '+
        'With SQLPaging As   ( '+
        'Select Top(@rowsPerPage * @pageNum) ROW_NUMBER() OVER (ORDER BY ID asc) '+
        'as resultNum, * '+
        'FROM myTableName)'+
        'select * from SQLPaging with (nolock) where resultNum > ((@pageNum - 1) * @rowsPerPage);';
sequelize.query(theQuery) 
 .spread(function(result) {
         console.log("Good old paginated results: ", result);
    });
});

```

**Comment by RedMage** [comment]
Hello
The error on the FETCH and NEXT also occurs when running a reload() on a model instance immediately after creation. Manually executing an SQL query in this case is tedious and poor practice. Any advice for reloading an object immediately after creation? The .create method does not populate the autoincremented primary key id field on the model, although it is present in the database.

**Comment by treythomas123** [comment]
@RedMage what version of sequelize are you using? My PR [4676](https://github.com/sequelize/sequelize/pull/4676), which was included in 3.12.1, should have fixed the reload issue. I just tried a `.reload()` on 3.17.1 and it worked for me.

**Comment by RedMage** [comment]
@treythomas123 thank you. It appears that something was not consistent between the package version and the node cache version.

**Comment by WillemLabu** [comment]
I'm getting the following error on `sequelize@3.23.3` in the MS SQL dialect on an MS SQL Server instance on AWS (SQL Server Web 12.00.4422.0.v1).

```
Invalid usage of the option NEXT in the FETCH statement.
```
I installed it via [Feathers](http://docs.feathersjs.com/databases/sequelize.html), which uses `tedious`.

The query that throws the error:
```
SELECT [id], [email], [password], [createdAt], [updatedAt] FROM [heros] AS [heros] WHERE [heros].[email] = N\'willem@flintntinder.com\' OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;
```
Any pointers, fixes and/or help would be appreciated.

**Comment by WillemLabu** [comment]
This issue is fixed when you add an `ORDER BY [id]` to the statement before the `OFFSET`.

**Comment by joeveiga** [comment]
Same issue here with `findOne` (version 3.24.3)

**Comment by Meloncon** [comment]
I am also having the same problem. I'm connecting to a Microsoft SQL Server 2012 - 11.0.5613.0 server using [Feathers](http://feathersjs.com/), Sequelize, and Tedious. Here's the exact error text I'm receiving: 

`Error: Invalid usage of the option NEXT in the FETCH statement.`

Not sure where to go from here.

**Comment by zgudino** [comment]
@WillemLabu is right!

Here is TechNet [Limitations in Using OFFSET-FETCH](https://technet.microsoft.com/en-us/library/gg699618(v=sql.110).aspx#Anchor_2).

**Comment by accugopher** [comment]
I too am having this problem, using Sequelize 3.29.0 from Node.js v6.9.4 with Tedious 1.14.0, mssql dialect. Backend is Microsoft SQL Server 2005, TDS version 7.2.

> Unhandled rejection SequelizeDatabaseError: Invalid usage of the option NEXT in the FETCH statement.

This is produced by the Sequelize SQL statement:

`SELECT [intOrderID], ... FROM [dbo].[tblOrders] AS [tblOrders] WHERE [tblOrders].[intStatus] IS NOT NULL ORDER BY [intOrderID] OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;`

Which is generated by a call to:

```
tblOrders.findOne({
  where: {
    intStatus: {
      $ne: null
    }
  }
})
```

**Comment by zgudino** [comment]
Hi @accugopher ,

I am afraid MSSQL Server 2005 does not support `OFFSET FETCH`clause. See [Limitations in Using OFFSET-FETCH](https://technet.microsoft.com/en-us/library/gg699618(v=sql.110).aspx#Anchor_2).


Best regards!

**Comment by aabragan** [comment]
@WillemLabu I was getting the same error as you in feathers using tedious (SQL2014) and I added a     ```
query: {
        $limit: 5,
        $sort: {createdAt: -1}
      }

```
The call was in an after hook. I don't get the items back but the query is executed correctly and I dont get the error any more.

**Comment by denizdogan** [comment]
Could someone clarify what the resolution here is? The issue is closed, so does that mean that Sequelize does not and will not support SQL Server 2005?

This code:

```js
MyModel.findOne().then((x) => { console.dir(x) })
```

generates this SQL:

```sql
SELECT [...] ORDER BY [...] OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;
```

...which fails on SQL Server 2005:

> Unhandled rejection SequelizeBaseError: Invalid usage of the option NEXT in the FETCH statement.

**Comment by accugopher** [comment]
That is apparently what this means. I just spent the last few weeks on one of the worst projects I've ever had in 30+ years of engineering, and largely because this package didn't support SQL Server 2005. If I had had the time, I would have fixed this myself, but as it stands right now, Sequelize is worthless for use with Microsoft SQL Server the way this has been implemented. To only support SQL Server 2012 or newer is probably the laziest thing I've ever seen an engineer do in my years of building and supporting systems, but hey, it fixed their problem, screw you lot, fix it yourself.

**Comment by janmeier** [comment]
@accugopher You do realize that nobody got paid a dime to implement sql support? If you were so annoyed by it, why didn't it do something to fix it? 

I know that things are different in the MS world, but do you really expect someone to go to the effort to support a version that was released more than 10 years ago, and reached its end of life last year? Especially when they didn't need it? Should we have refused to merge the code, because it did not support any verison of sql server release in the last 30 years?


More to the point: I don't have personal experience with sql server, but judging from https://github.com/sequelize/sequelize/pull/5616/files and https://github.com/sequelize/sequelize/blob/8cbd3750f5f8034cc53096de6ddb43593ba1c983/lib/dialects/mssql/query-generator.js#L769 it seems that we do indeed try to support older versions of sql server. We try to identify the version at startup, but perhaps it's failing? Perhaps try setting `options.databaseVersion` manually in the sequelize constructor (It has to be a semver valid string, in this case anything < `11.0.0` should work.

**Comment by stefanobider** [comment]
In my case (SQL Server 2012) the issue is yet another: the error `Invalid usage of the option NEXT in the FETCH statement.` is actually simply due to the fact that the default `ORDER BY` primaryKey is added in the wrong way in `query-generator.js`. Here is the generated query:
```
SELECT [title_index].[work_id] AS [workId], [artists].[relevance] AS [artists.relevance], /*...*/
FROM [sosecatalogue].[title_index] AS [title_index] 
INNER JOIN (
    [sosecatalogue].[artist_works] AS [artists.artist_works] 
    INNER JOIN [sosecatalogue].[artists] AS [artists] ON [artists].[artist_id] = [artists.artist_works].[artist_id]
   ) ON [title_index].[index_id] = [artists.artist_works].[index_id] 
    AND [artists].[label] LIKE N'%mozart%' 
WHERE ([title_index].[label] LIKE N'%sonata%') 
ORDER BY [artists].[relevance] DESC 
ORDER BY [index_id] 
OFFSET 0 ROWS FETCH NEXT 20 ROWS ONLY;
```
As you can see, the default `ORDER BY [index_id]` is added without comma after `ORDER BY [artists].[relevance] DESC `.
I identified where this happens in  `dialects/mssql/query-generator.js`:
```
850    if (!options.order || (options.include && !orders.subQueryOrder.length)) {
851        fragment += (options.order && !isSubQuery) ? ', ' : ' ORDER BY ';
852        fragment += this.quoteIdentifier(model.primaryKeyField);
853    }
```
There are two issues: 
* line 851: while `options.order` is set, `isSubQuery` is `true` therefore `ORDER BY` is added anyway instead of just the comma. **This is the reason why I did not create any PR**: I tried to change it to 851 to `fragment += options.order ? ', ' : ' ORDER BY '` and it works, but I have no idea how the `isSubQuery` condition should be treated and how it would impact in other scenarios.
* line 852: with the aforementioned change, the query fails anyway with error `Ambiguous column name 'index_id'`. This should therefore be changed into: `fragment += this.quoteIdentifier(model.tableName) + '.' + this.quoteIdentifier(model.primaryKeyField);`

For someone who knows the internals I'm sure it's an easy (enough?) fix.
And for the record: it might not be perfect, but it's still a great tool. Thanks guys.

P.S.: If it is any help, here is a dump of the `options` and `orders` vars:
```
options = { raw: true,
  attributes: [ [ 'work_id', 'workId' ] ],
  order: [ [ artists, 'relevance', 'DESC' ] ],
  where: '([title_index].[label] LIKE N\'%sonata%\')',
  include: 
   [ { model: artists,
       attributes: [Object],
       where: [Object],
       parent: [Circular],
       association: artists,
       as: 'artists',
       include: [Object],
       through: [Object],
       required: true,
       includeNames: [Object],
       includeMap: [Object],
       hasSingleAssociation: true,
       hasMultiAssociation: false,
       hasDuplicating: true,
       hasRequired: true,
       hasWhere: false,
       hasIncludeWhere: false,
       hasIncludeRequired: false,
       duplicating: true,
       hasParentWhere: true,
       hasParentRequired: false,
       subQuery: false,
       subQueryFilter: true } ],
  limit: 20,
  subQuery: false,
  hooks: true,
  rejectOnEmpty: false,
  hasJoin: true,
  model: title_index,
  includeNames: [ 'artists' ],
  includeMap: 
   { artists: 
      { model: artists,
        attributes: [Object],
        where: [Object],
        parent: [Circular],
        association: artists,
        as: 'artists',
        include: [Object],
        through: [Object],
        required: true,
        includeNames: [Object],
        includeMap: [Object],
        hasSingleAssociation: true,
        hasMultiAssociation: false,
        hasDuplicating: true,
        hasRequired: true,
        hasWhere: false,
        hasIncludeWhere: false,
        hasIncludeRequired: false,
        duplicating: true,
        hasParentWhere: true,
        hasParentRequired: false,
        subQuery: false,
        subQueryFilter: true } },
  hasSingleAssociation: true,
  hasMultiAssociation: true,
  topModel: title_index,
  topLimit: 20,
  hasDuplicating: true,
  hasRequired: true,
  hasWhere: true,
  hasIncludeWhere: true,
  hasIncludeRequired: true,
  tableNames: 
   [ '[sosecatalogue].[title_index]',
     '[sosecatalogue].[artists]',
     'undefined',
     '[sosecatalogue].[artist_works]' ],
  type: 'SELECT' }
```

```
orders = { mainQueryOrder: [ '[artists].[relevance] DESC' ],
  subQueryOrder: [] }
```

**Comment by stefanobider** [comment]
...any news? Is there something I can do?

**Comment by accugopher** [comment]
@janmeier So, nobody got paid a dime, and that justifies lazy engineering? I've personally contributed countless thousands of hours writing free software. Long, long before you lot had even invented the term "open source", we were building this world that you all use today, and we did it for free, and we did it in a way that made it useful for others, besides just ourselves.....INTENTIONALLY.  Don't lecture me about contributed software, or about design.

The way this was implemented does not support SQL server 2008 either, and that IS still supported by Microsoft, isnt' it? Ultimately, it doesn't matter what Microsoft supports, out here in the real world, where we all live and work, people are still using this JUNK. I hate MS SQL Server, but I have to work with it occasionally. I can't choose what my customers are using for their databases, any more than the rest of the people showing up here looking for support can. Do you think we're starting new projects with this crap? In this case, I didn't use Sequelize on the project, because it was useless.

Open the ticket back up, because this is an issue that is still broken in this software. Setting detection so the tool can report it's not going to work with MSSQL 2005 is not an option. Why would I do that? So I can have the app tell me a second way that it won't work with the database?

UPDATE or REMOVE the notice on the Sequelize web site that clams Microsoft SQL Sever support. YOU DO NOT support SQL Server the way this is implemented, you only support SQL Server 2012 or newer.

**Comment by treythomas123** [comment]
@accugopher Your attitude here is ridiculous. While I agree that it'd be good for the docs to mention that only 2012 or newer is fully supported, it would be far more productive for you to submit a PR making that doc change, than to come here and call volunteers lazy for not spending their free time implementing support for an old MS database that they don't use or need.

**Comment by sushantdhiman** [comment]
I have blocked @accugopher from sequelize organization for this rash and inappropriate behavior. We all work in our free time and try our best to support these literally hundreds of features requests constantly pouring in. But we can't cover everything. You dont have to be rash about it.

If something is missing, implement it, thats how open source works
