### ISSUE TITLE
Sequelize adds quotes to table name in query and so query return no results.

### ISSUE THREAD

**Issue by nikolaykletskin** [sequelize/sequelize#4409]
When I do something like this

    router.post('/', function(req, res, next) {
      models.User.findAll({ 
        where: { 
          username:req.body.username 
        } 
      }).then(function(user) {
        console.log(user);
      });
    });

I get log:

    Executing (default): SELECT "id", "username", "password" FROM "Users" AS "User" WHERE "User"."username" = 'admin';
    []

If I try this query in psql from command line, but without quotes around Users

    SELECT "id", "username", "password" FROM Users AS "User" WHERE "User"."username" = 'admin';

It works properly and return 1 row.

Connection from app to DB is ok.

What's wrong with query generated by Sequelize? May I turn off quoting or should I make some additional setup of my database?

**Comment by janmeier** [comment]
We do have an option called `quoteIdentifiers`, but I would not recomment using it, since its not consistently implemented all over the codebase, and does give some different problems instead (resevered words are not quoted either)

If at all possible, renaming the table to lower case should fix the problem

**Comment by janmeier** [comment]
Closing, no response
