### ISSUE TITLE
how to use 'convert(user_name using gbk)' in mysql

### ISSUE THREAD

**Issue by ymyang** [sequelize/sequelize#4529]
sql: 'select user_id, user_name from user order by'convert(user_name using gbk) '

how to use it as Model.find()?

**Comment by janmeier** [comment]
http://docs.sequelizejs.com/en/latest/docs/querying/#ordering

Probably the easiest would be to use write the string literally
`order: ['convert(user_name using gbk)']`

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by ymyang** [comment]
When i use as 'order: ['convert(user_name using gbk)']',
it throws error: SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'convert(user_name using gbk)' in 'order clause'.

**Comment by mickhansen** [comment]
Needs to be `order: 'convert(user_name using gbk)'` or `order: [[sequelize.literal('convert(user_name using gbk)')]]` i think.

**Comment by janmeier** [comment]
Oh right, without an array wrapper - the documentation should be updated then
