### ISSUE TITLE
Creating Enum has no logging

### ISSUE THREAD

**Issue by milovanderlinden** [sequelize/sequelize#4575]
When I run sync with logging: console.log and force, all the table creation shows up, but TYPE creation (in pg dialect) is not visible in the log.

**Comment by janmeier** [comment]
Hmm, seems to work fine for me.

Do note, that we only try to create the enum if it doesn't exist. You should be seeing `SELECT t.typname enum_name, array_agg(e.enumlabel) ... `, and if that returns the enum, it's not created. We have to do it this way since there is no `IF NOT EXISTS` for `CREATE TYPE`
