### ISSUE TITLE
Promise Recursive Raw Query

### ISSUE THREAD

**Issue by ruibritopt** [sequelize/sequelize#4613]
I am using MySQL, and have two tables **Project** and **Dependencies** :

|    |   Project   |         |
|:--:|:-----------:|---------|
| PK | idProject   | INT     |
|    | projectname | VARCHAR |

|       |     Dependencies    |         |
|:-----:|:-------------------:|---------|
| PK/FK | idProject           | INT     |
| PK/FK | idProjectDependency | VARCHAR |

**Dependencies is a ***Many-To-Many*** relationship between **Project**

For example, we can have:

| idProject | idProjectDependency |
|:---------:|:-------------------:|
| 5         | 3                   |
| 3         | 2                   |

So if I want to know the Dependencies of Project 5, I should received 3 and 2.

For the life of me, I couldn't find a way to do this in sequelize, so I result to do multiple queries, the logic is:

```sql
SELECT idProject, idProjectDependency 
FROM Project JOIN Dependencies ON WP_idWorkPackage = idProject 
WHERE idProjectDependency = 5
```

And I keep doing this until I receive a empty array.

My code so far is:

```javascript
var getListDependencies = function (wpID, total) {

    // Creates the query
    var sqlQuery = createDependencySQLQuery(wpID);
    return sequelize.query(sqlQuery, {type: sequelize.QueryTypes.SELECT}).done(function (result) {

        if (result.length > 0) {
            for (var i = 0; i < result.length; i++) {
                var dep = result[i].idProjectDependency;
                total.push(result[i].idProjectDependency);
                total = total.concat(getListDependencies(dep, total));                
            }
            return total;
        } else {
            return total;
        }
    })
}
```

I keep transporting the total, from one loop to loop, the code (even though is not pretty) works except  that it returns before everything is completed and prints undefined because of this.
This is where I call the above function:

```javascript
module.exports = {
    getWorkPackages: function (req) {
        var reqWorkPackage = 5; // for testing

        return Promise.resolve().then(function () {
            return getListDependencies(reqWorkPackage, []);
        }).then(function (list) {
            console.log("\n\nLIST", list) // for testing
            
            return {"list": something};
        }).catch(function (msg) {
            throw msg; // <- throw the message
        });
    }
}
```
I have been wrapping my head around this for 2 days, so I decided to come here and ask you guys, how can I make the promise wait for the recursive search to the database?

**Comment by janmeier** [comment]
This is a general promise question, and thus probably better suited for SO or the likes. 

Anyhow, I'll try to answer, since you explained your problem in such greate detail.

Firstly, don't use `done`, always use `then`, unless at the end of a promise chain https://github.com/petkaantonov/bluebird/blob/master/API.md#donefunction-fulfilledhandler--function-rejectedhandler----void

The gist is that you have to make the promise chain aware that you are doing something async - pseudo-ish code:
```js
var getListDependencies = function (wpID) {
    // Creates the query
    var sqlQuery = createDependencySQLQuery(wpID);
    return sequelize.query(sqlQuery, {type: sequelize.QueryTypes.SELECT}).done(function (result) {
        return sequelize.Promise.reduce(result, function (total, dep) {
          var dep = dep.idProjectDependency;
          total.push(dep);
          return getListDependencies(dep).then(function (listDeps) {
            return total.concat(listDeps 
          });
        }, []);
    })
}
```
The idea of `reduce` is to reduce the result array to a single value - in this case an array ;) - We start by giving it an empty array, and each item puts some more stuff on the array and returns the new array. Its inspired by `reduce` / `fold` from functional programming.

By always returning promises, the chain knows that it should wait until that promise is finished before iteration continues.

Hope it makes sense - otherwise please post on SO, or come talk to us on IRC ;)

Closing this issue, since it is neither a bug report nor a feature request.

**Comment by ruibritopt** [comment]
Thank you a lot for the help @janmeier  

My final code looks like this:
```javascript
var getListDependencies = function (wpID) {
    // Creates the query
    var sqlQuery = createDependencySQLQuery(wpID);
    return sequelize.query(sqlQuery, {type: sequelize.QueryTypes.SELECT}).then(function (result) {

        return sequelize.Promise.reduce(result, function (total, dep) {
            var dep = dep.WD_idDependency;
            total.push(dep);
            return getListDependencies(dep).then(function (listDep) {
                return total.concat(listDep);
            });
        }, []);
    })
}
```
