### ISSUE TITLE
Question: How to express SUM(`foo`) * SUM(`bar`) AS `baz`

### ISSUE THREAD

**Issue by briancray** [sequelize/sequelize#4633]
Title... Model has foo and bar fields, I want to multiply them (or more advanced operations like foo * bar / baz).... What's the best way to accomplish this during query time?

**Comment by janmeier** [comment]
Hmm, that would probably have to be express in raw sql, using `sequelize.literal(SUM(foo) * SUM(bar) AS baz)`. We do have support for functions (e.g. `sequelize.fn('sum', sequelize.col('foo'))`  but not aggrations 

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
