### ISSUE TITLE
Why underscored: true doesn't work for model?

### ISSUE THREAD

**Issue by moslemezzati** [sequelize/sequelize#4636]
As mentioned in document if put `underscored: true` you can use camelCase in your model so that I did that in my model as you can see blow:
```javascript
  var Data = sequelize.define('Data', {
    sell: DataTypes.INTEGER,
    buy: DataTypes.INTEGER,
    benefit: DataTypes.INTEGER,
    exchangeId: DataTypes.INTEGER
  }, {
    classMethods: {
      associate: function(models) {
        Data.hasMany(models.CoinTable, {foreignKey: 'data_id'});
        Data.hasMany(models.DraftTable, {foreignKey: 'data_id'});
        Data.hasMany(models.ExchangeTable, {foreignKey: 'data_id'});
      },
      underscored: true
    }
  });
```
But when I use model for example:
```javascript
models.Data.create({
        sell: req.body.sell,
        buy: req.body.buy,
        exchangeId: exchange.id,
        benefit: req.body.benefit
      }).then(function (data) {
        models.ExchangeTable.create({
          data_id: data.id
        }).then(function () {
          res.sendStatus(201);
        });
      });
```
it shows me exchangeId doesn't exist.
```
Unhandled rejection SequelizeDatabaseError: column "exchangeId" of relation "Data" does not exist
```
How Could I use underscored feature?

**Comment by janmeier** [comment]
`underscored` is used to convert all camel cased attributes to underscored - e.g. `updated_at` instead of `updatedAt` - It also applies to all other fields, which means the field - both in the model and db will be  `exchangeId`.

If you need camel cased in the model but underscored in the db use `exchangeId: { field: 'exchange_id' } `

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by moslemezzati** [comment]
ok. thanks
