### ISSUE TITLE
how belongsTo two table between two different name

### ISSUE THREAD

**Issue by zhfish** [sequelize/sequelize#4637]
in postgres

table User:
id : int4
name : string

table Session:
userID : int4
token : string

i use
```
db.User.belongsTo(db.Session,{foreignKey:'id',targetKey:'userID'});
db.Session.belongsTo(db.User,{foreignKey:'userID',targetKey:'id'});
```
is wrong

**Comment by janmeier** [comment]
Please read http://docs.sequelizejs.com/en/latest/api/associations/ - basically you shouldn't have `belongsTo` on both sides - User has one Session, Session belongs to User

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
