### ISSUE TITLE
`sync` should be locked

### ISSUE THREAD

**Issue by damongant** [sequelize/sequelize#4647]
Running `Sequelize.sync` more than once in parallel can have unintended consequences. There should be a locking mechanism that rejects a call right away if another is still running.

**Comment by DamonGant** [comment]
Test:
https://gitlab.com/DamonGant/sequelize-sync-conflict

**Comment by leroydev** [comment]
@schittler The GitLab repo you linked is not available anymore, would it be possible for you to make it available again?

**Comment by leroydev** [comment]
Should a parallel call to `Sequelize.sync` be rejected or should it be executed after the first call?

**Comment by schittler** [comment]
Don't have the repo any more, but it boils down to having autoSync and a manual sync running at the same time crashing the app.

It should be rejected as an invalid operation - changing the schema so a sync should be required/queued while another sync is happening seems dangerous to me.

**Comment by janmeier** [comment]
An alternative could also be to save a promise pointing to the current sync operation, and return that instead

(pseudo-code)
```js
class Sequelize {
  sync() {
    if (this._syncing) return this._syncing

    this._syncing = new Promise(() => /* magic happens here */).finally(() => this._syncing = null);
  }
}

**Comment by schittler** [comment]
@janmeier - That seems like it could ruin someones afternoon debugging why his changed schema is not updating. This should result in a clear error message so it can be caught during development. I don't quite remember the details but some operation automatically starts a sync and I wasn't aware, so that's why it was ever an issue for me. I'd rather have a clear cut error message than a potential race condition where I sometimes sync twice because the first one finishes faster sometimes.

**Comment by janmeier** [comment]
I guess theoretically yes (never experienced concurrent syncs myself, but it could happen)

I've updated the code accordingly  :)
