### ISSUE TITLE
[doc] the migration skeleton doc seems out of date

### ISSUE THREAD

**Issue by joneslee85** [sequelize/sequelize#4648]
That sections reads:

```
..... The third parameter is a callback function which needs to be called once everything was executed. The first parameter of the callback function can be used to pass a possible error. In that case, the migration will be marked as failed. Here is some code:

module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.dropAllTables();
  }
}
```

Firstly, the example is not relevant to `the third done() callback param`
Secondly, do we still support this callback way anymore?

**Comment by janmeier** [comment]
I think it might still be supported, but its highly discouraged

The text should definitely say that you should return a promise

PR welcome :)

**Comment by joneslee85** [comment]
@janmeier thanks for the reply. I will make a PR. Though I am still puzzled with how to catch the exception should any query fail. I think the example should have example on that too. If you happen to know of a good example, can you please share.

**Comment by janmeier** [comment]
@joneslee85 

You can attach a `.catch` handler, because all operations that hit the db return a promise.

```js
up: function () {
  return migration.addColumn(...).catch(function() {

  });
}
```

You can also catch different types of errors, e.g `catch(Sequelize.ValidationError, function` and since its promise chain the error will bubble up (i.e. no need to handle an error for each call, you can have a single handler) - but that might be a bit more general sequelize / promise and not so much migration
