### ISSUE TITLE
Possible? Virtual column That count number of children

### ISSUE THREAD

**Issue by EToreo** [sequelize/sequelize#4703]
I have a single table that describes a tree and I would like any given row to be able to report the number of other rows that reference it as a parent.

I basically want to know if this is possible to do and how I would describe it to Sequelize: http://sqlfiddle.com/#!2/039ee/6

**Comment by mickhansen** [comment]
You can define any type of virtual columns you like. They can be targeted with the alias part of attributes: `attributes: [[EXPRESSION, ALIAS]]`

**Comment by janmeier** [comment]
The fiddle you linked can be expressed with

```js
return Model.findAll({
    attributes: {
      include: [[sequelize.fn('count', sequelize.col('children.id')), 'count']]
    },
    where: {
      parent_id: 0
    },
    include: [
      {
        attributes: [],
        association: Model.associations.children,
        required: true
      }
    ],
    group: ['model.id']
  });
```
If you want to load that each time the model is loaded you could add it as a `defaultScope`

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
