### ISSUE TITLE
findAll() Asynchronous

### ISSUE THREAD

**Issue by AlexKhodaverdian** [sequelize/sequelize#4712]
Right now I need my findall to give me a result that I return from a method, but findall seems asynchronous. Does anyone have any idea as to why this is the case

**Comment by janmeier** [comment]
`findAll` is asynchronous by nature - because node is asynchronous by nature. 

I'd suggest you read up on how node handles asynchronousity - basically you attach a callback (via `.then`) which is called when the data has been returned by the db 

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
