### ISSUE TITLE
MySQL JSON Data Type

### ISSUE THREAD

**Issue by nodecode** [sequelize/sequelize#4727]
MySQL now has a JSON data type. See here: https://dev.mysql.com/doc/refman/5.7/en/json.html

An implementation in Sequelize.js (like with PostgreSQL) would be nice.

http://sequelize.readthedocs.org/en/latest/docs/models-definition/#data-types

**Comment by janmeier** [comment]
Interesting definitely! :)

It doesn't seem like 5.7 is supported on travis yet (I'd rather not have to fiddle around with a script that manually installs it), so thats the first hurdle

**Comment by camerondubas** [comment]
+1

**Comment by mujz** [comment]
+1

**Comment by golya** [comment]
+1

**Comment by gilo** [comment]
+1

**Comment by twilly86** [comment]
+1

**Comment by miralem** [comment]
+1

**Comment by tosone** [comment]
+1

**Comment by seanzx85** [comment]
+1

**Comment by rromanw** [comment]
+1

**Comment by saurabhverma2892** [comment]
+1

**Comment by ccg1415** [comment]
+1

**Comment by Glavin001** [comment]
Any progress on this? I would be interested in contributing, however I have yet to dive into Sequelize internals yet. Any pointers would be greatly appreciated! Thanks!

**Comment by janmeier** [comment]
@Glavin001 Perhaps you can draw some inspiration from https://github.com/sequelize/sequelize/pull/4013, which added geometry support. 

Basically, you need to add some code to mysql/data-types, something like this https://github.com/sequelize/sequelize/blob/a89f0f818657fc289c97e7f433b3499d02e661b5/lib/dialects/postgres/data-types.js#L276-337. Parse handles converting data that comes from the DB to json, while stringify converts JSON to the format the db expects.

If you have futher questions, ask them here, open the PR and we can discuss further, or join us on slack :)

**Comment by janmeier** [comment]
One problem is that travis-ci doesn't support mysql 5.7 out of the box - But you could try using https://gist.github.com/BenMorel/d981f25ead0926a0cb6d to update the mysql version.

If installing a new mysql version doesn't take too long, we might as well upgrade to the 14.04 image (which doesn't have mysql installed by default) - then we wouldn't have to manually upgrade gcc and clang https://github.com/sequelize/sequelize/blob/a89f0f818657fc289c97e7f433b3499d02e661b5/.travis.yml#L28-33

**Comment by ramsundhar20** [comment]
I am interested in making the fix for this, I need sequelize team to guide me, what needs to be done and how it needs to done, and what would be expected impact on the existing library?

**Comment by Glavin001** [comment]
@ramsundhar20 I haven't had time to start my Pull Request so feel free to jump in and start your own. I really hope to add support for this feature!

**Comment by janmeier** [comment]
@ramsundhar20 the work that needs to be done is twofold - first we need to be able to test he json functionality on Travis - which requires mysql 5.7. This probably means we need to run a docker container with mysql, since 5.7 is not a supported by Travis. I think running mysql in docker will be faster than upgrading the mysql version running on Travis. 
If you have experience with Travis /docker, you are welcome with to look at this as well, but if not that's fine as well - you can handle the code, and I'll handle the ops stuff. 

With regards to code, there are two main places you need to change. First, datatypes which I've linked previously is what handles converting the data to and from the value mysql expects. Stringify probably already works, but you might need to add the parse part for mysql to get back json instead of a string - or maybe it works out of the box if the node mysql driver takes care of parsing. 

The other place you need to look is the query generator - search for json in the postgres one to see how it is handled. Preferably we'd like to support the same operators for mysql and postgres, but I'm not sure if that's possible

**Comment by ramsundhar20** [comment]
@Janmeier, thank you, I will start looking into it in detail

@ramsundhar20 <https://github.com/ramsundhar20> the work that needs to be
done is twofold - first we need to be able to test he json functionality on
Travis - which requires mysql 5.7. This probably means we need to run a
docker container with mysql, since 5.7 is not a supported by Travis. I
think running mysql in docker will be faster than upgrading the mysql
version running on Travis.
If you have experience with Travis /docker, you are welcome with to look at
this as well, but if not that's fine as well - you can handle the code, and
I'll handle the ops stuff.

With regards to code, there are two main places you need to change. First,
datatypes which I've linked previously is what handles converting the data
to and from the value mysql expects. Stringify probably already works, but
you might need to add the parse part for mysql to get back json instead of
a string - or maybe it works out of the box if the node mysql driver takes
care of parsing.

The other place you need to look is the query generator - search for json
in the postgres one to see how it is handled. Preferably we'd like to
support the same operators for mysql and postgres, but I'm not sure if
that's possible

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sequelize/sequelize/issues/4727#issuecomment-232195657>,
or mute the thread
<https://github.com/notifications/unsubscribe/AEshvUx_RptBAs8433KvRXtvxOvHeMSBks5qVA8JgaJpZM4GVI_g>
.

**Comment by janmeier** [comment]
@ramsundhar20 Any progress? We are now testing against mysql 5.7 on travis so we can test the functionality :)

**Comment by juan55860** [comment]
+1

**Comment by felixfbecker** [comment]
Please don't +1 issues. It clutters the thread without adding value to the discussion and spams maintainers with notifications. Use GitHub reactions to upvote features.
![image](https://cloud.githubusercontent.com/assets/10532611/18344735/bb60c2f6-75b8-11e6-88a9-822fae298110.png)

**Comment by insanehong** [comment]
+1

**Comment by Rio517** [comment]
@insanehong Please read the comments above. Literally the last comment before yours reads:

"Please don't +1 issues. It clutters the thread without adding value to the discussion and spams maintainers with notifications. Use GitHub reactions to upvote features."

**Comment by soulman-is-good** [comment]
@Rio517 @felixfbecker try adding reaction to an issue on mobile version. Maybe I blind or something but there is none. 
And just MHO but why not use github API for automation? 
https://developer.github.com/v3/issues/comments/

**Comment by seangrogg** [comment]
I decided to give it a whirl anyways and lo and behold using Sequelize.JSON as the datatype for a column works "well enough" in MySQL 5.7 - you're able to create the column with the appropriate data type, insert values, and update values.

Two caveats:
* I haven't tried but I would imagine you can't perform WHERE queries on them the same way you can in PostgreSQL
* The results are currently returned as strings, so you'll have to JSON.parse to get the results back as a proper object/array

While imperfect, it's more than useable for my use case. Cheers.

**Comment by toddsby** [comment]
I needed this functionality for a project I'm working on. I found this: https://github.com/mysqljs/mysql/issues/1267#issuecomment-230739821 which lead me to  implement it in a fork here: https://github.com/toddsby/sequelize/commit/69f32975f48d3bd05227485a121a28b885e13207 This won't give you full support for INSERT/UPDATE but works great for SELECT queries. You could extend this to support INSERT/UPDATE with queryFormat see here: https://github.com/mysqljs/mysql/issues/1573

**Comment by chrishutchinson** [comment]
Any progress on this lately?

**Comment by joelwallis** [comment]
+1! 🎉

**Comment by autaut03** [comment]
God two years passed and it still throws an error. 

Gonna switch to Laravel as soon as possible, I've never seen anything worse than JS and it's support....

**Comment by thujikun** [comment]
Any progress?

**Comment by autaut03** [comment]
Why am I getting so much dislikes... I just told the truth and you're raging or what?

**Comment by Freezystem** [comment]
It's not the place to complain about "JS Support" or whatever that is suppose to mean. There is no such thing. This project is open source, if you want/need something done, you gotta do it yourself or help the other doing it. Complaining is not helping. If you wanna switch to Laravel, cool for you, go on. But this thread is not a social network, nobody cares of your tech choices.

**Comment by Shywim** [comment]
I'd say I dislike the javascript ecosystem too, but coming here and saying this in a JS project repository is like screaming "HIT ME!", it is also irrelevant to this issue, and like any open source project you can:

- Make the changes/additions yourself
- Search for alternatives that do what you want
- Patiently wait for someone to use their time to do something for free

In any case, being respectful to other's work is a minimum, whether you appreciate it or not.

**Comment by yungtechboy1** [comment]
https://sequelize.org/ helped me
