### ISSUE TITLE
find query doesn't include models on belongsToMany association

### ISSUE THREAD

**Issue by jose-nunez** [sequelize/sequelize#4746]
Hi again. Thank you for your time.
I have the following association table, wich associates product and pack tables. Note that price_product could not have a **pack_id (allows null)**

``` SQL
CREATE TABLE price_product (
    id             INTEGER      PRIMARY KEY AUTOINCREMENT       NOT NULL,
    product_id     INTEGER      NOT NULL,
    pack_id        INTEGER,
    /* some other attrs follow */
    CONSTRAINT fk_precio_producto_producto1 FOREIGN KEY (product_id)    REFERENCES product (id),
    CONSTRAINT fk_precio_producto_paquete1 FOREIGN KEY (pack_id)    REFERENCES pack (id) 
);
```

Here are the associations on sequelize:

``` javascript
db.product.belongsToMany(db.pack,{through:db.price_product,foreignKey:'product_id'});
db.pack.belongsToMany(db.product,{through:db.price_product,foreignKey:'pack_id'});
```

When I try to attach packs to a product, it does't work. But by using the getPacks() method, I does work.

``` javascript
db.product.find({where: {id:387},include:[{model:db.pack}]}).then(function(my_product){
// This one works. Array with packs (models) :D
    my_product.getPacks().then(function(result){console.log(result);});
// This one doesn't. It gives an empty array.
    console.log(my_product.packs);
});
```

If I do the same proccess inverted, packs retrieving their products, I get the right results.

``` javascript
db.pack.find({where: {id:1},include:[{model:db.product}]}).then(function(my_pack){
// Array with products
    my_pack.getProducts().then(function(result){console.log(result);});
// Array with the same products
    console.log(my_pack.products);
});
```

Let me know if you need something else from my code to find out what's happening here.
Thank you very much.

**Comment by mickhansen** [comment]
When you use prefetching you should not use the async getter aftwards.
Simply use `my_product.get('packs')`.

**Comment by peponerock** [comment]
If you pay atention, that function is the one that works correctly. This is just an example btw.
My problem is on **find-include** function.  That one is not givin packs for products (first case), but it is working well giving products for packs (second case).

**Comment by mickhansen** [comment]
Have you tried logging all the values to see if the naming might be wonky?

**Comment by peponerock** [comment]
Yes. I did, my friend. The instance obtained "my_product" has an attribute called "pack" wich is an empty array. (Array[0]). *my_product.get('packs')* is returning an empty array as well. *my_product.getPacks()* works OK.

![my_product](https://cloud.githubusercontent.com/assets/8520567/10786698/61f10a26-7d4a-11e5-850f-117364aa28e1.png)

Now I'm fixing this in the findAll function inserting packs "manually":

	db.product.findAll({
		include:[
			{model:db.pack,attributes:['id'],through:{attributes: []}},// not working
		]
	})
	.then(function(result){
		for(var i in result){
			result[i].dataValues.packs = result[i].getPacks();
		}
	});

Is this related to the fact that foreign key for pack in the association table allows null? I suspect of this, because retreiving packs containing products works well, and the only difference between both cases I can see is foreign key for product doesn't allow null. Does it make sense to you?
By the way, I'm using NWJS (Node webkit) on Win8.1

Thank you very much.

**Comment by WalterC87** [comment]
@peponerock dude could you teach me how you insert products and packs in your table price_product?, using the sequelize syntaxis , I'm searching some examples how do that but only found examples where are using Getters but no examples with setters. Thanks.

**Comment by peponerock** [comment]
Have you tried with model.create() or model.update()? http://docs.sequelizejs.com/en/latest/api/model/

**Comment by szilardracz91** [comment]
nice
