### ISSUE TITLE
Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR:Unknown column 'NaN' in 'field list'

### ISSUE THREAD

**Issue by superlbr** [sequelize/sequelize#4773]
Hi,I met error like this ,but don't know where to locate this,any help?
![image](https://cloud.githubusercontent.com/assets/8142164/10809178/23465700-7e2f-11e5-91fc-6a5a41d449c2.png)

**Comment by janmeier** [comment]
Somewhere you're padding nan to sequelize, probably in `attributes `. Other than that there's not really much we can say without some code to replicate the issue

**Comment by superlbr** [comment]
I guess it's better to add more info. in logs, lots of code

**Comment by mickhansen** [comment]
@superlbr DatabaseError is an SQL error, try looking at the SQL being run. But as @janmeier said there's likely something wrong with your `attributes` statement.

You need to provide a lot more info, but you should probably just start by doing some basic debugging on your own.

Closing this, please re-open if you identify an actual issue.

**Comment by normancarcamo** [comment]
I'm joining and commenting to this thread closed  just to let clarify that this happens in sequelize whenever you're modifying the attributes from your hooks, in my case was the "beforeUpdate" hooks, it modifies the version of the column when you have enabled the option in your config, if you are not logging for audit or something like that then just disable it, also if you want to keep the versions then modify the value of the version but I think that this is not a good way because it will increment it, if you still want to audit your versions then use another package to do that.

Hope it helps. (I'm not auditing version right now)

**Comment by lebron112** [comment]
i have the same question
