### ISSUE TITLE
Transactions in tests?

### ISSUE THREAD

**Issue by faceleg** [sequelize/sequelize#4823]
Is there a well known easy way to use transactions when writing tests?

Example of my ideal solution:

```JS
beforeEach(function() {
  return somethingThatStartsATransactionWrapper();
});

afterEach(function() {
  return somethingThatRollsbackATransactionWrapper();
});
```

```JS
describe('a test', function() {
  it('should leave the database how it found it when done', function() {
  });
});
```

**Comment by mickhansen** [comment]
Well it depends on whether or not you have access to the options passed to the sequelize calls.
If you do you can just setup a transaction in beforeEach and roll it back in afterEach.

**Comment by faceleg** [comment]
I do but was hoping for something more "set and forget"

**Comment by faceleg** [comment]
At the moment I have my tests truncate everything and re-run `sequelize-fixtures`. It works, it results in a predictable DB state but it's slow.

**Comment by mickhansen** [comment]
Well we have managed transactions but they default to a commit.

**Comment by janmeier** [comment]
This should actually be doable using [CLS](https://github.com/othiym23/node-continuation-local-storage)

```js
var cls = require('continuation-local-storage');

var ns = cls.createNamespace('test');

describe('foo', function () {
        beforeEach(function (done) {
                ns.run(function () {
                        ns.set('foo', true);
                        done();
                });
        });

        it('should work', function () { 
                console.log(ns.get('foo'));
        });
});
```
Logs `true` in the test, which means the namespace is available in the it (most likely because we are calling `done` inside `run` - so returning a promise won't work here.

If you replace `ns.set('foo', true);` with `sequelize.transaction`, the transaction should automagically be used in the test. See http://docs.sequelizejs.com/en/latest/docs/transactions/#automatically-pass-transactions-to-all-queries for more on CLS with sequelize

One problem is that the transaction is not available in `afterEach` - but at least it gets you some of the way (transaction automagically passed to all calls). You'll just have to manually roll it back

**Comment by faceleg** [comment]
So this way I would be able to have a "global" `beforeEach` that set the transaction, and roll it back at the end of each `it`? Why is the transaction not available in `afterEach`?

Thanks for providing this suggestion!

**Comment by mickhansen** [comment]
@janmeier did you test that? not sure how mocha internally does that, whether or not it calls the it() callback in the same event loop as when the done callback is called.

If it does work, the reason it would not be available in the afterEach @faceleg is because you've dropped out of the event loop chain (although not necessarily, depends on what happens inside).

I'm not at all sure you could make this work in a nice way without looking a lot at your test runner implementation and perhaps wrapping some of their internals.

**Comment by faceleg** [comment]
Thanks @janmeier and @mickhansen, I'm going to leave my tests alone and actually get on with feature building using my current slow but reliable buildup/teardown process.

Really appreciate the time and thought you've put into answering my questions
