### ISSUE TITLE
AWS Lambda connection always open

### ISSUE THREAD

**Issue by alex88** [sequelize/sequelize#4938]
Hi there,

I'm not sure it's an issue with sequelize but I connect to my database at the beginning of a function with:

```
var sequelize = new Sequelize('postgres://username:pwd@rds-postgresql-host:5432/database');
```

every time I run the function I see on the database side that there are 4 open connections that doesn't get closed at the end of the function, is it possible to close the connections manually?

**Comment by mickhansen** [comment]
`sequelize.close()` closes all all connections.
The pool will keep the connection around for a bit after having executed queries, but it shouldn't be forever.
You might want to tweak your pool settings for lambda (run 1/1 with low idle timeout maybe)

**Comment by alex88** [comment]
Thanks for the replay @mickhansen, I've tried to set maxIdleTime to 1000 (which I've seen now it's the default value), that should close all the connections after 1 second of inactivity, it works locally but on lambda the connection is now open since at least 20 minutes.

I'm gonna try with `sequelize.close()` the only problem is that I need to be sure it always works

**Comment by mickhansen** [comment]
Default idle is 10seconds (10000ms). 20 minutes definitely doesn't make sense.
Can you verify whether or not the lambda process actually closes? Could be the server keeping it alive.

**Comment by alex88** [comment]
I think it's the server keeping it alive, from the forums I've seen staff says they try to reuse the node process everytime, I've just pushed the code that uses `sequelize.close()` but the connections are still there

**Comment by alex88** [comment]
Anyway, now with `{ pool: { maxIdleTime: 1000, maxConnections: 1 } }` seems to work much better and the connections are actually closed after a small time, thanks!

**Comment by kennu** [comment]
I believe this problem has re-emerged with the new Lambda nodejs4.3 runtime, which by default waits for the event loop to become empty before ending each invocation. This adds an unnecessary extra 1000ms at the end of invocations using Sequelize.

However it seems to be possible to work around the timeout by setting this parameter inside the Lambda function:

    context.callbackWaitsForEmptyEventLoop = false; 

According to AWS documentation (http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html) the Lambda function is frozen immediately and the event loop will be processed later when a future invocation happens. I'm not quite sure what happens to the connection pool at that point, but hopefully it manages the timeout gracefully.

**Comment by mickhansen** [comment]
@kennu Connection pooling does not appear to work well for lambda so perhaps you could set the idle time to something like 100ms

**Comment by Dayjo** [comment]
Hi Guys,

I'm finding myself having issues here too. 

I've actually gone through and started closing connections manually when the lambda finishes (which appears to be working), without this I ended up with all the max connections just hanging and then not being able to create new connections and therefore nothing working. 

The issue I'm having with this is (well, I THINK it's this) AWS is not actually shutting down the Lambda between subsequent calls (to be clever), and because I've closed the connection, i get the following error;

```
Error: ConnectionManager.getConnection was called after the connection manager was closed!
```

I've tried playing with the pool values, currently set to;

```js
pool: {
            max: 10,
            min: 1,
            idle: 1000
          }
```

But I'm not sure what the best practice for this scenario is, whether to allow it to have multiple connections, or force it to one and try and get it to 'reconnect' if there's no connection when it needs one. 

My Lambda could be run several times simultaneously to run different queries. 

Any advice on best practice here would be super helpful.

Thanks!

**Comment by marclar** [comment]
@Dayjo if you figure out something better, please comment here. I tried your suggestion and it's working, but it's extremely slow to initialize on each lambda invocation.

**Comment by phikes** [comment]
@kennu This approach is the best imho. It will reuse connections, which significantly lowers the latency in my observations.

**Comment by Dayjo** [comment]
@marclar Yeah, unfortunately, there does seem to be an issue with the speed. I'm wondering if there's some way of determining how many connections are in use, and trying to be more clever on when to actually close them, or handling open ones.

**Comment by phikes** [comment]
Also have a look [here](https://github.com/sequelize/sequelize/issues/4596). Today my Lambda function executes in 2-3ms., while doing a `findAll()`. I used @kennu's approach.

**Comment by Dayjo** [comment]
You mean just setting `context.callbackWaitsForEmptyEventLoop = false;` and connecting outside of the handler function, without closing connections?

**Comment by phikes** [comment]
Yes. 

This leaves the connection pool intact for when AWS reuses the node process (hence my fast executions) but does not wait for the event loop to get empty (thus AWS does not time out the function). You also don't have unnecessary long execution times, because the connection pool needs to time out.

**Comment by Dayjo** [comment]
As far as what I understood from https://aws.amazon.com/blogs/compute/node-js-4-3-2-runtime-now-available-on-lambda/ and http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html, this is only applicable if you're not explicitly calling `context.succeed` et al?

**Comment by phikes** [comment]
From your first link:
> This property is useful to modify the default behavior of the callback. You can set this property to false to request AWS Lambda to freeze the process after the callback is called.

I am using the `callback` function after I found the stuff in the database my function was called for. Something like `...findAll().then(function(users){callback(null, users);});`.

**Comment by Dayjo** [comment]
I'll give this a try (replacing the context.succeed with callback) and let you know how I get on.

**Comment by jpsilvashy** [comment]
@phikes @Dayjo It might be helpful to review this comment thread: https://github.com/brianc/node-postgres/issues/930#issuecomment-235953730

There have been other issues with pg connection management on lambda.

**Comment by Dayjo** [comment]
Indeed, I did read that earlier. Would be great to get someone from the lambda team to give their 2 cents on how they think (based on how the lambdas work) we should be managing connections. .

**Comment by Dayjo** [comment]
@phikes I have done the following;

* Initialising my database before the handler function
* No longer doing `DB.sequelise.close();` 
* set `context.callbackWaitsForEmptyEventLoop = false;`
* Replaced all mentions of `context.succeed` and `context.fail` with `callback(..)`
* Set pool to; 

```js
pool: {
            max: 10,
            min: 1,
            idle: 100
          },
```
The connection does seem faster, and it seems to grab things out of the database faster. However, without closing the connections, I now have a growing list of idle connections in the database which was my original problem. They don't seem to ever get timed out.

The Lambda does seem to use the pool, but if I make maybe 3 / 4 quick requests to the lambda, new connections are opened up despite there being all of those connections already. Unsure whether this is Sequelize, AWS or MYSQL's fault really.

MYSQL is set up as default on RDS i.e. `connect_timeout=10; max_connections=66`

More than 10 conections in the pool?
![image](https://cloud.githubusercontent.com/assets/1255512/18271312/5f5e1a16-7429-11e6-810e-de0d86876da9.png)

**Comment by phikes** [comment]
I am doing the same things as you, except for the settings of the connection pool I just use the defaults. I am using Postgres and I don't see any open connections even immediately after the execution.

For your last question: I *think* it depends. When AWS **reuses the Node process** (which I have only heard of) then it would use the **same connection pool** (in my case it seems to do that; hence the low latency I reported). If it didn't reuse the process it would be n differen connection pools with m different connections.

**Comment by phikes** [comment]
My code for reference
```
var Sequelize = require('sequelize');
var sequelize = new Sequelize('database', 'username', 'password', {
  host: process.env.ADDRESS,
  port: process.env.PORT,
  dialect: 'postgres'
});

var User = sequelize.define('user', {
  username: {
    type: Sequelize.STRING,
    unique: true
  }
});

exports.handle = function(event, context, callback) {
  context.callbackWaitsForEmptyEventLoop = false;

  User.findAll().then(function(users){
    callback(null, users);
  }).catch(function(error){
    callback(error, null);
  });
}
```

**Comment by phikes** [comment]
Hm, now I also see one connection being open. But the number does not grow on subsequent calls of the lambda. Might be latency of the web interface of RDS.

Another idea: Switch off the pool and close the connection in a promise?

**Comment by Dayjo** [comment]
@phikes perhaps it's some sort of caveat of MYSQL 

It does appear that the connections are eventually timing out, but I still have 13 open (pool is set to 10) - 5500 seconds idle and counting, no idea why they've not timed out yet.  

Closing the connection when the lambda is done was what I was doing previously, though that means that everytime the lambda is called it has to re-connect. I guess that's better than re-initialising the whole config / models though. 

I will try with the pool not specified.

**Comment by Dayjo** [comment]
Just gone back to the same problem really, it's just far slower initialising the connection every time,  however it does obviously clean up the connections better. 

What would be perfect would be able to run a function on lambda 'shutdown' .. proper shutdown though, so that you could close the connection then. Or being able to determine if a pool is already open and using an existing one.

**Comment by phikes** [comment]
> but with it being just me hitting refresh I'd be concerned if there were lots of users using it.

Try [siege](http://linux.die.net/man/1/siege) to test that case. I just tried and for me it seems fine after 400 hits to the lambda.

**Comment by Dayjo** [comment]
For anyone that's interested, this is AWS response to my question about this issue, as you can see, there's obviously not a true solution to using connection pools, and due to the stateless nature of the lambdas, you should create a connection within the handler (although obviously this is very slow).

==========


Hello Joel,

Thank you for contacting AWS Premium Support. My name is Pratik and I will be assisting you with your support case.

I understand that you are seeing a lot of your MYSQL connections run idle and you're wondering why are they not closing quickly. I also took a look at the github issue you mentioned in your correspondence. 

First let me explain a bit about Lambda and connection pooling with Lambda. Since it is advisable to write your Lambda functions to be stateless, this would mean that you form the connection inside the handler. However, if you wish to use connection pooling, so that you can re-use these connections for subsequent invocations of the function, you will have to create your connection to RDS outside the handler.

Lambda may choose to retain an instance of your function and reuse it to serve a subsequent request, rather than creating a new copy. This is what we mean when we say container reuse.. Now since Lambda code is intended to be stateless, your code should not assume that this will always happen. However, by initializing the connection pool outside the handler function, you can ensure that if the container is going to be used again, the existing connection pool will be reused as well. This brings a new challenge though, as you will then need to rely on connection time outs to terminate unused connections to keep things manageable. This aspect can be hard to fine tune. 

Now the connection time out also presents new challenges, because premature timeouts can also cause failures. So in addition to creating the connection outside of your handler, you should create a connection inside of the handler too. Now, when you are attempting to create the connection inside the handler, you should only do this if no connection exists already exists, like what's shown in the following psuedo code:

var dbConnection;

exports.handler = function(event, context){
if(!dbConnection){
//init db connection
}
//otherwise reuse the connection
};

Doing things this way can give you the performance gain of connection pooling and reduce the number of connections. Moreover, you need to implement some kind of logic to clean these connections up, which is hard again since you can't see into another container. However, it does go against Lambda's stateless nature and can at times produce unpredictable or even adverse results that will need to be handled in your code. 

Now I see that you mentioned in one of the github posts: "The Lambda does seem to use the pool, but if I make maybe 3 / 4 quick requests to the lambda, new connections are opened up despite there being all of those connections already."
3/4 quick requests would mean concurrent invocations, and concurrent invocations will execute in new containers. Containers are not aware of each other and cannot share state information so if an execution occurs in new container, it will open a new connection if there are none in this new container, despite there being existing connections from different containers. This can also cause your RDS instance to have too many open connections, because another container may have all the connections saturated, and if a new container is required to handle the load it may not be able to create the new RDS connection it needs to do it's work.

Without knowing more about the rate at which this is happening, it can be hard to advise, and using Lambda like this requires extensive testing to ensure smooth operation. In a lot of situations, it is ideal to put some kind of caching layer between your worker and your database to help deal with problems like this.

Using EC2, connection pooling is easier to manage because a single instance can track the state of its connection pool without issue. Using EC2 there is a significantly reduced risk of running out of connections in RDS. Lambda is designed to work better when it can just hit an API and doesn't have to connect to a DB engine.

I'm sorry that there does not exist a complete solution for your use-case  but just suggestions. I hope you find this information helpful. Please feel free to reach back out in case you have any additional questions regarding this.

Best regards,

Pratik J.
Amazon Web Services

**Comment by Dayjo** [comment]
@phikes  My issue so far has been that some of the lambdas can take time. For instance image processing lambdas that get metadata and insert into the database, this will hold on to the lambda for up to 60 seconds sometimes. In this instance really you just want to create the connection on the handler so it doesn't create X empty connections or whatever. Searching is another one that takes a little longer and in the meantime while it's running another lambda or two could run at the same time and set up connections. 

I think my solution may have to be a combination of the two. For  Lambdas I consider that will take a 'long' time, I will use a single connection which will be closed after use, for Lambdas that will be quicker, concurrent and regularly called I will attempt to use connection pools.

**Comment by jakubknejzlik** [comment]
If it helps anyone, I was able to solve this issue by lowering MySQL's `wait_timeout`  settings (from 28800s to 600s). IMO the reason that the connections stay open is that the AWS Lambda freeze the function after sending response. So any scheduled timer that can close the connection (that are sitting in pool) won't run (only in cases when the function runs for long time or continuously serving requests)...that's the reason why lowering the `wait_timeout` helps, because the MySQL server is taking care of closing the connections.

**Comment by Dayjo** [comment]
@jakubknejzlik interesting, thanks for this, I shall certainly give it a go!

**Comment by mfrye** [comment]
I'm having decent success with what Pratik J. suggested. There's still a few idle connections, but it's a lot better than what it was before now that it's reusing connections.

I'm using Postgres, which doesn't seem to have a wait_timeout like @jakubknejzlik mentioned. So I'm first going to see how this does for a bit, then the next idea I'm considering is running a separate lambda cron to check for idles. I was looking at this for reference http://stackoverflow.com/questions/13236160/is-there-a-timeout-for-idle-postgresql-connections. I figured I'd share that if anyone was interested.

Thanks for all the help on this issue.

**Comment by dagumak** [comment]
@mfrye How did that cron turn out for you? Did you end up going with another solution?

**Comment by aditp91** [comment]
I was able to solve the issue by modifying my MYSQL settings:

```
{
  ...
  pool: {
       idle: 1000
       ...
  }
}
```

**Comment by marcogrcr** [comment]
Keep in mind that AWS has released a product for AWS Lambda called [Amazon RDS Proxy](https://aws.amazon.com/rds/proxy/) where you don't have to worry about connection pooling and you can create a new connection for every request.

Additionally, if you use `new Sequelize({ pool: { max: 1 }, /* (...) */ })` (common config for AWS Lambda functions based on the fact that Lambda containers only process one request at a time) and use `Model.findAndCountAll()`, you may experience `SequelizeConnectionAcquireTimeoutError` errors for expensive (latency-wise) queries. See #12633 for more details.

**Comment by marcogrcr** [comment]
For people experiencing issues in AWS Lambda, I have created a pull request that documents how to properly configure `sequelize` for Lambda. Hopefully you'll be able to see it in <https://sequelize.org/master/manual/aws-lambda.html> once it gets merged. In the meantime, please check #12642 out and provide feedback if you find any inaccuracies or space for improvement.

**Comment by prashant9428** [comment]
> 

This could be helpful for your senario where you probaly dont have heavy load, just think your api is serving heavy request and you are doing DB connection / closing the connection in each request will be very expensive operation. This will also endup causing slow api response + cost you more money in RDS.
