### ISSUE TITLE
unexpected _previousDataValues when calling .update(Attributes) method

### ISSUE THREAD

**Issue by mitjacotic** [sequelize/sequelize#4979]
Coming from prehistoric 1.6 version to the latest I get this unexpected behaviour, where `_previousDataValues` and `changed` props indicate no change after `update()` method is called.

for example:
```javascript
some_model
  .findById(1)
  .then(function (item) {
       return item.update({field: 'new value'})
  })
  .then(function (updated_item) {
       // updated_item._previousDataValues.field IS SAME AS updated_item.field 
  })
```

this happens because `update()` just combines `set()` and `save()` methods
`set()` method already correctly sets _previousDataValues
but then
`save()` [method does similar thing all over again and overrides them so that they indicate no change.](https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L685) (if I comment out this forEach block I get desired results in this case).

I know about hooks and will now have to refactor lots of code to use them, but my question is if this is intentionally so, or is it a bug? Maybe `update()` method could set some prop/whatever which would then be checked in `save()` method to avoid this problem?

**Comment by janmeier** [comment]
I believe this is intentional - `changed` stores if the value has been changed since it was loaded from the database, and when you call update the value is synced to the db, which means that model and the db have the same values - thus nothing is changed

**Comment by mitjacotic** [comment]
Hmm ok, I'll move to hooks then. But I liked previous flow better:) Thanks for the reply!

**Comment by pensierinmusica** [comment]
@janmeier this was very confusing for me as well...

From the docs I expected `instance.previous('property')` to return the value that the property had before being updated on the db through `instance.update({property: 'newValue'})`.

It turns out instead that once the instance is updated on the db `instance.previous()` is useless, since it works only to compare values before persisting the instance.

Could we please make this more clear in the docs? Thanks!
