### ISSUE TITLE
Is it POINT already supported?

### ISSUE THREAD

**Issue by feniixx** [sequelize/sequelize#4980]
I'd like to start using POINT in Sequelize, is it supported, any example of using it?, How do I create a migration with a column type point?

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/blob/master/test/integration/model/geometry.test.js#L71

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
