### ISSUE TITLE
bulkCreate skips validators

### ISSUE THREAD

**Issue by igittGit** [sequelize/sequelize#5023]
Is it supposed to be that bulkCreate does not make use of the validators?

```javascript
email: {
	type: DataTypes.STRING,
	allowNull: false,
	validate: {
		isEmail: true
	}
},
```

works for create:
` Contact.create({email: "abc"})` => `Validation error: Validation isEmail failed`

but not for bulkCreate:
`Contact.bulkCreate([{email: "abc}])` =>
```
INSERT INTO `contact` (`id`,`email`) VALUES (NULL,'abc')
```

sequelize v3.13.0
node v4.2.2
mysql

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L2040
validate is false by default for bulkCreate

**Comment by sylv3r** [comment]
@mickhansen I still noticed this "feature" as of today, which is an issue.

Since validate is false by default, you did not explain though how to turn it on.
adding `validate: true` along with other options to the model init method does not seem to help.

**Comment by nandanv2702** [comment]
I'm running across this problem too even after adding `validate: true` in the options. Does anyone know how to solve this? @sylver @mickhansen

**Comment by sylver** [comment]
Sorry @nandanv2702 It was a few years ago and I don't use Sequelize anymore (for various reasons that are out of the subject).

I dug into my old projects using Sequelize and apparently I made my own `bulkCreate` method in a custom `Model` class as a workaround at that time.
A lot of things have changed in Sequelize since then, so I'm surprised you still have this weird issue.

You can try to patch Sequelize and submit a new PR though, that should be a doable one, have a look in the method if anything stands out :

https://github.com/sequelize/sequelize/blob/56bb1d6ef9827f604d7bcef945abb7e213f2322d/lib/model.js#L2519

Cheers

/R

**Comment by nandanv2702** [comment]
Just looked into this issue more, turns out there was something wrong in my code (debugging ftw 🙃) `validate: true` works as expected now. Sorry about that!

**Comment by seunAwonugba** [comment]
Pass validate true in the bulk create method

e.g

`const createEventAvailability = await EventAvailability.bulkCreate(
            eventAvailability,
            { validate: true }
        );`
