### ISSUE TITLE
Do not set any transaction values unless explicitely defined by user or required by dialect.

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#5094]

**Comment by janmeier** [comment]
Re-open - Still needs to fix autocommit @sushantdhiman

**Comment by sushantdhiman** [comment]
Ok I thought this issue was specifically for isolation level. I will check what we can be done for autocommit.

**Comment by sushantdhiman** [comment]
Hi @janmeier , I think issue can be close because of these facts

- `MySQL` needs the `AUTO_COMMIT` query. `Postgres` will only send this when supported [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query-generator.js#L889). `Sqlite` don't support it, so we don't send it in that case. ( its already fixed )

- We can't merge the `START TRANSACTION` with `ISOLATION_LEVEL` because of cross dialect support. While `MySQL` and `Postgres` will allow it, `MSSQL` doesn't support this. `MSSQL` not only require different queries but also have different naming convention like `BEGIN TRANSACTION`. ( It will complicate code if we try to merge them )

Let me know what you think ?

**Comment by mickhansen** [comment]
@sushantdhiman No reason to send one at all for postgres unless specifically asked by the user. For MySQL i guess we'll have to.
