### ISSUE TITLE
Recent Commit Broke Attributes

### ISSUE THREAD

**Issue by atom0s** [sequelize/sequelize#5192]
In a project that I work on, the following commit has caused a lot of our queries to now fail:
https://github.com/sequelize/sequelize/commit/4aff3ae71e1c94b6454d25cfecc5912aed3cf796

Specifically the change to lib/model.js

This change overrides if you manually set attributes to collect and causes queries to fail. Perhaps this should be checked if attributes contains data already, if not then create an empty array instead. Otherwise this is a breaking commit that causes valid queries to now fail.

Based on the tests, the intended implementation of this fix is to be used while scopes are defined. If no scope is given, this commit breaks working code.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/5057

The code needs to be changed so that it's possible to apply scope without applying attributes.
The assumption and the tests for count has unfortunetaly been that we use the primary key, and users use `Model.aggregate` for more custom stuff, but obviously we do want to fix this regression.

**Comment by atom0s** [comment]
Thank you for your response @mickhansen I didn't realize there was another ticket already for the same issue, sorry about that.
