### ISSUE TITLE
Better way of importing models

### ISSUE THREAD

**Issue by afaayerhan** [sequelize/sequelize#5341]
sequalize models have to imported and with sequelize.import. talking about the express example. is there other ways which we could import our models directly in diffrent parts of app like one can do in mongoose?

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

If you import your models once, you can access them through `sequelize.models.NAME`

**Comment by sushantdhiman** [comment]
You can `require` this [file](https://github.com/sequelize/express-example/blob/master/models/index.js ) in your application.

```
-app
--model
---index.js
---users.js
---usermeta.js
--server
---app.js
```

in `app.js` you can just `require('../models')`; All the models are in this include. So you can just

```
var models = require('../models');

models.users.create({
 name: 'Hello',
 class: 'Five'
});
```
