### ISSUE TITLE
Custom join conditions during include.

### ISSUE THREAD

**Issue by dcbrwn** [sequelize/sequelize#5385]
Right now, when one wants to include some associated model, he needs to pass "include" option to Model.find*. I noticed that regardless of what I'll pass as "include.where", query always contains "a.{key} = b.{key}' right after 'ON' keyword.

I have specific problem (http://stackoverflow.com/questions/35278428/sequelize-js-how-to-create-non-trivial-associations-without-raw-sql) that can be simply solved by allowing user to override 'ON' clause. All I need is Just:

```js
// Nasty hack to allow include, since there is no other way to make joins.
Service.hasMany(ServiceGroup, { foreignKey: 'serviceCodePrefix', constraints: false });

Task.findAll({
  include: {
    model: Service,
    include: {
      model: ServiceGroup,
      where: [' "service"."serviceCode" LIKE ANY("serviceGroup"."serviceCodePrefix") '],
    },
  }
});
```

If there is a better solution, I'd be very happy to hear it!

**Comment by mickhansen** [comment]
We have experimantal support for `include.on`, you can give it a try.

**Comment by dcbrwn** [comment]
Works like a charm! Thanks!

**Comment by mickhansen** [comment]
Make sure to have good test coverage on this since it's not yet a well tested feature.

**Comment by dcbrwn** [comment]
Also I'm worrying about that nasty hack, which I need to allow `include` to work. Maybe there should be an option like `customAssociationMechanism: true | false` in association definition methods (.has*/belongsTo*)?

**Comment by simonv3** [comment]
is `include.on` documented anywhere?

**Comment by allisonking** [comment]
`include.on` worked for me as shown in #5551:

```javascript
{
  model: models['table1'],
  include: [{
    model: models['table2'],
    on: { '$table1.item_id$' : {$col: 'table2.item_id'}}
  }]
}
```
You might need to change the names of `table1` and `table2` depending on your associations (e.g. if nested, `parentTable.table1` or depending on the association, might need to pluralize to `table2s`)

**Comment by chirag2120787** [comment]
I tried this but it resulting in error : Unhandled rejection SequelizeEagerLoadingError: table2 is not associated to table1!

**Comment by overflowz** [comment]
bump, I'm, getting same error:

`SequelizeEagerLoadingError: X is not associated to Y!`

So basically I still have to define relationship even though I don't really need it? 😕

**Comment by JayDing** [comment]
As above, all of them can not work

I wrote like this, and it worked for me
```
on: {
	'star': { [Op.eq]: sequelize.col('characters.star') },
	'id': { [Op.eq]: sequelize.col('characters.id') }
}
```

**Comment by patricktyndall** [comment]
Chiming in after getting this working. This is extremely useful for e.g.:
- using `include` for array-based associations which aren't FKs (see [popular issue](https://github.com/sequelize/sequelize/issues/2752) on this)
- using `include` for any arbitrary associations that may be useful but not conveniently associated in DB (e.g. I could implement custom JOIN ON from `thread` table to `user` table to implement a `thread.latest_message_from_user` obj field in an API, without having to change my data modeling or second round-trip to DB).

Main pitfalls rn are:
- knowing what query aliases to use
- what to put in the association `foreignKey` field (because my tables weren't associated, I didn't have an actual FK to put in. I just used the PK name of the target table, so sequelize wouldn't try to guess a colname and select it)
- using `separate: true` does not work with associations created this way

Hope this gets more support & [documentation](https://github.com/sequelize/website/issues/93) soon!

**Comment by Senkai350** [comment]
Is include.on now works if i try to include m2m relationship through junction table? I tried to add "on" in include statement but sequelize simply ignore it. Also through options object doesn't have 'on' property at all.
