### ISSUE TITLE
warning: Promise was created in a handler but was not returned from it :(

### ISSUE THREAD

**Issue by ORESoftware** [sequelize/sequelize#5391]
I see this error/warning a lot and have to admit that I haven't figured out the real cause of it! :(

In an Express router.delete call:

```js
router.delete('/:id', function (req, res, next) {

    var id = req.params.id;
    UserModel.destroy({where: {id: id}}).then(function (result) {  // error is for this line
        return res.json({success: result});
    }).catch(function (err) {
        return next(err);
    });

});
```

can someone please help so I can get rid of this warning once and for all?

Is it because I am returning something, but res.json does not return a promise? I assume that this is it.
thx

**Comment by yonjah** [comment]
This is more of  a `bluebird` issue than `sequelize`
`res.json` and  `next` are callbacks that don't return any value but to actually get this warning they need to create a Promise inside them which I don't think they do. 
You can try returning `null` from the promise and see if it suppresses the warning
```javascript
 UserModel.destroy({where: {id: id}}).then(function (result) {  // error is for this line
        res.json({success: result});
        return null;
    }).catch(function (err) {
        next(err);
        return null;
    });
```

If it doesn't your issue is in a different place.

If you have a lot of code like this you might prefer to configure bluebird to suppress those warning globally -
http://bluebirdjs.com/docs/api/promise.config.html
(But you'll miss the benefit of seeing this warning when you actually forget to return a Promise)

**Comment by mickhansen** [comment]
There might be some issues in the sequelize codebase still aswell, but we're removing them as we track them down
