### ISSUE TITLE
Relations

### ISSUE THREAD

**Issue by kkuehm** [sequelize/sequelize#5422]
I'm pretty new with a lot of this in general. Luckily my question is high level!

Is any functionality lost from either table if the association is used on one table?

Example with one:
- Book.hasOne(Author)

Example with both sides:
- Book.hasOne(Author)
- Author.belongsTo(Book)

I don't see any clear recommendation one way or another. I want to be able to use the magic on both tables but wasn't sure if each required a specific statement to one another.

If both examples work, I'd like to know which one is ideal. Or if one causes problems I'd really like to know.

Thanks!

**Comment by mickhansen** [comment]
You only need both if you need to queyr from both sides.

**Comment by kkuehm** [comment]
Thanks a bunch. Have a great day!

**Comment by ms88privat** [comment]
@mickhansen could you please clarify for me this question:

If I write my own SQL queries, I only need it "one-sided" (e.g. hasOne OR belongsTo), because I don't need the provided ORM Model functionality and the ORM Relation doesn't add anything new to the table in regards to indexes or something like that, right?

So, if I have this:

UserRating.belongsTo(User, {as: 'user', foreignKey: 'userId'});
UserRating.belongsTo(User, {as: 'ratedUser', foreignKey: 'ratedUserId'});

I don't need to add this:

User.hasMany(UserRating);

Thank you very much!

**Comment by janmeier** [comment]
@ms88privat User hasMany UserRating allows you to do `user.getUserRatings`. The database structure will be the same as long as you set up one side of the relation
