### ISSUE TITLE
Model destroy with individualHooks doesn't call hooks in related models

### ISSUE THREAD

**Issue by intiQuo** [sequelize/sequelize#5439]
Hi!

We have two models: 
```javascript
var User = sequelize.define('user', {
    name: {
        type: Sequelize.STRING
    }
}, {
    hooks: {
        afterDestroy: function (item, options) {
            console.log('USER: afterDestroy');
        },
        afterBulkDestroy: function (item, options) {
            console.log('USER: afterBulkDestroy');
        }
    }
});

var Profile = sequelize.define('profile', {
    name: {
        type: Sequelize.STRING
    }
}, {
    hooks: {
        afterDestroy: function (item, options) {
            console.log('PROFILE: afterDestroy');
        },
        afterBulkDestroy: function (item, options) {
            console.log('PROFILE: afterBulkDestroy');
        }
    }
});

User.hasMany(Profile, {onDelete: 'CASCADE', hooks: true});
Profile.belongsTo(User);
```

When we destroy user by model: 
```javascript
User.destroy({where: {id: 1}, individualHooks: true}).then(function (result) {
        console.log(result);
    });
```

In console we can see that:
```javascript
USER: afterDestroy
USER: afterBulkDestroy
```

But Profile hooks doesn't calls. 
For correct hooks calling we need to get an instance of user, and destroy it.
Why does ```IndividualHooks: true``` not call hooks in related table?

**Comment by mickhansen** [comment]
The hook is simply run when using bulkDelete with individual hooks.
If you want cascade resolution, that's only supported with instance.destroy atm

**Comment by intiQuo** [comment]
Thanks!

**Comment by cjuega** [comment]
Is this going to be supported any time soon? It seems this is happening in master branch's code.

It's kind of confusing to have different behavior between instance and model methods. I would expect both to behave the same. If not, I think it's very helpful to document this difference between instance and model methods.

I would agree this is not an issue with regular associations because sequelize relies on database FK management. That ensures associated records will be deleted by the database directly. However, the behavior is quite different when we talk about polymorphic associations. In that case, FK constraints are disabled and hence, associated records remain there.

Use case:

```js
let ModelA = sequelize.define('modelA', {
      ...
      objectType: {
         type: DataTypes.STRING,
         allowNull: false,
         validate: {...}
   }, {
      classMethods: {
         associate: (models) => {
            models.modelA.belongsTo(models.modelB, {
               constraints: false
            });
         }
      }
   }
);

let ModelB = sequelize.define('modelB', {
      ...
   }, {
      classMethods: {
         associate: (models) => {
            models.modelB.hasMany(models.modelA, {
               onDelete: 'cascade',
               hooks: true,
               scope: {
                  objectType: 'some filtering value'
               }
            });
         }
      }
   }
);
```

Code below deletes any associated modelA too.
```js
return ModelB.findById(4)
   .then((instance) => {
     return instance.destroy();
   });
```

Code below doesn't delete associated modelA.
```js
return ModelB.destroy({where: {id: 4}});
```

I'm wondering if extending `queryInterface.bulkDelete` would be enough.  Would it be as easy as taking cascade management code from `delete` into `bulkDelete`? I'm not very familiar with Sequelize source code, but after a quick review it seems it might work.

So far, the only workaround I can think of is removing `onDelete` and `hooks` properties from modelB definition. Then, implement custom beforeUpdate/beforeDestroy hooks + transactions in order to mimic the behavior.
