### ISSUE TITLE
Using an alias for included model causes eager load to fail

### ISSUE THREAD

**Issue by edude03** [sequelize/sequelize#547]
I'm having anissue with the eager loading feature that according to the documentation should work.

If I have

``` javascript
Team = sequelize.define('Team', {
    teamname: Sequelize.string
});

User = sequelize.define('User', {
    username: Sequelize.string
});

Team.hasMany(User);
User.belongsTo(Team, {foreignKey: 'team_id'});

Team.findAll({include: [{model:User, as: 'Players'}]}).success(function(teams){
}
```

I get User (Players) is not associated with Team!

however removing {as: 'Players'} from the query causes it work as expected. What I'm trying to do is have each team include an array of Players instead of Users, though the underlying table is called Users.

Am I going about this wrong, or is this a legitimate bug?
Thanks!

**Comment by cubo1123** [comment]
one of my biggest problems using ES6 to declare the associations it was because the static method is never called by himself so i has to call it before start doing requests
`
const schema = new ApolloServer({
  typeDefs,
  resolvers,
  playground: {
    endpoint: "/graphql"
  },
  context: {
    CostPostgreSql: CostPostgreSql.init(sequelize),
    PricePostgreSql: PricePostgreSql.init(sequelize),
    ProductPostgreSql: ProductPostgreSql.init(sequelize)
  }
});
ProductPostgreSql.associate(sequelize);
PricePostgreSql.associate(sequelize);
CostPostgreSql.associate(sequelize);

const app = express();
schema.applyMiddleware({ app });

app.listen(3000, () => {
  console.log("Live on http://localhost:3000/graphql");
});

`

i declare my relations as follows in the products model, the id of each product is inside of each cost and price element so i use belongsTo when the id is going to be on the source and hasMany when the id is going to be on the target
```
static associate({ models }) {
    this.belongsTo(models.Unit, { foreignKey: "id" });
    this.belongsTo(models.Provider, { foreignKey: "id" });
    this.hasMany(models.Cost, { foreignKey: "product" });
    this.hasMany(models.Price, { foreignKey: "product" });
  }
```

and on the costs and prices models i declare something like `
  static associate({ models }) {
    this.belongsTo(models.Product, { foreignKey: "id" });
  }`
to the moment of make a query i did something like 
```
import { CostPostgreSql } from "../models";
import { PricePostgreSql } from "../models";
db
    .findAll({
      where: { id },
      include: [
        {
          model: CostPostgreSql
        },
        {
          model: PricePostgreSql
        }
      ]
    })
    .then(response => {
      console.log("Exito");
      console.log(JSON.stringify(response));
      return response;
    })
    .catch(err => {
      console.log("fracaso");
      console.log(err);
      return err;
    });
```
