### ISSUE TITLE
Need to get executed sql query after find/ findall

### ISSUE THREAD

**Issue by fabuhelow** [sequelize/sequelize#5470]
Hi,

I'm trying to get executed sql query after fetched the result, so is it possible to get query statement.

E.g.

Model.findAll(...).then(function(data)
{

// need to get executed sql query "select id,name from model where id = 12";
 
});  

Any help please.

Thanks,

**Comment by janmeier** [comment]
`findAll({ ...,  logging: function (sql)  ... })`

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by fabuhelow** [comment]
Thanks janmeier,

But i need the query inside then directive, so is it possible to pass it inside .then callback function ?

**Comment by janmeier** [comment]
Have the logging function store it in a variable variable

```js
var sql; 
findAll({ ..., logging: function (sql) ... }).then(function () {
 // do something with sql
});
```
