### ISSUE TITLE
Save/update model with association

### ISSUE THREAD

**Issue by carrbrpoa** [sequelize/sequelize#5471]
I'm implementing some RESTful stuff and now trying to update a model which it's children can be new or not:

``` javascript
router.put('/projects/:projectId', function (req, res, next) {
    models.database.transaction().then(function (t) {
        var project = models.Project.build(req.body, {
                isNewRecord : false,
                include : [{
                        model : models.Sprint,
                        as : 'sprints'
                    }
                ]
            });

        Promise.all([project.save({
                    transaction : t
                }), project.sprints.map(function (sprint) {
                    if (sprint.getDataValue('id')) {
                        return sprint.save({
                            transaction : t
                        });
                    } else {
                        sprint.projectId = project.id;
                        return models.Sprint.create(sprint, {
                            transaction : t
                        });
                    }
                })]).then(function (response) {
            t.commit(); //Debug enters here...
            return res.json(response);
        }, function (err) {
            t.rollback(); //...not here
            if (err.message === 'Validation error') {
                res.status(403);
                res.send(err);
            } else {
                next(err);
            }
        });
    });
});
```

So, assuming I pass one `sprint` with `id` and another without it, I was expecting an update in the first one and an insert in the second, but what I see is a `notNull Violation: name cannot be null` 
supposedly from the `sprint` that needs to be inserted - which is not the case, the `name` is there (I'm using node-inspector); also, it doesn't enter in the callback error function, but it actually commits the transaction, that apparently updates `project` and the first (not new) `sprint`.

There's a better way to do what I'm trying to achieve? Did something wrong?

![name_required](https://cloud.githubusercontent.com/assets/10212618/13225201/99153b40-d96a-11e5-9412-fce8623e41f6.png)

![exception](https://cloud.githubusercontent.com/assets/10212618/13225205/a0ad7f7a-d96a-11e5-8860-bc6534b10446.png)

PS1: The same happens with `upsert` command, but this way it seems to also complains about the first `sprint`'s name.
PS2: The same happens without transaction.

Thanks

**Comment by mickhansen** [comment]
When using `include` with build and then save you'll trigger the the nested creation code path. After that you then yourself save and create (duplicates most likely).

I can't specifically say what's going on here, too much going on.
Try including the stack as text and highlighting that line so we can see where the error starts.

**Comment by carrbrpoa** [comment]
Thanks for the reply @mickhansen. Here it goes:

```
 [31mUnhandled rejection SequelizeValidationError: notNull Violation: name cannot be null
    at C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\lib\instance-validator.js:74:14
    at tryCatcher (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:491:31)
    at Promise._settlePromise (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:676:18)
    at Promise._fulfill (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:617:18)
    at PromiseArray._resolve (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:553:26)
    at Promise._settlePromise0 (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:676:18)
    at Async._drainQueue (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\async.js:125:16)
    at Async._drainQueues (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\cesar.ribeiro\Trabalho\workspace\manage-lite-rest\node_modules\sequelize\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)[0m
```

Seems that the error is popped when all the promises are resolved, or something like that.

PS: I have no requires for `Promise` I'm using in my code above because I understood it's sequelize's built-in.

**Comment by mistercorea** [comment]
I am stuck on similar issue.

When i tried to create joined model, It will validate and create the first model then it will invalidate on second one.
Now If i am trying to create again it will fail on first model's validation because it already created the fist data model and unique column validation will throw an error.

For example 
```
Model.create(obj).then(function(model){
    model.createModel2(obj)
},function(err){next(err)
})
```


What I would like to do is 
```
Model.build(obj).validate().success(
    function(){Model2.build(obj).validate().success(function(){
        Model.save(function(m){
            Model2.save(function(m2){
                m2.setModel(m)
            })
        })
    }).error(function(e){next(e))
}).error(function(e){next(e))
```
If there is better way to do this I would love to know.

**Comment by mickhansen** [comment]
@mistercorea `save` doesnt take a callback like that, we use promises

**Comment by mistercorea** [comment]
ahhhhhh THANKS !!! 

below code works.
Model.build(obj).validate().then(function(e){console.log(e)})

But shouldn't be catch instead of using then? because validation throw an error??

**Comment by mickhansen** [comment]
@mistercorea validate will return validation errors unless it failed executing, you can use hookValidate for it to throw when theres a validation error (not completely logical i know).

**Comment by ybrodsky** [comment]
Isn't there any way to do this somehow simplier?
For example in my case.

model City hasMany CitiesDescription

So I can do:

`models.City.create(data, {include: [models.CitiesDescription]})`

This works great and as expected.

Now, updating is a different issue.
I have implemented a solution similar to @carrbrpoa and it works. The problem is that if my data doesn't include CitiesDescription, it breaks.
Anyway, it looks way too farfetched... Isn't there a way to do something like this:

`
models.City.update(data, {
where: {
  id: recordID
},
  include: [models.CitiesDescription]
})
`

So that it updates whether my data contains an array for CitiesDescriptions or not and will update those records that should be updated and create those that should, inside that array.???

**Comment by mistercorea** [comment]
So is there anyway do a validation before I create a row to associated table?

For example, if first validation passes then it will create a row by Model.create() then if associated Model2  failed to validate then createModel2 will not get written. Now i have half written and half not written.

That is why i tried to validate with build().validate() but id wont associated to each other.

I have to hard code the relationship. Is there a better way to do this, with or without using non-persistent instance?

**Comment by mistercorea** [comment]
@mickhansen I have a quick question if I want to build, validate then save two associated models.
I have to manually assign the foreign key ID to associate
```
data[0].dataValues.id = data[1].dataValues.id
```
where data is array of the models.
at the end i am doing something like
```
data.forEach(function(modelObj){
      savedObjs.push(modelObj.save())
})
Promise.all(savedObjs).then(function(){
      return res.send('OK');
})
``` 

Is this possible? because i cant find any documentation or people using build() to build associated model objects.

**Comment by mickhansen** [comment]
@mistercorea Validation happens automatically on create, why not just use a transaction?

**Comment by mistercorea** [comment]
@mickhansen I would like to know all the errors from multiple models, instead of tell me some error from one model then if I fixed the error then it tell me other errors from the other model.

I used first example from http://docs.sequelizejs.com/en/latest/api/transaction/ .

For me solution was some what troublesome. I build each objects then to validation. 
If there is any errors i dont save it.

```
arrayObjs.forEach(function(obj){
    let sqlizeObj = obj.build(input);
    retArrayObjs.push(sqlizeObj);
    errArrayObjs.push(sqlizeObj.validate());
  })
```

No one has this problem?

**Comment by mickhansen** [comment]
@mistercorea Your issue is with control flow, not with Sequelize - So finding others with the exact same problem is likely hard :)

Promise join method generally reject on the first error, but you could possible looking at using `hookValidate` + `settle` (http://bluebirdjs.com/docs/api/reflect.html)

**Comment by mistercorea** [comment]
@mickhansen I am little confused.

```
sequlize.transaction(function(t){
    return Model1.create({JSON}),{transaction:t})
    .then(function(m1){

    }}

**Comment by mickhansen** [comment]
@mistercorea Almost nothing in Sequelize is sync. Not sure how the piece of transaction code you listed is related, didn't you just say you wanted all errors?

**Comment by mistercorea** [comment]
@mickhansen yes, but if i get an error from Model1 I wont get error from Model2.
settle/reflect needs to have their own Promise object returned.

So I cant do m1.createModel2 because that has to have m1 object return from first promise.

I am not sure how people do validation for associated models and save it all together.
I have create my own way but it's not pretty or organized.

**Comment by mickhansen** [comment]
@mistercorea And that's why i told you to look at reflect, it will return the promise no matter if it fails so you can inspect

**Comment by bbuddha** [comment]
@mickhansen This issue was logged for discussing Save/Update model and its associations. Still not very clear if original issue logged by @carrbrpoa has been completely addressed. 
All I want to know is .. Does Sequelize JS support this feature?
1) When updating model (parent), with hasMany association(children), will sequelize update changes to children and create new children if they are new?

**Comment by ryan-ds17** [comment]
Please can someone provide a working example of creating and/or updating models along with associations?

**Comment by ryan-ds17** [comment]
Is it possible to update the model along with the association as @ybrodsky has mentioned?

**Comment by theill** [comment]
I've found http://docs.sequelizejs.com/manual/tutorial/associations.html#creating-with-associations useful with some good examples of how to create models along with associations.

**Comment by ameeakshay** [comment]
I also had a similar issue, I just changed the attribute for allownull to true(in your case probably for name), not sure how it was solving this particular notnull violation, even though for my case it always had a default value.

**Comment by cgomezmendez** [comment]
I have a similar problem
I have a belongsToAsociation non nullable but when I try to insert it with association it says I cannot insert because foreignKeyId is null.

**Comment by kennylbj** [comment]
Sooooo is there a clean solution for updating the model along with the association?
Something like updating model along with ```include```?

**Comment by kennylbj** [comment]
suppose we have ```document``` and ```tag``` model.
```js
// document
const Document = app.model.define('document', {
  id: {
    type: INTEGER,
    primaryKey: true,
    autoIncrement: true, 
    allowNull: false
  },
  name: STRING,
}

// tag
const Tag = app.model.define('tag', {
  id: {
    type: INTEGER,
    primaryKey: true,
    autoIncrement: true, 
    allowNull: false
  },
  documentId: INTEGER,
  name: STRING,
}
```

Then we could update document along with it's tags by:
```js
const updates = {
  id: 100,
  name: 'Java Concurrency in Practice',
  tags: ['java', 'concurrent', 'multi-thread'],
}

const document = this.ctx.Document.findById(updates.id);

// find the tags belongs to that document
const tagIds = document.getTags().map(tag => tag.id);

// bulk delete
await this.ctx.model.Tag.destroy({
  where: {
    id: {
      [Op.or]: tagIds,
    },
  },
});

// bulk create
await this.ctx.model.Tag.bulkCreate(updates.tags.map(tag => ({
  ...tag,
  documentId: document.id,
})));
```

I have to admit that this approach is quite not elegant though.  :-(

**Comment by NicolasNarvaez** [comment]
Why is not this backed into sequelize itself?, it wont be difficult to just add a recursive description of update behaviour for n-ary associations and a transaction tag, among others. 
Also, on the find, etc, the "includes" argument seems incomplete for me, it also should accept dynamic recursions for trees. I have found myself expanding trees very often.

**Comment by tizzyapunkt** [comment]
Is there any news on that? Whilst create + save with associations is possible as stated by the docs the following is stilll not possible, right?

```
 // find one user by filter query and include tokens
const user = await User.findOneBy({where: ..., include: [Tokens]})

// creating some updated token
const newToken = {
token: 'tokenstring'
...
}

// adding the new token to the previously fetched user
user.setDataValues('tokens', [newToken])

// persisting the updated model
await user.save();
```

The above code does not persist the new token data. 
When logging out the model, I can see `_changed: { tokens: true }`, so the change is basically recognized but not persisted.

Do I miss something or is persisting and updated-previously-fetched model not possible that way?

**Comment by papb** [comment]
> Why is not this backed into sequelize itself?, it wont be difficult to just add a recursive description of update behaviour for n-ary associations and a transaction tag, among others.

I disagree. It is difficult (relatively)... Doing nested updates is definitely nontrivial because deciding whether the nested objects are new or just changed from one that already exists is nontrivial. To me, at least.

If anyone is willing to submit a PR that would be great. However, before doing that please make sure you define what behavior are you exactly going to implement and let me know so I can agree with it first, in order to not waste anyone's time.

Thanks!!

**Comment by mohammednadeem772** [comment]
Hello guys,
Is there is a way to use include in PUT method like this

const newProduct = req.body;
        db.products.update(newProduct, where: { id: req.params.id },{
            include: [
            { 
                model: db.variants, 
                as: 'variants' ,
            },
        ],}).then(product => {
            res.json(product);
        }).catch((err) => {
            res.status(500).send(err);
        });

**Comment by papb** [comment]
After further investigation, this is indeed not possible currently, the issue #6808 tracks the feature request to enable this.

I will leave this open for now simply as a documentation issue, in order to make it clear in the documentation that this is currently not supported. The feature request itself should be tracked in #6808.

**Comment by papb** [comment]
This has been centralized in #11836

**Comment by pashka4281** [comment]
> > Why is not this backed into sequelize itself?, it wont be difficult to just add a recursive description of update behaviour for n-ary associations and a transaction tag, among others.
> 
> I disagree. It is difficult (relatively)... Doing nested updates is definitely nontrivial because deciding whether the nested objects are new or just changed from one that already exists is nontrivial. To me, at least.
> 
> If anyone is willing to submit a PR that would be great. However, before doing that please make sure you define what behavior are you exactly going to implement and let me know so I can agree with it first, in order to not waste anyone's time.
> 
> Thanks!!

I'd argue this,
it's pretty simple to implement,
just check if the nested object has id property. If it does - it's an existing record and we should be doing updates, otherwise - new record and we do insert.
That's exactly how Rails is doing it.

so 
```json 
{
  "firstName": "John",
   "Addresses": [
     {"id": 1, "streetName": "Church str"},
     {"streetName": "Brookers lane"}
   ]
}
```

assuming User.hasMany(Address)
the first one should be updated and the second one inserted

**Comment by sergiomendonca** [comment]
> > > Why is not this backed into sequelize itself?, it wont be difficult to just add a recursive description of update behaviour for n-ary associations and a transaction tag, among others.
> > 
> > 
> > I disagree. It is difficult (relatively)... Doing nested updates is definitely nontrivial because deciding whether the nested objects are new or just changed from one that already exists is nontrivial. To me, at least.
> > If anyone is willing to submit a PR that would be great. However, before doing that please make sure you define what behavior are you exactly going to implement and let me know so I can agree with it first, in order to not waste anyone's time.
> > Thanks!!
> 
> I'd argue this,
> it's pretty simple to implement,
> just check if the nested object has id property. If it does - it's an existing record and we should be doing updates, otherwise - new record and we do insert.
> That's exactly how Rails is doing it.
> 
> so
> 
> ```json
> {
>   "firstName": "John",
>    "Addresses": [
>      {"id": 1, "streetName": "Church str"},
>      {"streetName": "Brookers lane"}
>    ]
> }
> ```
> 
> assuming User.hasMany(Address)
> the first one should be updated and the second one inserted

no way its trivial. You are talking about a 1-1 association. Try it for any associations in any levels. Example: Customer > Address > Address Phone .   Customer-Adress: 1-n, Customer-Adress Phone: 1-n . I think it is very important in sequelize to have this, but its not trivial.
