### ISSUE TITLE
Create with association to existing objects

### ISSUE THREAD

**Issue by matejcik** [sequelize/sequelize#5583]
The docs state that:

> An instance can be created with nested association in one step, _provided all elements are new._

It would be extremely useful to have this work with existing instances as well.

---

As it stands, when I have a model with two non-null foreign keys in belongsTo relationship, there are two ways to create it:

Either set the foreign key field directly, which requires using foreign key field names:
```
ModelName.create({ foreignRelationId: foreignInstance1.keyId, foreignRelation2Id: foreignInstance2.id })
```
Which gets awkward when the foreign keys are not called what you expect, or when the relation is on a non-primary-key field, or something like that.

Or use the setters and specify `{save: false}`.
```
model = ModelName.build({ /* plain properties */})
model.setFK1(foreignInstance1,  {save: false})
model.setFK2(foreignInstance2).then( /* ... */ )
```
or maybe call `model.save()`. Anyway, with more foreign keys, this gets awkward fast, IMO it's already awkward enough with two ;)

Using the instances directly would be much cleaner.

**Comment by mickhansen** [comment]
There are already existing issues for this.
The issue is non trivial since knowing whether or not something already exists requires a database lookup.

**Comment by Pat-rice** [comment]
@mickhansen #3071

**Comment by abelosorio** [comment]
Hi! I'd really love to have this feature in.

@mickhansen @janmeier Could this issue be re-opened and have further discussion?

@matejcik how did you manage this?

**Comment by stoffern** [comment]
@mickhansen good idea to reference issues here before closing.

**Comment by sasha-borodin** [comment]
@mickhansen  - I apologize if this suggestion is naive, but why do you need to validate that target entity's existence eagerly?  Why not set whatever internal state is appropriate (ex. the foreign key when .set() is called for a BelongsTo property), and let the database worry about validating referential integrity when .save() is called?

Also, could you reference existing issues that request this feature, so that those interested can contribute to discussion and follow those?

Thank you!

**Comment by mickhansen** [comment]
@sasha-borodin I'm no longer involved with maintenance of Sequelize

**Comment by papb** [comment]
Duplicate of #5325
