### ISSUE TITLE
Rename Sequelize.import() function, because "import" is ES6 reserved word

### ISSUE THREAD

**Issue by ivosabev** [sequelize/sequelize#5638]
Calling this inside ES6 file gives Syntax error, I would suggest using a different name for this function.

**Comment by Etzos** [comment]
If this is raising an error then the ES6 interpreter is in error. ES6 proper allows keywords and reserved words to be used as properties of objects[1]. Since this is Sequelize.import() and not just import() it should be just fine.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_word_usage
