### ISSUE TITLE
Mocking sequelize

### ISSUE THREAD

**Issue by davidleureka** [sequelize/sequelize#5645]
I've been looking at sequelize and have a little experience using it. So far I'm pretty impressed with it. One area that I'm not finding a lot of information on is unit testing, particularly mocking sequelize so that I can write unit tests without needing an actual database. Does sequelize have direct support for this?

If not, what are the recommendations? Introducing a data access layer to abstract away sequelize and mocking that layer?

**Comment by sobotklp** [comment]
I recommend using an in-memory SQLite database when running unit tests. Then, you can run your tests against a "real" database, but the results are thrown away after the test runner finishes. It's also pretty straightforward to write a fixture loader for your Sequelize models so you can preload data into before your test cases run.

Generally, I prefer not having to write mocks in all my tests; in my opinion that leads to a lot of duplicated code and makes tests harder to write and understand.

**Comment by davidleureka** [comment]
Thanks for the response sobotklp. I don't want to start a religious war over testing methodologies, but I believe that mocking does have its place and it would be great to know if sequelize had any direct support for it.

**Comment by sobotklp** [comment]
Not a religious warrior over here. :) Just relating what's worked well for me. I still use mocks pretty commonly for behaviour verification. 

To answer your question more directly, I haven't seen any internal support within Sequelize for creating mock objects.

Check out these issues for more info: https://github.com/sequelize/sequelize/issues/2961 and https://github.com/sequelize/sequelize/issues/1721

**Comment by davidleureka** [comment]
Amen, I appreciate the input! The mock dialect is an interesting idea but seems like a lot of work. I think I'll probably go with my own data access layer.

**Comment by mickhansen** [comment]
We've only just recently (last year or so) started unit testing our codebase internally. Previously we were fanatic about having everything be integration tests since we feel it offers a more real world coverage. 

Test performance has had us look a little more at unit testing, especially for minor stuff like verifying correct options and call patterns.

We don't currently have any tools to help stub/mock but i could see an addon suite for something like it. At the lowest level you need simply mock out sequelize.query() to return a promise, that way we'll never hit the database since all methods go through `query`.

**Comment by jez9999** [comment]
Using an in-memory SQLite database breaks down if you're using features unique to PostgreSQL or something.

**Comment by ktsashes** [comment]
FYI for anyone who is checking on this issue going forward, we created a basic mocking library for Sequelize to do this sort of mocking without a DB. You can find it on [npm](https://www.npmjs.com/package/sequelize-mock) or on [github](https://github.com/BlinkUX/sequelize-mock). Also, it's in development and PRs are accepted for anyone who wants to contribute.

**Comment by jedwards1211** [comment]
I'm looking into this because I've been using a real connection to Postgres in my tests, but it leaves open connections even after I call `sequelize.close()`, keeping my test process from ending.

I think the best approach is to mock the connection to Postgres, and not touch Sequelize at all.
Unfortunately since Sequelize doesn't yet support the latest major version of `pg`, if that module enables some kind of mocking in the near future, we won't be able to use it until Sequelize supports the latest version.

**Comment by jedwards1211** [comment]
@mickhansen actually after thinking about this some more, wouldn't it be best if Sequelize itself has a mock mode without any connection to a database whatsoever, where `Model` instances live only in memory?

Obviously it would be a lot of work and probably none of us have the time for that :smile:
