### ISSUE TITLE
How to define temporaly non-db Models?

### ISSUE THREAD

**Issue by faiwer** [sequelize/sequelize#5668]
Hi. I'm wanna using sequelize models with validation and other API without real database tables. On fly... Wanna create and destroy model for every request. It's may be useful on specific forms or business logics. Unification.

How do right that? Currently I did that:
```js
options.sequelize = app.db; // already exists Sequelize instance
_.each(scheme, (v, k) => { v.fieldName = k; });
const model = new Sequelize.Model(name, scheme, options);
model.init({ sequelize: options.sequelize }); // rude hack :-(
```
I thinks it's not right way. How I can do it safely? Without memory leaks… Without excess linkage...

P.S. sorry for my bad english

**Comment by sushantdhiman** [comment]
You don't need the models to validate a form, you can easily do that by [validation schema](https://github.com/guillaumepotier/validator.js#validate-an-object). Doing that using models will be an overkill and add unnecessary complexity

**Comment by faiwer** [comment]
I need also getters, setters, instanceMethod, etc... Not only validation. Wanna working with data on one way. May be also relations...

**Comment by sushantdhiman** [comment]
relation without tables?

**Comment by faiwer** [comment]
Yeah. Why not? ;) hasOne, belongsTo... Without throught table.

**Comment by sushantdhiman** [comment]
`User` hasOne `Team` , this relation is 1:1 relation, your model will not have at least one table. So kind of 1:0 relation because other item doesn't exists anywhere. Can you elaborate your specific use case ?

**Comment by faiwer** [comment]
My current case: admin module for site settings. Tree of options. Every site module can add options to tree. Every option can have specific scheme... With validations, methods, may be relations. As result data of every option saving in posrgre json field. 

I'm already have many DAO trait methods for moderating. Have some system for moderate most of available records. And I wanna use it for site settings option schemes too. 

But I think tha using many many models at one time - bad idea. I wanna some of it create and destroy on the fly. 
Also I think this mechanism will be good for custom forms.

**Comment by sushantdhiman** [comment]
If I understand this correctly...
- You have nested settings to manage
- You want to be able to perform validation on each option
- Accessing related relation for a setting when required (for display or validation check)

Since they are nested you want to be able to perform the validation on each sub tree as dynamically generated model. Tables are not created until you actually call `sync` so you should be able to generate them on fly and use `validate` then destroy them later on.

But I think you should permanently maintain the nested settings in M:N related models...
- They are already having defined parent child relation
- You will have access to DAO, validation for each settings model
- M:N actually depict your requirement

It looks like some work to go by M:N approach but that will be far cleaner approach then generating models on fly and doing some magic :)

**Comment by faiwer** [comment]
Tree is static. Loaded from config. Some options can be overrided form database. Admin page using for setting additional values for options, instead default. Each option can have default value (from config files), overrided value (universal), and one value for each language. Not simply, yes? :)

Table (for overrided default values):
![img_29_03_14 27 28_441c86c710d](https://cloud.githubusercontent.com/assets/744114/14102115/79ff63f4-f5ba-11e5-8f73-8eecc0f9ffe1.png)

UI:
![img_29_03_14 18 43_9fa2b834302](https://cloud.githubusercontent.com/assets/744114/14101891/2f7068d4-f5b9-11e5-8787-e45ef0111bb1.png)

I need not parent-child relations, because scheme is static. Also I'm can have from 1 to 1+langlist.length overrided value (storing in database). And each option can have self scheme...

I can register this pseudo-models for options sub-sub-value on the fly after sync (because this pseudo model will not have table.. it only json-value in exists table). But pseudo-models may be many... 100+. I think I need method for unload it from models-manager. 

In Sequelize files I see
```js
Sequelize.prototype.define = {
  // ...
  // if you call "define" multiple times for the same modelName, do not clutter the factory
  if (this.isDefined(modelName)) {
    this.modelManager.removeModel(this.modelManager.getModel(modelName));
  }
}
```
That: `modelManager.removeModel`. Can I use it? Or it is inner private sequelize code?

### Also

I think I can use pseudo-model in diferrent situations. In compound forms (which haven't database tables) example. But I found nothing about pseudo-models in documentation. :)

**Comment by sushantdhiman** [comment]
Tree is static but it still have parent child relation may be something like this

```
-System
---Control
------A
------B
------C
------D
---Web
------A
------B
------C
```

In you case child parent relation may be too fine grained, that it will be difficult to have model for each property. Why don't use a single (or set of a few parent M:M) model and have required validation in `beforeValidate / afterValidate` hook. Each model can valid its child properties. Obviously it will require to get rid of JSON storage of settings and convert it to related models.

If you can't get rid of JSON storage and still want to emulate sub childs as virtual table I guess it will be difficult because Sequelize is SQL based ORM and emulating JSON as table is not support currently (may not be in future as well).

You can generate model on fly with validation rules for sub child properties and then validate the entire chain of tree one by one. But its will be same as writing validation schema for each model again :)

As to answer your question for removing model, We generally do have access to ModelManager so there should be no problem using the method. (But I have never unloaded a model in my practice so I don't know the side effects)

**Comment by faiwer** [comment]
> Why don't use a single (or set of a few parent M:M) model and have required validation in beforeValidate / afterValidate hook

Big overhead. 95% of options will not be overrided. It means that 95% record in database will excess. Also this tree will be loaded for every app-instance in cluster... Loading all records for each option from database at each instance start... My task is simplier. [Yii Form Model](http://www.yiiframework.com/doc/api/1.1/CFormModel) <-- I mean somethink like this. Also, changing option overrided values - very rare operations.

> As to answer your question for removing model, We generally do have access to ModelManager so there should be no problem using the method.

Nice, thanks.
