### ISSUE TITLE
How to get id from

### ISSUE THREAD

**Issue by AndrewBryukhov** [sequelize/sequelize#5704]
What is a best way to get ids (autogenerated primary keys) from this code?:

```
    return locations.bulkCreate(names);/*.then(function () {
        //return locations.findAll();

    });*/
```

After return i can see new models, but inside id = null.

**Comment by janmeier** [comment]
`returning: true` if you are on postgres or mssql, otherwise you'll have to `find` http://docs.sequelizejs.com/en/latest/api/model/#bulkcreaterecords-options-promisearrayinstance

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
