### ISSUE TITLE
Could i use both "hasMany" and "belongsTo"??

### ISSUE THREAD

**Issue by zzaemok** [sequelize/sequelize#5798]
It's my code:
```js
  defineRelationship(() => {
    models.Project.hasMany(models.Participation, {as: 'participations', foreignKey: 'projectId'});
    models.User.hasMany(models.Participation, {as: 'participations', foreignKey: 'userId'});
    models.Participation.belongsTo(models.Project, {as: 'project', foreignKey: 'projectId'});
    models.Participation.belongsTo(models.User, {as: 'user', foreignKey: 'userId'});
  });
```

Sequelize version: 3.20.0
Could i use both `hasMany` and `belongsTo`??
I want to use `Project.getParticipations()` with `Participation.getProject()`.
It will be a problem?

**Comment by janmeier** [comment]
Shouldn't give you any problems at all :)

You might also want to have `Project.belongsToMany(User, { through: Participation }`, which allows you to do `project.getUsers()`

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by zzaemok** [comment]
Thanks for your kind answer, and sorry.
I will use  Slack, StackOverflow, etc to do next questions
