### ISSUE TITLE
Bug: query postgresql schema fails

### ISSUE THREAD

**Issue by RichardJECooke** [sequelize/sequelize#5864]
Hi. It looks like sequelize does not create SQL statements for schemas correctly:

Steps to recreate:

1) In a new postgres database run

```
CREATE TABLE dbo.wallets
(
	wallets_id uuid PRIMARY KEY NOT NULL DEFAULT uuid_generate_v1mc(),
	created_at timestamptz not null default CURRENT_TIMESTAMP,
	updated_at timestamptz not null,

	confirmed_balance bigint,
	unconfirmed_balance	bigint
);

insert into dbo.wallets(updated_at, confirmed_balance) values ('2012-01-05', 50.0)
```

2) Run the following code

```
const options = {};
options['timestamps'] = true;
options['createdAt'] = 'created_at';
options['updatedAt'] = 'updated_at';
options['underscored'] = false;

options['paranoid'] = false;
options['deletedAt'] = false;

options['freezeTableName'] = true;
options['tableName'] = 'dbo.wallets';

const entity = {};
entity['wallets_id'] = {type: Sequelize.UUID, primaryKey: true, allowNull : false};
entity['confirmed_balance'] = Sequelize.BIGINT;
entity['unconfirmed_balance'] = Sequelize.BIGINT;

model = db.define('dbo.wallets', entity, options);
model.all().then(function(results) { console.log(results[0]); }
```

3) Get the error:

```
Executing (default): SELECT "wallets_id", "confirmed_balance", "unconfirmed_balance", "created_at", "updated_at" FROM "dbo.wallets" AS "dbo.wallets";
Unhandled rejection SequelizeDatabaseError: relation "dbo.wallets" does not exist

```
The expected SQL this query should generate should be 
```
FROM dbo.wallets
```
or even
```
FROM "dbo"."wallets"
```

**Comment by RichardJECooke** [comment]
Ah, by stepping into the code I see there's an options property called 'schema' that seems to work. 

But it's not in the documentation anywhere I can find. **Please will you add it** - this is essential for new Sequelize users who are using postgres.

**Comment by janmeier** [comment]
http://docs.sequelizejs.com/en/latest/api/sequelize/?highlight=schema#definemodelname-attributes-options-model

http://docs.sequelizejs.com/en/latest/api/sequelize/?highlight=schema#syncoptions-promise

Both show `schema` as an option

**Comment by janmeier** [comment]
Additionally, you can use the [`schema`](http://docs.sequelizejs.com/en/latest/api/model/#schemaschema-options-this) method on a model to define the same model in multiple schemas

**Comment by RyanThomas73** [comment]
@janmeier Can you clarify what you mean by using the "schema" method on a model to define it in multiple schema? More to the point can you clarify if the behavioral differences between options.schema in the define options and calling schema on the model itself described below are intentional? If they are intentional I would recommend updating the schema method documentation to be clear on this point and include a link to the define options.schema for users who are looking for that functionality.

The documentation for the schema method is not clear. I'm using the angular-fullstack yeoman generator. Prior to finding this issue I had not yet found the options.schema in the documentation and had been trying to set schema this way.

// product module
...
   return sequelize.define('Product', { /** attributes **/ }).schema('SchemaName');
....

// db def and sync logic created by yeoman generator
...
db.sequelize = new Sequelize(uri, options);
db.Product = db.sequelize.import('path/to/product/model');
...
db.sequelize.sync()

This was not behaving as I expected it to. The sequelize.sync() call ignores the fact that I've called schema('SchemaName') on the product model and instead creates the table in the 'public' schema in postgres. Additionally if I follow the db seeding pattern included in the generator like so:

db.Product.sync().then(() => do some dev server db seeding)

then the Product.sync() call creates the table as "SchemaName"."Product" but the later
db.sequelize.sync() call still ignores the schema and creates a 2nd copy of the Product table in public.

**Comment by janmeier** [comment]
@RyanThomas73 That is the correct behaviour, although I can see why it might be confusing. 

If you need a single default schema per model, use `options.schema`

If you need multiple schemas with the same model (for example if each tennant has their own database use `.schema` - and use it every time. In this case you probably wont use `sequelize.sync`, but call `model.schema().sync` for each model to ensure the models are created in the correct schema.

A docs PR to clarify the differences would be very welcome :)
