### ISSUE TITLE
Nested creation should use bulkCreate when array is provided

### ISSUE THREAD

**Issue by masad-frost** [sequelize/sequelize#5890]
Suppose we have `Author` and `Books`, with a `BookAuthor` junction. Obviously that's 2 belongsToMany through `BookAuthor`. Doing a nested creation of author with multiple books, I expect, at most, 3 queries, instead I get a query for each row.

``` js
Author.create({
  name: 'John Doe',
  age: 40,
  gender: 'Male',
  Books: [
    { title: 'FirstBook', Pages: 300 },
    { title: 'SecondBook', Pages: 400 },
    { title: 'ThirdBook', Page: 200 },
}, { include: [Books] });
```

This executes **7** insert queries, one for `Author` creation, three for `Books` (one each), and then three more for the `BookAuthor` table.

It's not a big deal as I could just do `Author.create` normally and then `Books.bulkCreate` then `BookAuthor.bulkCreate` (with a simple `.map` on books).

**Comment by evenfrost** [comment]
Up.

**Comment by mountaindude** [comment]
Old thread, I know.

I am struggling with this though.
I have a data structure three layers deep, where the middle layer is an array that may contain 100k values. Which takes a loooong time to insert one by one into the db.

I can write the top level to db just fine, and I can write the lower two levels using a bulkCreate with an include option making sure the 3rd level is brought in too.

The problem is that when I look in the db for the 2nd level, the foreign key field pointing to the top layer is just NULL.
For some reason the bulkCreate doesn't understand that there is a level above it, so to speak..

@masad-frost any hints on how you'd implement this? Sounds like you had it figured out...

Thx!

**Comment by mountaindude** [comment]
Never mind, I figured it out.
I was looking for a solution using some aspect of Sequelize, but it was way simpler than that. 
@masad-frost suggestion about using a .map and adding the missing foreign key to the data before it's sent to bulkCreate worked a treat. 


```
var res = extract.articles.map(function (o) {
    o.extractId = result2.id;     // extractId linked to the id field of the table about it in the db
    return o;
});

...bulkCreate(res1, ...)
```
