### ISSUE TITLE
Add NUMERIC data type to the SQLite dialect

### ISSUE THREAD

**Issue by koistya** [sequelize/sequelize#5927]
As of now, the following code:

``` js
db.createTable('Post', {
  id: {
    type: DataType.INTEGER,
    primaryKey: true,
  },
  isApproved: {
    type: DataType.NUMERIC, // <=
    defaultValue: 0,
  },
});
```

...generates this SQL schema:

``` sql
CREATE TABLE `User` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `isApproved` DECIMAL DEFAULT 0 # <= Shouldn't it be NUMERIC?
);
```
##### Reference

https://www.sqlite.org/datatype3.html

**Comment by janmeier** [comment]
Numeric maps to the decimal datatype behind the scenes: https://github.com/sequelize/sequelize/blob/3d14a4a63b2b8ecc517cb03e8d4ed59b1d177132/lib/data-types.js#L964

In sqlite numeric = decimal, so the end result should be the same :) https://www.sqlite.org/datatype3.html#section_3_2

**Comment by koistya** [comment]
Wouldn't it be better to generate SQL schema in dialect's lingua? E.g. use `NUMERIC` instead of `DECIMAL`, this way it will be clear that the column's affinity is `NUMERIC` without a need to memorize how SQLite converts types to affinities behind the scene.

**Comment by janmeier** [comment]
Sure. The easiest fix would probably be to change the`toSql` function on decimla for sqlite to return numeric instead of decimal https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/data-types.js, https://github.com/sequelize/sequelize/blob/3d14a4a63b2b8ecc517cb03e8d4ed59b1d177132/lib/data-types.js#L382
