### ISSUE TITLE
How to use MySQL VIEW model in sequelize

### ISSUE THREAD

**Issue by ymyang** [sequelize/sequelize#5934]
I use a MySQL VIEW model in sequelize.

when i use the find method,it throws an error:

 SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'

**Comment by janmeier** [comment]
You'll have to give some more information than that - what does your model definition and you view look like? If your primary key is different from `id` you can use `primaryKey: true` on the column defintion to mark it as such. Otherwise you can use `removeAttribute('id')` to have a table without primary key

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
