### ISSUE TITLE
Fillable 

### ISSUE THREAD

**Issue by CanKer** [sequelize/sequelize#5945]
Hello, do you have a fillable option like Eloquent?  where you chose the fields you wanna write. Ive been looking at the documentation but havent found anything... maybe didnt look well, but if I did well It would be nice if you include. 

Greetings 
```
protected $fillable = ['name'];
```

https://laravel.com/docs/5.2/eloquent

**Comment by alitaheri** [comment]
A lot of functions provide `fields` in their options bag, you can use that to simulate `fillable`.

creation: 
http://docs.sequelizejs.com/en/latest/api/model/#createvalues-options-promiseinstance
update: 
http://docs.sequelizejs.com/en/latest/api/instance/#saveoptions-promisethiserrorsvalidationerror
http://docs.sequelizejs.com/en/latest/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows

All support `fields`

**Comment by janmeier** [comment]
You could also use SSACL attribute roles https://github.com/mickhansen/ssacl-attribute-roles

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by CanKer** [comment]
@alitaheri Yeah, I just was thinking about that... my bad and sorry for the request. xD

**Comment by CanKer** [comment]
@janmeier thank you so much
