### ISSUE TITLE
Don't monkeypatch global bluebird Promise

### ISSUE THREAD

**Issue by mirek** [sequelize/sequelize#5974]
Can we avoid monkeypatching global bluebird Promise like this https://github.com/sequelize/sequelize/blob/master/lib/promise.js#L27 ?

Ie. by making it an optional (in some kind of init(...) function) or just use sequelize's own Promise object "inherited" from bluebird?

**Comment by janmeier** [comment]
I believe we actually did use our own version of bluebird at some point (`Promise = require('bluebird/js/release/promise')()`) - do you remember why we don't anymore @overlookmotel @mickhansen

**Comment by overlookmotel** [comment]
@mirek The monkey patching in `promise.js` is to support CLS for automatic transaction passing. It can't be removed without breaking the CLS support as bluebird's author isn't willing to support CLS within bluebird itself.

Can I ask what the problem with monkey-patching bluebird is?

Personally I think it'd be better if Sequelize used it's own instance of bluebird, rather than monkey-patching the global instance of bluebird (which an app author would get when using `require('bluebird')`. Is that the problem you're encoutering @mirek?

@janmeier This was a bit before my time, but I think Sequelize used to use a customised bluebird instance which also had some aspects of an Event Emitter to support `.on('sql')`.

**Comment by janmeier** [comment]
Ah okay - yes we definitely used a custom instance when we had event emitters. We might have switched back to regular bluebird when that was removed and forgot to switch back when the shims were added

**Comment by overlookmotel** [comment]
@mirek Can you say what problem you're having with bluebird being patched?

**Comment by felixfbecker** [comment]
How about  [`Promise.getNewLibraryCopy()`](http://bluebirdjs.com/docs/api/promise.getnewlibrarycopy.html)

**Comment by overlookmotel** [comment]
@felixfbecker Yes, I totally agree. I think we should use an independent instance of bluebird Promise constructor.

**Comment by overlookmotel** [comment]
PR #6135 submitted to make `Sequelize.Promise` an independent copy of bluebird.
