### ISSUE TITLE
Utils._ (lodash)

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#5992]
In utils.js we can find this piece of code:

``` js
const _ = require('lodash').runInContext(); // Prevent anyone messing with template settings by creating a fresh copy
```

So we are requesting out own instance of lodash that nobody has tempered with. However, all over the codebase lodash is most of the time required directly. Even more, this special instance is not even safe because in sequelize.js we can find:

``` js
/**
 * A reference to sequelize utilities. Most users will not need to use these utils directly. However, you might want to use `Sequelize.Utils._`, which is a reference to the lodash library, if you don't already have it imported in your project.
 * @property Utils
 */
Sequelize.prototype.Utils = Sequelize.Utils = Utils;
```

So we actually export this special lodash instance (and I don't understand why - users can easily install require lodash themselves)

**Comment by janmeier** [comment]
Yeah, if we're switching all usage of lodash templating to template strings there's no really any reason to have a lodash reference in utils. 

Originally we used run in context because a user reported problems with template strings - lodash allows you to override which characters are used in templates. But as you noticed, we're not using it  anyway...

**Comment by janmeier** [comment]
Actually I think I we should remove the mention of utils completely from the docs

**Comment by mickhansen** [comment]
Agreed, utils and lodash are internals.
All SQL will likely be template strings in the future anyways.

**Comment by felixfbecker** [comment]
Can we keep this open until lodash is actually removed from Utils?

**Comment by overlookmotel** [comment]
Sorry, I know this is closed and committed now. But...

I think some of Utils would be good to remain as documented. In my sequelize plugins, I use for example `Sequelize.Utils.pluralize()`. Accessing this function via `Sequelize.Utils` rather than requiring a `inflection` independently ensures that the plugin is in "sync" with the version of Sequelize that it's attached to.

**Comment by overlookmotel** [comment]
Maybe only document a subset of `Utils` and make it clear in the docs that they're only there for plugin developers?

**Comment by janmeier** [comment]
Yep, sounds like a good idea - Perhaps we could document it in the wiki instead of the docs site then. Less chance that normal users will stumble upon it

**Comment by felixfbecker** [comment]
My original issue was only about removing lodash from utils (and docs) :D

**Comment by felixfbecker** [comment]
still valid :)

**Comment by yonjah** [comment]
I think this change is a bit misleading - https://github.com/sequelize/sequelize/commit/49ac4c4fe9e0e1e42482e67bada5d0bd2a10d9cc

Marking it as private with no context but still exposing it explicitly (and as `.Utils` not even `.utils` or `._utils`) is basically contradicting it being private.

If I understand the discussion correctly it shouldn't be private since it is supposed to be used by plugin authors.
Sorry for being a bit anal about many trivial issues with 4.X but it seems like many changes were made without thinking of their full impact and the stability of the API. As a user I can not know if this will still be available on future 4 versions or is it might be removed at any time.

**Comment by felixfbecker** [comment]
@yonjah `Sequelize.Utils` was never documented API: https://sequelize.readthedocs.io/en/v3/
So this was not a change for v4.
As said in this thread, it is not meant for normal users, but there is a use case for plugin authors.
This issue is open for over a year now and there were several prereleases, imo plenty of time to participate in the discussion and make your voice heard ;)

**Comment by yonjah** [comment]
@felixfbecker I highly value the hard work you @janmeier and @mickhansen  put in this project.
I've been using Sequelize in my project since version 2 was in rc and I tried to contribute code and fixes when possible. I'm sure many contributors were following the discussion and issues a bit closer than I did but I doubt most of them are.
Since noticing the project mindshift i've been trying to follow it a bit more closely (by actively watching it) and the amount of issues being raised here require a full time team to keep track on (I was on vacation for two weeks and got more than 400 notifications for that time for this project alone).

This just put in perspective the hard work you guys are doing here which is highly appreciated,  but it also means that other than the very few people commenting on each issue and almost nobody is aware of the discussion.

You can see it in this issue where @overlookmotel after the code has changed and he noticed it breaks his plugins.

What I'm saying a adding a `private` comment to somewhere that will only be in the docs a year from when it was added changes nothing, breaks nothing, and so for most users this change has never happened.
If this is really meant to be private it should be private if not it shouldn't anything in between is just poor design that will cause stuff to break eventually.

I know you guys have a lot on your plate and sometimes stuff goes unnoticed and mistakes happen. But I'm finding more and more that when issues are raised and pointed at instead of addressing the actual issue and finding a way to solve it I'm getting responses that are not the the point about how my input is not welcome cause its too late now to change anything.

As owner of this project this is your decision to respond this way but personally it makes me wonder for how long I'll be able to keep relying on this project

**Comment by felixfbecker** [comment]
I don't understand the issue here. `Utils` wasn't documented before. With the switch from JSDoc to ESDoc, it needs to an `@private` tag to not show up in the public (user) documentation. So literally nothing changed, it's the same as before. The public API is defined by what is documented, ESDoc tags are just a way to generate this documentation.

Do you have a specific use case for `Utils`?

> the amount of issues being raised here require a full time team to keep track on

this. it applies to us as well, we are not a full time team.

**Comment by yonjah** [comment]
`Utils` was documented as part of the public API - 
https://sequelize.readthedocs.io/en/v3/api/sequelize/#utils

Other than having a custom relationship extension that uses all the pluralization methods,  I have some code generating complex sql queries and I'm using `mapOptionFieldNames` to create queries that can be selected into an existing model instance.

It would have been much nicer if Sequelize had a custom query builder but this feature have been  discussed for years (https://github.com/sequelize/sequelize/issues/394) so I doubt if it will happen any time soon.

Any way I can work around this limitations but since the only way I can see it working is for duplicating and maintaining `mapOptionFieldNames` in my own code, this will be much more fragile than using `Utils` as long as it is available so I rather not do the switch unless I have to.

This is not a technical issue but a stability one.
All I care is understanding how stable the API is.
As it stands now and maybe due to an error v4 was released where the `Utils` is exposed and part of the public API. Even that the documentation is inconsistent with the actual API (and the discussion here  since plugin authors wont be able to use it if its private).

Can I rely on it to stay as part of the public API for V4 ?
If not is there any other places where API is planned to be changed without following semver ?
Is there any other mistakenly exposed properties that are supposed to be private ?
What best practice plugin authors should follow in this case ?

**Comment by felixfbecker** [comment]
Right, but the individual contents of utils besides lodash were not.

All the thought behind this is we want to _discourage_ people to use utils. It is not _mistakenly exposed_, it was exposed before, and will likely continue to be. You can always do `require('sequelize/lib/utils')` anyway. The old docs said 

> However, you might want to use Sequelize.Utils._, which is a reference to the lodash library, if you don't already have it imported in your project.

That is what we want to discourage, if you need lodash, you should import it yourself, because there may come a time when Sequelize will not need Lodash anymore. Libary reexports are an antipattern. Other utils don't really have a thought-through API and are added as-needed for internal usage, so they are there, but I am hesitant to document them and commit to this public API without discussing what the ideal API for the specific use cases would look like.

> If not is there any other places where API is planned to be changed without following semver ?

Unless I am missing something, nothing here was changed without following semver and nothing is planned to change without following semver.

**Comment by yonjah** [comment]
As long as it actually going to be exposed through 4.x I'm good with it.
It doesn't fell like the best practice to expose a private feature but I can live with it.

And I totally agree that 3rd party libraries should be imported by the user and using them from inside sequelize doesn't add much while increasing the chance for breaking things.

It would be great if there was a public API for tapping into Sequelize query building and creating more advance queries so I won't need to rely on private API and less documented features but I understand this is not a simple task.
