### ISSUE TITLE
Partial models

### ISSUE THREAD

**Issue by KieronWiltshire** [sequelize/sequelize#6000]
Is there a way for me to define a partial model?

I have an application which generates tables and handles them accordingly, I want to only partially modify this table in sequelize though, I want to create a model that will only extend the table by 2 columns and will only allow updates to them two columns, is this achievable without knowing the full table structure?

**Comment by janmeier** [comment]
We don't have any inherent support for that in sequelize, and I don't think its something that would fit well in core either. But it should definitely be achieveable.

If you don't need to know _anything_ at all about the other columns, you should be able to simply define a model with only those two columns, and sequelize will only be able to select and update those two.

If you want to be able to fetch the data for the other columns but not update it, have a look at `before(Bulk)Update` hooks, or perhaps https://github.com/mickhansen/ssacl-attribute-roles

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
