### ISSUE TITLE
Tests fail on non-english Postgres installation

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6033]
It seems like Sequelize does assumptions on the error messages, which are automatically localized. Maybe it should rather look at error codes? 

[test_results.txt](https://github.com/sequelize/sequelize/files/300942/test_results.txt)

**Comment by mickhansen** [comment]
@felixfbecker It does look at error codes, but to extract error details we need to parse text.

**Comment by felixfbecker** [comment]
Why is this closed? What are users of localized database versions expected to do?

**Comment by janmeier** [comment]
They can't rely on message, fields etc, but can still use the error type, since that is identified from the error code. We can't begin to handle parsing in different locales.

If the program is crashing because of something being undefined we can definitely fix that, bug we shouldn't begin to parse in other languages
