### ISSUE TITLE
Cast column to date 

### ISSUE THREAD

**Issue by keyursakaria** [sequelize/sequelize#6060]
Can anyone help me with sequelize query of below given query ?

select * from ev_events where DATE(event_date) <= '2016-10-10'

**Comment by janmeier** [comment]
`where: sequelize.where(sequelize.fn('DATE', sequelize.col('event_date')), '2016-10-10')`

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by keyursakaria** [comment]
Thank you so much
