### ISSUE TITLE
ESLint plugin for sequelize

### ISSUE THREAD

**Issue by alecxe** [sequelize/sequelize#6111]
I hope this is an appropriate place to ask about that.

I am willing to build a ESLint plugin specifically for Sequelize to statically catch Sequelize code-style violations (https://github.com/alecxe/eslint-plugin-sequelize). Though, I have not seriously brainstormed that at this point and need an initial "boost".

What ESlint rules would you like to see implemented? What do you think are the most common Sequelize code style violations?

Would appreciate any pointers. Thank you.

**Comment by sushantdhiman** [comment]
I am not sure if this feature is supported in ESLint by default but I would definitely recommend these cases

```js
/** bad case **/
function(){ 
}

/** good case **/
function() {
}
```

And for `if` too

```js
/** bad code **/
if(){
}

/** good code **/
if () {
}
```

We are still using JSHint but we are going to switch soon https://github.com/sequelize/sequelize/issues/5963

**Comment by alecxe** [comment]
Thanks. I think we have a bit of a misunderstanding here. My bad, I should have provided a sample use case.

What I want to build is a ESLint plugin that would catch `Sequelize`-specific code style violations in user's codebases. In other words, if a user uses `Sequelize` but in his/her code there are things to improve. Let's take this example from Issue #222:

```
User.findAll({
  attributes: ['User.*', 'Post.*', [sequelize.fn('COUNT', 'Post.id'), 'PostCount']],
  include: [Post]
}
```

Here the plugin may issue a warning that `Post.id` should probably be enclosed into `sequelize.col()`:

```
User.findAll({
  attributes: ['User.*', 'Post.*', [sequelize.fn('COUNT', sequelize.col('Post.id')), 'PostCount']],
  include: [Post]
}
```

May not be the best example, but I hope you understand what I mean.

FYI, there are `ESLint` plugins for all sorts of things: https://github.com/tlvince/eslint-plugin-jasmine, https://github.com/alecxe/eslint-plugin-protractor etc.

**Comment by alecxe** [comment]
And, if there is a `Sequelize` style guide or a documented set of recommendations  - the plugin may help to enforce its rules through static analysis.

**Comment by sushantdhiman** [comment]
I can think of at least one @alecxe, User mostly forgot to pass the condition inside the `where`, they try to write something like this

```js
User.findAll({
   name: { 
      $like: '%a%'
   } 
})
```

But it should be 

```js
User.findAll({
   where: {
       name: { 
           $like: '%a%'
       }
   } 
})
```

Your plugin should warn users on all `find*` (except `findById`) methods if they forgot to pass `where`

**Comment by janmeier** [comment]
Interesting idea! I've never considered that you could write specialized eslint plugins:

Some ideas:

* Check for missing return when calling sequelize methods (`.then(function () { Foobar.findAll(); });` is probably missing a return)
* Missing `type` field in model definitions
* Perhaps mis-spellings in model definitions (`autoincrement` with lower case i etc.) - We've had a couple of cases where this was the issue, but it's probably hard to catch them all
* Wrong number of arguments - Specially we've had several people who try to do `define('foobar', attributes, optionsObject, anotherOptionsObject)` - The problem is often due to wonky formatting, so I don't know if people who dont format their code before posting an issue are going to use a linter ;). Would be cool if you could somehow generate the rules based on the method signatures though - Some methods are going to switch from two to one argument in 4.0 so it might be an easy way to catch that
* Generally, everywhere there is a `throw` for missing where / other missing argument we could have a lint check ([e.g. here](https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/model.js#L2421))
* Using `.spread` on methods that return an array of values (for example `Model.update`) - It should only be a warning but I think it would still help. Its hard to detect in all cases since you might return the promise and attach the handler elsewhere, but plain `Model.update().then` could give a warning

**Comment by alecxe** [comment]
@sushantdhiman @janmeier awesome! I'll start with a few and we'll see how it goes..as they say "appetite comes with eating". Thanks for the ideas!

**Comment by SteffenLanger** [comment]
Hey @alecxe,

That's a great idea! Looking forward to using this plugin and maybe even contributing to it.

Some things that come to my mind are:
### Capitalized First Letter
When the model's name starts with a capital letter, people sometimes forget that they have to refer to it with a capital letter when inserting it as a relation. An example might clarify things:
```
sequelize.define('Book', {
  title : Sequelize.STRING
});
Author.hasMany(Book);
Author.create({
  firstName : 'Georg',
  lastName : 'Büchner',
  books : [{ // <-- This won't work since it must read 'Books'
    title : 'Woyzeck',
  }, {
    title : 'Danton´s Death'
  }]
});
```

If I note something during my daily work, I'll be happy to post it here!

Thanks again,
Steffen

**Comment by ewnd9** [comment]
@alecxe https://github.com/alecxe/eslint-plugin-sequelize contains no code. Any updates on progress?

**Comment by alecxe** [comment]
@ewnd9 unfortunately, there is zero progress. I've got distracted and busy with other things, but I still hope I can start working on the plugin. I will really appreciate help with it. Let me know if you are interested. Thanks!

**Comment by mjdavidson** [comment]
Has anyone made any progress on this?
