### ISSUE TITLE
Is it possible to pass the database name in per query?

### ISSUE THREAD

**Issue by KieronWiltshire** [sequelize/sequelize#6174]
So I have an application built, but now I realize I want to be able to sell it as a service (SaaS). Using a machine per application setup is too cost heavy for me, so I want to be able to pass in the database names to my queries, and let me explain why:

So I'll setup unique sub-domains for my customers, example:
dracade.example.com

So, when user's go to:
dracade.example.com/api/user

It will get the sub-domain from the URL and pass that through as the database name in question, this allows me to only scale my application for load-balancing and storage. Is this possible?

So effectively, I want to be able to query something like:

`User.findAll({where: {id: 1}, database: 'dracade'})`

**Comment by janmeier** [comment]
For postgres you can use `searchPath` https://github.com/sequelize/sequelize/blob/66ba16666a11d2481e5e545ea9245f15a96c55bc/lib/sequelize.js#L521

Generally, we recommend a separate sequelize instance for each database

**Comment by KieronWiltshire** [comment]
@janmeier This doesn't work for me as I may eventually end up having hundreds of thousands of instances running :/

**Comment by janmeier** [comment]
Are you going to have hundreds of thousands of instances running simultaneously? In that case you are going to have hundres of thousands of open connections anyway. 

Sequelize is very tied up to the assumption that one instance connects to a database - our whole connection pooling assumption breaks if the same sequelize instance should connect to multiple databases. We would need to have a different connection manager + pool for each database in any case. 

Perhaps consider using separate schemas instead of databases?

**Comment by KieronWiltshire** [comment]
It's not really possible without a massive overhaul to my application. It's okay, I'll be able to manage, I'll just have to setup an instance for each customer, I was just trying to look for a way to cut costs ;)
