### ISSUE TITLE
Create a composite index with associated data?

### ISSUE THREAD

**Issue by kristoffernolgren** [sequelize/sequelize#6228]
I have a User-table and a userAttributes table. Every user can only have one instance of each userAttribute, so I would like to create a composite unique index for the columns name and userId. How can this be done ?

This is what I tried:
```
UserAttribute = sequelize.define('userAttributes', {
    name: {
        type:       Sequelize.STRING,
        allowNull:  false,
        unique: 'nameIndex',
        validate: {
            isIn: [['phone', 'name','driverRequest']],
        }
    },
    value: {
        type:       Sequelize.STRING,
        allowNull:  false
    },
});


User.hasMany(userAttributes, {unique: 'nameIndex'});
userAttributes.belongsTo(User, {unique: 'nameIndex'});
```
(I tried adding the unique nameIndex with no success, it seems to only apply to the name-column.)

**Comment by janmeier** [comment]
Try `User.hasMany(userAttributes, { foreignKey: {unique: 'nameIndex'}});` , or you could add the userId column to the userAttribute model

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
