### ISSUE TITLE
[Question] Advice on unit testing validation errors with model stubs

### ISSUE THREAD

**Issue by lukealbao** [sequelize/sequelize#6231]
## Doing
We use sinon to stub models like so
```js
// test.js
it('creates the thingy', function (done) {
  sinon.stub(db.models.Thing, 'create', function () {
    return Promise.resolve(fixtures.thing);
  });

  // Use supertest to test the http endpoint...
});
```

Cool, works pretty good. But we had a situation where we got to integration testing and found that, although all the unit tests were passing, and the client was adhering to the request body contract (which was the same that was used in unit tests), the client was receiving InternalErrors resulting from Sequelize ValidationErrors.

## Expected
It would be nice – and I realize this may not be possible at the moment – for a model to throw a `ValidationError` even when its query method is being stubbed. 

## Actual
Because the `create` method was stubbed, the test passed, even though it was not using a valid input. 

Perhaps there's another method we could/should be stubbing so that the unit tests work as expected, but we also get proper validation logic out of sequelize when stubbing methods? Or is there another way folks are handling this? Just do everything in integration? Thanks!

__Sequelize version:__ 3.23.4

**Comment by janmeier** [comment]
We don't use validations (other than `allowNull`) in our code, so this hasn't been a problem for us before - we usually also have both unit and integration tests for all endpoints. 

You can perhaps stub out `model.save` - which is what create calls internally. You could also call `validate` manually (but then you of course have to remember to actually do that..)

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
