### ISSUE TITLE
belongsTo & hasMany always throws error

### ISSUE THREAD

**Issue by gauravarora** [sequelize/sequelize#6247]
My model consists of two entities - rooms & shifts.
```
sequelize.define('shift', {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: false
    },
    room_id: {
      type: DataTypes.INTEGER,
      allowNull: true,
      references: {
        model: 'rooms',
        key: 'id'
      }
    }
  }, {
    tableName: 'shifts',
    indexes: [{
      fields: ['room_id']
    }]
  });
```

room (minimal fields):
```
sequelize.define('room', {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },
    shifts: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 1
    }
  }, {
    tableName: 'rooms'
  });
```

I define relations ships as
```
shift.belongsTo(room, {as: 'owner', foreignKey: 'room_id'});
room.hasMany(shift);
```
I always get an error saying
```
Error: Naming collision between attribute 'shifts' and association 'shifts' on model room. To remedy this, change either foreignKey or as in your association definition
```

From the stackoverflow threads I read, I understood that setting __as__ should fix the problem but it doesn't in my case. Am I doing something wrong?

__Dialect:__ postgres
__Database version:__ 9.4
__Sequelize version:__ 3.23.4

**Comment by janmeier** [comment]
You need to add an `as` to the hasMany.

This happens because of eager loading - If you only load room and call `room.get('shifts')` you will get an integer. If you call `room.find({ include: [shift] })`, suddenly `room.get('shifts')` would return an array of shifts - so you need to either provide an alias for the shift association, or rename the shift column 
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
