### ISSUE TITLE
Add DB2 Support

### ISSUE THREAD

**Issue by httpdigest** [sequelize/sequelize#6263]
It would be fantastic to have DB2 support in Sequelize. This would allow us to use it in a corporate environment with one of our customers.

## What you are doing?
Trying to connect to a IBM DB2 database which is part of a AS/400 IBM i Series.

## What do you expect to happen?
I am able to connect to the DB2 database and issue SQL statements.

## What is actually happening?
`Error: The dialect db2 is not supported. Supported dialects: mariadb, mssql, mysql, postgres, and sqlite.
`

__Dialect:__ db2
__Database version:__ v9.7.0.1
__Sequelize version:__ 3.23.4

**Comment by janmeier** [comment]
You are welcome to work on this yourself, but this is not something core of maintainers will have the time to do - it requires a substantial amount of work to make sure all tests pass for a new dialect, and adapt existing code to its oddities. Additionally we'd need some way to test it on Travis. 

We would also very much like the person who contributes this work to commit to maintaining it in the future, since none of us have any experience working with db2. 

I'm closing this, not because this will never happen, but because it would require a substantial outside contribution, and we try to keep the number of open issues down. This is not so much a feature request as an "epic" request ;-). I'd you are up to the task, then please ask away and we'd be glad to answer - just know that it's not an easy task, since we cannot accept he contribution before all tests pass.

**Comment by httpdigest** [comment]
Thanks for replying that quick! :) No problem. Staying with Java/Hibernate for the time being, then.

**Comment by chrisdewar** [comment]
Just came across this because I am looking for the same functionality.

Have you considered pulling out your dialects from the sequelize code and packaging them separately? Then I am free to inject whichever dialect to sequelize I like (rather than selecting from a predefined list), and developers are enabled to create their own dialects...

Let me know if interested :)

**Comment by janmeier** [comment]
@chrisdewar Yes, see https://github.com/sequelize/sequelize/issues/6285 :)

**Comment by felixfbecker** [comment]
@chrisdewar Again, if you want to contribute DB2 support, we would happily accept a PR

**Comment by aaronbartell** [comment]
I am also looking for this capability to connect with DB2 on IBM i (aka iSeries, AS/400).  I have a 1-tier scenario where my Node.js will be running in the PASE** environment on the IBM i. I will look into the code to see what changes would be necessary.  More just logging interest at this point.

** Basically a port of AIX with IBM i as its kernel.

**Comment by bimalkjha** [comment]
https://www.npmjs.com/package/ibm_db has inbuilt support of promises. Do we still require it to be supported by sequelize?

**Comment by aaronbartell** [comment]
Node.js ODBC support for IBM i is in the works which means ibm_db could potentially be used (I haven't tested it yet).  Previous to this reality there was a separate [idb-connector npm](https://bitbucket.org/litmis/nodejs-idb-connector) for Node.js to connect to DB2 for i.

I put my request on hold until the ODBC driver on IBM i can be further tested.

**Comment by bimalkjha** [comment]
@aaronbartell [ibm_db](https://www.npmjs.com/package/ibm_db) is IBM recommended node.js driver for connectivity to Db2 for LUW, Db2 for z/OS, Db2 for i-Series, Db2 on Cloud and Informix database servers from LUW platform. It seems nodejs-idb-connector is for i-Series platform that works for local i-Series server. I would suggest to use ibm_db instead of nodejs-idb-connector. Would request to share your findings using ibm_db. Thanks.

**Comment by I3uckwheat** [comment]
@aaronbartell any updates on this? We really need this.

**Comment by bimalkjha** [comment]
@aaronbartell You can try it: https://github.com/ibmdb/sequelize

**Comment by RabeaWahab** [comment]
Thanks @bimalkjha, I know it is an old thread, but I will definitely try it out, is there a possibility it will be added to Sequalize's main package ?

**Comment by hrmfcis** [comment]
> @aaronbartell You can try it: https://github.com/ibmdb/sequelize

@bimalkjha 
Does this support DB2 on AS/400?

**Comment by aaronbartell** [comment]
I am no longer in the IBM i community and don't have access to an IBM i so I will be unsubscribing from this thread.  I wish you the best as you figure this out.

**Comment by bimalkjha** [comment]
@hrmfcis No. https://github.com/ibmdb/sequelize supports only LUW server and we have tested it against LUW server only. It requires another set of mammoth work to update SQLs in sequelize which is compatible for IBMi. But, https://github.com/ibmdb/ibm_db supports IBMi which is internally used by sequelize. I have not tested https://github.com/ibmdb/sequelize against IBMi to know how much it works and what are the gap to support IBMi. It may work upto some extent and may not work. If you want, you can give a try.
@shilumathai FYI, there is a request to support IBMi for sequelize. Thanks.

**Comment by markdirish** [comment]
A while back, I created a port of sequelize to work with IBM i using the ODBC connector. **This connector requires no license and is the IBM i OSS Team's preferred method of connecting to Db2 for i from open-source software**: https://www.npmjs.com/package/sequelize-ibmi

Over the last year it has fallen further and further behind the upstream Sequelize branch. I will work on getting it back up to date with the latest commits and versions in master and commit to that package. The eventual end goal is to get it to the main upstream package, with a commitment of support from the IBM i OSS Team to support it for all future Sequelize versions.

**Comment by HaithamRashad** [comment]
> A while back, I created a port of sequelize to work with IBM i using the ODBC connector. **This connector requires no license and is the IBM i OSS Team's preferred method of connecting to Db2 for i from open-source software**: https://www.npmjs.com/package/sequelize-ibmi
> 
> Over the last year it has fallen further and further behind the upstream Sequelize branch. I will work on getting it back up to date with the latest commits and versions in master and commit to that package. The eventual end goal is to get it to the main upstream package, with a commitment of support from the IBM i OSS Team to support it for all future Sequelize versions.

@markdirish I have a nodejs application which uses sequelize-ibmi to connect to IBM i database through ODBC, but the application is very slow comparing with the same application which uses the ordinary sequelize to connect to sql database.

Is there any recommendations to solve this slowness when connecting to IBM i database through ODBC and sequelize-ibmi ?

**Comment by bimalkjha** [comment]
I think you opened issue in wrong repository. You should open issue here: https://github.com/markdirish/sequelize-ibmi/issues

Thanks and Regards,
Bimal Jha
Rocket Software
4th Floor, Bay HUB1, Karle Town Centre, Nagawara, Bengaluru - 45
M: +91 9886376749  •  E: bjha@rocketsoftware.com   •   W: www.rocketsoftware.com
