### ISSUE TITLE
upsert return wrong value when insert a row which db has

### ISSUE THREAD

**Issue by daleoooo** [sequelize/sequelize#6310]
If table user has a row like below:

(id, name) = (1, 'daleoooo')

and run code like this

``` js
user.upsert({
  id: 1,
  name: 'daleoooo'
}).then(res => console.log(res))
```

the output will be true, which is obviously not right.
I traced the code, and found [connection.query](https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/dialects/mysql/query.js#L40) returns wrong affectRows.

BTW:
I run the sql as same as the sql sequelize generated in the code above, affected row is 0. 

Thank you for your comments.

**Dialect:** mysql
**Database version:** 5.7
**Sequelize version:** 3.23.6

**Comment by janmeier** [comment]
> If you specify the CLIENT_FOUND_ROWS flag to mysql_real_connect() when connecting to mysqld, the affected-rows value is 1 (not 0) if an existing row is set to its current values.
https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html

The flag is set by default by node-mysql, which means affected rows is 1 when the rows is matched, but nothing is updated.

Can be fixed by setting `flags: '-FOUND_ROWS'` at `createConnection`. This would probably be a good idea to set by default in 4.0
