### ISSUE TITLE
Where is the documentation for mysql dialect options

### ISSUE THREAD

**Issue by brenthmiras** [sequelize/sequelize#6317]
I can't seem to find the available options for mysql like charset and collation

**Comment by felixfbecker** [comment]
https://www.npmjs.com/package/mysql#connection-options

**Comment by sushantdhiman** [comment]
You will have to use `dialectOption` to set any `mysql` dialect related options. You can pass these dialect specific options when creating Sequelize instance. ( [more docs on options available](http://docs.sequelizejs.com/en/latest/api/sequelize/?highlight=dialectOptions) )

**Comment by felixfbecker** [comment]
> options.dialectOptions | Object | optional | An object of additional options, which are passed directly to the connection library



http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html

**Comment by Wytrykus** [comment]
@sushantdhiman Why has this issue been closed? The link to mysql dialect options still doesn't work, see the "Options" link in here: http://docs.sequelizejs.com/manual/dialects.html#mysql
Could you please re-open the issue?

A useful link you could put into the doc (instead of the dead one) is indeed the one that @felixfbecker posted (https://www.npmjs.com/package/mysql#connection-options)
