### ISSUE TITLE
Custom class instances are rejected on sequelize.define

### ISSUE THREAD

**Issue by Ginden** [sequelize/sequelize#6335]
Simplest code that produce issue:

```javascript
'use strict';
const  Sequelize = require('sequelize');
const sequelize = new Sequelize('database', 'username', 'password');

class GuidAttribute {
    constructor() {
        this.primaryKey = true;
        this.type = Sequelize.UUID;
        this.allowNull = false;
    }
}

sequelize.define('myModel', {
    id: new GuidAttribute()
});
```

This code results in:

```Error: A column called 'id' was added to the attributes of 'myModels' but not marked with 'primaryKey: true'```

**Comment by felixfbecker** [comment]
Column definitions must either be an object literal (see lodash.isPlainObject), a data type factory or a data type object (that inherits from DataTypes.ABSTRACT). If you want a shortcut for `GuidAttribute`, why not do 
```js
const guidAttribute = {
  this.primaryKey = true;
  this.type = Sequelize.UUID;
  this.allowNull = false;
}
```

**Comment by Ginden** [comment]
> Column definitions must either be an object literal (see lodash.isPlainObject)

Not in documentation. Moreover, it doesn't make sense - why the hell is that required?

> If you want a shortcut for GuidAttribute, why not do 

Because I don't want to do this that way. Because minimal reproduction case isn't usage case.

**Comment by felixfbecker** [comment]
> Not in documentation

Are you kidding? Object literals is the only thing ever used in all examples. Never does it imply that passing instances of classes is supported.

> Moreover, it doesn't make sense - why the hell is that required?

Because you can also pass a data type, which is an object too, and the creators of sequelize thought that using `_.isPlainObject` was a good way to differentiate. Technically I guess we could go with just `instanceof` checks.

> Because I don't want to do this that way. Because minimal reproduction case isn't usage case.

I just showed you a way that works perfectly (I haven't tested it with inheritance though). "I don't want to do this that way" unfortunately is not enough reason for volunteer maintainers to use their free time to add this feature when there are 612 other issues to solve. Feel free to do a PR if you care deeply about this :)

**Comment by Ginden** [comment]
> the creators of sequelize thought that using _.isPlainObject was a good way to differentiate. 

But it isn't, that's the point.

> Are you kidding? Object literals is the only thing ever used in all examples. Never does it imply that passing instances of classes is supported.

"where" is always the last property on objects in examples. Does it imply that property order matter?

Assumption that such code make EXPLICIT check for object `[[Prototype]]` and that it's behaviour that can be expected from reading examples (examples are not authoritative in most documentations anyway) is totally ridiculous. In fact, it contradicts widely used practices like "wide parameter, narrow return" or duck typing. It's like writing code in Java:

```java
if (Object.getClass(obj) === VerySpecificClass.class) ...
```

In fact, Sequelize is the first popular library that I have seen to make such checks.

**Comment by felixfbecker** [comment]
Feel free to do a PR
