### ISSUE TITLE
where count >0 in include

### ISSUE THREAD

**Issue by vaibhavramteke787** [sequelize/sequelize#6398]
How can I put where condition in Include 
where it should contain atleast one record  in Students table

  models.Depts.findAll({
        raw: true,
        include: [{
		 model: models.Students,
                 attributes: [],
                  required: true,
		where:{
                       **Count(Students) > 0**		
                    }
		}]
    }).then(function (data) {
        res.json(data);
    });

**Comment by janmeier** [comment]
Setting `required: true` should already do that, since it turns into an inner join.

More generally, if you want another count, use a having on the outer options object `having: sequelize.where(sequelize.fn('count', sequelize.col('students.id')), '>', 2)`

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by Relequestual** [comment]
The current documentation says that if the include contains a where clause, the join is then an inner join, making the required redundant.

Is this only true in a newer version than the OP was using, or does the documentation need to be more specific?

**Comment by kuriel-trivu** [comment]
Support for literal replacements in the `where` object has been removed. +5126ms
