### ISSUE TITLE
Subqueries and missing fields, again

### ISSUE THREAD

**Issue by opatut** [sequelize/sequelize#6413]
Note: This post is to describe the problem, I posted a reply with a suggested solution approach below.
## What you are doing?
- do a find
- include 1:n association
- limit the outer query
- filter on the outer query (top-level `where`) with a "nested" key, e.g. `$child.childAttribute$: 1337`
  - no, I cannot filter on the include, because I need to AND/OR-combine the childAttribute condition with some other condition on the outer/parent model

``` js

var Parent = sequelize.define('Parent', {name: Sequelize.STRING}, {timestamps: false});
var Child = sequelize.define('Child', {name: Sequelize.STRING}, {timestamps: false});
Parent.hasMany(Child, {as: 'children', foreignKey: 'parentId'});
Child.belongsTo(Parent, {as: 'child', foreignKey: 'parentId'});

async function run() {
    await sequelize.sync();
    const p1 = await Parent.create({name: 'p1'});
    const p2 = await Parent.create({name: 'p2'});
    const c1 = await Child.create({name: 'c1', parentId: p1.id});
    const c2 = await Child.create({name: 'c2', parentId: p1.id});
    const c3 = await Child.create({name: 'c3', parentId: p2.id});
    const c4 = await Child.create({name: 'c4', parentId: p2.id});

    const p = await Parent.findAll({
        where: {
            $or: {
                name: 'p1',
                '$children.name$': 'c3',
            },
        },
        include: [{model: Child, as: 'children'}],
        limit: 1,
        order: [['name', 'ASC']],
    });

    console.log(JSON.stringify(p.map(p => p.toJSON()), null, 4));
}

run().catch((err) => console.error(err));
```
## What do you expect to happen?

I would like to receive **one** parent (`p1`, thanks to name ordering) for which the filter holds (the name matches 'p1'), including ALL their children (`c1` and `c2`) (since I'm not filtering on them, just filtering on the parent relation).
## What is actually happening?

It breaks with **ER_BAD_FIELD_ERROR: Unknown column** because the LIMIT is applied in the subquery, but the JOIN isn't.

I cannot move the `where` condition for the children into the `include`, since then I would only receive those children, not ALL children of the matching parents. Also I could not combine that condition using `$or` with the name condition on the parent.

**Dialect:** mysql
**Database version:** irrelevant
**Sequelize version:** 4.0.0-0

**Comment by opatut** [comment]
I fiddled around a little with the SQL generated. I think one possible solution would be to

* `LEFT OUTER JOIN` in the subquery, just like in the outer query
* *but!?!* you say, what's the point of the subquery then, if that join yields an increased count of rows that we cannot `LIMIT` on
* luckily we can break that count down again to after `WHERE`, but before `LIMIT` by using `GROUP BY` on primary key attributes of the main table

## Before

```sql
SELECT
    Parent.*,
    children.*,
FROM (
    SELECT Parent.*
    FROM Parents AS Parent
    WHERE (Parent.name = "p1" OR children.name = "c3") -- here is our problem
    LIMIT 1
) as Parent
LEFT OUTER JOIN Children AS children on Children.parentId = Parent.id;
```

## After

```sql
SELECT
    Parent.*,
    children.*,
FROM (
    SELECT Parent.*
    FROM Parents AS Parent
    LEFT OUTER JOIN Children AS children on Children.parentId = Parent.id     -- look at this!
    WHERE (Parent.name = "p1" OR children.name = "c3") -- no more problem
    GROUP BY Parent.id     -- and this!
    LIMIT 1
) as Parent
LEFT OUTER JOIN Children AS children on Children.parentId = Parent.id;
```

**Comment by opatut** [comment]
Bump.

**Comment by janmeier** [comment]
Sorry for leaving this hanging @opatut 

I think this could work. I don't it this would worsen performance significantly, since the performance problems with joins is mostly due to having to parse cartesian products in javascript, and not so much the query time itself.

One problem with the grouping is postgres - You cannot select rows from a group without either grouping on the, or applying an aggregate function. So we would need to group on all the attributes on the table for this subquery I think.
An alternative is to only select the primary key from the subquery (I believe we already do this somewhere).

I you can get it to work I think it should be the default, since it is the behaviour most people expect (always wanting the tables you joined to be available, not having to worry that it might be removed for a subquery.

Pinging @sequelize/core for additional feedback, but if you are up to it I think you can go ahead and start working on a PR (I'd love to see a lot of unit tests for sql generation for this, since it is a complicated case).

Also, thanks for pinging, and for providing a detail issue description! :tada:

**Comment by mickhansen** [comment]
Might be a workable solution.

Writing a subquery would achieve the same thing right? (Except Sequelize doesn't have great support fhat).

**Comment by opatut** [comment]
I don't think my SQL knowledge is good enough to complete this properly. I have no idea about the restrictions of the different DBMSs etc, so it's probably a good idea if someone else actually implements this. Also I had quite some trouble navigating the codebase 😉 

@mickhansen Yes, I am currently writing a [fine](http://i.imgur.com/c4jt321.png) subquery to achieve something similar. I am however not too happy about how that code turned out ;)

**Comment by mickhansen** [comment]
@opatut yeah i'd love to introduce better subquery support since we use it quite a bit for graphql servers these days
