### ISSUE TITLE
Documentation: Search functionality does not work.

### ISSUE THREAD

**Issue by meteormanaged** [sequelize/sequelize#6464]
Hello folks,
The documentation at http://sequelize.readthedocs.io/en/stable/ has had an issue where the search feature does not work.  It's been this way for a few weeks now.  Not sure what the grief is but searching for any term brings up the error page with the whale message:

```
        .
         ":"
       ___:____     |"\/"|
     ,'        `.    \  /
     |  O        \___/  |
   ~^~^~^~^~^~^~^~^~^~^~^~^~

   Fail.  Check back in a bit!
```

**Comment by felixfbecker** [comment]
There is also documentation build from the typings available [here](http://typed-sequelize.surge.sh/v3/) with working type-to-search :)

**Comment by janmeier** [comment]
Many competing documentations suddenly :D 

I'm also still working on https://doclets.io/sequelize/sequelize/doclets (though I haven't looked at it for a while)

How's yours generated @felixfbecker ?

**Comment by felixfbecker** [comment]
Doclets doesn't have search support afaik though :/
It's build from the [TypeScript typings](https://github.com/louy/typed-sequelize/tree/master/3) with [TypeDoc](https://github.com/TypeStrong/typedoc). But I find it helpful for JavaScript users too because the interfaces are a lot more readable than all those nested options in the tables.

Tipp: uncheck _inherited_ in the upper right corner to hide all the hooks.

**Comment by rummik** [comment]
This issue on ReadTheDocs looks like it might be relevant: https://github.com/rtfd/readthedocs.org/issues/1088

**Comment by sushantdhiman** [comment]
@rummik is right, Its related to readthedocs. We are working on new documentation https://github.com/sequelize/sequelize/pull/6226
