### ISSUE TITLE
Expansion of models not works

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#6526]
This code from manual not works. As far as I can see User become an Object but not a class function. And User.prototype is undefined

```
var User = sequelize.define('user', { firstname: Sequelize.STRING });

// Adding a class level method
User.classLevelMethod = function() {
  return 'foo';
};

// Adding an instance level method
User.prototype.instanceLevelMethod = function() {
  return 'bar';
};
```
output:
> Cannot set property 'instanceLevelMethod' of undefined

**Comment by janmeier** [comment]
Can you link to the documentation where it says that? Seems there is some confusion between versions (that syntax is for 4.0)

For 3.x you should use `User.Instance.prototype.instanceLevelMethod`

**Comment by alexey2baranov** [comment]
hire 
http://docs.sequelizejs.com/en/stable/docs/models-definition/

**Comment by alexey2baranov** [comment]
what version is stable by now? and what version this manual for?
http://docs.sequelizejs.com/en/stable/

**Comment by janmeier** [comment]
It seems that rtd is parsing out version numbers incorrectly, so that `4.0.0-x` is seen as a stable, and not a pre-release. See https://read-the-docs.readthedocs.io/en/latest/versions.html and https://github.com/rtfd/readthedocs.org/issues/2036

I've disable the `stable` tag for now, to avoid confusion. This unfortunately means that users are met with a Permission Denied message, but if they go to the root domain they will be redirected to the correct version (v3)
