### ISSUE TITLE
WHERE NOT EXISTS

### ISSUE THREAD

**Issue by kol9n93** [sequelize/sequelize#6529]
Hi. Is there analog for sql 'WHERE NOT EXISTS'?
I wanna find all RatingFactors where childrenRatingFactors aren't exist (bottom level items).

```
models.RatingFactor.findAll({
    include: [{
      model: models.RatingFactor,
      as: 'childrenRatingFactors',
     /** something like this
      * where: {
      *  id: {
      *    $notExists: true
      *  }
      * }
      **/
    }]
  })
```

**Comment by janmeier** [comment]
```js
where: {
  '$childrenRatingFactors.ratingFactorId$': null
}
```

Supposing that the foreign key in the relation is `ratingFactorId` - otherwise you need to adjust. Similarly you need to make sure that the table name matches (including case).

This should be added to the outer where, _not_ the join

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
