### ISSUE TITLE
Example [options.include[].on] ?

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6540]
Where is reasonable example for `[options.include[].on]`?  All you give is this:

> Supply your own ON condition for the join.

It is not enough.

**Comment by mickhansen** [comment]
It supports everything that `where` does

**Comment by felixfbecker** [comment]
You can do a PR to improve the docs

**Comment by sfertman** [comment]
@mickhansen @felixfbecker. Still unclear whether it overwrites existing association between models? Seems so, but without clear docs and examples there's a lot of trial and error one must do if one is not the one who build it.... For now it seems that the only safe way to join tables is to work with `where` and not use the `on` key. Plus,  unlike SQL, `on` doesn't seem to be able to join arbitrary tables without defining association on them. No sure if this is a different issue/bug or if this is by design.
