### ISSUE TITLE
Delete base on a date created? mysql db

### ISSUE THREAD

**Issue by redcode1** [sequelize/sequelize#6594]
I have tried this code below saw it on a trend but I dont know why its not working 
`	Posts.destroy({
 where: {
    createdAt: {
       isAfter: "2016-09-11"
    }
 }
})`
I want to destroy posts that are after 24hrs so I modified the above to 
`	Posts.destroy({
 where: {
    createdAt: {
       isAfter: "2016-09-11"
    }
 }
})`
I want to destroy p
Then I fetch to see the post that are left but I am still seeing the existing post

**Comment by janmeier** [comment]
Where did you see this? That is in no way official syntax :)

Try `$gt` http://docs.sequelizejs.com/en/v3/docs/querying/#operators

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by redcode1** [comment]
okay

**Comment by redcode1** [comment]
even though its close could this work 
`  Posts.destroy({
            where: {
                    createdAt: {
                          gte: Sequelize.literal("now() - INTERVAL 1 DAY")
                    }
                }
          }).catch(function(err) {
                console.log(" can't find posts " + err);
                res.send('error_getting_posts' + err);
          });`

**Comment by redcode1** [comment]
I am new to sequelize

**Comment by felixfbecker** [comment]
It's `$gte`, but yes, should work.
