### ISSUE TITLE
[query problems] m:n belongsToMany with through join table

### ISSUE THREAD

**Issue by frogcjn** [sequelize/sequelize#6595]
model associations:
```
'user' table < - m: n - >'project' table, through a 'user-project' table
```

query:
```
const users = await User.findAll({
  include: [{
    model: Project,
    through: {
      attributes: ['a', 'b']
    }
  }]
});
```

Then the sequelize will do LEFT OUTER JOIN, find all Users. Each User instance has a property `projects`.

I have 2 problems:

1. I ask sequelize to limit the join table attributes with only "a" and "b", but why sequelize query all properties of the join table in SQL?

2. Why this query return all users, no matter whether user has projects or not? (LEFT OUTER JOIN)
I just want to find all users have at least one project. (RIGHT OUTER JOIN)
Then how can I do it with sequelize?

Currently, I just filter the result to get what I want:
```node
users = users.filter($0 => $0.projects.length > 0)
```

Thanks!

**Comment by janmeier** [comment]
Right outer join means "all rows from the right table (Project), and their matching from the left (User)". This means you will get projects which have no users. This is not supported in sequelize, since rows are mapped to the left model (user), so if there are no left rows we can't map them to anything.

If you want an inner join, use `required: true` on the include http://docs.sequelizejs.com/en/v3/api/model/#findalloptions-promisearrayinstance

No. 2. should be fixed on master, but it might not - Please open a separate issue if this fails on master https://github.com/sequelize/sequelize/issues/5590

**Comment by frogcjn** [comment]
Thanks. I'll open a new issue.
