### ISSUE TITLE
send different queries from angular js ajax call and get the response from  same service in sequelize nodejs?

### ISSUE THREAD

**Issue by SIMHACHALAM1001** [sequelize/sequelize#6640]
service in nodejs using sequelize.

    var options={};
       options.where = {
        hp_builders_id: builders_id
              }
        app.get('/v1/project-listing', function(req, res) {
        hp_property.findAll(options).then(function(result) {
        });
        });

so based on builders id i am getting response from nodejs service.
if i want perform builder_id and bedrooms(1,2,3) so many inner joins in the code but i am not pasting all the code.
 
so for same service i want to use in multiple scenarios for filtering concepts
my doubt is how to handle this where condition based on client side query.
 queries from client side sending in angularjs

    {"filters":{"and":[{"equal":{"builderId":100002}}]} 
    {"filters":{"and":[{"equal":{"builderId":100002},bedrooms:[1,2]}]} 
so how to handle these two in nodejs service request and to perform in where condition in sequelize

**Comment by felixfbecker** [comment]
A question about how to get JSON from a client request and transform it into a sequelize query is totally out of scope for a GitHub issue at Sequelize.

**Comment by SIMHACHALAM1001** [comment]
just give a small approach man .how to handle in where Sequelize

**Comment by mickhansen** [comment]
@SIMHACHALAM1001 Loop over the input and generate a findAll acceptable object structure.

**Comment by SIMHACHALAM1001** [comment]
thanq so much @mickhansen. will u please give a small example

**Comment by mickhansen** [comment]
@SIMHACHALAM1001 Writing an example that parses your input isn't a one liner, please give it a shot and post what you have that doesn't work.

Write a method that takes your input and produces sequelize friendly output, unit test it, show us input/outputs you can't get to work and maybe we can provide a bit of help.

As a rule the contributors are more concerned with identifying and fixing bugs rather than how-to-code-stuff questions.
