### ISSUE TITLE
Passing parameters to getter method

### ISSUE THREAD

**Issue by ro70** [sequelize/sequelize#6679]
In sequelize 3.24.3 something like

```js
getterMethods   : {
    fullName       : function(delimiter)  { return this.name1 + delimiter + this.name2 }
  }
```

isn't working. How can I achieve this?

**Comment by janmeier** [comment]
That's not possible - `getterMethods` maps to a property getter. This means that `console.log(instance.fullName)` will call the getter method behind the scenes. Since getters are used for property access it is not possible to pass parameters to them.

If you want a getter with delimiter, you can define a normal method on the instance

**Comment by ro70** [comment]
Thanks @janmeier for your quick response. Well, I'm trying
```
var User = sequelize.define('user', {
   name1: DataTypes.STRING,
   name2: DataTypes.STRING
})

User.prototype.fullName = function(delimiter) {
   return this.name1 + delimiter + this.name2
}
```
as described in http://docs.sequelizejs.com/en/latest/docs/models-definition/#expansion-of-models

Then I get this error:
```
User.prototype.fullName = function(delimiter) {
                          ^

TypeError: Cannot set property 'fullName' of undefined
```

**Comment by janmeier** [comment]
Latest docs are for v4 - v3 is here http://docs.sequelizejs.com/en/v3/docs/models-definition/#expansion-of-models

You should use `User.Instance.prototype.fullName` or instance methods

**Comment by ro70** [comment]
@janmeier Thanks a lot. That was it. It's not really obvious at first glance to which sequelize version a text belongs. Maybe this can be improved in the docs.
