### ISSUE TITLE
How to order with three level models?

### ISSUE THREAD

**Issue by shuperry** [sequelize/sequelize#6692]
Two level include models, order is easy to write, but in three level, I was stumped.

Here is my code:
```js
const _case = await sequelize.models.Case.findOne({
    where: {
      case_id
    },
    include: [
      {
        model: sequelize.models.CaseRoleUsers, as: 'caseRoleUsers', include: [
          {model: sequelize.models.CaseRole, as: 'role'},
          {model: sequelize.models.User, as: 'user'}
        ]
      },
      { model: sequelize.models.Category, as: 'category' },
    ],
    order: [
      ['created_at', 'DESC'],
      [{ model: sequelize.models.OperHistory, as: 'operHistories' }, 'created_at', 'DESC']
    ]
  })
```

I want to order with the `rank` attribute include by  model `case.caseRoleUsers.role`, is there any way to do this, let me know, Thks first.

**Comment by janmeier** [comment]
```js
Company.findAll({
  include: [ { model: Division, include: [ Department ] } ],
  order: [ [ Division, Department, 'name' ] ]
});
```
http://docs.sequelizejs.com/en/v3/docs/models-usage/#ordering-eager-loaded-associations

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by shuperry** [comment]
@janmeier Thks, this function is very powerful and useful for me, hail sequelize.
