### ISSUE TITLE
findAndCountAll is not parallel

### ISSUE THREAD

**Issue by contra** [sequelize/sequelize#6695]
## What you are doing?

``` js
// this takes 30 seconds!
Model.scope('safe').findAndCountAll(queryOptions)

// this takes 15 seconds!
Promise.all([
  Model.scope('safe').count({
    ...queryOptions,
    attributes: []
  }),
  Model.scope('safe').findAll(queryOptions)
])
```
## What do you expect to happen?

Count and find should be executed at the same time.
## What is actually happening?

findAndCountAll executes the count, waits for it to finish, then executes the find. This is a huge perf loss, both queries should be run at the same time. This is a simple fix that will increase performance of this operation by 100% - what a nice unexpected win!

**Dialect:** postgres
**Database version:** 9.6
**Sequelize version:** 3.24.3

**Comment by contra** [comment]
Code responsible is here: https://github.com/sushantdhiman/sequelize/blob/master/lib/model.js#L1615

**Comment by felixfbecker** [comment]
The function inspects the result of the count - if it is 0, the find is not executed at all. We would lose that check, but it might be overall faster. It also only works if it picks a separate connection for the other query because the protocol is sequential.

This would be a very easy PR, no deep internals changed, no tests - if you want to provide one you can benchmark it with sequelize-benchmark

**Comment by contra** [comment]
@felixfbecker PR inbound
