### ISSUE TITLE
how to use sequelize.fn(['if'])?

### ISSUE THREAD

**Issue by Jealee3000** [sequelize/sequelize#6704]
for example：
```sql
SELECT if(`evaluates`.`all`, 'good','notgood') AS `sign`, count(*) AS `count` FROM `evaluates` AS `evaluates` WHERE `evaluates`.`deleted_at` IS NULL GROUP BY `sign`;
```

```js
await DBC.evaluates.count({
        attributes: [[DBC.sequelize.fn(['if'],
        DBC.sequelize.col("`evaluates`.`all`"), ["good", "notgood"]), 'sign']],
        group: ["sign"]
    });
```

but 
```sql
SELECT if(`evaluates`.`all` > 3, 'good','notgood') AS `sign`, count(*) AS `count` FROM `evaluates` AS `evaluates` WHERE `evaluates`.`deleted_at` IS NULL GROUP BY `sign`;
```

how?
```js
await DBC.evaluates.count({
        attributes: [[DBC.sequelize.fn(['if'], DBC.sequelize.col("`evaluates`.`all` > 3"), ["good", "notgood"]), 'sign']],
        group: ["sign"]
    });
```
it's false.

**Comment by janmeier** [comment]
`.col` refers to a column - If you want to write an expression use `.literal` (you should remember to take care of the escaping yourself.

Also, you don't need to wrap the function name in an array

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
