### ISSUE TITLE
How to implemet group by?

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#6708]
example:
**tableA**
```
{
id,
name
}
```
**tableB**
```
{
fk_tablea,
price
}
```
how to use sequelize to implemet below sql(not set 'raw')?
```
select a.name,sum(b.price) from tableA a,tableB b 
where a.id = b.fk_tablea
group by a.name
```

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

http://docs.sequelizejs.com/en/v3/docs/models-usage/#manipulating-the-dataset-with-limit-offset-order-and-group
