### ISSUE TITLE
model.create() method will be resolved when related table doesn't exist.

### ISSUE THREAD

**Issue by paperayo** [sequelize/sequelize#6710]
## What you are doing?

```js
A.findById(id)
  .then(function(a) {
      // ...
      return B.create({
          // ...
      });
  }).catch(function(err) {
    console.log(err);
    // ...
  }).then(function(b) {

    // when related table b doesn't exist yet, code here is executed(resolved)

    // ... 
  }
```

__Dialect:__ mysql
__database version:__ 14.14
__Sequelize version:__ 3.20.0

**Comment by janmeier** [comment]
You are cathing the error that comes from `B.create`, so the wrapping promise (from A.findById) is  -resolved. If you remove the catch handler or rethrow the whole promise will be rejected

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
