### ISSUE TITLE
Arbitrary JOIN with include

### ISSUE THREAD

**Issue by leandrosisloc** [sequelize/sequelize#6718]
I would like to give an expression like this

```
documentModel.hasOne(documentModel,
{
    as: "user",
    foreignKey: "(\"user\".\"data\"#>>\'{author}\')::uuid" 
               //("user"."data"#>>'{author}')::uuid
}

```

The models are different kind of records but belongs to the same table (document). This table has the column "data" (type = JSONB) and the column "id" (type = uuid)

Generated `join` part

`LEFT OUTER JOIN "document" AS "user" ON "document"."id" = "user"."(user.data#>>'{author}'):uuid" AND "user"."deletedAt" IS NULL`

Expected `join` part

`LEFT OUTER JOIN "document" AS "user" ON "document"."id" = ("user"."data"#>>'{author}')::uuid AND "user"."deletedAt" IS NULL`

My idea is that we could use something like this

```
postModel.hasOne(userModel,
{
    as: "user",
    foreignKey: {
        literal: "(\"user\".\"data\"#>>\'{author}\')::uuid"
    }
}

```

If you guys could guide me into the right files to change I would appreciate to try implementing this feature.
I'm kind of new in this project and I can't understand the source code well.

Thanks !

**Comment by leandrosisloc** [comment]
This is my model definition

```
var documentModel = sequelize.define("document", {
    
    id: {
        type: DataTypes.UUID,
        primaryKey: true
    },

    // tipo de documento
    type: DataTypes.STRING,

    // dados do documento
    data: DataTypes.JSONB,    

}, {
    tableName: 'document',
    paranoid: true
});
```

**Comment by felixfbecker** [comment]
You want an expression as a foreign key? I don't know any driver that supports this

**Comment by leandrosisloc** [comment]
@felixfbecker What I want is the possibility to put an expression as my "foreign key" part of the join clause. In my case i'm using PG but I only have one table (document) that has all of my records. The difference between those records is the value of the column "type" mentioned above at the model definition.

Example: An "user" record has the "type" column with the value "system.user", and a "task" record has the "type" column with the value "system.task".

**Comment by janmeier** [comment]
While i (sort of) get the whole "PG can be a key-value store as well", I'm not sure if this is something we want to support. I think it's too little gain to justify the increased code complexity

**Comment by felixfbecker** [comment]
The problem here is that `hasOne` is not a function to do a JOIN, it's a function to set up a relation, which means foreign keys. And you cannot have a foreign key on an expression, that would not be a proper relation. We do not have a syntax to do arbitrary JOINs (besides raw queries). Sequelize is an Object Relational Mapper, and using it as a document DB store with JSON columns is just not what an Object Relational Mapper is for. You are basically linking "documents" without any referential integrity. Either normalize your data relationally (highly recommended!), or denormalize it and duplicate the data (cannot recommend). But linking without referential integrity is not good.

Good read: http://www.sarahmei.com/blog/2013/11/11/why-you-should-never-use-mongodb/

Closing as out-of-scope for an ORM

**Comment by leandrosisloc** [comment]
So ... the only way that I can change the JOIN clause is using raw queries ? 
That's sad ... I really enjoy the way that the "where" clause was implemented on sequelize and it works very well for me when using the `findAll`and `findAndCount`methods. 
When it doesn't support a complex clause I can just use the `literal` attribute to get it to work for me. 
So, I thought that could be a good thing to support this same kind of need for the JOIN clauses.

**Comment by felixfbecker** [comment]
@janmeier Do we have something like
```js
include: [ Sequelize.literal('INNER JOIN Users ON ...') ]
```
?

If not, I think that could be a valid feature. Possibly with `Sequelize.join(User, { on: ..., required: true })`.
We do have syntax to give the `on` condition already.

**Comment by janmeier** [comment]
Nope, we don't - I was looking for a feature request for that but I can't find it...

**Comment by leandrosisloc** [comment]
Is there something I can do for help ? I could try to implement that but I'm lost at the source code ... 
If anyone could give me some tips such as which files might have a good chance of having to be modified I would be glad.

Thanks a lot, guys !

**Comment by felixfbecker** [comment]
We would first need an API design proposal

**Comment by leandrosisloc** [comment]
@felixfbecker Is it something that I need to do ? I don't know how it works, as I said I'm kind new here. Is there some guide that I can read to learn more about the proccess of "feature requests" in this project ? Sorry about these questions but I can't figure out where is the right place to ask them.

**Comment by felixfbecker** [comment]
No formal requirements. Just propose the API you would like to implement so we can discuss

**Comment by leandrosisloc** [comment]
@felixfbecker So, I think it could be something like you said 

```
documentModel.findAndCount({
    include: [ 
        Sequelize.join(
            {
                tablename: "document", 
                as: "user",
                on: " \"document\".\"id\" = (\"user\".\"data\"#>>\'{author}\')::uuid "+
                    "AND \"user\".\"deletedAt\" IS NULL ",
                required: false 
            })
     ]})

```

this is the string format it should applies

`([required] ? "INNER JOIN" : "LEFT OUTER JOIN") + [tablename] + "AS" + [as] + "ON" + [on]`

the "[value]" would be replaced by the join attributes

How about that ?

**Comment by felixfbecker** [comment]
It would probably be of benefit to not join just a table, but an arbitrary model (document) so you get actual instances. What do you think about this:
```js
find({ include: [ { model: Document, as: 'user', on: literal('...') } ] })
```
where Document is not associated, but the JOIN still works as long as you provide `on` and `as`

**Comment by leandrosisloc** [comment]
Great ! I loved your suggestion, thanks :)

But I only have two questions about this.

1- Where would be the "left outer join" and "Inner join" part ? If it is inside the "literal" statement so you do not need the "as" one.

2- the include doesn't change my model instance, right ? If I call the "find" using the same model, two times in a row for example, the result would be the same ?

**Comment by janmeier** [comment]
1 - This should be controlled by `required: true / false` like regular includes. Not sure if we would need to support other types as well` (right and lateral joins perhaps?)

2 - No, it doesn't change the model, it will just put the included data into model instances, like a regular include.


`on` should of course still support all the options it does today (particularly using a JSON object, instead of a literal string, e.g. `on: { fooBar: { $col: 'includedModel.baz' } } = `ON parent.fooBar = includedModel.baz`


It would be nice if includes were internally re-written to this new format - So the logic for which columns to join on etc. happens in the model (or maybe in the corresponding association), and the querygenerator is only responsible for converting the POJO to SQL. Not saying this should happen at the same time as arbitrary join support, but you are allowed to dream ;)

**Comment by felixfbecker** [comment]
Agree with Jan on 1, `on` is just the condition, not the JOIN type.
OUTER JOIN support has been discussed before and it doesn't make sense for an ORM. The left table (the model) must always be defined.
The where syntax should of course be supported for `on`, but I don't think we should rewrite literals to this syntax, because literals are mostly used for things the where syntax doesn't support. So that should just get passed through raw.

**Comment by leandrosisloc** [comment]
Ok about the 1, but I didn't get about the 2 ...

Are you guys saying that the `literal` syntax would be useless in this arbitrary join ? In my case I think its not because I can't figure out how to do this `("user"."data"#>>'{author}')::uuid` using the where syntax without the `literal` support.

Although, I didn't get yet WHO will implement this feature. 
Why do you guys need the conecpt of the API done at this point ?
1- To help me telling where in the source code I will need to change to implement this ? (In this case I will implement it)
2- To implement this ? (In this case, you will implement it)
3-Neither one, I'm completely wrong about where this discussion is taking us.

As I said, I'm new on git communities, so sorry about these dumb questions.

Best regards.

**Comment by felixfbecker** [comment]
No, you can use literal. But I think we have a syntax for accessing JSON properties.
We need an API proposal because software needs to be designed before it can be written 😄 
I can tell you that I won't have the time for this feature. Who ever needs it can pick it up and implement the syntax we agreed on. I also am the wrong person to ask about where in the code this needs to be implemented.
