### ISSUE TITLE
It throws an error without any messages when I add an 'as' filed to the 'include' param of 'findOne' method.

### ISSUE THREAD

**Issue by aoxls** [sequelize/sequelize#6738]
```
model1.findOne({
    where: {
        ...
    },
    include: [{
        model: model2
    }]
})
```
this is correct,I have got the data

```
model1.findOne({
    where: {
        ...
    },
    include: [{
        model: model2,
        as: 'myname'
    }]
})
```
but this throws an error,without any messages...

sequelize version: 3.24.4

**Comment by janmeier** [comment]
I'm pretty sure there is an error message - Perhaps you are just not looking at the right property?

In any case, `as` is only supported if you have the same `as` on the association - You can't use an arbitrary one.

If you still have issues, please create a [SSCCE](HTTP://SSCCE.ORG/)

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
