### ISSUE TITLE
SequelizeUniqueConstraintError: Validation error

### ISSUE THREAD

**Issue by thiagofernando** [sequelize/sequelize#6762]
## What you are doing?

when i try insert a record into an empty table I get this message:

**_SequelizeUniqueConstraintError: Validation error_**

 _**errors: 
   [ { message: 'PRIMARY must be unique',
       type: 'unique violation',
       path: 'PRIMARY',
       value: '2-50-100-431439-1' } ],
  fields: { PRIMARY: '2-50-100-431439-1' },
  parent: 
   { Error: ER_DUP_ENTRY: Duplicate entry '2-50-100-431439-1' for key 'PRIMARY'**_

When I run the insert generated by sequelize, the record is successfully inserted.
**_INSERT INTO `contrato.pbms` (`TPO_PBMS`,`CLS_PBMS`,`SCL_PBMS`,`SEQ_PBMS`,`CD_SIS_OGM`,`NOM_ITEM`,`IND_BASE`,`CD_TIP_ITEM`) VALUES (2,50,100,431439,1,'MANUT/SUP SOLUC VIDEOWALL          ',20,99);_**

_Post a minimal code sample that reproduces the issue, including models and associations_
Model :

```
var pbms = sequelize.define('pbms', {

        TPO_PBMS: {
            type: DataTypes.INTEGER,
            underscored: true,
            allowNull: false,
            primaryKey: true
        },
        CLS_PBMS: {
            type: DataTypes.INTEGER,
            underscored: true,
            allowNull: false,
            primaryKey: true
        },
        SCL_PBMS: {
            type: DataTypes.INTEGER,
            underscored: true,
            allowNull: false,
            primaryKey: true
        },
        SEQ_PBMS: {
            type: DataTypes.INTEGER,
            underscored: true,
            allowNull: false,
            primaryKey: true
        },
        CD_SIS_OGM: {
            type: DataTypes.INTEGER,
            underscored: true,
            allowNull: false,
            primaryKey: true
        },
        NOM_ITEM: {
            type: DataTypes.STRING(50),
            underscored: true,
            allowNull: true
        },
        IND_BASE: {
            type: DataTypes.INTEGER,
            allowNull: true,
            underscored: true
        },
        CD_TIP_ITEM: {
            type: DataTypes.INTEGER,
            underscored: true,
            allowNull: true
        }
    }, {
        schema   : 'contrato',
        tableName: 'pbms',
        freezeTableName: true,
        classMethods: {
        }
    });
```

Data

```
var data = {
            'TPO_PBMS' : 2,
            'CLS_PBMS' : 50,
            'SCL_PBMS' : 100,
            'SEQ_PBMS' : 431439,
            'CD_SIS_OGM' : 1,
            'NOM_ITEM' :        'MANUT/SUP SOLUC VIDEOWALL          ',
            'IND_BASE' : 20,
            'CD_TIP_ITEM' : 99
        };
```

Table
`CREATE TABLE`pbms`(
`TPO_PBMS`mediumint(6) NOT NULL,
`CLS_PBMS`smallint(6) NOT NULL,
`SCL_PBMS`smallint(6) NOT NULL,
`SEQ_PBMS`int(11) NOT NULL,
`CD_SIS_OGM`smallint(6) NOT NULL,
`NOM_ITEM`varchar(50) DEFAULT NULL,
`IND_BASE`smallint(6) DEFAULT NULL,
`CD_TIP_ITEM`smallint(6) DEFAULT NULL,
  PRIMARY KEY (`TPO_PBMS`,`CLS_PBMS`,`SCL_PBMS`,`SEQ_PBMS`,`CD_SIS_OGM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
`
## What do you expect to happen?

insert the record
## What is actually happening?

error

_Output, either JSON or SQL_

**Dialect:** mysql 
**Database version:** 5.6
**Sequelize version:** last version

**Comment by janmeier** [comment]
Please create a complete, selfcontained test case (http://sscce.org/)

I very much doubt this is the case - If you have a constraint in the database it _cannot_ be violated by sequelize.
But checking for those values will definitely give you a row - the row that already exists

**Comment by thiagofernando** [comment]
I think I know what the problem is. When using postgres and sequelize sync, when the table does not exist, it creates using the model information (schema + tablename). From what I noticed in mysql it joins the name (schema + tablename) and places like the table name. 
Another think in mysql this command is mandatory sequelize.dialect.supports.schemas = true;

**Comment by Hassaan-Ahmed** [comment]
having same problem with bulkCreate method it works fin the first time but do not allow me to add the record second time.
**Model Fields:**
`ContractItem = sequelize.define("contractItem", {
        id: {
            allowNull: false,
            type: Sequelize.UUID,
            defaultValue: Sequelize.UUIDV4,
            primaryKey: true
        },
        contractId: {
            allowNull: false,
            type: Sequelize.UUID,
            defaultValue: null,
        },
        name: {
            allowNull: false,
            type: Sequelize.STRING,
            defaultValue: ""
        },
        price: {
            allowNull: false,
            type: Sequelize.DECIMAL(18, 3),
            defaultValue: 0.0
        },
        duration: {
            allowNull: true,
            type: Sequelize.INTEGER
        },
        total: {
            allowNull: true,
            type: Sequelize.DECIMAL(18, 3),
            defaultValue: 0.0
        },
        details: {
            allowNull: false,
            type: Sequelize.STRING,
            defaultValue: ""
        },
        changedBy: {
            allowNull: true,
            type: Sequelize.STRING,
            defaultValue: null
        }`
here is the query that is returned when i try bulkCreate method the second time.

> 

INSERT INTO "contractItems" ("id","contractId","name","price","duration","total","det ails","changedBy","createdAt","updatedAt") VA LUES ('18a0b5c4-0ef3-4c46-892e-dbd536430e21', '147f7bc4-bb96-49f3-a0a0-0cec97accc8c','Ponst one P','1.000','100',100,'killer',NULL,'2019- 04-04 05:22:48.835 +00:00','2019-04-04 05:22: 48.835 +00:00'),('985af156-1045-4e9d-b901-f7e 9bf952b97','147f7bc4-bb96-49f3-a0a0-0cec97acc c8c','Penadol Sp','3.000','50',150,'killer',NULL,'2019-04-04 05:22:48.835 +00:00','2019-04 -04 05:22:48.835 +00:00');
--
The problem is bulkCreate returning same ids second time which eventually create the error. But when i update model field id to uuid it all starts to work fine.

**Comment by Andersonfrfilho** [comment]
no postbird in query run:
(table name, field name)
```query
select nextval ('contacts_id_seq')
```
```query
select setval('phones_id_seq', 91)
```

**Comment by agueroveraalvaro** [comment]
Try with `unique: false` in relation code

`MyModel(OtherModel, { foreignKey: { name:'myModel_id', unique: false}, as: 'otherModels' });`

**Comment by RicoHorta** [comment]
Your Database is not allowing the duplication of records based on index or relationship. Be careful with the UNIQUE attribute because it does just that. Handle the SEQUILIZE error as follows:
try {
  const user = await User.create({ name: request.body.email });
  // you can now access the newly created user
  console.log('success', user.toJSON());
} catch (err) {
  // print the error details
  console.log(err, request.body.email);
}
