### ISSUE TITLE
Table Change Log

### ISSUE THREAD

**Issue by doganmurat** [sequelize/sequelize#6764]
Is there a built-in way to track table data changes (Audit) ?

**Comment by janmeier** [comment]
According to the wiki, there is this plugin https://github.com/bonaval/sequelize-temporal (not officially maintained by sequelize)

While this might strictly speaking be tagged as a feature request, I don't think this feature fits in sequelize-core - It is better kept as a plugin

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by doganmurat** [comment]
Thanks.
