### ISSUE TITLE
Find entity with deleted associated entity

### ISSUE THREAD

**Issue by ro70** [sequelize/sequelize#6767]
## What you are doing?
There's an entity a in table A associated with an entity b in table B. The entity a is destroyed (but still in DB). When I look for the entity b then I'd like to get NULL as result. Is this possible?
```js
var Sequelize = require('sequelize')
var sequelize = new Sequelize('...', '...', '...')

var A = sequelize.define('A',
  {},
  {
    timestamps: true,
    deletedAt: 'deletedAt',
    paranoid: true
  }
)

var B = sequelize.define('B',
  {},
  {
    timestamps: false
  }
)

A.hasMany(B, {foreignKey: 'id'})
B.belongsTo(A, {foreignKey: 'id'})

sequelize.sync({force: true})
.then(function() {
  return A.create(
    {
      Bs: [{}]
    },
    {
      include: [B]
    }
  )
})
.then(function() {
  return A.destroy(
    {
      where: {id: 1}
    }
  )
})
.then(function() {
  return B.findOne(
    {
      where: {id: 1},
      include: [A]
    }
  )
})
.then(function(b) {
  console.log(b.get({plain: true}))
})
.catch(function(err) {
  console.log(err)
})
```

## What do you expect to happen?
```
null
```

## What is actually happening?
```
{ id: 1, A: null }
```
__Dialect:__ mysql
__Database version:__ 10.1.9-MariaDB
__Sequelize version:__ 3.24.4

**Comment by janmeier** [comment]
Try changing the include to `include: [{ model: A, required: true }]` - That will turn it into an inner join 

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by ro70** [comment]
@janmeier Works, thank you.
