### ISSUE TITLE
Close properly Sqlite connections

### ISSUE THREAD

**Issue by francescoinfante** [sequelize/sequelize#6798]
## What you are doing?
Using Sequelize with Sqlite.

## What do you expect to happen?
I want the connection with Sqlite to be closed properly and the file *shm and *wal deleted.

## What is actually happening?
*shm and *wal files persist after termination of the process.

__Dialect: sqlite
__Database version: 3.1.6
__Sequelize version: 3.24

A PR would be accepted? I would implement `disconnect()` in the sqlite connection manager. `disconnect()` would call `close()` on all `this.connections`

**Comment by felixfbecker** [comment]
Doesn't `sequelize.close()` work for you?

**Comment by francescoinfante** [comment]
No, `sequelize.close()` with sqlite does nothing.
`sequelize.close()` calls `this.connectionManager.close()`
`this.connectionManager.close()` calls `this.onProcessExit()`
`this.onProcessExit()` will do something only if `this.pool` is defined. But it's undefined for sqlite.

**Comment by nadrane** [comment]
I can fix this one. As @francescoinfante said, we're not closing the connection because the current implementation of `onProcessExit` assumes that we are using pools:

```
  onProcessExit() {
    if (this.pool) {
      this.pool.drain(() => {
        debug('connection drain due to process exit');
        this.pool.destroyAllNow();
      });
    }
  }
```

As it stands today, the `SqliteDialect` class does not even make an attempt to use pools. I noticed [#5914](https://github.com/sequelize/sequelize/pull/5914) makes it forbidden to not use pools. This PR doesn't mention how sqlite still does not have pooling support. And that's where I'm at a crossroads. I'm guessing it was an explicit decision not to support pooling for sqlite since the database isn't really designed for concurrent connections (is this an inaccurate statement? [This](https://www.sqlite.org/threadsafe.html) suggests we can have concurrent connections)). 

So is the solution to this issue to support pooling for sqlite anyway (maybe just limiting the number of connections to 1), giving us a common API for managing all SQL dialects? Or is it to add an exception in `onProcessExit` to handle sqlite a little bit differently? Or is it to support pooling with an unthrottled number of connections like every other DB?

**Comment by Deilan** [comment]
Not stale.

**Comment by aguynamedben** [comment]
Does anybody know if this bug could have caused SQLITE_CORRUPT issue? I.e. if a process was force quit during a database write or if the process was quit in the middle of a write?

We're on sequelize@4.42.0 (before this fix was merged), SQLCipher, and Electron and have a few users that have gotten SQLITE_CORRUPT. I'm wondering if their app was force quit somehow and the database connection wasn't closed properly, leaving the on-disk SQLite database in a corrupt state.
