### ISSUE TITLE
Builds get deadlocked on Travis CI

### ISSUE THREAD

**Issue by harshithkashyap** [sequelize/sequelize#6843]
Sequelize builds often run into deadlock error on Travis CI and the builds fail.
https://travis-ci.org/sequelize/sequelize/jobs/175360669

Is there a way to force Travis CI to run jobs within the same dialect sequentially and running the other dialect jobs in parallel?

**Comment by sushantdhiman** [comment]
That deadlock is occurring because Postgres is still busy building the index and we issue same query to that again, we are aware of the issue. I dont think we can detect when the postgres has finished building indexes. We are working on resolving it

Maintainer will restart your build before merging the PR
