### ISSUE TITLE
SequelizeDatabaseError: UNKNOWN_CODE_PLEASE_REPORT:

### ISSUE THREAD

**Issue by chill0ut** [sequelize/sequelize#6852]
Hi, i experienced this error when i tried to use the sample code from the [docs](http://docs.sequelizejs.com/en/latest/docs/querying/#orderingl).

```

var server = require('http').createServer();
var express = require('express');
var app = express();
var Sequelize = require('sequelize');
var sequelize = new Sequelize('database', 'root', '');

var User = sequelize.define('user', {
 	userNumber: Sequelize.INTEGER
 });

	User.findAll({
		order: [
	  		[Sequelize.fn('max', Sequelize.col('userNumber')), 'DESC']
		]
	}).then(function(users){
		console.log(users)
		});


app.listen(3000);
```
i get this error:
Unhandled rejection SequelizeDatabaseError: UNKNOWN_CODE_PLEASE_REPORT: Expression #1 of ORDER BY contains aggregate function and applies to the result of a non-aggregated query

I've updated mysql to version2.12.0 and sequelize to version 3.25.0, the error is still there.

when i try to run 

```
	User.findAll({
		limit: 100,
		order:[
			['userNumber', 'DESC']
		]	

	}).then(function(users){
		console.log(users);
	});

```
it works fine even if no user was created, so it have a workaround.

have a nice day

**Comment by felixfbecker** [comment]
What dialect?

**Comment by janmeier** [comment]
If you don't have a grouping, it does not make sense to apply a max - The max will be applied for each row, so there will only be one row to choose from.

Aggregate functions only work in the context of grouping - The documentation just shows the smallest possible example of how you would apply and aggregate function - Not necessarily how you would use in real life :)

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
