### ISSUE TITLE
Best way to handle associations with migrations?

### ISSUE THREAD

**Issue by gcatto** [sequelize/sequelize#687]
I'm starting to setup my sequelize migrations, but wasn't clear from the documentation on the best way to do associations with that. Should it still just be in the code, as per http://sequelizejs.com/documentation#associations and followed by using .sync()? Or is there some better approach?

**Comment by codrex** [comment]
sequelize should really make that part clear in their docs.

**Comment by wayne-o** [comment]
Agree I have been going around in circles with this for the last 2 hours and I'm still not clear on it :/

**Comment by codrex** [comment]
When using migration along with your model and u are associating your model in a class method always endeavor to call sync no your model for associations to work.

**Comment by wayne-o** [comment]
The issue is that when using migrations it's not clear where we are
supposed to be calling sync - a demo that shows a sensible setup would be
handy  - it's very hard for someone new to the project to get started and
that can't be a good thing.

I think I have it working now so I will try and put together a bit of code
as a starting point for a complete demo with HapiJs

Thanks

w
