### ISSUE TITLE
hasOne behaviour

### ISSUE THREAD

**Issue by rsommerard** [sequelize/sequelize#6913]
Hi :earth_africa: 

About the hasOne behaviour (and belongsTo in the other way).

```js
A.hasOne( B ) //  create a foreign key in the B table
```

When I make this, I expect that "A has one reference to B" because I apply the hasOne function on the A, but this is not the human expected thing that is actually done. This is B that has the reference in his table.

Why things are made by this way:grey_question: 

--Romain

**Comment by janmeier** [comment]
It's hard to think about in abstract terms such as A and B. Think about `User has one Profile` or `Account has one Subscription`

The naming is partly down to legacy, and partly down to how other frameworks (in particular active record http://guides.rubyonrails.org/association_basics.html#the-has-one-association) does it

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by felixfbecker** [comment]
hasOne is  the inverse of belongsTo.

Profile belongsTo User
User hasOne Profile

the foreign key will be on Profile.

**Comment by rsommerard** [comment]
Yeap, but when you read Profile belongsTo User, the first thing that come to mind is "I will have a foreign key in User because the Profile *belongsTo* User" ans not the inverse.

Dont you think that the meaning is inversed?

**Comment by felixfbecker** [comment]
Actually, no, I don't. I think the opposite. Anyway, this will not be changed because it would be an unneeded breaking change.

**Comment by rsommerard** [comment]
Yeap, no problem, I just want to understand the meaning which is inversed :)
I dont know if I am the only one who think that way, so thanks for your replies :)
