### ISSUE TITLE
How to connect Sequelize to Amazon RDS correctly

### ISSUE THREAD

**Issue by manuelfink** [sequelize/sequelize#6932]
I'm using an Amazon RDS hosted MySQL with Multi-AZ Support. Just could not find any information on how to connect to Amazon RDS probably so that Sequelize is handling fail-overs accordingly?

I'm just using the following config, but do not now if this is enough?

```
sequelizeConfig = {
  logging: false,
  pool: { maxConnections: 5, maxIdleTime: 30},
  sequelizeConfig[dialectOptions] = {
    ssl: 'Amazon RDS'
  }
}
```

Can anyone confirm, this is working and maybe add docs on how to connect probably?

### Using Amazon RDS two things are important:

1. Try reconnect if connections is missing
2. Don't cache mysql server IP-Adress too long (Amazon suggests less than 1 min)

### Similar Questions 

Simular questions only discuss about connection problems, but not how to connect probably

* Error Connecting to Amazon RDS over SSL #1380   
* Amazon ist not really saying anything to connection handling http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_nodejs.rds.html#create_deploy_nodejs.rds.newDB

**Comment by anonmily** [comment]
@manuelfink Whenever possible, you should avoid hard-coding IP addresses into your configuration since that can make it fragile when your server IP address changes. Instead, using a DNS/domain name can make it a bit more resilient (e.g. db1.domain.com instead of 123.456.7890).

Managing failovers also isn't something that should be handled by Sequelize or in your code. If you're using AWS RDS, you can use automatic failovers, which can change the DNS record of the DB instance to point to the standby DB instance if it goes down. Alternatively, you could probably handle this yourself with a new EC2 instance with a load balancer (e.g. Nginx/HaProxy) and use service discovery (e.g. Consul) to manage a dynamic inventory of your healthy hosts. I haven't done this with Amazon RDS, but it should work. 

Resources:
http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html
http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ConnectToInstance.html
