### ISSUE TITLE
Foreign key constraint error to be handled for merge statements too. - MSSQL 

### ISSUE THREAD

**Issue by rdhanasekar** [sequelize/sequelize#7011]
Please include the merge statement in the foreign key constraint error handler in MSSQL query.js

err.message.match(/The MERGE statement conflicted with the FOREIGN KEY constraint "(.*)". The conflict occurred in database "(.*)", table "(.*)", column '(.*)'./);

__Dialect: mssql

**Comment by janmeier** [comment]
Please show some code to replicate the error (models, associations and
relevant sequelize calls)

Den 20/12/2016 07.57 skrev "rdhanasekar" <notifications@github.com>:

Please include the merge statement in the foreign key constraint error
handler in MSSQL query.js

err.message.match(/The MERGE statement conflicted with the FOREIGN KEY
constraint "(.*)". The conflict occurred in database "(.*)", table "(.*)",
column '(.*)'./);

__Dialect: mssql

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sequelize/sequelize/issues/7011>, or mute the thread
