### ISSUE TITLE
update child value if parent value got updated

### ISSUE THREAD

**Issue by nasr18** [sequelize/sequelize#7017]
I have two models `Family` & `Member`. Each models have same field named `address`. If `address` field of `Family` model got updated means, i have to update `address` field  in `Member` model.

My question is 

> How do i know that the particular `address` field is updated or not?

**Comment by janmeier** [comment]
In sequelize code you can use `model.changed('address')` to know if a specific field was updated. You could also add hooks to the model that will updated the child when the parent is updated, http://docs.sequelizejs.com/en/v3/docs/hooks/

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by nasr18** [comment]
OK. Thanks a lot for immediate response. Sorry for opening an issue. will check out.

**Comment by nasr18** [comment]
Can you pls give me a sample code? @janmeier
