### ISSUE TITLE
Translate documentation

### ISSUE THREAD

**Issue by Volga** [sequelize/sequelize#7041]
How can I help translate the documentation into another language?

**Comment by janmeier** [comment]
@Volga Thanks for wanting to help, and I'm really sorry for the late reply. 

While I really like the idea of having the documentation in several languages, I feel that it would all too quickly be outdated - Since most of the maintainers / people who do PRs can only update the english docs. Additionally, I have no idea how we would host multi-lingual docs. 

I'd suggest writing some blog-posts in your preferred language instead :)
