### ISSUE TITLE
A desktop app to export sequelize models automatically

### ISSUE THREAD

**Issue by andyforever** [sequelize/sequelize#7114]
I have create a desktop app to export sequelize model from database automatically.
Welcome to have a try.
https://github.com/andyforever/sequelizer
![app](https://camo.githubusercontent.com/947fd823085437881c1b18918633f3dbaa5d718b/68747470733a2f2f67772e616c6963646e2e636f6d2f7470732f5442315a574c47505858585858636f5846585858585858585858582d313732302d313136302e706e67)

**Comment by janmeier** [comment]
You are welcome to add it to the wiki :) 

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
