### ISSUE TITLE
MySQL "Generated always as" virtual fields.

### ISSUE THREAD

**Issue by Crusader4Christ** [sequelize/sequelize#7240]
__Dialect:__ mysql
__Database version:__ 5.7

I use generated virtual fields in my db. As I see I can't  map it to the model in read-only state. Sequelize.VIRTUAL datatype aren`t work with db at all, so I propose to add GENERATED data type to make this fields.

**Comment by sushantdhiman** [comment]
MySQL Virtual columns are computed field but defined as regular columns.

I suggest you add them as regular field in Model, but define setter to always set value to null / undefined https://github.com/sequelize/sequelize/issues/5869#issuecomment-247759174 so they never sent for updation

**Comment by Crusader4Christ** [comment]
@sushantdhiman If I define setter as null - it will be sent for updation as `SET field=null` Moreover - how I can add them to work with `sync()` method?

**Comment by sushantdhiman** [comment]
Setter `undefined` should not trigger a query.

I think we need a `readOnly` or `computed` flag maybe, tagging this as a feature

**Comment by chucksellick** [comment]
Just encountered a need for this, I have a large JSON column in the DB i'm working on, and I'm using computed columns to extract/index certain data out of the JSON blob, rather than having to do expensive JSON parsing in node or the browser when e.g. I am rendering a summary list of many records. Would be handy to have a flag to handle these fields properly rather than risk causing errors during updates.

**Comment by davepacifico** [comment]
Here is my use-case for this - We use sequelize as our ORM for probably 95% of our queries. We have a few raw queries for more complex stuff where we want/need more control. We migrate our schema using raw migration queries because we care about low-level control, indexing, etc. However, we use sequelize sync for our tests to generate a temporary test DB where we can populate data and then run our tests and validate. This has worked great for a while, but now we have a generated column in our database that's pretty critical. Since sequelize doesn't really support this, when we generate the database for tests, that column is just empty at all times and causes test failures.

The two things I am considering are:

1. Just run a few raw queries when our tests spin up to recreate the column correctly as a generated column
2. Write a getter on the model property which does something like return the computed column definition if the environment is test

Both of these options are very messy. Some kind of legitimate support for this would be useful. I think the bottom line is that a lot of consumers of sequelize (or any ORM), aren't going to be able to use it for 100% of queries, so things like the VIRTUAL type aren't always a complete solution. Sometimes you need the definition actually in the database.

I very much appreciate the maintainers of this great library. Just wanted to try to explain my use-case here.

**Comment by aaronhong** [comment]
Hope this is not too annoying, but +1

**Comment by ustun** [comment]
@sushantdhiman This should be re-opened I think.

**Comment by fennellgb23** [comment]
Any update on this?  I too need to use generated columns for several of my projects.

**Comment by reediculous456** [comment]
This is an issue in postgre as well. Sequelize has the `autoIncrementIdentity: true,` value that allows you to use the `GENERATED BY DEFAULT AS IDENTITY` DDL, but you cannot use `GENERATED ALWAYS AS IDENTITY` because .save tries to update the id property and the database rejects it

**Comment by ekr3peeK** [comment]
+1 for this feature - we also use generated columns in MariaDB, and at the moment I see no way of mapping them to a Sequelize model.

**Comment by ephys** [comment]
Closing in favor of https://github.com/sequelize/sequelize/issues/12718
