### ISSUE TITLE
datatype string in postgresql without limit

### ISSUE THREAD

**Issue by santiag8** [sequelize/sequelize#7346]
In the table creation, the fields with datatype string i like without limit and i can't

__Dialect: postgres
__Database version: 9.4
__Sequelize version: 3.30.2

**Comment by janmeier** [comment]
Are you looking for [TEXT](http://docs.sequelizejs.com/en/v3/api/datatypes/#text)?

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by santiag8** [comment]
is that it create a text type field in postgres, i like character varying without limit
