### ISSUE TITLE
How find key in JSON array

### ISSUE THREAD

**Issue by MikeBazhenov** [sequelize/sequelize#7349]
Hi!

### Postgres table structure

```js
{
id: 1,
name: 'Name 1'
locations: [{ city: 'New York', country: 'USA' }, { country: 'Japan', city: 'Tokyo' }]
},
{
id: 2,
name: 'Name 2'
locations: [{ city: 'New York', country: 'USA' }]
}
```

### Problem
Need to find Name 1 by 'locations.country' = 'Japan'

```js
where: {
'locations.country':'Japan' //This query doesn't work:(
}
```

SQL code like this works fine
```sql
SELECT count(*) AS "count" FROM table_name t, json_array_elements(t.locations) loc WHERE loc->>'country' = 'Japan';
```

How i can do this?

**Comment by janmeier** [comment]
```js
where: {
  locations: {
    $contains: [{
      country: 'Japan'
    }]
  }
}
```

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by priyanka-TL** [comment]
@janmeier how to define JSON array in model
