### ISSUE TITLE
Question on usage of timezone in options

### ISSUE THREAD

**Issue by iamjoyce** [sequelize/sequelize#7505]
## What you are doing?
Let's say we specify timezone as such:

```js
var sequelize = new Sequelize({
    // ...
    timezone: "+08:00"
});
```

## What do you expect to happen?
Assuming I have a column with `Type: Sequelize.DATE`

When I insert `2010-01-01 09:00` for that column, Sequelize stores `2010-01-01 09:00` into the database without converting the value to UTC timezone which is correct.

However, when I query for that same column, Sequelize then returns me `2010-01-01T09:00Z`, with a Z at the back.

## What is actually happening?
Shouldn't the results be `2010-01-01T09:00+08:00` instead of `2010-01-01T09:00Z` since the date is not in UTC timezone?

__Dialect:__ mssql
__Database version:__ MSSQL 2014
__Sequelize version:__ 3.0

**Comment by harshithkashyap** [comment]
This has been fixed on `master` by https://github.com/sequelize/sequelize/pull/7201

**Comment by iamjoyce** [comment]
What about V3? (I am asking for V3 actually)

**Comment by harshithkashyap** [comment]
This is a breaking change and hence available in v4 only.  You'll have to submit a PR to v3 if you need it.

**Comment by iamjoyce** [comment]
@harshithkashyap Do you mind elaborating on why is this a breaking change? I was comparing the files in master and v3 in this case, and I think v3 can be modified the same way.

*I can submit a PR to v3, just that I was curious on why is this counted as a breaking change.

Thanks!

**Comment by harshithkashyap** [comment]
Since the datatypes are different, if we change it on v3, sequelize models will use `DATETIMEOFFSET` but the database has `DATETIME2` datatype. You would need to convert the existing datetime2 to datetimeoffset. If you create new tables without datatype​ change, you'll have some in old datatype and some in new. Hence it's a BC. You can submit a PR to v3 and add a note in change log under BC section.
