### ISSUE TITLE
Alternative to Manage Models

### ISSUE THREAD

**Issue by ldipasquale** [sequelize/sequelize#7519]
Hi all! Is there any other aproach to manage models in Sequelize than this one: https://github.com/sequelize/express-example?

Because it's hard to work with, for example, conditions on associations on this structure.

Thanks you!

**Comment by sushantdhiman** [comment]
I am not sure why you would need conditional association, once synced those relationships will be persisted to database layer.

But I feel keeping relationships in [models/index.js](https://github.com/sequelize/express-example/blob/master/models/index.js#L30) is very easy to make sense among different associations, rather than having them each model's associate function.

You can also keep all associations in separate file like `relationships.js`, pass models to this file and call it inside [models.index.js](https://github.com/sequelize/express-example/blob/master/models/index.js#L30)

**Comment by ldipasquale** [comment]
Thanks @sushantdhiman 

By `conditions on associations` I mean conditions (where) on relations.

I have to query something like this:

```
Model.findAll({
  include: [
    {
      model: Model2,
      where: [
        name: 'string',
      ],
    },
  ],
})
```

And I can't because `Model2` isn't a variable because I can't import this model.

Do you have any alternative to this case?

**Comment by Notifium** [comment]
I'm just encountering this problem as well.

[This might help](https://github.com/sequelize/sequelize/issues/7236): they have assigned the models to express app locales, then call them via req.app.models.<ModelName>

**Comment by Notifium** [comment]
Or something like:

Model2 = model.sequelize.model.<model2 name>;
Model.finAll( ... );

**Comment by sushantdhiman** [comment]
require('models')  should give you all the models

> And I can't because Model2 isn't a variable because I can't import this model.

Why ?
