### ISSUE TITLE
Eager loading rewrites model.attributes to an Array of attribute names

### ISSUE THREAD

**Issue by grimalschi** [sequelize/sequelize#7554]
Hello!

model.attributes is an array of Objects.

But if I use eager loading with n:m associations, some inner optimisations changes model.attributes to an Array of attribute names.

I have 3 tables:
message
user
message_recipient

This is how I include them:
![image](https://cloud.githubusercontent.com/assets/9027592/25317543/476048da-2883-11e7-83f0-a3c9cce72ed7.png)

This is how message_recipient.attributes looks like BEFORE findAll():
![image](https://cloud.githubusercontent.com/assets/9027592/25317562/a1a86c3c-2883-11e7-8f4f-fe8d1a4f6155.png)

And this is how it looks like AFTER:
![image](https://cloud.githubusercontent.com/assets/9027592/25317566/afaf3a5e-2883-11e7-8774-f0a7ada15e53.png)

REALLY.

It all starts here:
![image](https://cloud.githubusercontent.com/assets/9027592/25317574/d9a4371a-2883-11e7-9b40-fdfd0b22f6d7.png)

Line 542. You see here replacement of attributes.

Why?

After this I cannot make message_recipient.create, because message_recipient.attributes are broken.

Either I understand something wrong either this is bug.

(Sorry for sad english and hello from Moldova)

**Comment by grimalschi** [comment]
This is how do I fix this.

![image](https://cloud.githubusercontent.com/assets/9027592/25318043/be27026e-288e-11e7-9fb6-8f68f63c29d5.png)

**Comment by sushantdhiman** [comment]
Can you show full include code with console attributes before and after. its quite possible that you are overwriting Model.attributes or its reference somewhere

**Comment by grimalschi** [comment]
Here is a code:

![image](https://cloud.githubusercontent.com/assets/9027592/25781288/a55ecafc-3340-11e7-9ae7-bd442cf26710.png)

**Comment by sushantdhiman** [comment]
I cant see any issue here, you need to submit a small code sample which reproduce this issue. I can't work with code screenshots :)

It looks like you have been modifying attributes and other private stuff, most likely an user land problem. I'll reopen this issue once you submit some code which demonstrate this issue

**Comment by MattMcNam** [comment]
Hi!

Two things to add here since I came across this issue while debugging this problem myself:
1) Don't create your join table entry manually (`message_recipient.create`), instead add it using the functions sequelize generates, e.g. (`message.addUser(some_user)`)

2) Sequelize itself is changing the attributes in `_expandAttributes(options)`, the options argument may be a Model for a join table: https://github.com/sequelize/sequelize/blob/11ff7764819f2812018f3a7b8fa16ba1851e8c4d/lib/model.js#L2818-L2831

After changing the code to call `.add()` and `.remove()` it works as expected, so I'm not sure anything needs to be changed in Sequelize, but I want this to be documented for others to hopefully save them some hours of debugging 😄
