### ISSUE TITLE
addAssociation not setting join table attributes via `through: { ... }`

### ISSUE THREAD

**Issue by Kitanotori** [sequelize/sequelize#7572]
## What you are doing?
Trying to set custom attributes to the join table with addAssociation's `through: { ... }` options, similarly as in the [user.addProject(project, { through: { status: 'started' }})](http://docs.sequelizejs.com/en/latest/docs/associations/) example:
```js
my_model_instance.addAssociation(
	another_model_instance,
	{
		through: { custom_join_table_attribute: '...' },
		transaction: t
	}
);
```

## What do you expect to happen?
addAssociation should add custom join table attributes when specified via `through: { ... }`.

## What is actually happening?
Join table gets correct ids, but `custom_join_table_attribute` is not set (does not appear in the generated INSERT statement).

__Dialect:__ mysql
__Database version:__ 5.7.17
__Sequelize version:__ 3.30.4

**Comment by Kitanotori** [comment]
Just noticed that if I put custom attributes into the `options` body (i.e. without `through` object, as shown in the documentation), they are passed appropriately. It seems that either the documentation is not up-to-date, or the code does not work as it should.

**Comment by janmeier** [comment]
This is only supported in v4 - V3 docs are here http://docs.sequelizejs.com/en/v3/

**Comment by baldassarreFe** [comment]
I'm using version 4.0.0-0 and I noticed the same behavior. When doing:
```
User = sequelize.define('user', {});
Project = sequelize.define('project', {});
UserProject = sequelize.define('user_project', {
    role: Sequelize.STRING
});
User.belongsToMany(Project, { through: UserProject });
Project.belongsToMany(User, { through: UserProject });
```

The way I am able to get the role persisted is the [v3 style](https://sequelize.readthedocs.io/en/v3/docs/associations/#belongs-to-many-associations) (ignore the `await`, they are only there to avoid nesting some `then`):
```
let u = await User.create({})
let p = await Project.create({})
u.addProject(p, {role: 'manager' });
```

However, in the documentation for [v4](http://docs.sequelizejs.com/manual/tutorial/associations.html#belongs-to-many-associations) it says:
```
let u = await User.create({})
let p = await Project.create({})
await u.addProject(p, {through: {role: 'manager' }});
```

The way I noticed was because I had an through table with a non-null column that was not getting filled during the update, resulting in a constraint violation. In the case of `role` instead, Sequelize simply adds a row in the join table with a null value for the `role` field and the issue is completely transparent. Further debugging with the SQL logging enabled showed that Sequelize was completely ignoring the `{through: {role: 'manager' }}` option.

So either the api of Sequelize 4 should be updated to reflect the new documentation or the docs should revert back to the v3 examples

**Comment by raphodn** [comment]
hello, had the same issue after reading the docs from different sources

[here](http://docs.sequelizejs.com/class/lib/associations/belongs-to-many.js~BelongsToMany.html) they show an example with `through`:
```
user.addProject(project, { through: { role: 'manager' }});
```

but [here (readthedocs latest)](http://sequelize.readthedocs.io/en/latest/api/associations/belongs-to-many/) & [there (readthedocs v3)](http://sequelize.readthedocs.io/en/v3/api/associations/belongs-to-many/) without:
```
user.addProject(project, { role: 'manager', transaction: t });
```

I have sequelize `3.30.4` but was trying to save join table fields using `through` and they were not saving. removing the `through` fixed it for me

**Comment by fzamperin** [comment]
+1 I have a similar case but I cant set using v3 or v4 styles, I'm using Sequelize v4. I get an aggregation error since both of my join table attributes are `allowNull: false`

`result = await seguido.addSeguidor(seguidor, {through: { aprovado: true, recusado: false }});`
`result = await seguido.addSeguidor(seguidor, { aprovado: true, recusado: false });`

**Comment by ketus** [comment]
I also experience this, I think. At least something very similar. 
What I tried is:
`await order.addProduct(1, {through: {Quantity: 32}});`
which works.

> Quantity is separate attribute on N:M table

and these aren't:
```
[err, order] = await to(Order.findOne({ where: {ID: OrderID} })); //OK
[err, products] = await to(Product.findAll()); //OK
await order.addProducts(products); // Aggregation error
```
`products` returns two instances and of course don't include `Quantity` properties, but I'm not how I'm supposed to add them in this case.
 

Stack trace (with erased paths on purpose):
`Uncaught Error { filename: 'PATH_TO_FILE/node_modules/sequelize/lib/model.js',
  line: 2350,
  row: 24,
  message: 'aggregate error',
  type: 'AggregateError',
  stack: 'AggregateError: aggregate error\n    at Promise.try.then (/PATH_TO_FILE/node_modules/sequelize/lib/model.js:2350:24)\n    at tryCatcher (PATH_TO_FILE/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/PATH_TO_FILE/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/PATH_TO_FILE/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (PATH_TO_FILE/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (PATH_TO_FILE/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (PATH_TO_FILEnode_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (PATH_TO_FILE/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (PATH_TO_FILE/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)',
  arguments: undefined }
`

**Comment by wesleydeverdade** [comment]
I'm using the version 5.21.6 of sequelize, and I've tried the both solutions above and not works. Below one example of my code.

await list.addAlbum(album, {  through: { album_order, note }  });
await list.addAlbum(album, {  album_order, note, });
