### ISSUE TITLE
Finding all instances of modal which has a set field and aren't associated with a modal

### ISSUE THREAD

**Issue by christopherdiehl** [sequelize/sequelize#7675]
I have Product and CompetitorProduct modals which are n:m through a table ProductRelations. I am trying to find all CompetitorProducts which has a description like %s% and aren't associated with a particular product instance.

I have tried this and gotten an error back:

```
const cproducts = await CompetitorProduct.findAll({
      where: {
        description: { $ilike : `%${description}%`},
        '$Product.sku$': { $ne: sku } },

      },
      include: [{
        model: Product,
        attributes: [sku]
      }],
      limit: 10
    });
```
Current ugly fix so you can see my intention:

    const product = await Product.findOne({ where: { sku: sku }});
    const cproducts = await CompetitorProduct.findAll({
      where: {
        description: { $ilike : `%${description}%`},
      },
      limit: 10
    });
    let retval = [];
    for (cproduct of cproducts) {
      if (! await product.hasCompetitorProduct(cproduct)){
        retval.push(cproduct);
      }
    }

Is this a bug or am I just missing something?

__Dialect: postgres
__Sequelize version: 3.30.1

**Comment by aboveyou00** [comment]
I'm pretty sure that using a raw key (like '$Product.sku$') currently breaks when used in conjunction with 'limit'. I'm running into problems in my own project because of it. Can you try the query without adding the limit?

Also, it would be helpful to see the exact error message you are receiving, as well as exactly what SQL is being generated.
