### ISSUE TITLE
Error in self-join

### ISSUE THREAD

**Issue by priceen** [sequelize/sequelize#7775]
hi, after the update to Sequelize 4.0 version we have errors with self join like this:

` Company.belongsToMany(models.companies, { as:'shareholders', through: models.companies__stakes, foreignKey:'subsidiary_id' });
Company.belongsToMany(models.companies, { as:'subsidiaries', through: models.companies__stakes, foreignKey:'company_id' });
`

Error message: **You have used the alias shareholders in two separate associations. Aliased associations must have unique aliases**

Thanks for support,
Saverio

**Comment by priceen** [comment]
solved, my fault in other code lines ;)

**Comment by lassmann** [comment]
could you put what was your mistake?

**Comment by charlieargue** [comment]
Yes, please post your solution, I'm experiencing the same problem after upgrading to Sequelize ver 4. Thanks!

**Comment by Willey1986** [comment]
Hi, I had the same issue but found an error in my code.

I created my models using the sequelize cli. Inside of the generated models/index.js the associate function is called automatically if present:

```
Object.keys(db).forEach(function(modelName) {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
}); 
```

I was calling the associate function in my code again but because associate was already called the error occured.


**Somewhere in my code:**
`User.associate(models);`

**Solution: Don't call associate in your code manually if you use sequelize cli**

Hopefully this helps. If not I would guess that you are calling associate in multiple places.

**Comment by charlieargue** [comment]
Confirming @Willey1986 -- you are correct, I had the models loading twice -- just stumbled on this yesterday:
* once in app.js to .use the routes
* and again in various services 

Sequelize ver 3 was ok with it, but the error happened when switched to ver 4.

Since I DO need to load the models in such a way in multiple places (have multiple databases), the trick for me was to just add some _double tap_ flags and logic to prevent the association logic from firing twice.

Thanks @Willey1986 for your input, much obliged!

**Comment by ahlwong** [comment]
I have issues here as well:

`models.User.belongsToMany(models.Company, { as: 'JoinCompanies', through: 'CompanyJoin', onDelete: 'CASCADE' });
models.Company.belongsToMany(models.User, { as: 'JoinUsers', through: 'CompanyJoin', onDelete: 'CASCADE' });

SequelizeAssociationError: You have used the alias CompanyJoin in two separate associations. Aliased associations must have unique aliases.
`
