### ISSUE TITLE
Reload & Read Replica

### ISSUE THREAD

**Issue by p-j** [sequelize/sequelize#7844]
Hi !

I little summary first:
I'm trying to load balance queries on an AWS Aurora Cluster.
We have a fairly big app with tons of models, relations and scopes.
In order to decouple our logic, we often uses "mutations" (Command Pattern) to perform writes to the database, then we have a template engine that builds the response, fetching fresh data from the database.
It works very well on a single database, but when I introduced read replica, I started to get "random" errors.

## What you are doing?

```js
const master = { host, username, password, port, database }
const replica = { host2, username2, password2, port2, database2 }
const Sequelize = require('sequelize')
const sequelize = new Sequelize(null, null, null, {
  dialect: 'mysql',
  pool: {
    handleDisconnects: true,
    min: 1,
    max: 10,
    idle: 10000,
    replication: {
      write: master,
      read: [master, replica],
    },
  },
})

const models = {
  replies: sequelize.define('replies'),
  conversations: sequelize.define('conversations'),
}

models.conversations.hasMany(models.replies)
models.conversations.addScope('show', { include: [ { model: models.replies, separate: true } ] })
const conversationScope = models.conversations.scope('show').$scope

function addReply (mydata) {
  return model.replies.create(mydata).then((reply) => reply.reload(conversationScope)
}
```

## What do you expect to happen?
The reload function would be executed against the the Master

## What is actually happening?
The reload function may (or may not) be executed against the Replica, which needs 15-20 ms to synchronize. In this case it would throw a 

```
"Instance could not be reloaded because it does not exist anymore (find call returned null)" 
```

__Dialect:__ mysql
__Database version:__ Aurora on RDS (MySQL)
__Sequelize version:__ 3.30.4

---

I believe I can fix this by adding `useMaster: true` to the reload call, but as we have tons of similar case that may be a `find` call in a series of promise, or a `reload` right after to load a larger scope.

Is there a recommended way of doing things?

I found that the documentation around replication was a bit terse and I would very much like to help in this domain by contributing a Tutorial when we're done, but in the meantime I'll be more than happy if you could share what is the recommended way of doing things.

- Should I go around and add `{ useMaster: true }` anytime it might be needed
- Should I setup transactions at the HTTP query level to get all my queries within the same transaction ? Long running transactions should probably be avoided, so I guess it's not going to cut it. Also, from my understanding, read only transactions have to be flagged manually so it's just reversing the problem.
- Should I setup 2 instances of Sequelize, one configured for read/write and one for read only and scope my SQL interactions to one of these instances based on HTTP query ?
- Should I simply use the `retry` option ? What are the drawbacks ?
- Do you think the library should address this or is it not the scope of Sequelize ?

Thanks :)

**Comment by p-j** [comment]
At the moment I've gone through the whole app adding `useMaster: true` where it made sense.
Happy to listen to other possible solutions.

**Comment by Diluka** [comment]
I occurred this issue too.
I using transaction through `cls` and the `transaction` is not passed to `reload` automatically.
I solved by manually pass `transaction` to `reload`.

**Comment by Diluka** [comment]
I found the reason.
`cls` is **not** support `ES2017`

**Comment by sushantdhiman** [comment]
> Should I go around and add { useMaster: true } anytime it might be needed

In short, Yes. At Snaplytics, we run our GraphQL lambdas with read replicas. Each request include a `context`. We usually pass `context.useMaster: true` (when replicas are enabled, otherwise its just noop) and use them through all GraphQL mutations.

As you have already seen replica take some time to resync. Mutations change data, so its better to run them against master where fresh data is instantly available.


> Should I setup transactions at the HTTP query level to get all my queries within the same transaction ? Long running transactions should probably be avoided, so I guess it's not going to cut it. Also, from my understanding, read only transactions have to be flagged manually so it's just reversing the problem.

By running a mutation wide transaction you can avoid using read replica, yes. But that is just too complex and drains performance. You dont need all mutations in transaction.

> Should I setup 2 instances of Sequelize, one configured for read/write and one for read only and scope my SQL interactions to one of these instances based on HTTP query ?

Again this is going to be bit complex, depends upon your project structure. Simple `useMaster: true` will allow you to avoid possibly unnecessary overwrite 

> Should I simply use the retry option ? What are the drawbacks ?

You have to add retries to too many code fragments. Some time there will be silent issues if replica was not synced.

Suppose you depend upon a row to be found for next action, using read replica with lags that row may not be found in time, your may be have a switch to do something else in that case. Row is actually in database but read replica was not synced, thus performing an incorrect operation.

`useMaster: true` will add less code debt in my opinion. 

> Do you think the library should address this or is it not the scope of Sequelize ?

I don't see how other library may help here, Are you suggesting patching all methods and pass `useMaster: true` by default. I think fine control over when to use read replica and when to use master with `userMaster` is better. You don't want to have all your queries going to master, thus defeating purpose of read replica in first place.

**Comment by p-j** [comment]
Thanks for the detailed answer @sushantdhiman 
We reached the same conclusion and added `useMaster: true` where it made sense.

**Comment by ecdeveloper** [comment]
Just do add to the topic - we ran into same exact issue, and used the same exact approach - `useMaster: true`. It's clean and doesn't add unnecessary complexity.

**Comment by yuriploc** [comment]
Something I couldn't understand from the docs is: should I use `reload()` when working with replicas and using the `useMaster`?

**Comment by DaveStein** [comment]
All my models are basically A extends BaseClass extends Sequelize.Model. We only ever use reload directly after an update where we need the most up-to-date data. My `BaseModel` has this:

```js
  async reload(options = {}) {
    // Reload should only be used after updates and therefore should always read from master
    options.useMaster = true;
    return super.reload(options);
  }
```

I can always tweak this to optimize later on in life, but we need master to make sure data is latest for when we save to Redis cache key for an instance.

That being said, I am still seeing `SequelizeInstanceError: Instance could not be reloaded because it does not exist anymore (find call returned null)`. Am I doing it right? I had also filed an issue around `useMaster` not being documented, but mentioned in several issues such as the one above.

**Comment by papb** [comment]
Hello @DaveStein sorry to take long to reply, have you figured out a workaround for your issue?

**Comment by DaveStein** [comment]
@papb I had forgotten about this ticket. I found the reason and hopefully this helps someone - race conditions! I had two people hitting my service at the same time. One to update and one to delete. The delete would finish ahead of the update and that would cause this error. It was unfortunate coincidence that I had added in replicas right around the time this started happening.

**Comment by DaveStein** [comment]
@papb as an aside, can we expect to use `useMaster` in any options? ie 
```js
   const chapters = await this.findAll({
      where: { id: 55 },
      order: [['seconds_in', 'ASC']],
      useMaster: true
    });
```
