### ISSUE TITLE
Why the 'subQuery' option from findAll() isn't on the documentation?

### ISSUE THREAD

**Issue by edu791** [sequelize/sequelize#7865]

**Comment by felixfbecker** [comment]
Cause it is one of these "only use them if you know what you're doing" options. You can only use them for 1:n relations if you know for sure that your include will only yield one result (because of JOIN or WHERE conditions etc.). That said, if the caveats are documented, I don't see a reason why it shouldn't be documented.

**Comment by eduardrock** [comment]
mmmm, I don't agree.
I discovered the 'subQuery' option because of a comment on a StackOverFlow question. I think it would be easier if it were documented. I would not had wasted productivity hours by figuring out this problem.

**Comment by felixfbecker** [comment]
As I said, if the caveats are documented, I don't see a reason why it shouldn't be documented. Feel free to do a PR

**Comment by apapap** [comment]
Like eduardrock, I only discovered the 'subQuery' option because of a comment buried in a StackOverFlow question.  It first took me a while to recognize that Sequelize was using a subquery in the FROM clause.  Then, I spent hours wondering why.  Scouring the documentation, I couldn't figure it out.

"You can only use them for 1:n relations if you know for sure that your include will only yield one result (because of JOIN or WHERE conditions etc.)."

An explanation of why and when subqueries are used would be helpful.  In my case, I wanted parent.findAll() to include a COUNT and MIN of fields from a child table, in addition to all the parents' other fields.  Seems like a situation many people would run across.  Looks like a limit I included was causing Sequelize to generate the subquery.  I almost gave up and used a separate raw query.

Thanks all for your work on Sequelize.  It's had a big impact on many projects, including mine.

**Comment by jmwielandt** [comment]
Greetings from the future! (?)

I've discovered the option because of the linter. Now reading first @felixfbecker comment I think the bug I've found yesterday (not reported yet) with a top-level condition using `$nested.columns$` (`"$axis.subject.students.id$": userId`, where User and Subject has a many-to-many relationship called "StudentsSubject") could be due to this option was enabled by default.
🤔 
I'm buissy right now, eventually I'll come back with news. Comments on this are appreciated btw~

**Comment by edu791** [comment]
Hi @jmwielandt , 4 years have passed and the problem never was solved.
Sequelize is dead. Now I'm  using TypeORM and I'm happy

**Comment by jmwielandt** [comment]
@edu791 hi, ironically we are switching our project from typeorm to sequelize (using sequelize-typescript and type-graphql) due to the insane lack of documentation of typeorm and we are already happy with our decision 😂

**Comment by ephys** [comment]
It's not in the guides part of the documentation but it is present & explained in our jsdoc. Should become visible on the website once we're done with https://github.com/sequelize/sequelize/pull/13914

**Comment by ephys** [comment]
It is part of the API reference now
