### ISSUE TITLE
findAndCount doesn't return a count when passed raw:false and includes

### ISSUE THREAD

**Issue by skinofstars** [sequelize/sequelize#7931]
## What you are doing?

Using findAndCount with raw:false and includes doesn't return a count.

```js
Blah.findAndCount({
  include: [Model],
  raw: false,
  distinct: true
})
```

## What do you expect to happen?
Have a count in the result

## What is actually happening?
count: 0

----

Further investigation shows this may be a problem with `count` itself returning NaN when raw:false

**Comment by DesignByOnyx** [comment]
This issue was discovered while working on a feathersjs project (referenced above), however, I can confirm that the issue is with Sequelize and not feathers. Setting `raw: true` returns the expected results. I tested with the following versions:

- v3.23.2
- v3.30.4 (latest 3.x)
- v4.3.2 (latest 4.x)

I created a stand-alone file for testing. This is a minimal test case that you can copy and paste to quickly see the error. Just run the file with a valid connection string:

https://gist.github.com/DesignByOnyx/2fe00cdc96312dda971020dd54ba84b6

**Comment by skinofstars** [comment]
this is still an issue

**Comment by snewell92** [comment]
Observed same behavior with `sequelize: 4.8.4`.

**Comment by purepear** [comment]
this is a bug i think... if you remove/comment `raw` it works.. but if you explicitly set it `raw: false` it fails

**Comment by iofluxdev1** [comment]
Explicitly setting raw: false causes count to be 0 in our case too.

**Comment by chrisc96** [comment]
still an issue

"sequelize": "^4.37.6",

**Comment by a631807682** [comment]
still an issue

4.39.0

**Comment by purepear** [comment]
Haven't tested it but setting `raw: undefined` instead of `raw: false` might work... but still not pretty :)

**Comment by ch-stephenzuniga** [comment]
I was running into this as well and dug a bit into the sequelize source code to try and find the problem. Here's the code path that fails:
1. [`findAndCountAll` calls `count`](https://github.com/sequelize/sequelize/blob/d38c7cc04d61e0b537df37e7a4b08bf7528656a5/lib/model.js#L2050)
2. [`count` sets `options.plain` to true when not grouping](https://github.com/sequelize/sequelize/blob/d38c7cc04d61e0b537df37e7a4b08bf7528656a5/lib/model.js#L1990). This will be important later.
3. [`count` calls `aggregate`](https://github.com/sequelize/sequelize/blob/d38c7cc04d61e0b537df37e7a4b08bf7528656a5/lib/model.js#L2000)
4. [`aggregate` calls `rawSelect`](https://github.com/sequelize/sequelize/blob/d38c7cc04d61e0b537df37e7a4b08bf7528656a5/lib/model.js#L1950)
5. [`plain` is set to true, so `rawSelect` skips this if block and runs into the buggy code](https://github.com/sequelize/sequelize/blob/d38c7cc04d61e0b537df37e7a4b08bf7528656a5/lib/query-interface.js#L1151)
6. [`rawSelect` attempts to access the "count" property of a Model which is undefined](https://github.com/sequelize/sequelize/blob/d38c7cc04d61e0b537df37e7a4b08bf7528656a5/lib/query-interface.js#L1155)
7. [`undefined` is run through `parseFloat` which returns `NaN`](https://github.com/sequelize/sequelize/blob/d38c7cc04d61e0b537df37e7a4b08bf7528656a5/lib/query-interface.js#L1165)

As far as I can tell, there is no way to pass `raw: false` to the `findAndCountAll` method and get a valid count. I attempted to add a `group` option to the original `findAndCountAll` options object which skipped the buggy code, but then `count` was an array of model objects which wasn't really useful. For now, I'm back to using `raw: true` since it works well enough for me.

**Comment by jslok** [comment]
Still an issue on 5.12.3
Setting `raw: undefined` instead of `raw: false` works for me as @purepear said.
