### ISSUE TITLE
Bad time Format

### ISSUE THREAD

**Issue by jack118104** [sequelize/sequelize#7944]
## What you are doing?

```js
// code here
 const sequelize = new Sequelize(config.database, config.username, config.password, {
     host: config.host,
     dialect: 'mysql',
     dialectOptions: {
         dateStrings: 'DATETIME',
     },
 })

//`create_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 const sql = `select create_at from users`;
 sequelize.query(sql, { type: sequelize.QueryTypes.SELECT })
     .then((res) => {
         console.log(res)
     })
```

## What do you expect to happen?
_I wanted Foo!_
I want the field create_at format for the 2017-07-13 00:00:00, but the return format is 2017-01-11T00: 00: 00.000Z, the current official document api no configuration can be set, I try to set dialectOptions But the result is bad. You can only modify the _typecast method in /sequelize/lib/dialects/mysql/connection-manage.js
## What is actually happening?
_But the output was bar!_
select * from users
_Output, either JSON or SQL_
[ { id: 3,
    appid: '123',
    username: '123',
    password: '123',
    type: 0,
    wechatname: '123',
    create_at: 2017-07-12T12:12:49.000Z } ]

__Dialect:__ mysql 
__Database version:__ ^1.3.6
__Sequelize version:__ ^4.1.0

**Comment by jack118104** [comment]
why,why,why,why

**Comment by jack118104** [comment]
why,why,why,why

**Comment by micksatana** [comment]
The time format is according to [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601)

In case of selecting data, if you want to use it on server-side, just convert the date to string format you need. if you want to use it on client-side simply pass the UTC date to client and let javascript on client-side handle the conversion.

In case of inserting or updating data, you need to parse it to the database acceptable format to use with direct query string or use a method provided by Sequelize instead of direct query string.

Why save in UTC format instead of server local time? I think it's a good practice to keep the date time in database server in UTC as it can guaranteed to be consistent. For examples, you have database servers syncing data in two different timezone and your users are in many different timezone. Saving data in UTC on server-side and let client-side app converts the date time to its timezone is easier than saving data in server local time and need to handle date time from different timezone.

**Comment by jack118104** [comment]
@micksatana Thank you for your answer. I mean that the sequelize configuration conflicts with the dialectOptions configuration. If I use mysql2 alone, I only need to set up
DialectOptions: {
          DateStrings: 'DATETIME'
}
, I get the format is 2017-02-05 17:00:00, if you write sql set create_at so too elegant

**Comment by jack118104** [comment]
https://www.npmjs.com/package/sequelize-date 
This is a fix for the problem
