### ISSUE TITLE
How to support findAll with View ? 

### ISSUE THREAD

**Issue by Symous** [sequelize/sequelize#7991]
Hi, I have create a View on MySQL, But when I try to invoke findAll/findOne method it gives me an error that:
Cannot read property 'findAll' of undefined

Is there any way with Sequelize to support these method on View just like table ?Thanks.

**Comment by linusws** [comment]
I have the same problem. Any suggestions of how to fix it?

**Comment by KeyOnTech** [comment]
Hi saw this thread and figured it out if this is still an issue for anybody...
going to try and explain best i can
first create a model file with the fields you need from your view, in this model there has to be a primary index...

sequelize/model/view_model_vwloginslist.js

const Sequelize = require('sequelize');
const sequelize = require('../database/connection');
module.exports = sequelize.define("vwloginslist",
    {
        loginid: {
            field: 'id',
            type: Sequelize.INTEGER,
            allowNull: false,
            autoIncrement: true,
            primaryKey: true,
        },
        name: {
            type: Sequelize.STRING(255),
        },
        login: {
            type: Sequelize.STRING(255),
        },
        roledescription: {
            type: Sequelize.STRING(255),
        },
    },
    {
        timestamps: false,
    }
);

**Comment by KeyOnTech** [comment]
next make a migration file, the special thing about this file is you will delete the table model auto created by sequelize then create or replace the view with the same name.  Once this is done you will be able to do a findAll against the model because it will call the view

20200102010201-vwloginslists_create_view_delete_model_table.js


/*
  * create new migration file and name
npx sequelize migration:create --name create_view_vwloginslist

  * run all 
npx sequelize db:migrate

  * run single - from here to there in files list
npx sequelize-cli db:migrate --from 20170316142544-create-an-index.js --to 20170421112638-do-some-refactor.js

  * undo single
npx sequelize db:migrate:undo

  * undo all
npx sequelize db:migrate:undo

*/
'use strict';
const sequelize = require("../database/connection");
/*** 
if you are using views make sure you add the s to the end of the name below in proper grammer format and this way you will
auto delete the model on sync

migrations file no mvw just vw name, add the s to the end for proper grammar
  vwLoginsLists
      ex:
      20200102010201-vwloginslists_create_view_delete_model_table.js
      const view_name = 'vwloginslists';


models file no s, s will automatically be added 
  vwLoginsList
  s will automatically be added 
    ex:
      vwloginslist.js
      module.exports = sequelize.define("vwloginslist",
      vwloginslist.js

now on your routes you can use the vw model file to do a findAll
    ex:
      loginsroles-routes.js
      const vwLoginsList = require('../sequelize/models/vwloginslist');
      await vwLoginsList.count()
      return vwLoginsList.findAll(
        whereCondition
      )

 */
/*** this is only used for views if this is not related to a view delete these sections --- start */
const auto_created_model_table_name = 'vwloginslists';
/*** this is only used for views if this is not related to a view delete these sections --- end */
const view_name = 'vwloginslists';
const original_query = "SELECT "
  + " logins.id, logins.name, logins.login, logins.loginenabled, logins.role,  "
  + " CASE "
  + " WHEN logins.loginenabled = 0 THEN 'DISABLED' "
  + " WHEN logins.loginenabled = 1 THEN 'ENABLED' "
  + " END AS loginenableddescription, "
  + " loginroles.description AS roledescription  "
  + " FROM logins "
  + " LEFT JOIN loginroles "
  + " ON loginroles.id = logins.role "

const new_query = "SELECT "
  + " logins.id, logins.name, logins.login, logins.loginenabled, logins.role,  "
  + " CASE "
  + " WHEN logins.loginenabled = 0 THEN 'DISABLED' "
  + " WHEN logins.loginenabled = 1 THEN 'ENABLED' "
  + " END AS loginenableddescription, "
  + " loginroles.description AS roledescription  "
  + " FROM logins "
  + " LEFT JOIN loginroles "
  + " ON loginroles.id = logins.role "

module.exports = {
  up: function (database, Sequelize) {
    return Promise.all([
      /*** this is only used for views if this is not related to a view delete these sections --- start */
      sequelize.query(`DROP TABLE IF EXISTS ${auto_created_model_table_name}`)
        .then(result => {
      /*** this is only used for views if this is not related to a view delete these sections --- end */
          sequelize.query(`CREATE OR REPLACE VIEW ${view_name} AS ${new_query}`)
            .then(result => {
                return result
            })
      /*** this is only used for views if this is not related to a view delete these sections --- start */
        })
      /*** this is only used for views if this is not related to a view delete these sections --- end */

    ]);
  },
  down: function (database, Sequelize) {
    return Promise.all([
      sequelize.query(`DROP TABLE IF EXISTS ${auto_created_model_table_name}`)
        .then(result => {
          sequelize.query(`CREATE OR REPLACE VIEW ${view_name} AS ${new_query}`)
            .then(result => {
                return result
            })
        })
    ]);
  }
};

**Comment by KeyOnTech** [comment]
next make a migration file, the special thing about this file is you will delete the table model auto created by sequelize then create or replace the view with the same name.  Once this is done you will be able to do a findAll against the model because it will call the view

The code below keeps auto formating.... but. you get the jest of what i'm doing and i cant paste it without the bullets that are actually * / or the bullets that are actually + " so here you go...

20200102010201-vwloginslists_create_view_delete_model_table.js


/*
  * create new migration file and name
npx sequelize migration:create --name create_view_vwloginslist

  * run all 
npx sequelize db:migrate

  * run single - from here to there in files list
npx sequelize-cli db:migrate --from 20170316142544-create-an-index.js --to 20170421112638-do-some-refactor.js

  * undo single
npx sequelize db:migrate:undo

  * undo all
npx sequelize db:migrate:undo

*/
'use strict';
const sequelize = require("../database/connection");
/*** 
if you are using views make sure you add the s to the end of the name below in proper grammer format and this way you will
auto delete the model on sync

migrations file no mvw just vw name, add the s to the end for proper grammar
  vwLoginsLists
      ex:
      20200102010201-vwloginslists_create_view_delete_model_table.js
      const view_name = 'vwloginslists';


models file no s, s will automatically be added 
  vwLoginsList
  s will automatically be added 
    ex:
      vwloginslist.js
      module.exports = sequelize.define("vwloginslist",
      vwloginslist.js

now on your routes you can use the vw model file to do a findAll
    ex:
      loginsroles-routes.js
      const vwLoginsList = require('../sequelize/models/vwloginslist');
      await vwLoginsList.count()
      return vwLoginsList.findAll(
        whereCondition
      )

 */
/*** this is only used for views if this is not related to a view delete these sections --- start */
const auto_created_model_table_name = 'vwloginslists';
/*** this is only used for views if this is not related to a view delete these sections --- end */
const view_name = 'vwloginslists';
const original_query = "SELECT "
  + " logins.id, logins.name, logins.login, logins.loginenabled, logins.role,  "
  + " CASE "
  + " WHEN logins.loginenabled = 0 THEN 'DISABLED' "
  + " WHEN logins.loginenabled = 1 THEN 'ENABLED' "
  + " END AS loginenableddescription, "
  + " loginroles.description AS roledescription  "
  + " FROM logins "
  + " LEFT JOIN loginroles "
  + " ON loginroles.id = logins.role "

const new_query = "SELECT "
  + " logins.id, logins.name, logins.login, logins.loginenabled, logins.role,  "
  + " CASE "
  + " WHEN logins.loginenabled = 0 THEN 'DISABLED' "
  + " WHEN logins.loginenabled = 1 THEN 'ENABLED' "
  + " END AS loginenableddescription, "
  + " loginroles.description AS roledescription  "
  + " FROM logins "
  + " LEFT JOIN loginroles "
  + " ON loginroles.id = logins.role "

module.exports = {
  up: function (database, Sequelize) {
    return Promise.all([
      /*** this is only used for views if this is not related to a view delete these sections --- start */
      sequelize.query(`DROP TABLE IF EXISTS ${auto_created_model_table_name}`)
        .then(result => {
      /*** this is only used for views if this is not related to a view delete these sections --- end */
          sequelize.query(`CREATE OR REPLACE VIEW ${view_name} AS ${new_query}`)
            .then(result => {
                return result
            })
      /*** this is only used for views if this is not related to a view delete these sections --- start */
        })
      /*** this is only used for views if this is not related to a view delete these sections --- end */

    ]);
  },
  down: function (database, Sequelize) {
    return Promise.all([
      sequelize.query(`DROP TABLE IF EXISTS ${auto_created_model_table_name}`)
        .then(result => {
          sequelize.query(`CREATE OR REPLACE VIEW ${view_name} AS ${new_query}`)
            .then(result => {
                return result
            })
        })
    ]);
  }
};

**Comment by KeyOnTech** [comment]
last step go to your route file and here's is how you can now findAll

const vwLoginsList = require('../sequelize/models/view_model_vwloginslist');
                await vwLoginsList.count(
                    whereConditionCount
                )

or
                    return vwLoginsList.findAll(
                        whereCondition
                    )

or etc...

**Comment by KeyOnTech** [comment]
next npm run start to auto create all the models and tables
stop the node server
next run sequelize migration to clean up the auto created tables and create your view for you
npx sequelize db:migrate

now start your server again npm run start and your findAll should work great

hope this helps the next person or myself in the future

Note to future self... your awesome and its all gonna be worth it one day :)
