### ISSUE TITLE
Model inheritance chain causes associations to throw an error

### ISSUE THREAD

**Issue by jimsimon** [sequelize/sequelize#8258]
## What you are doing?

```js
class MyBaseModel extends Model {
  ...
}

class MyActualModel extends MyBaseModel {
  ...
}

class MyOtherModel extends MyBaseModel {
  ...
}

MyActualModel.hasMany(MyOtherModel)
```

## What do you expect to happen?
I expected this to not throw an error.

## What is actually happening?
`MyActualModel.hasMany called with something that's not a subclass of Sequelize.Model`

It looks like the `instanceof` check on line 12 of mixin.js is a little too strict and should just be `!(target instanceof this.sequelize.Model)`.  Right now it's checking `target.prototype` instead of just `target`.

__Dialect:__ any
__Database version:__ N/A
__Sequelize version:__ 4.8.0

**Comment by FMurray** [comment]
I have this error as well

**Comment by jimsimon** [comment]
That's odd, I'm not sure why the file structure would matter here.  I haven't checked to see if this has been fixed, as I ended up not using Sequelize.

**Comment by wescorn** [comment]
still a problem...

**Comment by jawadakram20** [comment]
@jimsimon Were you able to fix this issue and where can I start with single table inheritance?

**Comment by jimsimon** [comment]
@jawadakram20 I didn't fix the issue and I ended up not using Sequelize.

**Comment by sophiayang1997** [comment]
that's odd...I had this error as well when I was defining my models in separate files and using module.exports.

**Comment by peabnuts123** [comment]
Just posting this around on all these similar issues; I ran into this error because i was importing my Models from another folder i.e. the file where my model was defined was importing `sequelize` from a different node_modules. This meant that the `instanceof` check was false because, even though my models WERE inheriting from `Model` from `sequelize` - it was a different class, technically (with all the same properties and attributes). 

You can think of a `foo instanceof MyClass` check as comparing the prototype of `foo` all the way up the chain e.g. `foo.__proto__ === MyClass.prototype`, `foo.__proto__.__proto__ === MyClass.prototype` etc. until either `__proto__` is `null` (in which case `instanceof = false`) or the `===` equality check is true (in which case `instanceof = true`). So this is why a different instance of the `Sequelize.Model.prototype` object would return `false` for an `instanceof` check. 

This is a pretty unique scenario so I solved it by symlinking the `node_modules` from my database project to my "shared code" project. Just wanted to post this in case anybody else was doing a similar thing, in an attempt to save somebody from a couple of hours of WTFing.

**Comment by nbkhope** [comment]
@peabnuts123 I have a project that defines some models as a separate npm package. When I import those models in my project and start my application, I get an error when it calls `.associate`:

```
Error: ModelNameGoesHere.hasMany called with something that's not a subclass of Sequelize.Model
```

`ModelNameGoesHere` is a model that is defined in a separate npm package. That is, it comes from

```
import ModelNameGoesHere from 'some-separate-npm-package'
```

When I copy the code from the package into my application, the problem goes away.

Is there any solution to this?
