### ISSUE TITLE
upsert performance

### ISSUE THREAD

**Issue by willin** [sequelize/sequelize#8293]
## What you are doing?

```js
// length 100,000
tasks.forEach(async (task) => {
    await Task.upsert(task);
    // how to commit 1000 tasks each time?
});
```

## What do you expect to happen?
_I wanted Foo!_

```js
// 1000 items
insert (),(),(),(),...;
// 1000 items
insert (),(),(),(),...;
// 1000 items
insert (),(),(),(),...;
// 1000 items
...
```

## What is actually happening?
_But the output was bar!_

```js
insert (); 
insert (); 
insert (); 
insert ();
```

__Dialect:__ mysql

**Comment by willin** [comment]
???

**Comment by sushantdhiman** [comment]
This issue is closed because of very low effort issue reporting . You didn't followed issue template. You failed to report which version was affected or which dialect was causing this issue.

Reporting performance issue require explanation why you think there is a performance issue, GC mark sweep errors, taking lots of time for something very simple or sudden rise in memory consumption.

As far as I can see you are trying to commit 100K tasks, do you have an standard case in raw SQL which is significantly faster than Seqeulize upsert version? How much is the difference?

If you can properly report this issue I will happily try to investigate if its legitimate :)
