### ISSUE TITLE
FindAndCountAll generates incorrect sql for mariadb

### ISSUE THREAD

**Issue by kustom666** [sequelize/sequelize#8380]
## What are you doing?
Calling findAndCountAll on a simple model

```js
Notification.findAndCountAll(filter);
```

## What do you expect to happen?
I should get all notifications and the number of unique notifications found

## What is actually happening?
Getting the following sql error: ER_PARSE_ERROR.

```text
Executing (default): SELECT count(DISTINCT(*)) AS `count` FROM `Notifications` AS `Notification`;
ERROR: An exception ocurred: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '*)) AS `count` FROM `Notifications` AS `Notification`' at line 1
```

Note that according to the [mariadb documentation](https://mariadb.com/kb/en/library/count-distinct/) the generated SQL should be as follows in order to work:

```sql
SELECT count(DISTINCT(id)) AS `count` FROM `Notifications` AS `Notification`;
```

Running that query manually does work.

__Dialect:__ mysql (mariadb)
__Dialect version:__ ?
__Database version:__ 10.1
__Sequelize version:__ 3.19.0
__Tested with master branch:__ No

**Comment by sushantdhiman** [comment]
> 3.19.0

Sorry, but we dont support this version anymore. Only critical security fixes will be released for this version. Please try with master.

We only support MariaDB because they offer API compatibility with MySQL, which I am sure they adhere to. I think you might be using an old version of MariaDB, which didn't support some feature Sequelize v3 queries are using
