### ISSUE TITLE
Query "SELECT now();" return wrong timezone in postgre

### ISSUE THREAD

**Issue by Sirius207** [sequelize/sequelize#8516]
## What are you doing?

Version:
sequelize: 4.4.2,
Postgre: 9.6.4

Hi, I try to log current time by SQL below

```sql
SET TIME ZONE 'Europe/Paris';
SHOW TIMEZONE;
SELECT now();
```
with

```js
const Sequelize = require('sequelize')

const CONFIG = global.CONFIG

// Setup Sequelize
const sequelize = new Sequelize(CONFIG['database'], CONFIG['user'], CONFIG['password'], {
  host: 'localhost',
  dialect: 'postgres',
  pool: {
    max: 5,
    min: 0,
    idle: 1000
  },
  timezone: 'Europe/Paris'
})

sequelize
  .authenticate()
  .then(async () => {
    console.log(`${CONFIG['database']} Connection has been established successfully.`)
    await sequelize.query('SHOW TIMEZONE;').then((data) => { console.log(data) })
    await sequelize.query(`SELECT now();`).then((data) => { console.log(data) })
  })
  .catch(err => {
    console.error('Unable to connect to the database:', err)
  })
```

## What do you expect to happen?

If I use pgAdmin to run the same query, it will output

![image](https://user-images.githubusercontent.com/7900936/31853650-93afea7c-b651-11e7-96ea-7839e7ceb59c.png)
That`s correct.

## What is actually happening?

Although the code above output right timezone('Europe/Paris'), 
the 'SELECT now();' query still output time in '+0' timezone(2017-10-21T16:18:05.842Z) which is not correct.

**Code Output**

```
db_sample Connection has been established successfully.
Executing (default): SHOW TIMEZONE;
[ anonymous { TimeZone: 'Europe/Paris' } ]              // Correct timezone
Executing (default): SELECT now();
[ [ anonymous { now: 2017-10-21T16:18:05.842Z } ],      // Wrong current time, still in '+0' timezone
  Result {
    command: 'SELECT',
    rowCount: 1,
    oid: NaN,
    rows: [ [Object] ],
    fields: [ [Object] ],
    _parsers: [ [Function: parseDate] ],
    RowCtor: [Function: anonymous],
    rowAsArray: false,
    _getTypeParser: [Function: bound ] } ]
```

Why the code above still output current time in +0 timezone?  Is that right?

**Comment by mhombach** [comment]
Since i had trouble with timezones earlier this year, i'll give it a try:
It could be that this is just a conversion-error from your output-method (consoloe.log).
The time is 16:18 in +0 what related to 18:18 in a +2 timezone. I am not exactly sure how the console.log handles date-objects but you should try the following:
Do NOT output the `data` directly, instead create a new Date-object and insert the `data` into it. Then try to analyse/output the date-object and see, if the timezone is correct.
NodeJS is getting my timezone wrong too so a direct output of the time will be wrong if compared to my computer's clock... So i think this is really an output-issue where the time outputed is converted to the +0 zone.
