### ISSUE TITLE
Tips on reducing GC time?

### ISSUE THREAD

**Issue by jsha** [sequelize/sequelize#8532]
In https://github.com/jsha/blocktogether I have one particular service, actions.js, that reads and writes Sequelize objects from the database at about 100-300 reads per second, and about 100-300 writes per second. Most of these objects are then immediately discarded. Each object is small; probably less than 100 bytes of data total. But I'm finding that my services spends about 20% of a CPU on GC.

Are there any tips to using sequelize in a way that minimizes garbage production? e.g. reusing DAOs rather than creating new ones each time? How big is the overhead of a typical DAO?

Also, FWIW, I'm on sequelize 3.24.6. Happy to upgrade if there have been improvements recently that affect memory use, but I didn't spot any in the changelog.

Thanks,
Jacob

**Comment by iamjochem** [comment]
firstly I would recommend upgrading sequelize and node to their respective latest stable version - that is likely to give you a noticable performance boost (latest sequelize is ES2015 code and latest node has a new v8 engine which really makes a difference) ... might be a quick win.

secondly are you sure your GC problem is related to sequelize objects? hundreds of DAO objects per second does not really sound like much in real terms. how are you measure GC time? do you GC problems start to occur after the process has been running for a long(er) time?

I think the code `setInterval(processActions, processingIntervalSeconds * 1000);` is problematic because you cannot garantee that `processActions` will complete within the interval time ... as time goes by you may potentially have an every increasing of `processActions` calls  running ... given that `processActions` can trigger numerous http requests this is not at all unlikely. I would suggest you change the strategy for periodic processing in order to garantee that only one call is ever active.

to get an idea of object creation performance you could checkout this:

     https://github.com/icebob/js-perf-benchmark/blob/master/suites/properties.js 

I'm sure it wouldn't be difficult to implement a sequelize DAO instance creation variant - no doubt creation of sequelize instances would be slower but I just ran that code on my 2014 macbook and the slowest test ran @ just over 20 million objects per second, using node v8.9.0 (it was 5 million/second with node v6.11.0) so I think a couple of hundred/second of more complex sequelize model instances wouldn't be likely to be a bottleneck. (the absolute number are pretty meaningless given that I only did a couple of runs BUT it does show the relative difference between node6 & node8 on this front!)

if it turns out your issues is not related to sequelize please be so kind as to close this issue :-)

**Comment by jsha** [comment]
Thanks for the detailed comments! They are very helpful, and I agree with you that it seems unlikely the allocation issues are specifically related to Sequelize. I saw Sequelize objects showing up a lot in my heap diffs, which is what led me to ask, but I suspect that the answer lies elsewhere.
