### ISSUE TITLE
Feature Request: Audit User ID

### ISSUE THREAD

**Issue by FredLackeyOfficial** [sequelize/sequelize#8535]
Please add the ability to update a `auditUserId` field during any CRUD operation.  For simplicity, this could be one of the options passed in.  For example:

    models.User
      .destroy({
        where: {
          name: {
            [Op.like]: 'Fred%'
          }
        },
        auditUserId: (passedInUserOrId.id || passedInUserOrId)
      })
      .then(success => {
        return next();
      })
      .catch(error => {
        return next(error);
      });

**Comment by iamjochem** [comment]
you seem to be asking for this library to implement something very particular to your situation (e.g. you have a `auditUserId` field, your using the `paranoid` feature), given that sequelize is a general ORM I'd hazard a guess that the maintainers would not find this to be a good candidate for implementation.  

I can imagine that, if implemented, your request would cost someone many hours of work - you might consider whether it is fair to expect a hand full of volunteers that build/maintain this project (which we use for free) to spend such time based purely on a issue someone took all of a couple of minutes to write. 

In future please use your ability to google for potential solutions to your problem, e.g.:

     https://www.npmjs.com/package/sequelize-paper-trail

this "paper-trail" plugin may not be exactly what you're looking for but it should show you might implement your own version of auditing. it comes down to using sequelize "lifecycle" hooks which you can implement in your own project without requiring changes to sequelize itself.

P.S. whatever it is you need/want, with regard to software, the chances are quite slim that you're the first to have said want/need, in fact chances are quite often pretty good that somebody somewhere already has a solution that comes pretty close.

**Comment by FredLackeyOfficial** [comment]
> something very particular to your situation

Capturing the user ID or username, of the person changing the record, is a common practice in millions of applications.

> please use your ability to google for potential solutions

Prior to submitting this request, I *did* find several other relevant plugins.  However, none are stable enough to rely upon.

> would cost someone many hours of work

As you have already pointed out, there are multiple similar projects out there.  Adapting their code should not be difficult.  Likewise, with date-based audit fields already being a part of the library, extending it by one *relevant* field should be trivial for someone actively working in the codebase.

My overall goal with this request was to have an *official* solution permanently baked into the library.  Again, capturing the identity of the user impacting the row is common practice in most applications where audit fields are needed.  This request simply rounds out, what appears to be, a partially implemented feature.

**Comment by iamjochem** [comment]
yes tracking users who make change is a common scenario. I do it myself. but conceptually "the person" is not something that _always_ exists in the context of an ORM, where as _time_ is always conceptually present ... sequelize is an ORM not a "track the people who make changes + ORM" (you can use sequelize as the basis for such funtionality as we have both seen in various plugin projects) ... the auditing you are looking for is something that belongs in a different layer of your stack, the alternative would be to bake everything into sequelize (api-server, crud-ui webserver, [gorillas](https://www.johndcook.com/blog/2011/07/19/you-wanted-banana/)).

Your overall goal _seems_ to get some one else to do a **** ton of work based on you under-specified request ... not particularly cool IMO; if you had written a fully spec'ed proposal and backed it up with a PR implementing that then it would be a different matter ... although I still think you would have wasted your time because I doubt very much that the maintainers would agree with your premise that such functionality is with the scope of the project.

you make assumptions about _relevance_ ,  _triviality_ - this is rather bold, maybe you should familiarize with the codebase before making such assumptions, relevance will always remain open for discussion but triviality.

- I strongly believe that you have a snowball's chance in hell of getting the feature you desire (regardless of whether you create a PR or wait for someone else to do so)
- you are much better off implementing something yourself - it will work exactly the way you want it to (which is unlikely in the case of a baked-in solution) ... alternatively pick up one of the potential solutions and help make it stable enough for your liking.
