### ISSUE TITLE
How can I get the affectedRows at call with bulkCreate?

### ISSUE THREAD

**Issue by kk8686** [sequelize/sequelize#8555]
Hi all!

The following code are batchInsert the multiple article data to MySql, but some articles may be aready exist, such as I insert for 10 articles but only 7 data items are created to MySql, And I want to get the **affectedRows** for this created job, but I can't find the way

```js
Article.bulkCreate(articles, {
	ignoreDuplicates : true
}).then((result) => {
	console.log(result);
}).catch((err) => {
	console.log(err);
});
```

----

The following codes is call with `mysql` module, It can get the **affectedRows** ：

```js
let mysql = require('mysql'),
	connection = mysql.createPool(config);

mysqlDB.query({
	sql : 'INSERT IGNORE INTO ?? (fields...) VALUES (values...)',
	values : 'tableName',
}, function (err, result) {
	connection.end();
	if (!err) {
		console.log(result.affectedRows); //!!!! here
	}
});
```

**Comment by iamjochem** [comment]
I believe you cannot because of the following method (which underlies the `bulkCreate` method):

https://github.com/sequelize/sequelize/blob/bf5fa6d7e9213129e21c22ea89fad00bea32066e/lib/query-interface.js#L925 (the `.then(results => results[0]);` is what is making it impossible to access `affectedRows`).

I suppose you have a couple of options:

1. create a PR to expose the `affectRows` information in this context (tricky because it's a breaking change for the API, additionally not all dialect are garanteed to have/return this information ... which is probably why they chose not to expose it even when a dialect does make it available)

2. reproduce the relevant bulkCreate code in a custom [model] function and make that return the `affectedRows` data.

3. try using a transaction and follow the bulkCreate call with a raw query using [this](https://dev.mysql.com/doc/refman/5.7/en/mysql-affected-rows.html) ... I believe that you'll need the transaction to ensure your using the same DB connection.

4. figure out if you can eliminate your `affectedRows` requirement (you mention you "wanted" it, so maybe you can live without it in this instance)

PS. don't be afraid to search through the source code! (this is what I did to figure out whether your problem was down to the implementation or your usage)

**Comment by xianxingg** [comment]
Well, there is a alternative solution:
`bulkCreate` will return all instances including the ignored, and every one of them contains `updatedAt`, you may run `select pk from table where "updatedAt" between ?` to get all rows updated during `bulkCreate` runtime. But you should notice this: the updated rows may be updated by others.

**Comment by yoya93** [comment]
> ¡Hola a todos!
> 
> El siguiente código es por lotes Inserte los datos de varios artículos en MySql, pero es posible que algunos artículos ya existan, como inserto para 10 artículos pero solo se crean 7 elementos de datos en MySql, y quiero obtener las filas **afectadas** para este trabajo creado, pero No puedo encontrar el camino
> 
> ```js
> Articulo . bulkCreate ( artículos ,  { 
> 	ignoreDuplicates : true 
> } ) . luego ( ( resultado )  =>  { 
> 	consola . log ( resultado ) ; 
> } ) . catch ( ( err )  =>  { 
> 	consola . log ( err ) ; 
> } ) ;
> ```
> 
> Los siguientes códigos son llamadas con `mysql`módulo, puede obtener las **filas afectadas** :
> 
> ```js
> deje  mysql  =  require ( 'mysql' ) , 
> 	conexión  =  mysql . createPool ( config ) ;
> 
> mysqlDB . query ( { 
> 	sql : 'INSERT IGNORE INTO ?? (campos ...) VALUES (valores ...)' , 
> 	valores : 'tableName' , 
> } ,  function  ( err ,  result )  { 
> 	connection . end ( ) ; 
> 	if  ( ! err )  { 
> 		consola . registro ( resultado . filas afectadas ) ;  // !!!! aquí 
> 	} 
> } ) ;
> ```

Hi, I have exactly the same problem as you. Could you solve something? Thank you
