### ISSUE TITLE
Add option to specify partition(s) for select queries

### ISSUE THREAD

**Issue by alexcrack** [sequelize/sequelize#8575]
## What are you doing?

We have very big table (over 50Gb). Table is partitioned. But selects very slow. But usually we need data only for last month. We have partitions by months. When we specify partition name query execution time reduces in 3-4 times. So, it would be pretty to add option for specifying partition. 

Syntax might be like:

```js
MessagesLog.findAll({
    where: {
        user_id: 123
    },
    partition: ["p_2017_11"]
})
```

## What do you expect to happen?

It should insert partitions names to generated query:

```mysql
SELECT `MessagesLog`.`id`, `MessagesLog`.`user_id`, `MessagesLog`.`requestdate`, `MessagesLog`.`text`
FROM `messages_log` PARTITION(p_2017_11) AS `MessagesLog` 
WHERE `MessagesLog`.`user_id` = 123;

```

## What is actually happening?
Nothing

__Dialect:__ mysql
__Dialect version:__ 5.7
__Database version:__ 5.7
__Sequelize version:__ 4.20
__Tested with master branch:__ No

**Comment by iamjochem** [comment]
all queries go through here:

https://github.com/sequelize/sequelize/blob/bf5fa6d7e9213129e21c22ea89fad00bea32066e/lib/sequelize.js#L442

add use this class (in the case of MySQL):

https://github.com/sequelize/sequelize/blob/bf5fa6d7e9213129e21c22ea89fad00bea32066e/lib/dialects/mysql/query.js

you could consider monkey patching that particular class so that you overload the `run` method so that you can do some string-foo to stick the `PARTION xxxx` into the SQL based on `this.options.partion` value & then calling the original `run` method (e.g. `return originalRun.call(this, hackedsql);`

you might also consider that MySQL is not the best fit for, what looks like, large amounts of readonly data - my first thought was "dump all that data into into Elasticsearch, with per-month indexes and be happy" :-) ... what I often do is use MySQL as my primary store and use Elasticsearch as a cache (it's super fast for searching/reading data and it great for taking pressure off of your DB), having MySQL as your primary store also means your can recreate your Elasticsearch indexes whenever you need to change the way and/or the what you want search.

**Comment by plusmancn** [comment]
I have the same requirement。
