### ISSUE TITLE
Alias not set on result object

### ISSUE THREAD

**Issue by Skaronator** [sequelize/sequelize#8614]
## What are you doing?
I try to bind a alias on the result object (`result[0].MyAlias`) which doesn't work but when `JSON.stringify()` the result is actually as expected.

Model:
```js
//Minimized Version:
const TransactionModel = db.define(
  'Transaction',
  {
    id: {
      type: Sequelize.INTEGER.UNSIGNED,
      field: 'tid',
      primaryKey: true,
      autoIncrement: true,
    },
    amount: {
      type: Sequelize.DECIMAL(11, 2),
      field: 'betrag', //'betrag' is german for 'amount'
    },
  },
);
```

Query:
```js
const tt = await Transaction.findAll({
  where: args,
  limit: 1,
  attributes: [
    ['betrag', 'amount'],
    ['betrag', 'lol'],
    ['betrag', 'betrag'],
  ]
});
console.log(tt[0].amount, tt[0].lol, tt[0].betrag);
console.log(JSON.stringify(tt, null, 2));
```

## What do you expect to happen?
`tt[0].lol` and `tt[0].betrag` should **not be undefined**!

I'm using sequelize for my Apollo Server and currently if I query with this bug I'll get this result:
```
"data": {
  "getTest": [
    {
      "amount": 1774.96,
      "lol": null,
      "betrag": null
    }
  ]
}
```
A workaround currently is converting the obj to json and back to a obj with: `JSON.parse(JSON.stringify(result));`

## What is actually happening?
```
Executing (default): SELECT `betrag` AS `amount`, `betrag` AS `lol`, `betrag` AS `betrag` FROM `hhb_transaktion` AS `Transaction` LIMIT 1;
1774.96 undefined undefined
[
  {
    "amount": "1774.96",
    "lol": "1774.96",
    "betrag": "1774.96"
  }
]
```

__Dialect:__ mysql2
__Dialect version:__ 1.4.2
__Database version:__ MySQL 5.7.17
__Sequelize version:__ 4.22.5
__Tested with master branch:__ Basically yes since there are not commits since latest release

**Comment by mhombach** [comment]
I found the solution but when i first tested your problem i ran into the same issue.

The solution is described here: http://docs.sequelizejs.com/manual/tutorial/querying.html

> When using aggregation function, you must give it an alias to be able to access it from the model. In the example above you can get the number of hats with instance.get('no_hats').

So in your example, since "lol" isn't a real attribute of the MODEL of "Transaction", you need to access it by using `tt[0].get('lol')`, that simply fixes your problem :)

If this fixed your problem, please close this issue, otherwise i'm happy to help you if the issue lies somewhere else.

**Comment by Skaronator** [comment]
The problem is, that I pass the whole result object back to my GraphQL server so I can't do `.get()`.

Currently I'm doing this:
`resolve(JSON.parse(JSON.stringify(result)));`

Or run map on the result array:

```
const result = await MainCategory.findAll({
    ...
});
result.map(row => {
    row.subCategory = row.SubCategory;
});
resolve(result);
```

**Comment by mhombach** [comment]
Uhm... Maybe i am not understanding you here right but Sequelize as ORM is made to be consistent what data exactly are written to the database (regardless of the database-dialect). If you define a Model "Transaction" with 2 attributes (ID and amount), then you can never save other attributes to the database than these 2.
Although some databases like MongoDB support this, not every database can. Since you are using MySQL, saving a 3rd attribute to the database would mean that the table has to be altered and that is something that should never happen on demand and while your server is running production.
I guess that your example here is not where the problem occured in your real code so i cannot help you in detail here, but there are 2 ways i would suggest:
1: If you are going to need more attributes to save data, then define them in your model to make data consistent throughout your whole code.
2. If you are going to need calculated data in your app but not in your database (for example you have 2 attributes with numbers and you now need a 3rd attribute for the sume of both) then you could create an virtual attribute 'mySum' on your model, which returns (a + b) as get-method. This way you can access this calue directly by using `tt[0].mySum`. But this value would not be saved in your database because it's just a calculated value during runtime.

If both solutions are not what you need, then i'm happy to help you by email or discord. But i think this issue 'Alias not set on result object' should be closed, since the alias is applied correctly and can bet retrieved by ".get" :)

**Comment by Skaronator** [comment]
>Maybe i am not understanding you here right but Sequelize as ORM is made to be consistent what data exactly are written to the database (regardless of the database-dialect). If you define a Model "Transaction" with 2 attributes (ID and amount), then you can never save other attributes to the database than these 2.
Although some databases like MongoDB support this, not every database can. Since you are using MySQL, saving a 3rd attribute to the database would mean that the table has to be altered and that is something that should never happen on demand and while your server is running production.

Those are all `SELECT` querys, they only fetch/get the data, they are never saving the data.


>If you are going to need calculated data in your app but not in your database (for example you have 2 attributes with numbers and you now need a 3rd attribute for the sume of both) then you could create an virtual attribute 'mySum' on your model, which returns (a + b) as get-method. This way you can access this calue directly by using `tt[0].mySum`.

And here is the issue. **They aren't definded as `tt[0].mySum`**

I've a *SELECT* query with these attributes:
```
attributes: [
  [
    Sequelize.fn(
      'SUM',
      Sequelize.literal(
        'CASE WHEN `KidFrom` = ' +
          Account.id +
          ' THEN `betrag`*-1 ELSE `betrag` END'
      )
    ),
    'amount', //TODO: rename this???!
  ],
],
```
Here is the build query string
```
SELECT SUM(CASE WHEN `KidFrom` = 1 THEN `betrag`*-1 ELSE `betrag` END) AS `amount` FROM `hhb_transaktion` AS `Transaction` WHERE (`Transaction`.`KidFrom` = 1 OR `Transaction`.`KidTo` = 1);
```

When running these I get this console.log:
`console.log(AccountResult[0].amount);`
`107.99`

`console.log(AccountResult[0].balance);`
`undefined`

`console.log(JSON.stringify(AccountResult, null, 2));`
```
[
  {
    "amount": "107.99"
  }
]
```

Now I change the `attributes` to this:

```
attributes: [
  [
    Sequelize.fn(
      'SUM',
      Sequelize.literal(
        'CASE WHEN `KidFrom` = ' +
          Account.id +
          ' THEN `betrag`*-1 ELSE `betrag` END'
      )
    ),
    'balance', //<-- CHANGED THIS LINE!
  ],
],
```
Here the query:
```
SELECT SUM(CASE WHEN `KidFrom` = 1 THEN `betrag`*-1 ELSE `betrag` END) AS `balance` FROM `hhb_transaktion` AS `Transaction` WHERE (`Transaction`.`KidFrom` = 1 OR `Transaction`.`KidTo` = 1);
```

When running these I get this console.log:
`console.log(AccountResult[0].amount);`
`undefined`

`console.log(AccountResult[0].balance);`
`undefined` //<- **WHY?**

`console.log(JSON.stringify(AccountResult, null, 2));`
```
[
  {
    "balance": "107.99"
  }
]
```

### As you can see `AccountResult[0].balance` is undefined.

**Comment by mhombach** [comment]
It's simple.
It's not about your query, it is about your model-definition.
If your model-definition contains the attribute `amount`, then you can access it with `AccountResult[0].amount`. If not, like in your case, you need to `get` the value with `AccountResult[0].get('amount')`.
I don't know if you are on Object-Oriented-Coding and if you are aware of what classes mean (no offense, you don't need to fully understand classes for coding wit Sequelize), but:
When you define a model in Sequelize, it is like a class you are creating.
When you give your model "user" 2 attributes, "name" and "password" for example, then if you are working with a user-object (regardless from if you want to save one or you have queried one), this object only has 2 attributes: "name" and "password", EVEN if in your query you selected some value/calculation with `AS`. IF you did query some custom values, then these values can NOT exist in the model directly, because that the class-definition would not allow it (an object itself can never alter/change a class-definition). BUT: You can still get those attributes for sure, you just need to use the function `get` to target values/data, that is existing in the object but not in the model.

So the short way to put it:
You can target every attribute of the MODEL-DEFINITION directly by using `modelObject.attributeName`.
But for every attribute the models does NOT have in its definition you MUST use `modelObject.get('customAttributeName')`.
Did you understand what this means? If not, feel free to ask for something specific again but first please read carefully and try to completely understand my written text :)

**Comment by Skaronator** [comment]
But why does the alias works when converting the result to JSON and then back to an Object?

As you can see `AccountResult[0].balance` is `undefined` but doing `JSON.parse(JSON.stringify(AccountResult))[0].balance` returns the actually value?

Also why does the `SUM()` function in my last post apply `AccountResult[0].amount` when using `amount` as alias? It probably only works because this name exist in the Model but has actually nothing to do with this `SUM()` function.

**Comment by mhombach** [comment]
> It probably only works because this name exist in the Model but has actually nothing to do with this SUM() function

Exactly this is what i am thinking too.
I don't know exactly how the JSON.stringify and parse function work in detail but they don't return the exact representation of the object.
You can inspect the object in all detail by requiring `const util = require('util');` and using `util.inspect(object, {showHidden: false, depth: null})` to get all information about the object. Those may be more than your default-commandline may show so you can log it to a file
`fs.writeFile("mylog.txt", util.inspect(ergebnis[0], {showHidden: false, depth: null}), function(err) {
            if(err) {
                return console.log(err);
            }
            console.log("The file was saved!");
        }); `
if you imported `var fs = require('fs');`.
I ran into same issues a long time ago and then realized that you need to be CAREFULL of what you parse-stringify and what not. An object for example can hold a function `calculateSomething()` but this function for example will vanish if you `JSON.parse(stringify())` it.
I guess that Sequelize-Objects output all data-values (including those who are not in the model itself) when you JSON-convert it. And that is valid, because if you convert it to a JSON-object, then this object is not representing the model-definition. This converted model for example has NOT a function like `save` (which is a Sequelize-Only method) and you can do whatever you want with the object like adding attributes, changing a value to a string, even if the model-definition requires a number and so on... converting it to JSON deletes all connections to the Sequelize-Class and leaves a "dumb" and normal JS-Object, which you can interact with.
