### ISSUE TITLE
Promise catch intercepts wrong error

### ISSUE THREAD

**Issue by furyscript** [sequelize/sequelize#8722]
## What are you doing?

A simple findOne to get data using `async` and `sequelize`
```js
async.waterfall([
    function(callback) {
        var token = "123";
        authTokens.findOne({where: {token: token}}).then(function(auth_token_found) {
            if (!auth_token_found) {
                console.log("Not found");
                return callback("Invalid token");
            }
            auth_token = auth_token_found;
            callback();
        }).catch(function(error) {
            console.log("Catch in error");
            callback(error);
        });
    }
], function(err) {
    if (err) {
        console.log(err);
    } else {
        console.log("DONE");
    }
});
```

## What do you expect to happen?
_In the previous version, sequelize doesn't intercepts error called by `return callback("Invalid token");`. Now when I fire the return callback, sequelize get in `.catch` callback (that I'm using to intercepts SQL fail error). So I get error 500 from my server because callback is called twice by `async`._

## What is actually happening?
_Describe before. Please correct this as soon as possible. Any feedback about this? In the mainwhile can you give me a version of `sequelize` that haven't this error?_

**Comment by sushantdhiman** [comment]
So you are saying Sequelize method should not intercept that error. Well its not related to Sequelize.

If `callback` throws a synchronous error or returns a rejected promise, it will go to `.catch`. Thats how promises works.

This issue is not related to Sequelize, but a call for help for some user specific code. Its better to post this question on Stackoverflow or discuss it among your peers.
