### ISSUE TITLE
InstanceValidator validating fields it should not be when doing an update() with 'skip'

### ISSUE THREAD

**Issue by twelve17** [sequelize/sequelize#8743]
## What are you doing?

I am trying to update a model with the `skip` option to skip validation on one of its attributes.

Here's a simplified version of the model, with one "real" attribute (e.g. with a db column) and one virtual attribute:

```js

   const User = sequelize.define(
      'User',
      {
        guid: {
          allowNull: false,
          type: DataTypes.STRING,
          defaultValue: DataTypes.UUIDV4,
          validate: {
            ...
          },
        },
        role: {
          type: DataTypes.VIRTUAL,
          defaultValue: 'user',
          allowNull: false,
          validate: {
            ...
          },
        },
    },
    {
        setterMethods: {
          role: function() {
            this.setDataValue('role', 'user');
          },
      }
    }
```

This is a bit of a contrived example, but the important things to note are that:
1. Both fields have validators.
2. One of the fields is virtual.

I have a use case where I want to update the `guid` but want to skip its validation, so I make the call:

```js
const u1 = User.findById(...);
u1.update({ guid: null }, { skip: ['guid']})
```

## What do you expect to happen?
I expect the update to happen without errors.

## What is actually happening?
A validation error is being thrown for the virtual field, which is not even being updated:
```js
  name: 'SequelizeValidationError',
  errors: 
   [ ValidationErrorItem {
       message: '',
       type: 'notNull Violation',
       path: 'role',
       value: null },
```

I debugged the sequelize code, and I _think_ the issue is in the `InstanceValidator`, with [this](https://github.com/sequelize/sequelize/blob/9a75a5db6c14acc6a6a617c1797b0434ffb473fa/lib/instance-validator.js#L21) and [this](https://github.com/sequelize/sequelize/blob/9a75a5db6c14acc6a6a617c1797b0434ffb473fa/lib/instance-validator.js#L112) part of the code.

Here's what is happening:

When *not* specifying `skip` on update, then this block runs:
```js
  if (options.fields && !options.skip) {
    options.skip = Utils._.difference(Object.keys(modelInstance.Model.attributes), options.fields);
  }
```

`options.skip` ends up with the difference between the defined properties and the ones specified in the `model.update()` call.  In the above use case, that means the virtual field `role` is marked to be skipped, which results in the `builtinValidators` function returning early:

```js
    if (self.options.skip.indexOf(field) >= 0) {
      return;   // "guid" is in the options.skip array, so it is not validated
    }

    var value = self.modelInstance.dataValues[field];
```

Now, let's examine when the `update` is called with `skip: ['guid']`.

Since `skip` is specified, nothing happens, so `skip` remains with the value `['guid']`.
```js
  if (options.fields && !options.skip) {
    options.skip = Utils._.difference(Object.keys(modelInstance.Model.attributes), options.fields);
  }
```

Moving on to the `builtinValidators` function (which I am now showing more of), here is what happens:

```js
InstanceValidator.prototype._builtinValidators = function() {
  var self = this;

  // promisify all attribute invocations
  var validators = [];
  Utils._.forIn(this.modelInstance.rawAttributes, function(rawAttribute, field) {
    if (self.options.skip.indexOf(field) >= 0) {
      return;
    }

    var value = self.modelInstance.dataValues[field];
```

Since only `guid` was in the `skip` array, then when this runs for `role`, it  does *not* return early.  In addition, because `role` is a `VIRTUAL` field, it will not have a value in `dataValues` unless one called the setter method, thus the `value` variable ends as `null`.  Validation continues later on:

```js
   ...
    // 'role' is validated here, and its value is null since it does live in dataValues
    if (self.modelInstance.validators.hasOwnProperty(field)) {
      validators.push(self._builtinAttrValidate.call(self, value, field).reflect());
    }
  });

  return Promise.all(validators);
};
```

I would be open to submitting a PR, but I feel like I don't exactly know what the right way to handle this should be.  Maybe, in calculating `skip`, should it merge the caller's requested fields _plus_ the ones not specified in the `update`?

```js
import { uniq } from 'lodash';

if (options.fields) {
   const defaultSkipFields = Utils._.difference(Object.keys(modelInstance.Model.attributes), options.fields);
   const requestedSkipFields = options.skip || [];
    options.skip = uniq(requestedSkipFields.concat(defaultSkipFields));
  }
```

Or perhaps did I misunderstand the `skip` attribute behavior?

__Dialect:__ mysql
__Dialect version:__ ? 
__Database version:__ 5.7
__Sequelize version:__  4.1.0
__Tested with latest release:__ No

**Comment by mhombach** [comment]
Hey there,
there are a few things that seem weird to me, so i'm going to list them, although they may not be related to your specific error:

- You define the attribute `guid` as `allowNull: false` but later you try to set `guid: null`. That itself should not work because of a Null-violation.

- On the role-model you define `defaultValue: 'user'` which is totally ok andn normal but for some reason you have a custom setterMethod for exactly the same result. More than that, since you overwrite the setterMethod for `role` in this scenario you are completely unable to ever change the role to something different than `user`.

- You indicate `validate: {...}` some validation, but you are not giving us information on that part, which is crucial for an issue about validation.

- If you can link me to some documentation about the `skip` option i would be happy, because i couldn't find any with a few searches.

- What you are doing in your given update-statement is... wrong i would say. Because if the `skip`
-option skips one attribute, then you are updating the gui and skipping it, so in sum you are not updating anything.


If you want to just update one or more specific attributes, then you just have to specify them directly like you did with `{ guid: null }`.
If these information didn't help you, then please give more details on what you are trying to do in your code, maybe you did understand something wrong :)
