### ISSUE TITLE
Cannot read property 'source' of undefined when trying to add association in queryGenerator.SelectQuery

### ISSUE THREAD

**Issue by shareefsakk** [sequelize/sequelize#8751]
I am trying to generate a query using QueryGenerator.selectQuery.

```
let query = models.sequelize.dialect.QueryGenerator.selectQuery('table', {
    include: [{
        model: models.Users,
        where: {
            deleted: false
        },
        required: true,
        attributes: ['id']
    }],
    where: {
        createdAt: {
            [Op.between]: [o.start, o.end]
        },
        deleted: false
    },
    attributes: [[models.sequelize.fn("COUNT", models.sequelize.col("Table.id")), 'count']]
}, models.Table).slice(0, -1);
```

T‌his is the error I am getting.

> TypeError: Cannot read property 'source' of undefined
>     at Object.generateJoin (/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1433:30)
>     at Object.generateInclude (/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1358:24)
>     at Object.selectQuery (/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1001:34)

**Comment by slaveofcode** [comment]
got same error as @shareefsakk

**Comment by slaveofcode** [comment]
@shareefsakk I just answered your question at [https://stackoverflow.com/questions/47652112/cannot-read-property-source-of-undefined-when-trying-to-add-association-in-que/48053952#48053952](https://stackoverflow.com/questions/47652112/cannot-read-property-source-of-undefined-when-trying-to-add-association-in-que/48053952#48053952)

**Comment by tarieli1** [comment]
Hi, this issue still reproduces

**Comment by pontepotchet** [comment]
Looking at the source code here https://github.com/sequelize/sequelize/blob/master/src/dialects/abstract/query-generator.js, it seems to assume that your `include` param included this structure:
```
{
 association: { source }
}
```

I also had an issue earlier where `generateInclude` assumed that my `include` had an `attributes` field, otherwise I'd get this error: `TypeError: Cannot read property 'map' of undefined at MySQLQueryGenerator.generateInclude (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1481:52)`

Maybe this query generator is not the same that's used in in findAll() for example.
