### ISSUE TITLE
MariaDB v10.2.7++ JSON_VALID check

### ISSUE THREAD

**Issue by lgraziani2712** [sequelize/sequelize#8767]
## What are you doing?

I'm trying to add the JSON_VALID validation into a column but I don't know how to do it, or if is it possible. Code example:

```sql
CREATE TABLE t2 (
  j JSON 
  CHECK (JSON_VALID(j))
);
```

## What do you expect to happen?

To add the JSON_VALID validation at DB level.

## What is actually happening?

Right now, I didn't found any information related to this problem.

__Dialect:__ mysql (MariaDB)
__Dialect version:__ XXX
__Database version:__ v10.2.7++
__Sequelize version:__ v4.25.1
__Tested with latest release:__ v4.25.1

## Extra documentation

- https://mariadb.com/kb/en/library/json-data-type/
- https://mariadb.com/resources/blog/json-mariadb-102

Thank you so much!

**Comment by sushantdhiman** [comment]
You can use http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-addConstraint to add `CHECK` constraint.

Please note for MySQL CHECK constraint do nothing, for Maria DB they actually works. Sequelize only supports MySQL and MariaDB support only exists because API of both engine matches.

**Comment by lgraziani2712** [comment]
Thank you!

I solved it like this:

```js
queryInterface.addConstraint('logs', ['column1', 'column2'], {
  type: 'check',
  where: {
    column1: Sequelize.literal('JSON_VALID(column1)'),
    column2: Sequelize.literal('JSON_VALID(column2)'),
  },
  name: 'check_data_has_valid_json',
}),
```
