### ISSUE TITLE
db: migrate creates table with plural name, while freezeTableName:true option specified.

### ISSUE THREAD

**Issue by hbgdPro** [sequelize/sequelize#8785]
## What are you doing?
I call db:migrate and it creates table with plural name, though I've specified freezeTableName: true option.
```js
 development: {
    dialect: "sqlite",
    storage:[hidden on purpose],
    operatorsAliases: Sequelize.Op,
    define: { freezeTableName: true },
    query: { raw: true } // Always get raw result
  },
```

## What do you expect to happen?
_I expect the name of created table to be singular while running db:migrate_

## What is actually happening?
_It creates a valid table , but with plural name. Instead of User it creates Users_

__Dialect:__ sqlite
__Dialect version:__ 3.1.13
__Database version:__ 3.1.13
__Sequelize version:__ 4.28.0
__Tested with latest release:__ No

**Comment by hbgdPro** [comment]
If anyone is interested I solved the problem by modifying migration script, where Sequelize CLI generated plural name.

**Comment by sushantdhiman** [comment]
Related to Sequelize CLI

**Comment by stonedraider** [comment]
I have the same issue. define: { freezeTableName: true } in db options doesn't do anything for me. modifying the migration script as suggested by hbgdPro also isn't helpful, because the sequelize queries are still expecting pluralized tables, which means I will get SequelizeDatabaseError, because it will look for e.g. table buildings instead building in database.

**Comment by hbgdPro** [comment]
@stonedraider You will or you do get any errors? Because my solution works for me pretty smooth.
Of course you might need to rename your old references manually, or start migration from scratch to make it work.

**Comment by massimosgrelli** [comment]
> If anyone is interested I solved the problem by modifying migration script, where Sequelize CLI generated plural name.

May I ask you how? What should I do to get the same change applied to my sequalize installation? Sequelize CLI [Node: 8.9.4, CLI: 5.4.0, ORM: 4.42.0]

**Comment by walter-garcia** [comment]
https://sequelize.org/master/manual/models-definition.html#configuration

**Comment by jasp402** [comment]
It is incredible that they have since 2017 or less ... trying to solve this problem. they should allow the property to pass

`define: {freezeTableName: true},`

However, this does not work from the config because the methods used for confing are these:

```
export interface Config {
  readonly database: string;
  readonly dialectModule?: object;
  readonly host?: string;
  readonly port?: string;
  readonly username: string;
  readonly password: string | null;
  readonly pool?: {
    readonly acquire: number;
    readonly idle: number;
    readonly max: number;
    readonly min: number;
  };
  readonly protocol: 'tcp';
  readonly native: boolean;
  readonly ssl: boolean;
  readonly replication: boolean;
  readonly dialectModulePath: null | string;
  readonly keepDefaultTimezone?: boolean;
  readonly dialectOptions?: {
    readonly charset?: string;
    readonly timeout?: number;
  };
}
```

they do not provide alternatives, it is needed in the configurator and that this is assigned to each model so it is simpler they do not have to make a great effort to modify this.

it is also required in the CLI but I am satisfied that I have the config.js
