### ISSUE TITLE
Wrong value for 'count' when including hasMany associations

### ISSUE THREAD

**Issue by cantell** [sequelize/sequelize#8842]
Fetching rows using .findAndCountAll returns 0 as the value of count when also including associations linked to the model using .hasMany

## What are you doing?

```js
   const Brand = sequelize.define('brand', {
    name: DataTypes.STRING,
    logo: DataTypes.STRING,
  })

  const Model = sequelize.define('model', {
   name: DataTypes.STRING,
   price: DataTypes.INTEGER,
  })

 Model.belongsTo(Brand)
 Brand.hasMany(Model)

 Brand.findAndCountAll({
    offset: 0,
    limit: 10,
    include: [model]
  }).then(({ count, rows }) => {
    // Expects count => actual count
   // But count is always 0.
  })
```

## What do you expect to happen?
 Expect count to be actual number of model entry in the database.

## What is actually happening?
count always evaluate to zero, irrespective of the total number of entries in the database. In contrast, the number of elements in 'rows' is always the actual number of elements expected. Removing the include options, restores the expected behaviour.

 ```js
Brand.findAndCountAll({
    include: [model]
  }).then(({ count, rows }) => {
    console.log(count)  // 0, even when rows.length > 0
  })

```

__Dialect:__  postgres
__Sequelize version:__ 4.28.6

**Comment by mccabemj** [comment]
It seems to be working fine for me with the same version and Postgres. My only thought could be your include and the model called model. Use 'Model'

**Comment by cantell** [comment]
Finally figured it out. This seems to be the case if 

```js
{
   raw: false
}
```

in the options passed to .findAndCountAll(...). removing `raw` entirely from the options seems to restore the correct behaviour. Not sure if this is a bug or a feature. :)

**Comment by mccabemj** [comment]
I'd be interested in knowing why this is. I can recreate. 

Using `raw: false` stops `query.js` taking the `count` portion of the query and mapping out the property value. Thus the `handleSelectQuery` function treats it as a regular query and returns a bunch more data. Ultimately, the query returns dataValues with an object containing the count, instead of the count value. query-interface then has it as `NaN`.

Is this a bug, or a feature (like @cantell said).
