### ISSUE TITLE
Virtual Columns Ignored in Associations

### ISSUE THREAD

**Issue by pokedpeter** [sequelize/sequelize#8946]
## What are you doing?
Trying to fetch associated model data using a VIRTUAL column as the sourceKey.

```js
// Setup models
const Hammer = sequelize.define('user', {
	...
	metadataType: {
		type: DataTypes.VIRTUAL,
		get() { return 'Tool' },		
	},
	...
})

const Potato = sequelize.define('user', {
	... 
	metadataType: {
		type: DataTypes.VIRTUAL,
		get() { return 'Food' },		
	},
	... 
})

const Metadata = sequelize.define('project', {
	... 
        type: {
          type: DataTypes.STRING,
          allowNull: false,
        },
	...
})

// Set associations
Banana.hasMany(Metadata, {as: 'Metadata', foreignKey: 'type', sourceKey: 'metadataType' });
Potato.hasMany(Metadata, {as: 'Metadata', foreignKey: 'type', sourceKey: 'metadataType' });

// Fetch additional properties available for food
const potato = await Potato.findById(256);
const metadata = await potato.getMetadata();
```

## What do you expect to happen?
metadata should contain database records where metadataType = 'Food'

## What is actually happening?
No results are returned.

The query generated is like the below:
```
SELECT ... FROM [Metadata] AS [Metadata] WHERE [Metadta].[type] = NULL;
```
After digging through Sequelize source, it is because of this:
hasMany.js: line: 185
```
values = instances.map(instance => instance.get(association.sourceKey, {raw: true}));
```
The raw property is excluding values from VIRTUAL columns

__Dialect:__ mssql
__Dialect version:__ 2016
__Database version:__ 2016
__Sequelize version:__ 4.18.0
__Tested with latest release:__ No, but line 185 remains unchanged in the latest version 4.32.1

**Comment by sushantdhiman** [comment]
I dont think we want to support this, `VIRTUAL` fields in my understanding were implemented to abstract data representation away from real table columns. They should not be used to form references etc.

I suggest you use a `ENUM` type and have `hasMany` or other relation over that key

**Comment by issy123** [comment]
The most common application for virtual columns is having a full name composed of first name and lastname

E.g.

```const user = sequelize.define('user', {
	... 
	fullName: {
		type: DataTypes.VIRTUAL,
		get() { return `${firstName} ${lastName} ` },		
	},
	... 
})```

This is really convenient for those usecases
This prevents having us to define fullname each time we retrieve it. 

Would love to have this supported!

**Comment by RomanShabanov** [comment]
Years after this is still not a thing?

**Comment by dvddpl** [comment]
I understand that Enum might be a better solution for the use case in this issue,  but i agree with @ssy123 ( we have currently a very similar use case) and when it comes to concatenating columns i would expect the virtual column to be retrieved.

**Comment by dvddpl** [comment]
after trying out a few things it seems that my ( and @issy123 ) use case is different from @pokedpeter 

In his case i think Enum would work. and in my case,  virtual columns are not ignored, provided you specify the include properly.  You might want to eagerly load them ( and remember to include the nested association as well) or you want to load the lazily, but virtual colums are properly given. 

Offcourse, they will not be shown in dataValues. ( because they are not datavalues retrieved from DB), but they are still available (. you can find those virtualcolums getters in the model proto)

Different story for the Filter on Virtual colums. (for concatenated values of other colums).  in that case you need to either decompose that concatenation and run a normal where on those columns or do a Where with a Concat

**Comment by ephys** [comment]
I can confirm that this is not something we can support. VIRTUAL doesn't exist in the database and it's impossible to use them as part of an association
