### ISSUE TITLE
Tables getting locked while using sequelize select query.

### ISSUE THREAD

**Issue by JasimJamal** [sequelize/sequelize#9068]
## What are you doing?

```js
 var clientConfig = {

        getClientConfigId: function (req, callback) {
            models.clientConfig.findAll({
                raw: true,
                where: {
                    application: commonFunctions.getSourceApplication(req),
            
                }, attributes:["clientconfigid"]

            }).then(
                clientConfig => {
                    callback(null, clientConfig);
                },
                err => {
                    callback(err, null);
            }); 
        }
    }
```

## What do you expect to happen?
Tables are getting locked. It is not happening on every hit. But sometimes when this query fires. We see that the tables get locked for hours and the application stuck. Is there some configuration that we are missing on. Help will be highly appreciated.

## What is actually happening?
We are getting some data from database using the above code. Once in a blue moon we see that the tables gets locked. If we use normal SQL query it does not happens. We had tested this ample of time. It is happening due to sequelize. May be some configuration that we are missing on.

**Comment by JasimJamal** [comment]
When he tables get's locked it usually takes 3 to 4 hours to release the lock or else we have to restart the database engine.

**Comment by JasimJamal** [comment]
@sushantdhiman  can you please help. It will be highly appreciated.

**Comment by yonjah** [comment]
@JasimJamal  I'm not sure pinging owners of this repo is going to be useful.
They get a notification for every new issue anyway but since this is a highly popular with literally hundreds of active issues being discussed it can take time.

If you want to get to the bottom of your issue as quickly as possible please read the new issue instructions and fill in **all** the relevant information.
Your issue is specificly missing any useful information that will help to track down your problem -
_Output, either JSON or SQL_


__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

Turning on logging and seeing what queries are being sent to your sql server will probably help you understand what is actually causing the table lock (if it is actually a sequelize issue)

**Comment by JasimJamal** [comment]
Dialect: mysql
Dialect version: 1.5.1
Database version: 5.6.10
Sequelize version: 4.32.2
Tested with latest release: No 

@yonjah Please find information.

**Comment by JasimJamal** [comment]
Updated code with table hint:

  models.clientConfig.findAll({
                tableHint: TableHints.NOLOCK,
                raw: true,
                where: {
                    application: commonFunctions.getSourceApplication(req),
                    client: commonFunctions.getClient(req),
                    culture:commonFunctions.getCulture(req),
                    lineofbusiness: commonFunctions.getlineOfBusiness(req),
                    methodofpayment: commonFunctions.getMethodOfPayment(req)
                }, attributes:["clientconfigid"]


But still does not see "With no lock" in query

**Comment by yonjah** [comment]
wait is your issue that you can't read rows from another transaction that haven't committed yet ?

Mysql doesn't support the NOLOCK syntax.

You can change the transaction isolation level to read dirty data, but unless you really know what your doing you can easily end up with inconsistent data. 
Are you sure you need to read uncommited data ?

**Comment by JasimJamal** [comment]
Yes we need to read uncommited data. Becouse the data that we are reading using this code. Has been inserted once only. At the time of deployment.

**Comment by yonjah** [comment]
That doesn't seem like a reason for reading uncommitted data.

Any way enable query log on mysql level and go over the your DB log an see which query actually gets your tabel locked (you should probably also run process list when it happens). And hopefully you'll find whats causing it.

But the query you have shouldn't cause any locks on the table level and your issue is probably not related to sequelize
