### ISSUE TITLE
.belongsToMany .create() doesn't populate additional through table fields

### ISSUE THREAD

**Issue by andrewholsted** [sequelize/sequelize#9094]
## What are you doing?

I have 3 models. 
* `User`
* `Team`
* `TeamMembership`

When trying to create a team, the through table (`TeamMembership`) gets populated with the correct `foreignKey` and `otherKey` but the additional values do not seem to get populated. Additionally, after the team is created, there is no `users` property unlike when I use `.get()`. 

### Models
```js
const { db, DataTypes } = require('../sequelize');

const Team = db.define('Team',
  {
    name: {
      type: DataTypes.STRING,
      field: 'name',
    },
  });

const User = db.define('User',
  {
    name: {
      type: DataTypes.STRING,
      field: 'name',
    },
  });

const TeamMembership = db.define('TeamMembership',
  {
    userId: {
      type: DataTypes.UUID,
      field: 'user_id',
    },
    teamId: {
      type: DataTypes.UUID,
      field: 'team_id',
    },
    role: {
      type: DataTypes.STRING,
      field: 'role',
    });

Team.belongsToMany(User, {
  through: TeamMembership,
  as: 'users',
  foreignKey: 'team_id',
  otherKey: 'user_id',
});

User.belongsToMany(Team, {
  through: TeamMembership,
  as: 'teams',
  foreignKey: 'team_id',
  otherKey: 'user_id',
});

```

### Service
```js

const params = {
      name: 'foobar',
      users: [
        {
          userId: '96b92a93-e6fd-4fc7-b647-233e57646cef',
          role: 'admin',
        },
      ],
    };

 return TeamModel.create(params, {
      include: [
        {
          model: User,
          as: 'users',
        },
      ],
    });
```

## What do you expect to happen?
I expect the `role` column of `TeamMemberships` to be populated. I also expect the result after creating a team to contain `users` with the relevant details. 

## What is actually happening?

```
{ 
  id: '74ed9f56-30a9-4d8a-ac18-9570f274f581',
  name: 'foobar',
  users: [ 
    { 
       id: '96b92a93-e6fd-4fc7-b647-233e57646cef',
       name: null,
    } 
  ],
}
```

__Dialect:__ Postgres
__Dialect version:__ 10
__Database version:__ ?
__Sequelize version:__ ^4.33.1
__Tested with latest release:__ Yes. 4.33.4

**Comment by tomprogers** [comment]
I'm having this same problem. I have not solved it yet, but I have a few notes:

1. I think you can omit the `field` property from your schema definitions, since the values match the key names
2. Experimentation reveals the `otherKey` option has no effect on the SQL that is generated

My current theory is that the solution lies in this comment, from the docs:

> To add a new project to a user and set its status, you pass extra options.through to the setter, which contains the attributes for the join table

```
user.addProject(project, { through: { status: 'started' }})
```

For single-item manipulation, I think this means you need to extract the user properties from the input object, then add them to an explicit `user.addTeam` call. My interface is quite different from yours and I can't readily test an apples-to-apples scenario, or I would provide real sample code. The call might look like:

`user.addTeam(team, { through: { role: 'admin' } })`

I'm trying to figure out how to solve the join-attrs problem when calling `thing.setXList`. I have a [SO question](https://stackoverflow.com/questions/48957191/how-do-i-orm-additional-columns-on-a-join-table-in-sequelize), in case you want to follow along or add anything.

**Comment by sushantdhiman** [comment]
Correct call is

```js
user.addProject(project, { through: { status: 'started' }})
```

this was changed in v4, in v3 you would do something like this

```js
user.addProject(project, { status: 'started' })
```
