### ISSUE TITLE
Creating a new record - created_at and updated_at should be exactly the same value

### ISSUE THREAD

**Issue by switzer** [sequelize/sequelize#918]
Hi!  When I create a new record in a table, the created_at and updated_at values are slightly different (due to each performing a 'new Date()').  For example:

  "created_at": "2013-09-18T21:23:09.711Z",
  "updated_at": "2013-09-18T21:23:09.713Z",

This will have unintended consequences if you use these columns for any sort of analytics (e.g.  has_been_modified = (updated_at > created_at)

Can you please perform a single 'new Date()' function for a database function, and use this single value for all columns that need Sequelize.NOW?

Thanks!

**Comment by yvele** [comment]
@mickhansen hey I have the exact same problem.. and that's a big issue for me as I'm using `createdAt` to generate GraphQL cursors 🤔 

I think the problem has NOT been fixed by  #1182

Note also that I'm using `.get({ plain: true })` to get back the object after insertion

Is it possible to be a regression bug? Is there some unit tests covering this case?
