### ISSUE TITLE
In Sequelize, how do you make default value unique, random and n digits long?

### ISSUE THREAD

**Issue by techsin** [sequelize/sequelize#9263]
## What are you doing?
currently I've a function returning x number of digits that are randomly generated: 324322, 28393, 3294329, 928593, 032293,..... so on. I need them to be unique as well. I've unique constraint on the field. My question is would sequelize try again if unique constraint fails?? If not then what is the good way to fix this as I can't make value really long to prevent collisions.

**Comment by sushantdhiman** [comment]
If creation of a record fails you can catch [UniqueConstraintError](2) and repeat create operation, you can also use [findOrCreate](1), if record with same unique id exists it will be returned otherwise created

[1]: http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findOrCreate
[2]: http://docs.sequelizejs.com/class/lib/errors/index.js~UniqueConstraintError.html
