### ISSUE TITLE
is mysql 8 supported?

### ISSUE THREAD

**Issue by HosseinAlipour** [sequelize/sequelize#9432]
I couldn't find any information about the supported version.
does Sequelize support MySQL 8 and new features?

**Comment by sushantdhiman** [comment]
You can run Sequelize with MySQL 8 Server and it should work. If there are any new specific features that are only available for MySQL 8 we just need a PR to support them

**Comment by alanpurple** [comment]
sequelize use "mysql2" library, which doesn't support mysql 8.0

**Comment by yi-ge** [comment]
MySQL 8 change authentication method, https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html

You can write `my.cnf` to use MySQL8.0, example:
[mysqld-8.0]
default_authentication_plugin=mysql_native_password

**Comment by DayBr3ak** [comment]
MySQL8 doesn't work with sequelize and mysql2 module 

    SequelizeDatabaseError: The user specified as a definer ('mysql.infoschema'@'localhost') does not exist

**Comment by tolgaatam** [comment]
It seems like if the mysql server is configured with the old authentication method, everything works correctly.

I spinned up an Amazon RDS server for mysql 8.0.13 to try it out. I was not able to connect to it with the new xdevapi connector. But mysql2 and sequelize was working correctly. The error message I got with the new connector was something like, "Either invalid port or x-toolkit is not supported". Port was surely valid so it means that Amazon deploys mysql 8 without the new auth and API mechanism. I suspect it is due to either compatibility purposes or for not having a nosql flavoured db in their environenment against DynamoDB :)

After all, it seems like if you are in the Amazon train, you are all clear. If not, @yi-ge 's solutions should let you work with mysql8 via sequelize/mysql2.

**Comment by gzurbach** [comment]
I am trying to connect to a DigitalOcean managed MySQL instance which is running 8.0.16 and has `default_authentication_plugin=caching_sha2_password`. I cannot edit the system variables so I have to find a client that works.

Uninstalling `mysql2` and installing `@mysql/xdevapi` did not work because Sequelize cannot find the new client. 

@DayBr3ak Is it possible to tell Sequelize to use the new client? If not, what are my options to connect to this instance?

PS: Looks like `mysql2` is aware of the issue but has no ETA for a fix: https://github.com/sidorares/node-mysql2/issues/991

**Comment by sidorares** [comment]
@gzurbach I'm very close to finish new mysql8 auth support, see https://github.com/sidorares/node-mysql2/pull/1021
