### ISSUE TITLE
Implement asynchronicity in getters / setters

### ISSUE THREAD

**Issue by thanpolas** [sequelize/sequelize#965]
Allow for async execution of virtual getters / setters.

I will implement this feature as it's a show-stopper for me (hashing algo for passwords is async).

Since there is no established pattern for async callbacks in Sequelize (apart from chained promises) i'll take the initiative to use the [`this.async()`](http://gruntjs.com/creating-tasks#why-doesn-t-my-asynchronous-task-complete) pattern.

I'm not choosing detecting function arity (ala express.js) as this has side-effects in combination with promises.
### Proposed Pattern using this.async()

``` js
var Foo = sequelize.define('Foo', {
  title: {type     : Sequelize.STRING, allowNull: false,}

  }, {

  getterMethods   : {
    title_slug  : function()  { 
      var done = this.async();

      doSomethingAsync(function(){
        done(slugify(this.title));
      })
    }
});
```
### Using Function Arity Detection

``` js
var Foo = sequelize.define('Foo', {
  title: {type     : Sequelize.STRING, allowNull: false,}

  }, {

  getterMethods   : {
    title_slug  : function(done)  {  // defining an argument means async
      doSomethingAsync(function(){
        done(slugify(this.title));
      })
    }
});
```

// @sdepold

**Comment by diosney** [comment]
This is really a shame, it could be a very useful feature to have (if used properly of course).

In my case, I've an Account model with several attributes that are saved to the database, but I wanted to have a VIRTUAL attribute named `balance` that it won't be stored in the database but it will be the result of an async operation (returning a promise) that will sum/rest the transactions related to this account.

Of course, since this is not supported, bu returning the Promise is set balance to be:

```js
{
   "isFulfilled": false,
   "isRejected": false
}
```

instead of solving the Promise.

**Comment by mickhansen** [comment]
@diosney It's simply too complicated to get right, and would change pretty much everything.
You could add a afterFind that checks if the VIRTUAL attribute has been requested and then injected the value.

**Comment by diosney** [comment]
@mickhansen Thanks! As always, you give me another light of hope :smile: 

I didn't know about the `afterFind` hook, that definitively will work for me.

Thanks!

**Comment by tremby** [comment]
@mickhansen, can you give an example of how to use an `afterFind` hook in that way, with an async bit of code? In particular, checking if the virtual attribute has been requested, and then fulfilling a promise of a result for that field.

**Comment by mickhansen** [comment]
@tremby Hmm that's odd, the options should be options passed, so your attribute should be in there.

**Comment by tremby** [comment]
I added an afterFind hook which just logs out the second argument.

When I try the following

```coffee
  console.log "find by id"
  models.User.findById 1,
    attributes:
      include: 'position'
  .then ->
    console.log "findall"
    models.User.findAll
      attributes:
        include: 'position'
```

I get back this:

```
find by id
{ attributes: 
   [ 'id',
     'provider',
     'providerId',
     'name',
     'image',
     'email',
     'createdAt',
     'updatedAt' ],
  where: '`User`.`id` = 1',
  plain: true,
  hooks: true,
  tableNames: [ 'Users' ],
  type: 'SELECT',
  model: User }
findall
{ attributes: 
   [ 'id',
     'provider',
     'providerId',
     'name',
     'image',
     'email',
     'createdAt',
     'updatedAt' ],
  hooks: true,
  tableNames: [ 'Users' ],
  type: 'SELECT',
  model: User }
```

If I instead have, as the options,

```coffee
    attributes:
      include: ['position']
```

I get the same output.

If I have

```coffee
    attributes:
      include: ['position', 'pos']
```

I'm told `pos` doesn't exist (that's correct).

If I have

```coffee
    attributes:
      include: [
        ['position', 'pos']
      ]
```

I'm told `Unknown column 'position' in 'field list'`. This is legit, because that column doesn't exist. But it is a virtual field so I expected it not to really add it to the query.

If I have

```coffee
    attributes:
      include: [
        ['(select 1)', 'one']
      ]
```

I get

```
find by id
{ attributes: 
   [ 'id',
     'provider',
     'providerId',
     'name',
     'image',
     'email',
     'createdAt',
     'updatedAt',
     [ '(select 1)', 'one' ] ],
  where: '`User`.`id` = 1',
  plain: true,
  hooks: true,
  tableNames: [ 'Users' ],
  type: 'SELECT',
  model: User }
findall
{ attributes: 
   [ 'id',
     'provider',
     'providerId',
     'name',
     'image',
     'email',
     'createdAt',
     'updatedAt',
     [ '(select 1)', 'one' ] ],
  hooks: true,
  tableNames: [ 'Users' ],
  type: 'SELECT',
  model: User }
```

What I want is to request the `position` attribute (which is defined as `VIRTUAL`), and have the afterFind know about it, as you suggested was possible above. Am I going about this totally wrongly?

**Comment by mickhansen** [comment]
You're going about this correctly but it appears there's a bug in our code. You're getting the cleaned and normalized options rather than the original options.

**Comment by tremby** [comment]
Want me to open a new ticket?

**Comment by mickhansen** [comment]
Please do @tremby

**Comment by twelve17** [comment]
Thanks to @iamjochem and others for making what I believe are good points regarding the problem with asynchronous calls in getters and setters.  May I suggest, in this case, that the example code in the [VIRTUAL datatype](http://docs.sequelizejs.com/en/latest/api/datatypes/#virtual) be changed to something else besides password hashing as a setter method, since it might mislead folks to the problem discussed here?

**Comment by felixfbecker** [comment]
@twelve17 sure, feel free to do a PR. I prefer the firstName / lastName / fullName example

**Comment by twelve17** [comment]
@felixfbecker Sounds good, I'll take a look.

**Comment by thomascgray** [comment]
How do you change a virtual field in `afterFind`? Tried everything with getters and setters, but it still comes out with original values.

**Comment by iamjochem** [comment]
@thomascgray - what does it mean to change a virtual field value? (given that is it niether stored in the instance nor represented in the underlying storage). When you say you tried "everything" it is always helpful to show actual code. I'll hazard a guess that your virtual-field is retrieving a value from the instance using `this.getDataValue('some_real_attribute')` and then possibly doing something with it then returing a value based on it ... in your `afterFind` hook you'll want to manipulate the `some_real_attribute` somehow (e.g. `this.some_real_attribute = "my fudged after-find value"`)

- nice thread hijack btw ;-) maybe consider opening a new issue instead?

**Comment by BuistvoPloti** [comment]
though it is closed i'm leaving my answer on the opened issue 
https://github.com/aws/aws-sdk-js-v3/issues/5509#issuecomment-1992184090
