### ISSUE TITLE
CLS is not used when opening a nested transaction

### ISSUE THREAD

**Issue by Strate** [sequelize/sequelize#9820]
## What are you doing?

```js
// use cls
db.transaction(async () => {
  db.transaction(async () => {
    // here we have a new transaction, instead of re-use already opened transaction
  })
}
```

## What do you expect to happen?
I expect `.transaction()` method pick existing transaction from cls

## What is actually happening?
Existing transaction is not picked up by cls

__Dialect:__ postgres
__Database version:__ 10.x
__Sequelize version:__ 4.38.0
__Tested with latest release:__ 4.38.0

**Comment by sushantdhiman** [comment]
What do you mean by picking existing transaction, it should create a new child transaction.

**Comment by Strate** [comment]
@sushantdhiman yes, pick existing transaction and create a child.

**Comment by yonjah** [comment]
@Strate  @sushantdhiman This is a known issue https://github.com/sequelize/sequelize/issues/8621 (even though it was recently closed by stale bot).

Currently you have to explicitly pass parent transaction in the options when creating a child transaction.

Also I would be cautious when using child transactions since they currently can not handle concurrency  and can have unexpected results (as described in https://github.com/sequelize/sequelize/issues/9770)

**Comment by sushantdhiman** [comment]
@yonjah oh yeah because we use `options.transaction` to set parent, should be injected in case of cls. I will reopen that issue as it seems there is more discussion there
