### ISSUE TITLE
bulkCreate ignores virtual attribute validation

### ISSUE THREAD

**Issue by ryanzyy** [sequelize/sequelize#9947]
## What are you doing?

```js
  await User.bulkCreate([
      {
        email: 'user1@example.com',
        password: '123',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],{ validate: true})

// In model attribute:
      password: {
        type: dt.VIRTUAL,
        set: function (val) { this.setDataValue('password', val)  },
        validate: { 
          len: [10,200],
          virtualFieldValidator: function() {
            console.log('---validator---') // never called
            return false;
          },
        },
      },
```

## What do you expect to happen?
Expected Validation Error in promise

Add a new option of bulkCreate to explicitly enable virtual field validators.
```js
{ 
  validate: true,
  validateVirtual: true,
}
```

Or

implicitly enable virtual field validators whenever 'validate' is set to true

## What is actually happening?
User records are successfully created since validators of virtual field are ignored

Sequelize version: "4.38.1"

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
This happens because we are using `tableAttributes` for setting `options.fields` https://github.com/sequelize/sequelize/blob/8a8366b4dde3060145f0037f85b4aad816b94aa3/lib/model.js#L2493 which skips `password` (as VIRTUAL) from validation

Not sure what are the implications of setting `options.fields` to `rawAttributes` but we can at least pass full fields when doing validation https://github.com/sequelize/sequelize/blob/8a8366b4dde3060145f0037f85b4aad816b94aa3/lib/model.js#L2536
